// Thai locale — complete key parity with English; common UI strings translated natively.
// Unlisted keys intentionally inherit the English source text so new features remain usable.
(function () {
  const base = window.I18N_EN || {};
  const overrides = {
    'app.title':'SCMS — ระบบจัดการชั้นเรียนโรงเรียน',
    'common.all':'ทั้งหมด','common.edit':'แก้ไข','common.close':'ปิด','common.cancel':'ยกเลิก','common.add':'เพิ่ม','common.saving':'กำลังบันทึก…','common.years':'ปี','common.failed':'ล้มเหลว:','common.saveFailed':'บันทึกไม่ได้ — ลองอีกครั้ง','common.removed':'ลบแล้ว',
    'nav.dashboard':'แดชบอร์ด','nav.students':'นักเรียน','nav.attendance':'การเข้าเรียน','nav.homework':'การบ้าน','nav.messages':'ข้อความ','nav.incidents':'เหตุการณ์','nav.timetable':'ตารางเรียน','nav.reports':'รายงาน','nav.settings':'การตั้งค่า',
    'topbar.search':'ค้นหา...','topbar.notifications':'การแจ้งเตือน','topbar.profile':'โปรไฟล์','topbar.logout':'ออกจากระบบ','topbar.language':'ภาษา',
    'btn.save':'บันทึก','btn.cancel':'ยกเลิก','btn.delete':'ลบ','btn.edit':'แก้ไข','btn.add':'เพิ่ม','btn.close':'ปิด','btn.confirm':'ยืนยัน','btn.export':'ส่งออก','btn.refresh':'รีเฟรช','btn.submit':'ส่ง',
    'msg.loading':'กำลังโหลด...','msg.saving':'กำลังบันทึก...','msg.saved':'บันทึกสำเร็จ','msg.error':'เกิดข้อผิดพลาด','msg.noData':'ไม่มีข้อมูล','msg.offline':'คุณออฟไลน์อยู่','msg.confirmDelete':'คุณแน่ใจหรือไม่ว่าต้องการลบ?',
    'students.title':'นักเรียน','students.name':'ชื่อ','students.class':'ชั้นเรียน','students.parent':'ผู้ปกครอง','students.phone':'โทรศัพท์','students.addNew':'เพิ่มนักเรียนใหม่','att.title':'การเข้าเรียน','att.present':'มาเรียน','att.absent':'ขาดเรียน','att.late':'สาย','att.leave':'ลา','att.markAll':'ทำเครื่องหมายมาครบทั้งหมด','att.date':'วันที่','att.saveAttendance':'บันทึกการเข้าเรียน',
    'landing.title':'การจัดการชั้นเรียนโรงเรียน','landing.titleEm':'ทำได้ง่ายๆ','landing.emailLink':'เข้าสู่ระบบด้วยอีเมล','landing.or':'หรือ','landing.telegram':'เข้าสู่ระบบด้วย Telegram','landing.teacherId':'เข้าสู่ระบบด้วยรหัสครู','landing.registerSchool':'ลงทะเบียนโรงเรียนใหม่','landing.joinSchool':'เข้าร่วมโรงเรียนที่มีอยู่แล้ว',
    'login.title':'🔐 เข้าสู่ระบบ','login.loginName':'ชื่อเข้าสู่ระบบ','login.pin':'PIN','login.btn':'เข้าสู่ระบบ','login.signingIn':'กำลังเข้าสู่ระบบ…','pw.old':'รหัสผ่านปัจจุบัน','pw.new':'รหัสผ่านใหม่ (อย่างน้อย 6 ตัวอักษร)','pw.confirm':'ยืนยันรหัสผ่านใหม่','pw.btnChange':'เปลี่ยนรหัสผ่าน',
    'page.dashboard.eyebrow':'ภาพรวม','page.dashboard.title':'<em>แดชบอร์ด</em> วันนี้','page.students.title':'<em>นักเรียน</em>ของฉัน','page.attend.title':'<em>การเข้าเรียน</em>','page.hw.title':'<em>การบ้าน</em>','page.grades.title':'<em>ผลการเรียน</em>','page.billing.title':'<em>การเรียกเก็บเงิน</em>','page.admissions.title':'<em>การรับสมัคร</em>','page.library.title':'<em>ห้องสมุด</em>','page.transport.title':'<em>การเดินทาง</em>','page.incidents.title':'<em>เหตุการณ์</em>','page.timetable.title':'<em>ตารางเรียน</em>','page.summary.title':'<em>สรุปรายเดือน</em>','page.more.title':'<em>ฟีเจอร์เพิ่มเติม</em>',
    'tab.students':'นักเรียน','tab.attend':'เข้าเรียน','tab.daily':'รายวัน','tab.hw':'การบ้าน','tab.chat':'แชต','tab.more':'เพิ่มเติม',
    'att.clearMarks':'ล้างเครื่องหมาย','att.history':'ประวัติ','att.historyTitle':'ประวัติและรายงาน','att.codes':'รหัส'
  };
  Object.assign(overrides, {
    'hw.tapAdd':'แตะ + เพื่อเพิ่มการบ้าน','hw.due':'กำหนดส่ง','hw.addTitle':'เพิ่มการบ้าน','hw.subject':'วิชา','hw.addSubject':'เพิ่มวิชา','hw.class':'ชั้นเรียน','hw.type':'ประเภท','hw.description':'รายละเอียด','hw.descPh':'รายละเอียดการบ้าน…','hw.lbPage':'หน้า LB','hw.wbPage':'หน้า WB','hw.pagePh1':'เช่น 24','hw.pagePh2':'เช่น 25','hw.dueDate':'วันครบกำหนด','hw.saved':'✓ บันทึกการบ้านแล้ว','hw.editTitle':'แก้ไขการบ้าน','hw.updated':'✓ อัปเดตแล้ว','hw.confirmTitle':'ลบการบ้านนี้?','hw.confirmBody':'คุณแน่ใจหรือไม่ว่าต้องการลบการบ้านนี้?',
    'comms.none':'ยังไม่มีข้อความ','comms.noneSub':'ส่งข้อความถึงผู้ปกครองจากที่นี่','comms.broadcast':'ประกาศ','comms.purpose':'วัตถุประสงค์','comms.confirmTitle':'ยืนยันการส่ง','comms.sendTitle':'ส่งข้อความ','comms.sendTo':'ส่งถึง','comms.wholeClass':'ทั้งชั้น','comms.individual':'รายบุคคล','comms.class':'ชั้นเรียน','comms.student':'นักเรียน','comms.chooseStudent':'เลือกนักเรียน','comms.message':'ข้อความ','comms.msgPh':'พิมพ์ข้อความ…','comms.send':'ส่ง','comms.pickerTitle':'เลือกผู้รับ','comms.msgRequired':'กรุณาใส่ข้อความ','comms.pickStudentFirst':'กรุณาเลือกนักเรียนก่อน','comms.sending':'กำลังส่ง…','comms.sent':'✓ ส่งแล้ว',
    'inc.none':'ยังไม่มีเหตุการณ์','inc.tapLog':'แตะเพื่อบันทึกเหตุการณ์','inc.action':'การดำเนินการ','inc.parentNotified':'แจ้งผู้ปกครองแล้ว','inc.pickerTitle':'เลือกนักเรียน','inc.logTitle':'บันทึกเหตุการณ์','inc.student':'นักเรียน','inc.tapChoose':'แตะเพื่อเลือก','inc.type':'ประเภท','inc.severity':'ระดับความรุนแรง','inc.description':'รายละเอียด','inc.whatHappened':'เกิดอะไรขึ้น','inc.actionTaken':'การดำเนินการที่ทำ','inc.actionPh':'ระบุการดำเนินการ…','inc.notifyParent':'แจ้งผู้ปกครอง','inc.logged':'✓ บันทึกแล้ว','inc.pickFirst':'กรุณาเลือกนักเรียนก่อน','inc.editTitle':'แก้ไขเหตุการณ์','inc.updated':'✓ อัปเดตแล้ว','inc.confirmTitle':'ลบเหตุการณ์นี้?',
    'tt.adminManages':'ผู้ดูแลระบบจัดการตารางเรียน','tt.adminOnly':'เฉพาะผู้ดูแลระบบ','tt.entryNotFound':'ไม่พบรายการ','tt.editTitle':'แก้ไขตารางเรียน','tt.addTitle':'เพิ่มคาบเรียน','tt.day':'วัน','tt.periodLbl':'คาบเรียน','tt.startTime':'เวลาเริ่ม','tt.class':'ชั้นเรียน','tt.subject':'วิชา','tt.roomOptional':'ห้อง (ไม่บังคับ)','tt.roomPh':'เช่น ห้อง 101','tt.addEntry':'เพิ่มรายการ','tt.updated':'✓ อัปเดตแล้ว','tt.added':'✓ เพิ่มแล้ว','tt.confirmDelete':'ลบรายการนี้?',
    'sum.none':'ยังไม่มีข้อมูล','sum.noneSub':'ยังไม่มีข้อมูลสรุปสำหรับช่วงเวลานี้','sum.absent':'ขาดเรียน','sum.days':'วัน','sum.hw':'การบ้าน',
    'enum.assessType.Quiz':'แบบทดสอบสั้น','enum.assessType.Test':'แบบทดสอบ','enum.assessType.Exam':'สอบ','enum.assessType.Assignment':'งานที่มอบหมาย','enum.assessType.Project':'โครงงาน',
    'grades.current':'ภาคเรียนปัจจุบัน','grades.addTerm':'เพิ่มภาคเรียน','grades.reportCard':'ใบรายงานผล','grades.noClasses':'ยังไม่มีชั้นเรียน','grades.noAssessments':'ยังไม่มีการประเมิน','grades.pickTerm':'เลือกภาคเรียน','grades.pickClass':'เลือกชั้นเรียน','grades.reportTitle':'รายงานผลการเรียน','grades.noGraded':'ยังไม่มีคะแนน','grades.thStudent':'นักเรียน','grades.overall':'โดยรวม','grades.newTitle':'การประเมินใหม่','grades.title':'ชื่อการประเมิน','grades.titlePh':'เช่น แบบทดสอบคณิตศาสตร์','grades.type':'ประเภท','grades.maxScore':'คะแนนเต็ม','grades.weight':'น้ำหนัก','grades.date':'วันที่','grades.create':'สร้าง','grades.creating':'กำลังสร้าง…','grades.enterTitle':'กรุณาใส่ชื่อการประเมิน','grades.created':'✓ สร้างแล้ว','grades.confirmTitle':'ลบการประเมินนี้?','grades.confirmBody':'ข้อมูลคะแนนของการประเมินนี้จะถูกลบ','grades.saveScores':'บันทึกคะแนน','grades.enterOne':'กรุณาใส่คะแนนอย่างน้อยหนึ่งคน','grades.scoresSaved':'✓ บันทึกคะแนนแล้ว','grades.addTermTitle':'เพิ่มภาคเรียน','grades.termName':'ชื่อภาคเรียน','grades.termNamePh':'เช่น ภาคเรียนที่ 1','grades.year':'ปี','grades.yearPh':'เช่น 2026','grades.start':'วันที่เริ่ม','grades.end':'วันที่สิ้นสุด','grades.enterTermName':'กรุณาใส่ชื่อภาคเรียน','grades.termAdded':'✓ เพิ่มภาคเรียนแล้ว',
    'enum.billStatus.All':'ทั้งหมด','enum.billStatus.Unpaid':'ยังไม่ชำระ','enum.billStatus.Partial':'ชำระบางส่วน','enum.billStatus.Paid':'ชำระแล้ว','enum.billStatus.Overdue':'เกินกำหนด','enum.payMethod.Cash':'เงินสด','enum.payMethod.Bank Transfer':'โอนธนาคาร','enum.payMethod.Mobile':'มือถือ','enum.payMethod.Other':'อื่นๆ','enum.feeCategory.Tuition':'ค่าเล่าเรียน','enum.feeCategory.Transport':'ค่ารถรับส่ง','enum.feeCategory.Meals':'ค่าอาหาร','enum.feeCategory.Uniform':'ค่าเครื่องแบบ','enum.feeCategory.Books':'ค่าหนังสือ','enum.feeCategory.Activity':'ค่ากิจกรรม','enum.feeCategory.Other':'อื่นๆ',
    'bill.allTerms':'ทุกภาคเรียน','bill.none':'ยังไม่มีใบแจ้งหนี้','bill.ready':'พร้อมใช้งาน','bill.billed':'เรียกเก็บแล้ว','bill.collected':'เก็บเงินแล้ว','bill.outstanding':'ค้างชำระ','bill.newTitle':'สร้างใบแจ้งหนี้','bill.student':'นักเรียน','bill.chooseStudent':'เลือกนักเรียน','bill.termOptional':'ภาคเรียน (ไม่บังคับ)','bill.noTerm':'ไม่มีภาคเรียน','bill.dueDate':'วันครบกำหนด','bill.lineItems':'รายการ','bill.addLineItem':'เพิ่มรายการ','bill.notes':'หมายเหตุ','bill.optional':'ไม่บังคับ','bill.createInvoice':'สร้างใบแจ้งหนี้','bill.pickerTitle':'เลือกนักเรียน','bill.fromCatalog':'จากรายการค่าธรรมเนียม','bill.descPh':'รายละเอียด…','bill.chooseStudentToast':'กรุณาเลือกนักเรียน','bill.needItem':'เพิ่มรายการอย่างน้อยหนึ่งรายการ','bill.invoiceCreated':'✓ สร้างใบแจ้งหนี้แล้ว','bill.rowTotal':'รวม','bill.rowPaid':'ชำระแล้ว','bill.rowBalance':'ยอดคงเหลือ','bill.payments':'การชำระเงิน','bill.noPayments':'ยังไม่มีการชำระเงิน','bill.enrollment':'การลงทะเบียน','bill.makeActive':'เปิดใช้งาน','bill.pendingNote':'นักเรียนจะยังอยู่ในสถานะ <em>รอดำเนินการ</em> จนกว่าจะเปิดใช้งาน','bill.recordPayment':'บันทึกการชำระเงิน','bill.deleteInvoice':'ลบใบแจ้งหนี้','bill.activating':'กำลังเปิดใช้งาน…','bill.activated':'✓ เปิดใช้งานแล้ว','bill.method':'วิธีชำระเงิน','bill.savePayment':'บันทึกการชำระเงิน','bill.validAmount':'กรุณาใส่จำนวนเงินที่ถูกต้อง','bill.paymentRecorded':'✓ บันทึกการชำระเงินแล้ว','bill.removePayTitle':'ลบการชำระเงินนี้?','bill.removePayBody':'การชำระเงินนี้จะถูกลบออกจากใบแจ้งหนี้','bill.removedToast':'✓ ลบแล้ว','bill.delInvTitle':'ลบใบแจ้งหนี้นี้?','bill.delInvBody':'การลบใบแจ้งหนี้ไม่สามารถย้อนกลับได้','bill.addFeeItem':'เพิ่มค่าธรรมเนียม','bill.noFeeItems':'ยังไม่มีรายการค่าธรรมเนียม','bill.recurring':'เกิดซ้ำ','bill.addFeeTitle':'เพิ่มค่าธรรมเนียม','bill.name':'ชื่อ','bill.namePh':'เช่น ค่าเล่าเรียน','bill.category':'หมวดหมู่','bill.defaultAmount':'จำนวนเงินเริ่มต้น','bill.enterName':'กรุณาใส่ชื่อ','bill.feeAdded':'✓ เพิ่มค่าธรรมเนียมแล้ว','bill.delFeeTitle':'ลบค่าธรรมเนียมนี้?','bill.delFeeBody':'รายการค่าธรรมเนียมนี้จะถูกลบ',
    'enum.admStatus.All':'ทั้งหมด','enum.admStatus.Applied':'สมัครแล้ว','enum.admStatus.Interview Scheduled':'นัดสัมภาษณ์แล้ว','enum.admStatus.Interview Done':'สัมภาษณ์แล้ว','enum.admStatus.Accepted':'รับเข้าแล้ว','enum.admStatus.Waitlisted':'รอคิว','enum.admStatus.Rejected':'ปฏิเสธ','enum.admStatus.Enrolled':'ลงทะเบียนแล้ว','enum.admStatus.Withdrawn':'ถอนใบสมัคร','enum.gender.Male':'ชาย','enum.gender.Female':'หญิง','enum.gender.Other':'อื่นๆ',
    'adm.none':'ยังไม่มีผู้สมัคร','adm.total':'ทั้งหมด','adm.inProgress':'กำลังดำเนินการ','adm.noParent':'ไม่มีข้อมูลผู้ปกครอง','adm.moveTo':'ย้ายไป','adm.enrollOwn':'ลงทะเบียน','adm.clear':'ล้าง','adm.failedN':'ล้มเหลว {n} รายการ','adm.noClassSet':'ยังไม่ได้ตั้งค่าชั้นเรียน','adm.newTitle':'ผู้สมัครใหม่','adm.nameEn':'ชื่อภาษาอังกฤษ','adm.fullName':'ชื่อเต็ม','adm.nameLocalOpt':'ชื่อท้องถิ่น (ไม่บังคับ)','adm.nameLocal':'ชื่อท้องถิ่น','adm.dob':'วันเกิด','adm.gender':'เพศ','adm.desiredClass':'ชั้นเรียนที่ต้องการ','adm.parentName':'ชื่อผู้ปกครอง','adm.parentPhone':'โทรศัพท์ผู้ปกครอง','adm.parentEmail':'อีเมลผู้ปกครอง','adm.optional':'ไม่บังคับ','adm.source':'แหล่งที่มา','adm.sourcePh':'เช่น เว็บไซต์','adm.notes':'หมายเหตุ','adm.add':'เพิ่มผู้สมัคร','adm.enterName':'กรุณาใส่ชื่อ','adm.validEmail':'อีเมลไม่ถูกต้อง','adm.added':'✓ เพิ่มแล้ว','adm.rowLocal':'ชื่อท้องถิ่น','adm.rowParent':'ผู้ปกครอง','adm.rowPhone':'โทรศัพท์','adm.rowEmail':'อีเมล','adm.rowApplied':'วันที่สมัคร','adm.rowInterview':'สัมภาษณ์','adm.moveToTitle':'ย้ายผู้สมัคร','adm.enrollBtn':'ลงทะเบียนนักเรียน','adm.editDetails':'แก้ไขรายละเอียด','adm.deleteApplicant':'ลบผู้สมัคร','adm.createRegInvoice':'สร้างใบแจ้งหนี้ลงทะเบียน','adm.goBilling':'ไปการเรียกเก็บเงิน','adm.scheduleTitle':'กำหนดการสัมภาษณ์','adm.interviewDate':'วันที่สัมภาษณ์','adm.interviewScheduled':'✓ นัดสัมภาษณ์แล้ว','adm.editTitle':'แก้ไขผู้สมัคร','adm.nameRequired':'ต้องระบุชื่อ','adm.saved':'✓ บันทึกแล้ว','adm.convertNote':'ผู้สมัครจะถูกแปลงเป็นนักเรียน','adm.enroll':'ลงทะเบียน','adm.enterClass':'กรุณาเลือกชั้นเรียน','adm.enrollingBtn':'กำลังลงทะเบียน…','adm.recordCreated':'✓ สร้างรายการนักเรียนแล้ว — {id} (รอดำเนินการ)','adm.regTitle':'ใบแจ้งหนี้ลงทะเบียน','adm.needAmountItem':'เพิ่มรายการอย่างน้อยหนึ่งรายการที่มีจำนวนเงิน','adm.regCreated':'✓ สร้างใบแจ้งหนี้ลงทะเบียนแล้ว','adm.delTitle':'🗑 ลบผู้สมัครนี้?','adm.delBody':'รายการสมัครจะถูกลบ แต่จะไม่กระทบกับนักเรียนที่อาจสร้างไว้แล้ว',
    'health.bloodType':'กรุ๊ปเลือด','health.allergies':'อาการแพ้','health.allergiesPh':'เช่น ถั่วลิสง เพนิซิลลิน','health.conditions':'โรคประจำตัว','health.conditionsPh':'เช่น หอบหืด','health.medications':'ยา','health.emContactName':'ชื่อผู้ติดต่อฉุกเฉิน','health.emContactPhone':'โทรศัพท์ผู้ติดต่อฉุกเฉิน','health.doctorName':'ชื่อแพทย์','health.doctorPhone':'โทรศัพท์แพทย์','health.notes':'หมายเหตุ','health.allergiesLabel':'อาการแพ้:','health.conditionsLabel':'โรคประจำตัว:','health.emergencyContact':'ผู้ติดต่อฉุกเฉิน','health.doctor':'แพทย์','health.editProfile':'แก้ไขข้อมูลสุขภาพ','health.vaccinations':'วัคซีน','health.noDate':'ไม่มีวันที่','health.noVax':'ยังไม่มีบันทึกวัคซีน','health.addVax':'+ เพิ่มวัคซีน','health.visits':'การพบแพทย์ / พยาบาล','health.noVisits':'ยังไม่มีบันทึกการพบแพทย์','health.logVisit':'+ บันทึกการพบแพทย์','health.editTitle':'แก้ไขข้อมูลสุขภาพ','health.bloodTypePh':'เช่น O+','health.medicationsOpt':'ไม่บังคับ','health.addVaxTitle':'เพิ่มวัคซีน','health.vaccineName':'ชื่อวัคซีน','health.vaccineNamePh':'เช่น MMR','health.dateGiven':'วันที่ได้รับ','health.enterVaccine':'กรุณาใส่ชื่อวัคซีน','health.delVaxTitle':'🗑 ลบบันทึกวัคซีนนี้?','health.logVisitTitle':'บันทึกการพบแพทย์','health.reason':'เหตุผล','health.reasonPh':'เช่น ไข้ ปวดศีรษะ','health.treatment':'การรักษา','health.enterReason':'กรุณาใส่เหตุผล','health.delVisitTitle':'🗑 ลบบันทึกการพบแพทย์นี้?','health.added':'✓ เพิ่มแล้ว','health.logged':'✓ บันทึกแล้ว',
    'lib.titles':'ชื่อหนังสือ','lib.copies':'จำนวนเล่ม','lib.checkedOut':'ถูกยืม','lib.none':'ยังไม่มีหนังสือ — แตะ + เพื่อเพิ่ม','lib.unknownAuthor':'ไม่ทราบผู้แต่ง','lib.newTitle':'หนังสือใหม่','lib.title':'ชื่อเรื่อง','lib.bookTitle':'ชื่อหนังสือ','lib.author':'ผู้แต่ง','lib.category':'หมวดหมู่','lib.categoryPh':'เช่น นิยาย อ้างอิง (ไม่บังคับ)','lib.isbn':'ISBN','lib.add':'เพิ่มหนังสือ','lib.enterTitle':'กรุณาใส่ชื่อหนังสือ','lib.added':'✓ เพิ่มหนังสือแล้ว','lib.avail':'มี {a} เล่ม / ทั้งหมด {t} เล่ม','lib.checkoutBtn':'ยืมให้นักเรียน','lib.currentlyOut':'กำลังถูกยืม','lib.since':'ตั้งแต่ {date}','lib.due':' ครบกำหนด {date}','lib.return':'คืน','lib.none2':'ไม่มีในขณะนี้','lib.history':'ประวัติ','lib.editTitle':'แก้ไขหนังสือ','lib.totalCopies':'จำนวนเล่มทั้งหมด','lib.titleRequired':'ต้องระบุชื่อหนังสือ','lib.checkoutTitle':'ยืมหนังสือ','lib.student':'นักเรียน','lib.selectStudent':'เลือกนักเรียน','lib.checkoutBtn2':'ยืม','lib.pickStudent':'เลือกนักเรียน','lib.checkingOut':'กำลังยืม…','lib.checkedOutToast':'✓ ยืมแล้ว','lib.returnedToast':'✓ คืนแล้ว','lib.delTitle':'🗑 ลบหนังสือนี้?','lib.delBody':'ทำได้เมื่อไม่มีเล่มใดกำลังถูกยืม','lib.mustReturn':'กรุณาคืนหนังสือทั้งหมดก่อนลบ',
    'tr.none':'ยังไม่มีเส้นทาง — แตะ + เพื่อเพิ่ม','tr.noDriver':'ยังไม่ได้กำหนดคนขับ','tr.newTitle':'เส้นทางใหม่','tr.routeName':'ชื่อเส้นทาง','tr.routeNamePh':'เช่น เส้นทาง A — เหนือ','tr.driverName':'ชื่อคนขับ','tr.driverPhone':'โทรศัพท์คนขับ','tr.vehicle':'รถ','tr.vehiclePh':'เช่น Toyota Coaster เลขทะเบียน (ไม่บังคับ)','tr.add':'เพิ่มเส้นทาง','tr.enterName':'กรุณาใส่ชื่อเส้นทาง','tr.added':'✓ เพิ่มเส้นทางแล้ว','tr.driver':'คนขับ','tr.phone':'โทรศัพท์','tr.vehicleLabel':'รถ','tr.students':'นักเรียน ({n})','tr.noStudents':'ยังไม่มีนักเรียนที่กำหนด','tr.assign':'กำหนดนักเรียน','tr.editRoute':'แก้ไขเส้นทาง','tr.deleteRoute':'ลบเส้นทาง','tr.editTitle':'แก้ไขเส้นทาง','tr.routeRequired':'ต้องระบุชื่อเส้นทาง','tr.assignTitle':'กำหนดนักเรียน','tr.pickupStop':'จุดรับ','tr.pickupStopPh':'เช่น ประตูหลัก (ไม่บังคับ)','tr.pickupTime':'เวลารับ','tr.dropoffTime':'เวลาส่ง','tr.assignBtn':'กำหนด','tr.assigning':'กำลังกำหนด…','tr.assigned':'✓ กำหนดแล้ว','tr.delTitle':'🗑 ลบเส้นทางนี้?','tr.delBody':'นักเรียนที่อยู่ในเส้นทางจะถูกยกเลิกการกำหนดเท่านั้น ไม่ถูกลบออกจากโรงเรียน',
    'settings.title':'⚙️ การตั้งค่า','settings.version':'เวอร์ชัน','settings.platform':'แพลตฟอร์ม','settings.school':'โรงเรียน','settings.teacher':'ครู','settings.role':'บทบาท','settings.login':'เข้าสู่ระบบ','settings.telegram':'Telegram','settings.connected':'🟢 เชื่อมต่อแล้ว','settings.notConnected':'⚪ ยังไม่ได้เชื่อมต่อ','settings.manageTeachers':'👥 จัดการครู','settings.connectTelegram':'🔗 เชื่อมต่อ Telegram','settings.disconnectTelegram':'🔌 ยกเลิกการเชื่อมต่อ Telegram','settings.changePassword':'🔑 เปลี่ยนรหัสผ่านของฉัน','settings.footerNote':'SCMS จัดการโดยผู้ดูแลโรงเรียนของคุณ','settings.googleAccount':'บัญชี Google','settings.webPassword':'เว็บ (รหัสผ่าน)',
    'tm.title':'👥 จัดการครู','tm.subtitle':'สร้างบัญชีเข้าสู่ระบบสำหรับครู','tm.addNew':'+ เพิ่มครูใหม่ (รหัสครู + รหัสผ่าน)','tm.inviteGoogle':'✉️ เชิญผ่าน Google (แชร์รหัส)','tm.loading':'กำลังโหลด…','tm.loadFailed':'โหลดข้อมูลครูไม่สำเร็จ','tm.none':'ยังไม่มีครู','tm.lastLogin':'เข้าสู่ระบบล่าสุด: {date}','tm.never':'ไม่เคย','tm.idCard':'บัตรประจำตัวครู','tm.cardLoading':'กำลังสร้างบัตรที่ปลอดภัย…','tm.cardScan':'สแกน QR เพื่อเริ่มเข้าสู่ระบบครู',
    'tm.cardPurposeTitle':'บัตรนี้ใช้สำหรับอะไร',
    'tm.cardPurpose':'บัตรนี้ใช้สำหรับเข้าสู่ระบบโรงเรียนของครูอย่างปลอดภัย',
    'tm.cardStep1':'1. สแกน QR บนบัตรนี้',
    'tm.cardStep2':'2. กรอก Login Name ของคุณ',
    'tm.cardStep3':'3. กรอก PIN เพื่อเข้าสู่ระบบ',
    'tm.cardSecurity':'เก็บบัตรและ PIN ให้ปลอดภัย ห้ามแชร์ QR หรือ PIN','tm.printCard':'พิมพ์บัตร','tm.regenerateCard':'สร้างบัตรใหม่','tm.cardFailed':'ไม่สามารถสร้างบัตรครูได้','tm.resetPassword':'รีเซ็ตรหัสผ่าน',
    'inv.title':'✉️ เชิญผ่าน Google','inv.subtitle':'ครูเข้าสู่ระบบด้วยบัญชี Google ของตนเองและเข้าร่วมด้วยรหัสนี้','inv.name':'ชื่อ (ไม่บังคับ)','inv.namePh':'เช่น Daw Hla Hla','inv.role':'บทบาท *','inv.roleTeacher':'ครู','inv.roleAdmin':'ผู้ดูแลระบบ','inv.generate':'สร้างรหัส','inv.generating':'กำลังสร้าง…','inv.codeLabel':'รหัสเชิญ','inv.hint':'ส่งรหัสนี้ให้ครู (ใช้ได้ 14 วัน) ครูสามารถใช้รหัสจาก Google Sign-In → “ฉันมีรหัสเชิญ”','inv.pastInvites':'คำเชิญก่อนหน้า','inv.usedBy':'✅ ใช้โดย {id}','inv.expired':'⌛ หมดอายุ','inv.pending':'⏳ รอดำเนินการ','inv.back':'ย้อนกลับ','inv.failed':'สร้างคำเชิญไม่สำเร็จ: {err}'
  });
  Object.assign(overrides, {
    'students.stat.students':'นักเรียน','students.stat.classes':'ชั้นเรียน','students.stat.hereToday':'มาเรียนวันนี้','students.subtitle':'นักเรียนที่ใช้งานอยู่ {n} คน ใน {c} ชั้นเรียน','students.empty.title':'ไม่พบนักเรียน','students.empty.searchHint':'ลองค้นหาด้วยคำอื่น','students.empty.addHint':'แตะ + เพื่อเพิ่มนักเรียน','students.notMarked':'ยังไม่ได้ทำเครื่องหมาย','students.tgLinked':'เชื่อมต่อ TG แล้ว','students.homeLabel':'บ้าน:','students.bday.today':'วันนี้!','students.bday.tooltip':'วันเกิดในอีก {n} วัน','students.linked':'✓ เชื่อมต่อแล้ว','students.getLink':'รับลิงก์ →','students.sendLinkBtn':'📤 ส่งลิงก์ให้ผู้ปกครอง','students.field.gender':'เพศ','students.field.grade':'ระดับชั้น','students.field.birthday':'วันเกิด','students.field.home':'บ้าน','students.field.parent':'ผู้ปกครอง','students.field.parentPhone':'โทรศัพท์ผู้ปกครอง','students.field.parentEmail':'อีเมลผู้ปกครอง','students.field.parentTg':'Telegram ผู้ปกครอง','students.detail.recentReports':'รายงานล่าสุด','students.detail.recentIncidents':'เหตุการณ์ล่าสุด','students.detail.editInfo':'แก้ไขข้อมูลนักเรียน',
    'students.form.editTitle':'แก้ไขนักเรียน','students.form.addTitle':'เพิ่มนักเรียนใหม่','students.form.removePhoto':'ลบรูปภาพ','students.form.localName':'ชื่อท้องถิ่น (เมียนมา / ชื่อพื้นเมือง)','students.form.localNamePh':'ชื่อนักเรียน…','students.form.englishName':'ชื่อภาษาอังกฤษ *','students.form.englishNamePh':'ชื่อภาษาอังกฤษเต็ม','students.form.class':'ชั้นเรียน *','students.form.selectClass':'เลือกชั้นเรียน','students.form.grade':'ระดับชั้น','students.form.selectGrade':'เลือกระดับชั้น','students.form.gender':'เพศ','students.form.genderM':'ชาย','students.form.genderF':'หญิง','students.form.genderOther':'อื่นๆ','students.form.birthday':'วันเกิด','students.form.birthdayHint':'(ใช้สำหรับการแจ้งเตือน 🎂)','students.form.homeColor':'สีบ้าน','students.form.homeColorHint':'(ทีม / บ้าน)','students.form.parentSection':'ผู้ปกครอง / ผู้ดูแล','students.form.parentName':'ชื่อผู้ปกครอง','students.form.parentNamePh':'ชื่อผู้ปกครอง / ผู้ดูแล','students.form.parentPhone':'โทรศัพท์ผู้ปกครอง','students.form.parentPhonePh':'+95 9 xxx xxx xxx','students.form.parentEmail':'อีเมลผู้ปกครอง','students.form.parentEmailOptional':'อีเมลผู้ปกครอง (ไม่บังคับ)','students.form.parentEmailPh':'parent@example.com','students.form.parentTg':'Telegram ผู้ปกครอง','students.form.saveEdit':'บันทึกการเปลี่ยนแปลง','students.form.register':'ลงทะเบียนนักเรียน','students.form.removeBtn':'ลบนักเรียน','students.form.savingEdit':'กำลังบันทึก…','students.form.registering':'กำลังลงทะเบียน…','students.form.parentTgInfo':'ID Telegram ของผู้ปกครองจะถูกกรอก <b>อัตโนมัติ</b> หลังลงทะเบียนนักเรียน เราจะแสดงลิงก์ให้แชร์กับผู้ปกครอง เมื่อแตะลิงก์ใน Telegram ระบบจะบันทึก ID ให้โดยอัตโนมัติ',
    'students.toast.imageOnly':'กรุณาเลือกไฟล์รูปภาพ','students.toast.imageTooBig':'รูปภาพใหญ่เกินไป (สูงสุด 20 MB)','students.toast.studentNotFound':'ไม่พบนักเรียน','students.toast.nameRequired':'ต้องระบุชื่อภาษาอังกฤษ','students.toast.classRequired':'ต้องระบุชั้นเรียน','students.toast.emailInvalid':'อีเมลผู้ปกครองไม่ถูกต้อง','students.toast.phoneInvalid':'โทรศัพท์ผู้ปกครองไม่ถูกต้อง','students.toast.updated':'✓ อัปเดต {name} แล้ว','students.toast.registered':'✓ ลงทะเบียน {name} แล้ว','students.toast.photoUploadFailedEdit':'บันทึกแล้ว แต่การอัปโหลดรูปภาพล้มเหลว: {err}','students.toast.photoRemoveFailed':'บันทึกแล้ว แต่การลบรูปภาพล้มเหลว: {err}','students.toast.photoUploadFailedAdd':'ลงทะเบียนแล้ว แต่การอัปโหลดรูปภาพล้มเหลว: {err}','students.toast.saveFailed':'บันทึกไม่สำเร็จ: {err}','students.toast.registerFailed':'ลงทะเบียนไม่สำเร็จ: {err}','students.delete.title':'ลบ {name}?','students.delete.body':'นักเรียนจะถูกทำเครื่องหมายเป็น <b>ไม่ใช้งาน</b> ข้อมูลเดิมยังคงอยู่ แต่จะไม่แสดงในรายการรายวัน','students.delete.confirm':'ใช่ ลบ','students.delete.done':'✓ ลบนักเรียนแล้ว',
    'parentLink.title':'เชื่อมต่อ Telegram ของผู้ปกครอง','parentLink.body':'แชร์ลิงก์นี้ให้ผู้ปกครองของ {name} เมื่อผู้ปกครองแตะลิงก์ใน Telegram ระบบจะเชื่อม ID กับนักเรียนโดยอัตโนมัติ','parentLink.copy':'📋 คัดลอกลิงก์','parentLink.share':'📤 แชร์ผ่าน Telegram','parentLink.waiting':'รอผู้ปกครองแตะลิงก์…','parentLink.linkedHtml':'✓ <b>เชื่อมต่อแล้ว!</b> Parent ID: <code>{id}</code>','parentLink.done':'เสร็จแล้ว — ฉันจะแชร์ภายหลัง','parentLink.copied':'✓ คัดลอกลิงก์แล้ว','parentLink.copyFail':'คัดลอกไม่สำเร็จ — กดค้างเพื่อคัดลอกด้วยตนเอง','parentLink.shareText':'สวัสดี! กรุณาแตะลิงก์นี้ใน Telegram เพื่อรับข้อมูลอัปเดตเกี่ยวกับ {name} จากโรงเรียน:',
    'picker.class.title':'เลือกชั้นเรียน','picker.class.addLabel':'เพิ่มชั้นเรียนใหม่','picker.class.placeholder':'(เช่น P4 Online)','picker.grade.title':'เลือกระดับชั้น','picker.grade.addLabel':'เพิ่มระดับชั้นใหม่','picker.select':'เลือก…','picker.empty':'ยังไม่มีตัวเลือก — เพิ่มด้านล่าง','picker.typeName':'กรุณาพิมพ์ชื่อก่อน','picker.deleteConfirm':'ลบ "{value}" จากรายการ {list} หรือไม่?',
    'leave.pageEyebrow':'คำขอ','leave.pageTitle':'คำขอลา','leave.loading':'กำลังโหลดคำขอลา…','leave.empty':'ไม่มีคำขอลา','leave.status.Pending':'รอดำเนินการ','leave.status.Approved':'อนุมัติแล้ว','leave.status.Rejected':'ปฏิเสธแล้ว','leave.approve':'อนุมัติ','leave.reject':'ปฏิเสธ','leave.approveTitle':'อนุมัติคำขอลานี้?','leave.approveMsg':'ระบบจะทำเครื่องหมาย “ลา” ให้ทุกวันในช่วงที่เลือก','leave.rejectTitle':'ปฏิเสธคำขอลานี้?','leave.rejectMsg':'ผู้ปกครองจะไม่ถูกแจ้งเตือนอัตโนมัติ','leave.decided':'คำขอลา {status}, ทำเครื่องหมายแล้ว {n} วัน','leave.decideFailed':'อัปเดตคำขอนี้ไม่สำเร็จ',
    'dash.classesToday':'ชั้นเรียนวันนี้','dash.notYetMarked':'ยังไม่ได้ทำเครื่องหมาย','dash.homeworkLogged2d':'การบ้านที่บันทึก (2 วัน)','dash.recentIncidents':'เหตุการณ์ล่าสุด','dash.messagesQueued':'ข้อความรอส่ง','dash.myClassesOnly':'เฉพาะชั้นเรียนของฉัน',
'dash.wholeSchool':'ทั้งโรงเรียน','dash.dashboardScope':'ขอบเขตแดชบอร์ด','dash.noAssignedClasses':'ยังไม่มีชั้นเรียนที่กำหนดให้บัญชีครูของคุณ','dash.todaysSchedule':'ตารางวันนี้','dash.noClassesToday':'วันนี้ไม่มีชั้นเรียน','dash.quickActions':'การดำเนินการด่วน','dash.takeAttendance':'เช็กชื่อ','dash.logHomework':'บันทึกการบ้าน','dash.messageParent':'ส่งข้อความถึงผู้ปกครอง','dash.recordIncident':'บันทึกเหตุการณ์','dash.studentsAttention':'นักเรียนที่ต้องติดตาม','dash.recentIncidentsTitle':'เหตุการณ์ล่าสุด','dash.absences14':'ขาดเรียน {n} ครั้งใน 14 วันที่ผ่านมา','dash.bannerTitle':'ส่งข้อความไม่สำเร็จ {n} ข้อความ','dash.bannerText':'บอทส่ง Telegram ออฟไลน์ ข้อความผู้ปกครองเหล่านี้ยังค้างอยู่ในคิว','dash.loading':'กำลังโหลดแดชบอร์ด…','dash.loadFailed':'โหลดแดชบอร์ดไม่สำเร็จ','dash.todayLabel':'วันนี้','dash.totalStudents':'นักเรียนทั้งหมด','dash.presentToday':'มาเรียนวันนี้','dash.absentToday':'ขาดวันนี้','dash.pendingHomework':'การบ้านค้าง','dash.leaveRequests':'คำขอลา','dash.notifications':'การแจ้งเตือน','dash.newCount':'ใหม่ {n} รายการ','dash.leavePendingOne':'มีคำขอลา {n} รายการรอดำเนินการ','dash.leavePendingMany':'มีคำขอลา {n} รายการรอดำเนินการ','dash.leaveReview':'มีคำขอลาใหม่ที่ต้องตรวจสอบ','dash.messageNotDeliveredOne':'มีข้อความ {n} รายการที่ยังส่งไม่สำเร็จ','dash.messageNotDeliveredMany':'มีข้อความ {n} รายการที่ยังส่งไม่สำเร็จ','dash.noNewNotifications':'ไม่มีการแจ้งเตือนใหม่',
  'dash.fromDashboard': 'เลือกจากแดชบอร์ด',
    'idCard.title':'บัตรประจำตัวนักเรียน','idCard.failed':'สร้างบัตรไม่ได้: {err} นักเรียนต้องมีสถานะใช้งาน','idCard.scanHint':'ผู้ปกครองสแกนเพื่อเข้าสู่ Parent Portal','idCard.copyLink':'คัดลอกลิงก์','idCard.testHint':'ใช้ทดสอบลิงก์หรือส่งให้ผู้ปกครองโดยตรง','idCard.print':'🖨 พิมพ์บัตร','idCard.lost':'🔄 บัตรหาย — ออกโค้ดใหม่','idCard.regenTitle':'🔄 ออกโค้ดใหม่?','idCard.regenBody':'QR ของบัตรเก่าจะหยุดทำงานทันที','idCard.regenConfirm':'ออกโค้ดใหม่','idCard.regenDone':'✓ ออกโค้ดใหม่แล้ว','idCard.selectMode':'เลือกสำหรับบัตร','idCard.nSelected':'เลือกแล้ว {n} รายการ','idCard.selectAllVisible':'เลือกทั้งหมดที่แสดง','idCard.selectNone':'ล้าง','idCard.printSelected':'พิมพ์บัตรนักเรียน','idCard.preparing':'กำลังเตรียม {n} บัตร…','idCard.orientVertical':'บัตรแนวตั้ง','idCard.orientHorizontal':'บัตรแนวนอน',
    'stuLib.title':'การยืมหนังสือ','stuLib.empty':'ยังไม่มีรายการยืม','stuLib.since':'ตั้งแต่ {date}','stuLib.returnedOn':'คืนเมื่อ {date}','stuLib.return':'คืน','stuLib.returned':'✓ คืนแล้ว','stuTr.title':'การเดินทาง','stuTr.none':'ยังไม่มีเส้นทาง','stuTr.goto':'ไปที่การเดินทาง','stuTr.route':'เส้นทาง','stuTr.driver':'คนขับ','stuTr.phone':'โทรศัพท์','stuTr.pickupStop':'จุดรับ','stuTr.pickupTime':'เวลารับ','stuTr.dropoffTime':'เวลาส่ง','stuTr.manage':'จัดการการเดินทาง',
    'picker.remove':'ลบ','picker.removeFromList':'ลบจากรายการ','picker.deleteNote':'นักเรียนที่มีอยู่ใน {kind} นี้จะไม่ได้รับผลกระทบ','picker.list.classes':'ชั้นเรียน','picker.list.grades':'ระดับชั้น','picker.kind.classes':'ชั้นเรียน','picker.kind.grades':'ระดับชั้น',
    'att.code.P.label':'มาเรียน','att.code.P.short':'มา','att.code.P.desc':'นักเรียนมาเรียน','att.code.A.label':'ขาดเรียน','att.code.A.short':'ขาด','att.code.A.desc':'ขาดโดยไม่มีเหตุผล','att.code.L.label':'ลา','att.code.L.short':'ลา','att.code.L.desc':'ได้รับอนุมัติให้ลา','att.code.T.label':'สาย','att.code.T.short':'สาย','att.code.T.desc':'มาสาย','att.code.S.label':'ป่วย','att.code.S.short':'ป่วย','att.code.S.desc':'ลาป่วย','att.code.E.label':'มีเหตุผล','att.code.E.short':'มีเหตุ','att.code.E.desc':'การขาดที่ได้รับอนุญาต','att.code.H.label':'ครึ่งวัน','att.code.H.short':'½ วัน','att.code.H.desc':'มาเรียนเพียงบางส่วนของวัน','att.noClasses':'ไม่มีชั้นเรียน — เพิ่มนักเรียนก่อน','att.classOption':'ชั้นเรียน {name}','att.noActive':'ไม่มีนักเรียนที่ใช้งานใน {cls}','att.noteAdd':'เพิ่มหมายเหตุ','att.noteAddTitle':'เพิ่มเหตุผล / หมายเหตุ','att.hasNote':'มีหมายเหตุ: {note}','att.codeGroup':'รหัสการเข้าเรียน','att.notMarkedYet':'ยังไม่ได้ทำเครื่องหมาย','att.noteTitle':'หมายเหตุสำหรับ {name}','att.currentStatus':'สถานะปัจจุบัน:','att.reasonLabel':'เหตุผล / หมายเหตุ (ไม่บังคับ)','att.reasonPh':'เช่น ไปพบแพทย์ งานครอบครัว รถมาสาย…','att.charCount':'{n} / 200 ตัวอักษร','att.saveNote':'บันทึกหมายเหตุ','att.noteSaved':'บันทึกหมายเหตุแล้ว','att.noteRemoved':'ลบหมายเหตุแล้ว','att.markedAll':'ทำเครื่องหมายทั้งหมดเป็น {label}','att.cleared':'ล้างเครื่องหมายแล้ว','att.legendTitle':'รหัสการเข้าเรียน','att.legendHint':'แตะรหัสใต้ชื่อนักเรียนเพื่อทำเครื่องหมาย','att.gotIt':'เข้าใจแล้ว','att.stat.marked':'ทำเครื่องหมายแล้ว','att.stat.more':'เพิ่มเติม','att.selectClassFirst':'เลือกชั้นเรียนก่อน','att.noStudentsInClass':'ไม่มีนักเรียนในชั้นเรียนนี้','att.saved':'✓ บันทึกการเข้าเรียนสำหรับ {cls} — {date}','att.saveFailed':'บันทึกไม่สำเร็จ: {err}',
    'landing.subtitle':'การเช็กชื่อ การบ้าน การอัปเดตผู้ปกครอง และทีมของคุณ — รวมไว้ในที่เดียว','landing.getStarted':'หรือเริ่มต้นใช้งาน','landing.registerSchoolSub':'ตั้งค่าโรงเรียนผ่าน Telegram','landing.joinSchoolSub':'สมัครเป็นครู','landing.parentQ':'คุณเป็นผู้ปกครองหรือไม่?','landing.parentBody':'ไม่ต้องติดตั้งแอป ขอให้ครูส่งลิงก์ผ่าน Telegram แล้วคุณจะได้รับรายงานที่นั่น','landing.waitTg':'กำลังรอ Telegram…','landing.waitTgSub':'เราเปิด Telegram แล้ว แตะ <b>Start</b> ในบอทเพื่อเข้าสู่ระบบ','landing.openAgain':'เปิด Telegram อีกครั้ง','landing.tgNotOpen':'Telegram ไม่เปิด?','landing.tgManual':'คัดลอกลิงก์นี้แล้วเปิดใน Telegram ด้วยตนเอง:','landing.copyLink':'📋 คัดลอกลิงก์','landing.copied':'✓ คัดลอกแล้ว','landing.checking':'กำลังตรวจสอบการเข้าสู่ระบบ…','landing.timeout':'หมดเวลา ลองอีกครั้งไหม?','landing.signedIn':'เข้าสู่ระบบแล้ว! กำลังโหลดโรงเรียน…',
    'login.sub':'ใช้ Teacher ID ที่ผู้ดูแลโรงเรียนให้คุณ','login.needBoth':'กรอก Teacher ID และรหัสผ่านทั้งสองช่อง','login.failed':'เข้าสู่ระบบไม่สำเร็จ','login.connErr':'เกิดข้อผิดพลาดในการเชื่อมต่อ — ตรวจสอบอินเทอร์เน็ต','pw.titleFirst':'ตั้งรหัสผ่านใหม่','pw.titleChange':'เปลี่ยนรหัสผ่าน','pw.firstNote':'คุณต้องเปลี่ยนรหัสผ่านเมื่อเข้าสู่ระบบครั้งแรก','pw.btnFirst':'ตั้งรหัสผ่านและดำเนินการต่อ','pw.tooShort':'รหัสผ่านต้องมีอย่างน้อย 6 ตัวอักษร','pw.mismatch':'รหัสผ่านไม่ตรงกัน','pw.sessionExpired':'เซสชันหมดอายุ — กรุณาเข้าสู่ระบบอีกครั้ง','pw.failed':'เปลี่ยนรหัสผ่านไม่สำเร็จ','pw.connErr':'ข้อผิดพลาดในการเชื่อมต่อ','pw.done':'✓ เปลี่ยนรหัสผ่านแล้ว','login.help':'ไม่มี Teacher ID? ขอให้ผู้ดูแลสร้างให้ หรือใช้ <b>เข้าสู่ระบบด้วย Telegram</b>',
    'page.dashboard.sub':'ภาพรวมประจำวันของคุณ','page.students.eyebrow':'รายชื่อนักเรียน','page.attend.eyebrow':'เช็กชื่อประจำวัน','page.attend.sub':'ทำเครื่องหมายการเข้าเรียนวันนี้','page.daily.eyebrow':'สำหรับผู้ปกครอง','page.daily.title':'<em>รายงานประจำวัน</em>','page.daily.sub':'ภาพรวมวันนี้สำหรับส่งให้ผู้ปกครอง','page.hw.eyebrow':'งานที่มอบหมาย','page.hw.sub':'ติดตามและมอบหมายงานแต่ละชั้น','page.grades.eyebrow':'การประเมิน','page.grades.sub':'บันทึกและติดตามคะแนนนักเรียน','page.billing.eyebrow':'ค่าธรรมเนียม','page.billing.sub':'ใบแจ้งหนี้และการชำระเงินของนักเรียน','page.admissions.eyebrow':'การรับสมัคร','page.admissions.sub':'ติดตามผู้สมัครตั้งแต่สอบถามจนถึงลงทะเบียน','page.library.eyebrow':'ทรัพยากร','page.library.sub':'แค็ตตาล็อกหนังสือและการยืม','page.transport.eyebrow':'ทรัพยากร','page.transport.sub':'เส้นทางรถและการรับส่งนักเรียน','page.parents.eyebrow':'การสื่อสาร','page.parents.title':'ข้อความ<em>ผู้ปกครอง</em>','page.parents.sub':'การสื่อสารล่าสุดกับครอบครัว','page.incidents.eyebrow':'บันทึก','page.incidents.sub':'พฤติกรรม ความสำเร็จ และหมายเหตุสำคัญ','page.timetable.eyebrow':'ตารางเวลา','page.summary.eyebrow':'การวิเคราะห์','page.more.eyebrow':'เครื่องมือ',
    'msg.offlineBanner':'📡 ออฟไลน์ — การเปลี่ยนแปลงจะซิงก์เมื่อเชื่อมต่ออีกครั้ง','btn.retry':'ลองอีกครั้ง','menu.open':'เปิดเมนู','menu.title':'เมนู','status.connection':'สถานะการเชื่อมต่อ','lang.switchTitle':'เปลี่ยนภาษา','btn.refreshData':'รีเฟรชข้อมูล','students.searchPh':'ค้นหานักเรียน…','att.prevWeek':'สัปดาห์ก่อน','att.jumpToday':'ไปวันนี้','att.nextWeek':'สัปดาห์ถัดไป','btn.addNew':'เพิ่มใหม่','billing.feeItems':'รายการค่าธรรมเนียม','att.legendBtn':'ดูรหัสการเข้าเรียน',
    'module.incidents':'เหตุการณ์','module.grades':'ผลการเรียน','module.billing':'การเรียกเก็บเงิน','module.admissions':'การรับสมัคร','module.library':'ห้องสมุด','module.transport':'การเดินทาง','module.parents':'ผู้ปกครอง','module.timetable':'ตารางเรียน','module.summary':'สรุป',
    'sb.dashboard':'แดชบอร์ด','sb.leave':'การลา','page.leave.eyebrow':'คำขอ','page.leave.title':'คำขอลา','sb.students':'นักเรียน','sb.attend':'เข้าเรียน','sb.daily':'รายวัน','sb.hw':'การบ้าน','sb.chat':'แชต','sb.settings':'การตั้งค่า','sb.signout':'ออกจากระบบ','sb.cover':'ภาพหน้าปก','sb.changeCover':'เปลี่ยนภาพหน้าปก','sb.changeLogo':'เปลี่ยนโลโก้',
    'more.browse':'เรียกดู','more.help':'ช่วยเหลือ','more.modules':'โมดูล','more.staffChat':'แชตทีมงาน','more.admin':'ผู้ดูแลระบบ','more.logo':'โลโก้','more.cover':'ภาพหน้าปก','more.classes':'ชั้นเรียน','more.schoolSettings':'การตั้งค่าโรงเรียน','more.teachers':'ครู','more.export':'ส่งออก','more.exportSoon':'การส่งออกจะพร้อมเร็วๆ นี้','more.display':'การแสดงผล','more.bottomBar':'แถบด้านล่าง','more.bottomBarSub':'แสดงแถบนำทางด้านล่าง','more.bottomBarOn':'เปิด','more.bottomBarOff':'ปิด','more.about':'เกี่ยวกับ','more.schoolId':'รหัสโรงเรียน','more.activeStudents':'นักเรียนที่ใช้งาน','more.platform':'แพลตฟอร์ม','more.version':'เวอร์ชัน','more.currentTerm':'ภาคเรียนปัจจุบัน','more.changeLogo':'เปลี่ยนโลโก้','more.changePhoto':'เปลี่ยนรูปภาพ','more.changePhotoAria':'เปลี่ยนรูปภาพ','more.logoAlt':'โลโก้โรงเรียน',
    'modules.title':'โมดูล','modules.hint':'เลือกโมดูลที่ต้องการแสดงในเมนูด้านข้าง','modules.showInSidebar':'แสดงในแถบด้านข้าง','modules.save':'บันทึก','modules.needWeb':'ต้องใช้เว็บ','modules.saved':'✓ บันทึกแล้ว',
    'signout.title':'ออกจากระบบ?','signout.body':'คุณแน่ใจหรือไม่ว่าต้องการออกจากระบบ','schoolInfo.title':'ข้อมูลโรงเรียน','schoolInfo.name':'ชื่อโรงเรียน','schoolInfo.subjects':'วิชา','schoolInfo.attCodes':'รหัสการเข้าเรียน','schoolInfo.currency':'สกุลเงิน','schoolInfo.hint':'ข้อมูลนี้ใช้ทั่วทั้งโรงเรียน',
    'cg.adminOnly':'เฉพาะผู้ดูแลระบบ','cg.none':'ยังไม่มีข้อมูล','cg.hint':'จัดการชั้นเรียนและระดับชั้นของโรงเรียน','cg.classes':'ชั้นเรียน','cg.grades':'ระดับชั้น','cg.classPh':'เช่น P4 Online','cg.gradePh':'เช่น Grade 4','cg.exists':'มีอยู่แล้ว','common.done':'เสร็จแล้ว','common.saved':'บันทึกแล้ว','common.saveFailedShort':'บันทึกไม่สำเร็จ','common.unknown':'ไม่ทราบ',
    'boot.openingTg':'กำลังเปิด Telegram','boot.starting':'กำลังเริ่มต้น…','boot.preview':'ตัวอย่าง','boot.title':'กำลังเปิด SCMS','boot.auth':'กำลังตรวจสอบสิทธิ์','boot.loadingSchool':'กำลังโหลดโรงเรียน','boot.building':'กำลังเตรียมระบบ','boot.signingIn':'กำลังเข้าสู่ระบบ','boot.loadingYourSchool':'กำลังโหลดโรงเรียนของคุณ',
    'err.connFailed':'การเชื่อมต่อล้มเหลว','err.authFailed':'การยืนยันตัวตนล้มเหลว','err.notRegistered':'ยังไม่ได้ลงทะเบียน','err.startup':'เริ่มต้นระบบไม่สำเร็จ','err.unknown':'เกิดข้อผิดพลาดที่ไม่ทราบสาเหตุ','toast.refreshing':'กำลังรีเฟรช…','toast.updated':'อัปเดตแล้ว','toast.refreshFailed':'รีเฟรชไม่สำเร็จ','subject.add':'เพิ่มวิชา','subject.ph':'ชื่อวิชา','subject.enter':'กรุณาใส่ชื่อวิชา','subject.adding':'กำลังเพิ่ม…','subject.added':'✓ เพิ่มวิชาแล้ว','picker.searchPh':'ค้นหา…','chat.ph':'พิมพ์ข้อความ…','chat.loadFailed':'โหลดแชตไม่สำเร็จ','chat.retry':'ลองอีกครั้ง','chat.emptyTitle':'ยังไม่มีข้อความ','chat.emptySub':'เริ่มการสนทนาได้เลย','chat.sendFailed':'ส่งข้อความไม่สำเร็จ',
    'enum.meal.Full':'หมดจาน','enum.meal.Half':'ครึ่งหนึ่ง','enum.meal.Little':'เล็กน้อย','enum.meal.None':'ไม่ได้กิน','enum.mood.Happy':'มีความสุข','enum.mood.OK':'ปกติ','enum.mood.Tired':'เหนื่อย','enum.mood.Sad':'เศร้า','enum.mood.Energetic':'กระฉับกระเฉง','enum.yesno.Yes':'ใช่','enum.yesno.No':'ไม่','enum.hwType.Homework':'การบ้าน','enum.hwType.Lesson':'บทเรียน','enum.hwType.Test':'แบบทดสอบ','enum.hwType.Quiz':'แบบทดสอบสั้น','enum.hwType.Project':'โครงงาน','enum.hwType.Worksheet':'ใบงาน','enum.commType.All':'ทั้งหมด','enum.commType.General':'ทั่วไป','enum.commType.Absent Alert':'แจ้งขาดเรียน','enum.commType.Daily Report':'รายงานประจำวัน','enum.commType.Praise':'ชื่นชม','enum.commType.Incident':'เหตุการณ์','enum.commType.Homework':'การบ้าน','enum.commType.Broadcast':'ประกาศ','enum.commStatus.Sent':'ส่งแล้ว','enum.commStatus.queued':'รอส่ง','enum.commStatus.Queued':'รอส่ง','enum.incType.All':'ทั้งหมด','enum.incType.Good Behaviour':'พฤติกรรมดี','enum.incType.Participation':'การมีส่วนร่วม','enum.incType.Achievement':'ความสำเร็จ','enum.incType.Concern':'ข้อกังวล','enum.incType.Conflict':'ความขัดแย้ง','enum.incType.Health':'สุขภาพ','enum.incType.Bullying':'การกลั่นแกล้ง','enum.incType.Injury':'การบาดเจ็บ','enum.incType.Other':'อื่นๆ','enum.severity.Info':'ข้อมูล','enum.severity.Low':'ต่ำ','enum.severity.Medium':'ปานกลาง','enum.severity.High':'สูง','enum.severity.Critical':'วิกฤต','enum.subject.Mathematics':'คณิตศาสตร์','enum.subject.English':'ภาษาอังกฤษ','enum.subject.Science':'วิทยาศาสตร์','enum.subject.Social Studies':'สังคมศึกษา',
    'common.deleted':'ลบแล้ว','common.itemNotFound':'ไม่พบรายการ','common.cantUndo':'ไม่สามารถยกเลิกได้','common.saveChanges':'บันทึกการเปลี่ยนแปลง','common.opt':'ไม่บังคับ',
    'daily.noClasses':'ไม่มีชั้นเรียน','daily.addStudentsFirst':'เพิ่มนักเรียนก่อน','daily.nap':'งีบ','daily.min':'นาที','daily.notFilled':'ยังไม่ได้กรอก','daily.confirmDelete':'ลบรายงานนี้?','daily.mealToday':'มื้ออาหารวันนี้','daily.napMin':'เวลางีบ (นาที)','daily.mood':'อารมณ์','daily.behaviourNote':'หมายเหตุพฤติกรรม','daily.behaviourPh':'เขียนหมายเหตุ…','daily.toilet':'ห้องน้ำ','daily.save':'บันทึก','daily.pickMeal':'เลือกมื้ออาหาร','daily.pickMood':'เลือกอารมณ์','daily.pickerTitle':'รายงานของนักเรียน',});
  Object.assign(overrides, {
    'students.rollNo':'เลขที่','students.section':'ห้อง','students.searchPlaceholder':'ค้นหาด้วยชื่อหรือเลขที่','common.optional':'(ไม่บังคับ)','common.error':'ข้อผิดพลาด','common.networkError':'ข้อผิดพลาดของเครือข่าย','common.loadFailed':'โหลดไม่สำเร็จ: {err}','students.subtitleOneClass':'นักเรียนที่ใช้งานอยู่ {n} คน ใน {c} ชั้นเรียน','students.subtitleOne':'นักเรียนที่ใช้งานอยู่ {n} คน ใน {c} ชั้นเรียน','students.bday.tooltipOne':'วันเกิดใน 1 วัน','students.bday.short':'{n} วัน','students.detail.meal':'มื้ออาหาร:','students.btn.health':'ข้อมูลสุขภาพ',
    'color.red':'แดง','color.orange':'ส้ม','color.amber':'อำพัน','color.yellow':'เหลือง','color.lime':'เขียวมะนาว','color.green':'เขียว','color.teal':'เขียวอมฟ้า','color.cyan':'ฟ้าอมเขียว','color.sky':'ฟ้า','color.blue':'น้ำเงิน','color.indigo':'คราม','color.violet':'ม่วง','color.fuchsia':'ฟูเชีย','color.pink':'ชมพู','color.rose':'กุหลาบ','color.slate':'เทาเข้ม','page.summary.sub':'ภาพรวมผลการดำเนินงานของเดือนนี้','hw.none':'ยังไม่มีการบ้าน',
    'ct.title':'+ ครูใหม่','ct.subtitle':'สร้างบัญชีเข้าสู่ระบบ ครูจะต้องเปลี่ยนรหัสผ่านเริ่มต้น','ct.teacherId':'Teacher ID *','ct.teacherIdPh':'เช่น T1001','ct.loginName':'ชื่อเข้าสู่ระบบ *','ct.loginNamePh':'เช่น teacher1','ct.teacherName':'ชื่อครู *','ct.email':'อีเมล (ไม่บังคับ)','ct.role':'บทบาท *','ct.roleAdmin':'ผู้ดูแลระบบ (จัดการครูคนอื่นได้)','ct.startPw':'รหัสผ่านเริ่มต้น (≥ 6 ตัวอักษร) *','ct.startPwHint':'แชร์รหัสผ่านนี้อย่างปลอดภัย ครูจะเปลี่ยนเมื่อเข้าสู่ระบบครั้งแรก','ct.create':'สร้างบัญชี','ct.needFields':'ต้องกรอก Teacher ID ชื่อ และรหัสผ่าน','ct.pwTooShort':'รหัสผ่านต้องมีอย่างน้อย 6 ตัวอักษร','ct.sessionExpired':'เซสชันผู้ดูแลหมดอายุ กรุณาเข้าสู่ระบบอีกครั้ง','ct.creating':'กำลังสร้าง…','ct.createFailed':'สร้างไม่สำเร็จ','ct.created':'✓ สร้างบัญชีครูแล้ว','ct.connErr':'ข้อผิดพลาดในการเชื่อมต่อ','rp.prompt':'รีเซ็ตรหัสผ่านของ {name} ({id})\n\nรหัสผ่านใหม่ (≥ 6 ตัวอักษร):','rp.sessionExpired':'เซสชันผู้ดูแลหมดอายุ','rp.failed':'รีเซ็ตไม่สำเร็จ: {err}','rp.done':'✓ รหัสผ่านใหม่ของ {name}: {pw}\nกรุณาแชร์ให้ครู',
    'ga.signingIn':'กำลังเข้าสู่ระบบ…','ga.loginFailed':'เข้าสู่ระบบไม่สำเร็จ','ga.connErr':'ข้อผิดพลาดในการเชื่อมต่อ — ตรวจสอบอินเทอร์เน็ต','ga.welcome':'👋 ยินดีต้อนรับ','ga.noAccount':'ยังไม่มีบัญชี SCMS กับบัญชี Google นี้ ต้องการทำอะไร?','ga.startSchool':'เริ่มโรงเรียนใหม่','ga.startSchoolSub':'คุณจะเป็นผู้ดูแลระบบ','ga.haveInvite':'ฉันมีรหัสเชิญ','ga.haveInviteSub':'เข้าร่วมด้วยรหัสจากผู้ดูแล','ga.back':'← กลับ','ga.yourName':'ชื่อของคุณ','ga.namePh':'เช่น Sangfa','ga.schoolName':'ชื่อโรงเรียน','ga.schoolNamePh':'เช่น Vavida ISB','ga.startSchoolBtn':'เริ่มโรงเรียน','ga.enterSchoolName':'กรุณาใส่ชื่อโรงเรียน','ga.inviteCode':'รหัสเชิญ','ga.inviteCodePh':'เช่น AC3F79','ga.join':'เข้าร่วม','ga.enterInviteCode':'กรุณาใส่รหัสเชิญ','ga.emailSignIn':'📧 เข้าสู่ระบบด้วยอีเมล','ga.emailSignInSub':'กรอกอีเมลและรหัสผ่าน','ga.email':'อีเมล','ga.password':'รหัสผ่าน','ga.rememberMe':'จดจำฉัน','ga.signIn':'เข้าสู่ระบบ','ga.noAccountQ':'ยังไม่มีบัญชี?','ga.signUp':'สมัครบัญชี','ga.enterEmailPw':'กรอกอีเมลและรหัสผ่าน','ga.createAccount':'✨ สร้างบัญชีใหม่','ga.createAccountSub':'เลือกอีเมลและรหัสผ่านของคุณ','ga.atLeast6':'อย่างน้อย 6 ตัวอักษร','ga.whatToDo':'ต้องการทำอะไร?','ga.chooseToContinue':'เลือกตัวเลือกเพื่อดำเนินการต่อ','ga.haveAccountQ':'มีบัญชีอยู่แล้ว?','ga.enterName':'กรุณาใส่ชื่อ','ga.enterEmail':'กรุณาใส่อีเมล','ga.pwAtLeast6':'รหัสผ่านต้องมีอย่างน้อย 6 ตัวอักษร','ga.chooseSchoolOrInvite':'เลือกโรงเรียนใหม่หรือรหัสเชิญ','ga.creatingAccount':'กำลังสร้างบัญชี…','ga.signupFailed':'สมัครบัญชีไม่สำเร็จ',
    'tg.connectTitle':'🔗 เชื่อมต่อ Telegram','tg.connectSub':'เชื่อมต่อ Telegram สำหรับรายงานผู้ปกครองและการเข้าสู่ระบบสำรอง','tg.waitingStart':'เปิดบอท Telegram แล้วแตะ Start…','tg.openTelegram':'เปิด Telegram','tg.connectFailed':'เชื่อมต่อไม่สำเร็จ — ลองอีกครั้ง','tg.reopen':'เปิดอีกครั้ง','tg.waitingTap':'แตะ Start ใน Telegram… กำลังรอ','tg.timedOut':'หมดเวลา — ลองอีกครั้ง','tg.connected':'✓ เชื่อมต่อ Telegram แล้ว','tg.disconnectTitle':'🔌 ยกเลิกการเชื่อมต่อ Telegram?','tg.disconnectSub':'จะยกเลิก Telegram สำหรับรายงานผู้ปกครองและการเข้าสู่ระบบสำรอง','tg.disconnect':'ยกเลิกการเชื่อมต่อ','tg.disconnected':'ยกเลิกการเชื่อมต่อ Telegram แล้ว','ga.showPassword':'แสดงรหัสผ่าน',
    'branding.adminOnly':'เฉพาะผู้ดูแลระบบเท่านั้นที่เปลี่ยนได้','branding.chooseImage':'📷 เลือกรูปภาพ','branding.imageTypes':'กรุณาเลือก PNG, JPG หรือ WebP','branding.imageTooBig':'รูปภาพใหญ่เกินไป (สูงสุด 8 MB)','branding.tryAgain':'ลองอีกครั้ง','reg.title':'การลงทะเบียน','reg.instructions':'หากต้องการลงทะเบียนโรงเรียนใหม่หรือเข้าร่วมเป็นครู โปรดใช้คำสั่งบอท Telegram:','reg.createSchool':'สร้างโรงเรียนใหม่','reg.joinSchool':'เข้าร่วมโรงเรียนที่มีอยู่','reg.approvedNote':'เมื่อผู้ดูแลอนุมัติ บัญชีจะเปิดใช้งานและแดชบอร์ดจะโหลดอัตโนมัติ','reg.gotIt':'เข้าใจแล้ว','enum.roleName.admin':'ผู้ดูแลระบบ','enum.roleName.teacher':'ครู','enum.roleName.super_admin':'ผู้ดูแลระบบสูงสุด',
    'help.title':'วิธีใช้ SCMS','help.subtitle':'วิธีใช้ · คู่มือฉบับย่อ','help.tab.basics':'พื้นฐาน','help.tab.features':'ฟีเจอร์','help.tab.admin':'ผู้ดูแลระบบ','help.tab.trouble':'แก้ไขปัญหา','help.tab.about':'เกี่ยวกับ',
    'help.basics.introTitle':'SCMS คืออะไร?','help.basics.introBody':'ระบบจัดการชั้นเรียนโรงเรียน — จัดการโรงเรียนทั้งหมดผ่านบอท Telegram เดียว ทั้งการเข้าเรียน การบ้าน รายงานประจำวัน และข้อความถึงผู้ปกครอง','help.basics.step1Title':'เข้าสู่ระบบ','help.basics.step1Body':'แตะปุ่มเมนูในบอท Telegram เพื่อเปิดแอป ระบบตรวจพบบัญชีของคุณอัตโนมัติ','help.basics.step2Title':'แท็บด้านล่าง','help.basics.step2Body':'นักเรียน · เข้าเรียน · รายวัน · การบ้าน · เพิ่มเติม — แตะแต่ละแท็บเพื่อไปยังหน้านั้น','help.basics.step3Title':'+ ปุ่ม (FAB)','help.basics.step3Body':'ปุ่ม + ด้านขวาล่างจะทำหน้าที่เพิ่มรายการตามหน้าปัจจุบัน เช่น หน้า Student จะเพิ่มนักเรียน','help.basics.step4Title':'รีเฟรช','help.basics.step4Body':'ใช้ปุ่ม ↻ ด้านขวาบนเพื่อดึงข้อมูลล่าสุด','help.basics.tip':'เคล็ดลับ: ครั้งแรกให้เพิ่มนักเรียนก่อน จากนั้นการเข้าเรียน การบ้าน และฟีเจอร์อื่นจะทำงานได้',
    'help.feat.students.title':'นักเรียน','help.feat.students.1':'แตะบัตรนักเรียน → ดูรายละเอียด','help.feat.students.2':'ปุ่ม ✎ แก้ไขชื่อ ชั้น วันเกิด อีเมลผู้ปกครอง','help.feat.students.3':'เพิ่มนักเรียนแล้วจะมีลิงก์ผู้ปกครอง → ส่งลิงก์ → Telegram เชื่อมต่ออัตโนมัติ','help.feat.students.4':'🎂 แสดงนักเรียนที่ใกล้ถึงวันเกิด','help.feat.attend.title':'การเข้าเรียน','help.feat.attend.1':'แถบวันที่ — เลือกวันที่ต้องการบันทึก','help.feat.attend.2':'ต่อนักเรียน — แตะรหัส P/A/L/T/S/E/H','help.feat.attend.3':'“มาครบทุกคน” — ทำเครื่องหมายทุกคนในครั้งเดียว','help.feat.attend.4':'✏️ หมายเหตุ — เพิ่มเหตุผล','help.feat.attend.5':'อย่าลืมแตะ “บันทึกการเข้าเรียน”','help.feat.daily.title':'รายงานประจำวัน','help.feat.daily.1':'ต่อนักเรียน — บันทึกอาหาร อารมณ์ งีบ พฤติกรรม','help.feat.daily.2':'พร้อมส่งให้ผู้ปกครอง','help.feat.daily.3':'✎ แก้ไข, 🗑 ลบ','help.feat.hw.title':'การบ้าน','help.feat.hw.1':'เพิ่มวิชา ชั้น ประเภท และรายละเอียด','help.feat.hw.2':'เพิ่มเลขหน้า LB/WB ได้','help.feat.hw.3':'กำหนดวันครบกำหนดได้','help.feat.hw.4':'✎ แก้ไข / 🗑 ลบ','help.feat.msg.title':'ข้อความผู้ปกครอง','help.feat.msg.1':'เลือกทั้งชั้นหรือรายบุคคล','help.feat.msg.2':'พิมพ์ข้อความแล้วส่ง','help.feat.msg.3':'ส่งตรงถึงผู้ปกครองทาง Telegram','help.feat.inc.title':'เหตุการณ์','help.feat.inc.1':'บันทึกพฤติกรรม ความสำเร็จ และสุขภาพ','help.feat.inc.2':'กำหนดระดับ Info/Low/Medium/High','help.feat.inc.3':'ตัวเลือกแจ้งผู้ปกครอง',
    'help.ai.introTitle':'ผู้ช่วย AI อัจฉริยะ','help.ai.introBody':'ในแชต Telegram ไม่ต้องกรอกฟอร์ม เพียงพูดเพื่อเพิ่มข้อมูล ระบบเข้าใจทั้งภาษาไทยและอังกฤษ','help.ai.examplesLabel':'ลองพูดแบบนี้ —','help.ai.ex1':'Adam ไม่มาเรียนวันนี้','help.ai.ex2':'✓ Adam → ทำเครื่องหมายขาดเรียน','help.ai.ex3':'Hannah ป่วย','help.ai.ex4':'✓ Hannah → ทำเครื่องหมายป่วย','help.ai.ex5':'บอก P4 ว่าพรุ่งนี้มีสอบคณิตศาสตร์','help.ai.ex6':'✓ บันทึกการบ้าน · ส่งประกาศให้ผู้ปกครอง','help.ai.ex7':'ลบการบ้านคณิตศาสตร์เมื่อวาน','help.ai.ex8':'อันไหน? 1. คณิต P4 · 2. คณิต KG','help.ai.cheatLabel':'คำสั่งตามหมวดหมู่','help.ai.cheat.attend.title':'✅ การเข้าเรียน (ทั้งชั้น)','help.ai.cheat.attend.1':'“Adam มาเรียน” / “Adam present”','help.ai.cheat.attend.2':'“Hannah ขาดเรียน” / “Hannah absent”','help.ai.cheat.attend.3':'“Mg Mg ป่วย” → ป่วย','help.ai.cheat.attend.4':'“Su Su มาสาย” → สาย','help.ai.cheat.attend.5':'“P4 มาครบ” → มาครบ','help.ai.cheat.hw.title':'📚 การบ้าน','help.ai.cheat.hw.1':'“ให้ P4 คณิตหน้า 24-25”','help.ai.cheat.hw.2':'“KG ใบงานภาษาอังกฤษ 3”','help.ai.cheat.hw.3':'“แก้รายละเอียดการบ้านวิทยาศาสตร์เมื่อวาน”','help.ai.cheat.hw.4':'“ลบการบ้านคณิตวันนี้”','help.ai.cheat.daily.title':'📋 รายงานประจำวัน','help.ai.cheat.daily.1':'“วันนี้ Adam กินอาหารหมด อารมณ์ดี”','help.ai.cheat.daily.2':'“Hannah งีบ 30 นาที”','help.ai.cheat.daily.3':'“เปลี่ยนอารมณ์ของ Adam เป็นมีความสุข”','help.ai.cheat.inc.title':'⚡ เหตุการณ์','help.ai.cheat.inc.1':'“Adam ช่วยเพื่อน — พฤติกรรมดี”','help.ai.cheat.inc.2':'“เปลี่ยนระดับเหตุการณ์ของ Mg Mg เป็นสูง”','help.ai.cheat.inc.3':'“ลบเหตุการณ์ของ Hannah”','help.ai.cheat.parent.title':'💬 ผู้ปกครอง / ประกาศ','help.ai.cheat.parent.1':'“บอกผู้ปกครอง Adam ให้โทรโรงเรียน”','help.ai.cheat.parent.2':'“บอก P4 ว่าโรงเรียนปิดพรุ่งนี้”','help.ai.cheat.parent.3':'“ลบประกาศที่ส่งผิด”','help.ai.cheat.query.title':'🔍 คำถาม','help.ai.cheat.query.1':'“P4 มีนักเรียนกี่คน?”','help.ai.cheat.query.2':'“เบอร์โทร Adam”','help.ai.cheat.query.3':'“ใครขาดเรียนวันนี้?”','help.ai.cheat.query.4':'“แสดงรายชื่อนักเรียน”','help.ai.tip1':'AI ทำอะไรได้บ้าง: การเข้าเรียน รายงานประจำวัน การบ้าน เหตุการณ์ ข้อความผู้ปกครอง ประกาศ ตารางเรียน และเพิ่ม/แก้ไข/ลบข้อมูลได้ทั้งหมด','help.ai.tip2':'ระวัง: เมื่อลบหรือแก้ไข AI จะถามว่า “อันไหน?” ก่อน และจะทำงานเมื่อคุณเลือกถูกต้อง',
    'help.trouble.introTitle':'แก้ไขปัญหา','help.trouble.introBody':'หากพบปัญหา ลองวิธีแก้ด้านล่าง','help.trouble.q1':'แอปเปิดไม่ได้ / แสดง “Connection failed”','help.trouble.a1':'ตรวจสอบอินเทอร์เน็ต แล้วแตะ Retry หากยังไม่สำเร็จหลังลอง 2-3 ครั้ง ให้ติดต่อผู้ดูแล','help.trouble.q2':'บันทึกการเข้าเรียนไม่ได้','help.trouble.a2':'ตรวจสอบวันที่ด้านบน แล้วหลังทำเครื่องหมายอย่าลืมแตะ “บันทึกการเข้าเรียน”','help.trouble.q3':'เพิ่มนักเรียนไม่ได้','help.trouble.a3':'ต้องระบุชื่อภาษาอังกฤษและเลือกชั้นเรียน','help.trouble.q4':'เชื่อม Telegram ผู้ปกครองไม่ได้','help.trouble.a4':'ส่งลิงก์ให้ผู้ปกครอง หลังแตะลิงก์ให้แตะ Start ในบอท แล้วรอประมาณหนึ่งนาที','help.trouble.q5':'AI ไม่เข้าใจ','help.trouble.a5':'ลองพูดให้ชัดขึ้น เช่น “Adam ขาดเรียนวันนี้” และตรวจสอบการสะกดชื่อ','help.trouble.q6':'ข้อมูลไม่แสดง / เป็นข้อมูลเก่า','help.trouble.a6':'แตะ ↻ รีเฟรชด้านขวาบน หรือปิดแล้วเปิดแอปใหม่','help.trouble.tip':'หากยังไม่สำเร็จ ติดต่อผู้ดูแลโรงเรียนหรือช่องทางช่วยเหลือ',
    'help.admin.introTitle':'เครื่องมือผู้ดูแล','help.admin.introBody':'ผู้ดูแลสามารถเปลี่ยนการตั้งค่าของทั้งโรงเรียน','help.admin.logo.title':'โลโก้โรงเรียน','help.admin.logo.1':'เพิ่มเติม → โลโก้โรงเรียน → อัปโหลดรูป','help.admin.logo.2':'แสดงในส่วนหัว แถบด้านข้าง และรายงาน','help.admin.classes.title':'ชั้นเรียนและระดับชั้น','help.admin.classes.1':'เพิ่มเติม → ชั้นเรียนและระดับชั้น','help.admin.classes.2':'เพิ่ม/ลบชื่อชั้นเรียนของโรงเรียน','help.admin.classes.3':'รายการนี้จะแสดงเมื่อเพิ่มนักเรียน','help.admin.timetable.title':'ตารางเรียน','help.admin.timetable.1':'เพิ่มเติม → ตารางเรียน → + เพื่อเพิ่มคาบ','help.admin.timetable.2':'วัน คาบ ชั้นเรียน วิชา ห้อง','help.admin.reg.title':'การลงทะเบียน','help.admin.reg.1':'ครูใหม่ — ใช้ /register_teacher ในบอท','help.admin.reg.2':'บัญชีครูใช้งานได้เมื่อผู้ดูแลอนุมัติ',
    'help.about.introTitle':'เกี่ยวกับ SCMS','help.about.introBody':'SCMS v11 — ระบบจัดการโรงเรียนที่ใช้ Telegram เป็นหลัก สร้างสำหรับโรงเรียนเมียนมา','help.about.version':'เวอร์ชัน','help.about.platform':'แพลตฟอร์ม','help.about.school':'โรงเรียน','help.about.needHelpTitle':'ต้องการความช่วยเหลือ?','help.about.needHelpBody':'หากพบปัญหา ติดต่อผู้ดูแลโรงเรียนหรือช่องทางช่วยเหลือ','help.about.replayTour':'🔄 ดูทัวร์ต้อนรับอีกครั้ง','help.close':'ปิด',
    'tour.s1.title':'ยินดีต้อนรับสู่ SCMS 👋','tour.s1.text':'จัดการโรงเรียนทั้งหมดได้จากที่นี่ มาดูการใช้งาน 5 ขั้นตอน','tour.s2.title':'นักเรียน','tour.s2.text':'นักเรียนของคุณอยู่ที่นี่ แตะการ์ดเพื่อดูรายละเอียดหรือแก้ไข','tour.s3.title':'การเข้าเรียน','tour.s3.text':'ทำเครื่องหมายว่าใครมาเรียนหรือไม่มาในครั้งเดียวด้วย P/A/L/T/S/E/H','tour.s4.title':'+ ปุ่มเพิ่ม','tour.s4.text':'ปุ่ม + จะเพิ่มรายการใหม่ตามหน้าที่กำลังเปิดอยู่','tour.s5.title':'เพิ่มเติม — มีคู่มืออยู่ที่นี่','tour.s5.text':'แท็บเพิ่มเติมมีคู่มือ วิธีใช้ เครื่องมือผู้ดูแล และการตั้งค่า','tour.skip':'ข้าม','tour.next':'ถัดไป →','tour.done':'เสร็จ ✓'
  });
  Object.assign(overrides, {
    'modules.saveFailed':'บันทึกไม่สำเร็จ: {err}','cg.confirmRemove':'ลบ "{value}" จาก {list} หรือไม่?','cg.couldNotSave':'บันทึกไม่สำเร็จ: {err}','boot.user':'ผู้ใช้: {name}','common.deleteFailed':'ลบไม่สำเร็จ: {err}','common.updateFailed':'อัปเดตไม่สำเร็จ: {err}','daily.noStudents':'ไม่มีนักเรียนใน {cls}','daily.modalTitle':'รายงานประจำวัน — {name}','daily.saved':'✓ บันทึกรายงานสำหรับ {name} แล้ว','daily.pickerSub':'สำหรับ {date}','hw.lb':'หน้า LB p.{n}','hw.wb':'หน้า WB p.{n}','comms.classBroadcast':'ประกาศ — {class}','tt.noClasses':'ไม่มีชั้นเรียนใน {day}','tt.room':'ห้อง {n}','tt.periods':'มี {n} คาบใน {day}','tt.period1':'มี {n} คาบใน {day}','grades.metaLine':'{date} · คะแนนเต็ม {max} · น้ำหนัก {w}%','grades.classMax':'{cls} · คะแนนเต็ม {max}','bill.cardSub':'{cls} · ครบกำหนด {due} · รวม {total}'
  });
  Object.assign(overrides, {'bill.total':'รวม: {n}','bill.feePaidPending':'ชำระค่าธรรมเนียมแล้ว ✓ — {name} ยังอยู่ในสถานะ <em>รอดำเนินการ</em> และไม่แสดงในรายชื่อนักเรียน','bill.amountBalance':'จำนวนเงิน (ยอดคงเหลือ: {n})','adm.appliedOn':'สมัครเมื่อ {date}','adm.movedTo':'✓ ย้ายไป {status} แล้ว','adm.selected':'เลือกแล้ว {n} รายการ','adm.bulkMoving':'กำลังย้าย {n} รายการไป {status}…','adm.bulkMoved':'✓ {ok} รายการย้ายไป {status} แล้ว','adm.enrolling':'กำลังลงทะเบียน {n}…','adm.skipped':' ({n} รายการข้าม — ไม่มีชั้นเรียน)','adm.enrolledPending':'✓ ลงทะเบียนแล้ว {ok} รายการ (รอดำเนินการ)','adm.savedPhotoFail':'บันทึกแล้ว แต่การอัปโหลดรูปภาพล้มเหลว: {err}'});
  Object.assign(overrides, {'adm.addedPhotoFail':'เพิ่มแล้ว แต่การอัปโหลดรูปภาพล้มเหลว: {err}','adm.officialStudent':'✓ นักเรียนอย่างเป็นทางการ — ID <strong>{id}</strong>, ชั้นเรียน {cls} แสดงในรายชื่อนักเรียน','adm.pendingCreated':'สร้างรายการนักเรียนแล้ว (ID <strong>{id}</strong>) แต่สถานะเป็น <em>รอดำเนินการ</em> — จะซ่อนจากรายชื่อนักเรียนจนกว่าจะชำระค่าลงทะเบียน','adm.regPaid':'ใบแจ้งหนี้ลงทะเบียน {no} — <strong>ชำระแล้ว ✓</strong> เปิดใบแจ้งหนี้ในหน้าการเรียกเก็บเงินแล้วแตะ <em>เปิดใช้งานนักเรียน</em>','adm.regUnpaid':'ใบแจ้งหนี้ลงทะเบียน {no} — {status}, ยอดคงเหลือ {bal} บันทึกการชำระเงินในหน้าการเรียกเก็บเงิน แล้วแตะ <em>เปิดใช้งานนักเรียน</em>'});

  Object.assign(overrides, {
    'students.validation.parentEmail':'โปรดกรอกอีเมลผู้ปกครองให้ถูกต้อง','students.validation.phone1':'โปรดตรวจสอบหมายเลขโทรศัพท์หลัก','students.validation.phone2':'โปรดตรวจสอบหมายเลขโทรศัพท์สำรอง',
    'students.form.savingParent':'กำลังบันทึก…','students.toast.parentSaved':'บันทึกข้อมูลผู้ปกครองแล้ว','students.form.saveParentDetails':'บันทึกข้อมูลผู้ปกครอง','students.form.parentGuardian':'ผู้ปกครอง / ผู้ดูแล',
    'students.history.title':'ประวัตินักเรียน','students.history.empty':'ยังไม่มีประวัติ','students.toast.reactivated':'เปิดใช้งานนักเรียนอีกครั้งแล้ว',
    'att.historyRecent':'รายการล่าสุดและสรุป 30 วัน','att.report30':'รายงาน 30 วัน','att.auditWebOnly':'ดูประวัติการตรวจสอบได้เฉพาะเซสชันเว็บ',
    'att.auditTitle':'ประวัติการตรวจสอบการเข้าเรียน','att.auditSubtitle':'ประวัติการบันทึกการเข้าเรียนสำหรับผู้ดูแลระบบของโรงเรียนนี้เท่านั้น','att.auditLoading':'กำลังโหลดประวัติการตรวจสอบ…',
    'att.auditEmpty':'ไม่พบประวัติการตรวจสอบการเข้าเรียน','att.auditLoadFailed':'ไม่สามารถโหลดประวัติการตรวจสอบได้','att.correctionMode':'โหมดแก้ไข: ตรวจสอบและบันทึกวันที่ที่เลือก',
    'comms.portalScheduleTitle':'กำหนดการ Parent Portal','comms.portalScheduleSub':'แสดงการประชุม ประกาศ และกิจกรรมของโรงเรียนใน Parent Portal',
    'comms.portalTitlePh':'ตัวอย่าง — ประชุมผู้ปกครองและครู','comms.portalDescPh':'ข้อมูลที่ผู้ปกครองควรทราบ',    'comms.portalEventType':'ประเภทกิจกรรม',
    'comms.portalEventMeeting':'ประชุมผู้ปกครอง',
    'comms.portalEventAnnouncement':'ประกาศ',
    'comms.portalEventSchool':'กิจกรรมโรงเรียน',
    'comms.portalEventHoliday':'วันหยุด',
    'comms.portalTitle':'ชื่อเรื่อง',
    'comms.portalClass':'ชั้นเรียน',
    'comms.portalWholeSchool':'ทั้งโรงเรียน',
    'comms.portalStart':'เริ่มต้น',
    'comms.portalEnd':'สิ้นสุด',
    'comms.portalOptional':'ไม่บังคับ',
    'comms.portalDescription':'รายละเอียด',
    'comms.portalPublish':'เผยแพร่ไปยัง Parent Portal',
    'comms.portalCancel':'ยกเลิก',
'comms.portalRequired':'กรุณากรอกชื่อเรื่องและเวลาเริ่มต้น','comms.portalPublished':'เผยแพร่ไปยัง Parent Portal แล้ว'
  });
  Object.assign(overrides, {});
  Object.assign(overrides, {'err.sessionVerify':'ไม่สามารถตรวจสอบเซสชันที่บันทึกไว้ได้','err.retryHint':'แตะ Retry แล้วลองอีกครั้ง','err.serverUnreachable':'ไม่สามารถเชื่อมต่อเซิร์ฟเวอร์ SCMS ได้','err.technicalDetails':'รายละเอียดทางเทคนิค (โปรดแนบภาพหน้าจอเมื่อขอความช่วยเหลือ):','err.likelyCause':'สาเหตุที่เป็นไปได้: workflow n8n ยังไม่ Active, URL ไม่ถูกต้อง หรือ CORS บล็อกคำขอ'});
  Object.assign(overrides, {'login.loading':'กำลังโหลดการเข้าสู่ระบบ…','login.waitRetry':'โปรดรอสักครู่แล้วลองอีกครั้ง','cg.required':'โปรดกรอกทั้ง Class และ Grade'});
  Object.assign(overrides, {'teacher.editTitle':'แก้ไขครู','teacher.editSubtitle':'แก้ไขชื่อครูและ Login Name ที่ใช้สำหรับบัตรประจำตัวและการเข้าสู่ระบบครู','teacher.superAdmin':'ผู้ดูแลระบบสูงสุด'});
  Object.assign(overrides, {'settings.theme':'ธีม','settings.themeLight':'☀️ สว่าง','settings.themeDark':'🌙 มืด'});
  Object.assign(overrides, {
    'login.loginNamePh':'เช่น teacher1','cg.pairHint':'จัดการชั้นเรียนและระดับชั้นได้ในที่เดียว','cg.pairExample':'ตัวอย่าง: Grade 5 + ห้อง A, Grade 5 + ห้อง B, Kindergarten + K1','cg.classGrade':'ชั้นเรียน → ระดับชั้น',
    'tm.teacherIdCardTitle':'บัตรประจำตัวครู','settings.actionsLabel':'การดำเนินการตั้งค่า','tm.editTeacher':'แก้ไขครู','tm.manageAccess':'จัดการสิทธิ์การเข้าถึง',
    'branding.logoTitle':'โลโก้โรงเรียน','branding.logoSubtitle':'แสดงในแถบด้านข้าง ส่วนหัวแอป และหน้าเพิ่มเติม','branding.logoTip':'ใช้รูปสี่เหลี่ยมจัตุรัส แนะนำ PNG พื้นหลังโปร่งใส ระบบจะปรับเป็น 256×256 อัตโนมัติ',
    'branding.coverTitle':'ภาพหน้าปก','branding.coverSubtitle':'ภาพแบนเนอร์ที่แสดงด้านหลังโลโก้โรงเรียนด้านบนของแถบด้านข้าง','branding.coverTip':'ใช้ภาพแนวนอนประมาณ 3:1 ระบบจะครอปจากตรงกลางเป็น 1200×400 อัตโนมัติ',
    'branding.photoTitle':'รูปโปรไฟล์ของฉัน','branding.photoSubtitle':'แสดงในแถบด้านข้างและการ์ดโปรไฟล์','branding.photoTip':'แนะนำรูปหน้าตรงที่คมชัด ระบบจะครอปเป็นสี่เหลี่ยมจัตุรัสอัตโนมัติ',
    'branding.processing':'กำลังประมวลผล…','branding.uploading':'กำลังอัปโหลด…','branding.removing':'กำลังลบ…','branding.saved':'บันทึกแล้ว ✓','branding.removed':'ลบแล้ว ✓',
    'branding.removeConfirmTitle':'ลบหรือไม่?','branding.removeConfirmText':'คุณแน่ใจหรือไม่ว่าต้องการลบรูปนี้?','branding.removeConfirmButton':'ลบ','branding.savedToast':'บันทึกแล้ว','branding.removedToast':'ลบแล้ว',
    'tm.requiredEdit':'ต้องกรอกชื่อผู้ใช้และชื่อครู','tm.updated':'อัปเดตข้อมูลครูแล้ว','tm.saveChanges':'บันทึกการเปลี่ยนแปลง',
    'branding.readImageFailed':'ไม่สามารถอ่านรูปภาพได้','branding.processImageFailed':'ไม่สามารถประมวลผลรูปภาพได้','branding.failed':'ดำเนินการไม่สำเร็จ','branding.saveFailed':'บันทึกไม่สำเร็จ',
    'tm.editTeacherLabel':'แก้ไขครู','tm.editTeacherSubtitle':'อัปเดตชื่อครูและ Login Name ที่ใช้สำหรับบัตรครูและการเข้าสู่ระบบ','tm.teacherId':'รหัสครู','tm.loginName':'ชื่อเข้าสู่ระบบ','tm.teacherName':'ชื่อครู','tm.email':'อีเมล','tm.role':'บทบาท','tm.roleTeacher':'ครู','tm.roleAdmin':'ผู้ดูแลระบบ','tm.roleSuperAdmin':'ผู้ดูแลระบบสูงสุด','tm.saving':'กำลังบันทึก…','tm.cancel':'ยกเลิก','tm.teacherIdCardLabel':'รหัสครู','tm.loginNameLabel':'ชื่อเข้าสู่ระบบ','tm.teacherLoginQr':'QR สำหรับเข้าสู่ระบบครู','tm.qrUnavailable':'ไม่สามารถใช้ QR ได้',
    'subject.exists':'มีวิชานี้อยู่แล้ว','subject.addFailed':'เพิ่มวิชาไม่สำเร็จ','picker.noMatch':'ไม่พบนักเรียนที่ตรงกับ “{query}”','teacher.updateRequired':'ต้องกรอกชื่อผู้ใช้และชื่อครู','teacher.qrUnavailable':'ไม่สามารถใช้ QR ได้','password.hide':'ซ่อนรหัสผ่าน','password.show':'แสดงรหัสผ่าน','password.newLabel':'รหัสผ่านใหม่','password.newPlaceholder':'อย่างน้อย 6 ตัวอักษร','password.reset':'ตั้งรหัสผ่านใหม่'
  });
  window.I18N_TH = Object.assign({}, base, overrides);
})();
