// Thai locale — complete key parity with English; common UI strings translated natively.
// Unlisted keys intentionally inherit the English source text so new features remain usable.
(function () {
  const base = window.I18N_EN || {};
  const overrides = {
    'app.title':'SCMS — ระบบจัดการชั้นเรียนโรงเรียน',
    'common.all':'ทั้งหมด','common.edit':'แก้ไข','common.close':'ปิด','common.cancel':'ยกเลิก','common.add':'เพิ่ม','common.saving':'กำลังบันทึก…','common.years':'ปี','common.failed':'ล้มเหลว:','common.saveFailed':'บันทึกไม่ได้ — ลองอีกครั้ง','common.removed':'ลบแล้ว',
    'nav.dashboard':'แดชบอร์ด','nav.students':'นักเรียน','nav.attendance':'การเข้าเรียน','nav.homework':'การบ้าน','nav.messages':'ข้อความ','nav.incidents':'เหตุการณ์','nav.timetable':'ตารางเรียน','nav.reports':'รายงาน','nav.settings':'การตั้งค่า',
    'topbar.search':'ค้นหา...','topbar.notifications':'การแจ้งเตือน','topbar.profile':'โปรไฟล์','topbar.logout':'ออกจากระบบ','topbar.language':'ภาษา',
    'btn.save':'บันทึก','btn.cancel':'ยกเลิก','btn.delete':'ลบ','btn.edit':'แก้ไข','btn.add':'เพิ่ม','btn.close':'ปิด','btn.confirm':'ยืนยัน','btn.export':'ส่งออก','btn.refresh':'รีเฟรช','btn.submit':'ส่ง',
    'msg.loading':'กำลังโหลด...','msg.saving':'กำลังบันทึก...','msg.saved':'บันทึกสำเร็จ','msg.error':'เกิดข้อผิดพลาด','msg.noData':'ไม่มีข้อมูล','msg.offline':'คุณออฟไลน์อยู่','msg.confirmDelete':'คุณแน่ใจหรือไม่ว่าต้องการลบ?',
    'students.title':'นักเรียน','students.name':'ชื่อ','students.class':'ชั้นเรียน','students.parent':'ผู้ปกครอง','students.phone':'โทรศัพท์','students.addNew':'เพิ่มนักเรียนใหม่','att.title':'การเข้าเรียน','att.present':'มาเรียน','att.absent':'ขาดเรียน','att.late':'สาย','att.leave':'ลา','att.markAll':'ทำเครื่องหมายมาครบทั้งหมด','att.date':'วันที่','att.saveAttendance':'บันทึกการเข้าเรียน',
    'landing.title':'การจัดการชั้นเรียนโรงเรียน','landing.titleEm':'ทำได้ง่ายๆ','landing.emailLink':'เข้าสู่ระบบด้วยอีเมล','landing.or':'หรือ','landing.telegram':'เข้าสู่ระบบด้วย Telegram','landing.teacherId':'เข้าสู่ระบบด้วยรหัสครู','landing.registerSchool':'ลงทะเบียนโรงเรียนใหม่','landing.joinSchool':'เข้าร่วมโรงเรียนที่มีอยู่แล้ว',
    'login.title':'🔐 เข้าสู่ระบบ','login.teacherId':'รหัสครู','login.password':'รหัสผ่าน','login.btn':'เข้าสู่ระบบ','login.signingIn':'กำลังเข้าสู่ระบบ…','pw.old':'รหัสผ่านปัจจุบัน','pw.new':'รหัสผ่านใหม่ (อย่างน้อย 6 ตัวอักษร)','pw.confirm':'ยืนยันรหัสผ่านใหม่','pw.btnChange':'เปลี่ยนรหัสผ่าน',
    'page.dashboard.eyebrow':'ภาพรวม','page.dashboard.title':'<em>แดชบอร์ด</em> วันนี้','page.students.title':'<em>นักเรียน</em>ของฉัน','page.attend.title':'<em>การเข้าเรียน</em>','page.hw.title':'<em>การบ้าน</em>','page.grades.title':'<em>ผลการเรียน</em>','page.billing.title':'<em>การเรียกเก็บเงิน</em>','page.admissions.title':'<em>การรับสมัคร</em>','page.library.title':'<em>ห้องสมุด</em>','page.transport.title':'<em>การเดินทาง</em>','page.incidents.title':'<em>เหตุการณ์</em>','page.timetable.title':'<em>ตารางเรียน</em>','page.summary.title':'<em>สรุปรายเดือน</em>','page.more.title':'<em>ฟีเจอร์เพิ่มเติม</em>',
    'tab.students':'นักเรียน','tab.attend':'เข้าเรียน','tab.daily':'รายวัน','tab.hw':'การบ้าน','tab.chat':'แชต','tab.more':'เพิ่มเติม',
    'att.clearMarks':'ล้างเครื่องหมาย','att.history':'ประวัติ','att.historyTitle':'ประวัติและรายงาน','att.codes':'รหัส'
  };
  Object.assign(overrides, {
    'hw.tapAdd':'แตะ + เพื่อเพิ่มการบ้าน','hw.due':'กำหนดส่ง','hw.lb':'หน้า LB','hw.wb':'หน้า WB','hw.addTitle':'เพิ่มการบ้าน','hw.subject':'วิชา','hw.addSubject':'เพิ่มวิชา','hw.class':'ชั้นเรียน','hw.type':'ประเภท','hw.description':'รายละเอียด','hw.descPh':'รายละเอียดการบ้าน…','hw.lbPage':'หน้า LB','hw.wbPage':'หน้า WB','hw.pagePh1':'เช่น 24','hw.pagePh2':'เช่น 25','hw.dueDate':'วันครบกำหนด','hw.saved':'✓ บันทึกการบ้านแล้ว','hw.editTitle':'แก้ไขการบ้าน','hw.updated':'✓ อัปเดตแล้ว','hw.confirmTitle':'ลบการบ้านนี้?','hw.confirmBody':'คุณแน่ใจหรือไม่ว่าต้องการลบการบ้านนี้?',
    'comms.none':'ยังไม่มีข้อความ','comms.noneSub':'ส่งข้อความถึงผู้ปกครองจากที่นี่','comms.broadcast':'ประกาศ','comms.classBroadcast':'ประกาศถึงทั้งชั้น','comms.purpose':'วัตถุประสงค์','comms.confirmTitle':'ยืนยันการส่ง','comms.sendTitle':'ส่งข้อความ','comms.sendTo':'ส่งถึง','comms.wholeClass':'ทั้งชั้น','comms.individual':'รายบุคคล','comms.class':'ชั้นเรียน','comms.student':'นักเรียน','comms.chooseStudent':'เลือกนักเรียน','comms.message':'ข้อความ','comms.msgPh':'พิมพ์ข้อความ…','comms.send':'ส่ง','comms.pickerTitle':'เลือกผู้รับ','comms.msgRequired':'กรุณาใส่ข้อความ','comms.pickStudentFirst':'กรุณาเลือกนักเรียนก่อน','comms.sending':'กำลังส่ง…','comms.sent':'✓ ส่งแล้ว',
    'inc.none':'ยังไม่มีเหตุการณ์','inc.tapLog':'แตะเพื่อบันทึกเหตุการณ์','inc.action':'การดำเนินการ','inc.parentNotified':'แจ้งผู้ปกครองแล้ว','inc.pickerTitle':'เลือกนักเรียน','inc.logTitle':'บันทึกเหตุการณ์','inc.student':'นักเรียน','inc.tapChoose':'แตะเพื่อเลือก','inc.type':'ประเภท','inc.severity':'ระดับความรุนแรง','inc.description':'รายละเอียด','inc.whatHappened':'เกิดอะไรขึ้น','inc.actionTaken':'การดำเนินการที่ทำ','inc.actionPh':'ระบุการดำเนินการ…','inc.notifyParent':'แจ้งผู้ปกครอง','inc.logged':'✓ บันทึกแล้ว','inc.pickFirst':'กรุณาเลือกนักเรียนก่อน','inc.editTitle':'แก้ไขเหตุการณ์','inc.updated':'✓ อัปเดตแล้ว','inc.confirmTitle':'ลบเหตุการณ์นี้?',
    'tt.noClasses':'ยังไม่มีชั้นเรียน','tt.adminManages':'ผู้ดูแลระบบจัดการตารางเรียน','tt.room':'ห้อง','tt.periods':'คาบเรียน','tt.period1':'คาบที่ 1','tt.adminOnly':'เฉพาะผู้ดูแลระบบ','tt.entryNotFound':'ไม่พบรายการ','tt.editTitle':'แก้ไขตารางเรียน','tt.addTitle':'เพิ่มคาบเรียน','tt.day':'วัน','tt.periodLbl':'คาบเรียน','tt.startTime':'เวลาเริ่ม','tt.class':'ชั้นเรียน','tt.subject':'วิชา','tt.roomOptional':'ห้อง (ไม่บังคับ)','tt.roomPh':'เช่น ห้อง 101','tt.addEntry':'เพิ่มรายการ','tt.updated':'✓ อัปเดตแล้ว','tt.added':'✓ เพิ่มแล้ว','tt.confirmDelete':'ลบรายการนี้?',
    'sum.none':'ยังไม่มีข้อมูล','sum.noneSub':'ยังไม่มีข้อมูลสรุปสำหรับช่วงเวลานี้','sum.absent':'ขาดเรียน','sum.days':'วัน','sum.hw':'การบ้าน',
    'enum.assessType.Quiz':'แบบทดสอบสั้น','enum.assessType.Test':'แบบทดสอบ','enum.assessType.Exam':'สอบ','enum.assessType.Assignment':'งานที่มอบหมาย','enum.assessType.Project':'โครงงาน',
    'grades.current':'ภาคเรียนปัจจุบัน','grades.addTerm':'เพิ่มภาคเรียน','grades.reportCard':'ใบรายงานผล','grades.noClasses':'ยังไม่มีชั้นเรียน','grades.noAssessments':'ยังไม่มีการประเมิน','grades.metaLine':'{n} รายการประเมิน','grades.pickTerm':'เลือกภาคเรียน','grades.pickClass':'เลือกชั้นเรียน','grades.reportTitle':'รายงานผลการเรียน','grades.noGraded':'ยังไม่มีคะแนน','grades.thStudent':'นักเรียน','grades.overall':'โดยรวม','grades.newTitle':'การประเมินใหม่','grades.title':'ชื่อการประเมิน','grades.titlePh':'เช่น แบบทดสอบคณิตศาสตร์','grades.type':'ประเภท','grades.maxScore':'คะแนนเต็ม','grades.weight':'น้ำหนัก','grades.date':'วันที่','grades.create':'สร้าง','grades.creating':'กำลังสร้าง…','grades.enterTitle':'กรุณาใส่ชื่อการประเมิน','grades.created':'✓ สร้างแล้ว','grades.confirmTitle':'ลบการประเมินนี้?','grades.confirmBody':'ข้อมูลคะแนนของการประเมินนี้จะถูกลบ','grades.classMax':'คะแนนเต็มของชั้นเรียน','grades.saveScores':'บันทึกคะแนน','grades.enterOne':'กรุณาใส่คะแนนอย่างน้อยหนึ่งคน','grades.scoresSaved':'✓ บันทึกคะแนนแล้ว','grades.addTermTitle':'เพิ่มภาคเรียน','grades.termName':'ชื่อภาคเรียน','grades.termNamePh':'เช่น ภาคเรียนที่ 1','grades.year':'ปี','grades.yearPh':'เช่น 2026','grades.start':'วันที่เริ่ม','grades.end':'วันที่สิ้นสุด','grades.enterTermName':'กรุณาใส่ชื่อภาคเรียน','grades.termAdded':'✓ เพิ่มภาคเรียนแล้ว',
    'enum.billStatus.All':'ทั้งหมด','enum.billStatus.Unpaid':'ยังไม่ชำระ','enum.billStatus.Partial':'ชำระบางส่วน','enum.billStatus.Paid':'ชำระแล้ว','enum.billStatus.Overdue':'เกินกำหนด','enum.payMethod.Cash':'เงินสด','enum.payMethod.Bank Transfer':'โอนธนาคาร','enum.payMethod.Mobile':'มือถือ','enum.payMethod.Other':'อื่นๆ','enum.feeCategory.Tuition':'ค่าเล่าเรียน','enum.feeCategory.Transport':'ค่ารถรับส่ง','enum.feeCategory.Meals':'ค่าอาหาร','enum.feeCategory.Uniform':'ค่าเครื่องแบบ','enum.feeCategory.Books':'ค่าหนังสือ','enum.feeCategory.Activity':'ค่ากิจกรรม','enum.feeCategory.Other':'อื่นๆ',
    'bill.allTerms':'ทุกภาคเรียน','bill.none':'ยังไม่มีใบแจ้งหนี้','bill.cardSub':'ใบแจ้งหนี้และการชำระเงิน','bill.ready':'พร้อมใช้งาน','bill.billed':'เรียกเก็บแล้ว','bill.collected':'เก็บเงินแล้ว','bill.outstanding':'ค้างชำระ','bill.newTitle':'สร้างใบแจ้งหนี้','bill.student':'นักเรียน','bill.chooseStudent':'เลือกนักเรียน','bill.termOptional':'ภาคเรียน (ไม่บังคับ)','bill.noTerm':'ไม่มีภาคเรียน','bill.dueDate':'วันครบกำหนด','bill.lineItems':'รายการ','bill.addLineItem':'เพิ่มรายการ','bill.total':'รวม','bill.notes':'หมายเหตุ','bill.optional':'ไม่บังคับ','bill.createInvoice':'สร้างใบแจ้งหนี้','bill.pickerTitle':'เลือกนักเรียน','bill.fromCatalog':'จากรายการค่าธรรมเนียม','bill.descPh':'รายละเอียด…','bill.chooseStudentToast':'กรุณาเลือกนักเรียน','bill.needItem':'เพิ่มรายการอย่างน้อยหนึ่งรายการ','bill.invoiceCreated':'✓ สร้างใบแจ้งหนี้แล้ว','bill.rowTotal':'รวม','bill.rowPaid':'ชำระแล้ว','bill.rowBalance':'ยอดคงเหลือ','bill.payments':'การชำระเงิน','bill.noPayments':'ยังไม่มีการชำระเงิน','bill.enrollment':'การลงทะเบียน','bill.feePaidPending':'ค่าธรรมเนียมชำระแล้ว รอเปิดใช้งาน','bill.makeActive':'เปิดใช้งาน','bill.pendingNote':'นักเรียนจะยังรอจนกว่าจะเปิดใช้งาน','bill.recordPayment':'บันทึกการชำระเงิน','bill.deleteInvoice':'ลบใบแจ้งหนี้','bill.activating':'กำลังเปิดใช้งาน…','bill.activated':'✓ เปิดใช้งานแล้ว','bill.amountBalance':'ยอดคงเหลือ','bill.method':'วิธีชำระเงิน','bill.savePayment':'บันทึกการชำระเงิน','bill.validAmount':'กรุณาใส่จำนวนเงินที่ถูกต้อง','bill.paymentRecorded':'✓ บันทึกการชำระเงินแล้ว','bill.removePayTitle':'ลบการชำระเงินนี้?','bill.removePayBody':'การชำระเงินนี้จะถูกลบออกจากใบแจ้งหนี้','bill.removedToast':'✓ ลบแล้ว','bill.delInvTitle':'ลบใบแจ้งหนี้นี้?','bill.delInvBody':'การลบใบแจ้งหนี้ไม่สามารถย้อนกลับได้','bill.addFeeItem':'เพิ่มค่าธรรมเนียม','bill.noFeeItems':'ยังไม่มีรายการค่าธรรมเนียม','bill.recurring':'เกิดซ้ำ','bill.addFeeTitle':'เพิ่มค่าธรรมเนียม','bill.name':'ชื่อ','bill.namePh':'เช่น ค่าเล่าเรียน','bill.category':'หมวดหมู่','bill.defaultAmount':'จำนวนเงินเริ่มต้น','bill.enterName':'กรุณาใส่ชื่อ','bill.feeAdded':'✓ เพิ่มค่าธรรมเนียมแล้ว','bill.delFeeTitle':'ลบค่าธรรมเนียมนี้?','bill.delFeeBody':'รายการค่าธรรมเนียมนี้จะถูกลบ',
    'enum.admStatus.All':'ทั้งหมด','enum.admStatus.Applied':'สมัครแล้ว','enum.admStatus.Interview Scheduled':'นัดสัมภาษณ์แล้ว','enum.admStatus.Interview Done':'สัมภาษณ์แล้ว','enum.admStatus.Accepted':'รับเข้าแล้ว','enum.admStatus.Waitlisted':'รอคิว','enum.admStatus.Rejected':'ปฏิเสธ','enum.admStatus.Enrolled':'ลงทะเบียนแล้ว','enum.admStatus.Withdrawn':'ถอนใบสมัคร','enum.gender.Male':'ชาย','enum.gender.Female':'หญิง','enum.gender.Other':'อื่นๆ',
    'adm.none':'ยังไม่มีผู้สมัคร','adm.total':'ทั้งหมด','adm.inProgress':'กำลังดำเนินการ','adm.noParent':'ไม่มีข้อมูลผู้ปกครอง','adm.appliedOn':'สมัครเมื่อ','adm.moveTo':'ย้ายไป','adm.movedTo':'ย้ายไปแล้ว','adm.selected':'เลือกแล้ว','adm.enrollOwn':'ลงทะเบียน','adm.clear':'ล้าง','adm.bulkMoving':'กำลังย้ายหลายรายการ…','adm.bulkMoved':'✓ ย้ายแล้ว','adm.failedN':'ล้มเหลว {n} รายการ','adm.noClassSet':'ยังไม่ได้ตั้งค่าชั้นเรียน','adm.enrolling':'กำลังลงทะเบียน…','adm.skipped':'ข้ามแล้ว','adm.enrolledPending':'ลงทะเบียนแล้ว — รอดำเนินการ','adm.newTitle':'ผู้สมัครใหม่','adm.nameEn':'ชื่อภาษาอังกฤษ','adm.fullName':'ชื่อเต็ม','adm.nameLocalOpt':'ชื่อท้องถิ่น (ไม่บังคับ)','adm.nameLocal':'ชื่อท้องถิ่น','adm.dob':'วันเกิด','adm.gender':'เพศ','adm.desiredClass':'ชั้นเรียนที่ต้องการ','adm.parentName':'ชื่อผู้ปกครอง','adm.parentPhone':'โทรศัพท์ผู้ปกครอง','adm.parentEmail':'อีเมลผู้ปกครอง','adm.optional':'ไม่บังคับ','adm.source':'แหล่งที่มา','adm.sourcePh':'เช่น เว็บไซต์','adm.notes':'หมายเหตุ','adm.add':'เพิ่มผู้สมัคร','adm.enterName':'กรุณาใส่ชื่อ','adm.validEmail':'อีเมลไม่ถูกต้อง','adm.addedPhotoFail':'เพิ่มแล้ว แต่การอัปโหลดรูปภาพล้มเหลว','adm.added':'✓ เพิ่มแล้ว','adm.rowLocal':'ชื่อท้องถิ่น','adm.rowParent':'ผู้ปกครอง','adm.rowPhone':'โทรศัพท์','adm.rowEmail':'อีเมล','adm.rowApplied':'วันที่สมัคร','adm.rowInterview':'สัมภาษณ์','adm.moveToTitle':'ย้ายผู้สมัคร','adm.enrollBtn':'ลงทะเบียนนักเรียน','adm.editDetails':'แก้ไขรายละเอียด','adm.deleteApplicant':'ลบผู้สมัคร','adm.officialStudent':'นักเรียนอย่างเป็นทางการ','adm.pendingCreated':'สร้างรายการแล้ว — รอดำเนินการ','adm.createRegInvoice':'สร้างใบแจ้งหนี้ลงทะเบียน','adm.regPaid':'ชำระแล้ว','adm.regUnpaid':'ยังไม่ชำระ','adm.goBilling':'ไปการเรียกเก็บเงิน','adm.scheduleTitle':'กำหนดการสัมภาษณ์','adm.interviewDate':'วันที่สัมภาษณ์','adm.interviewScheduled':'✓ นัดสัมภาษณ์แล้ว','adm.editTitle':'แก้ไขผู้สมัคร','adm.nameRequired':'ต้องระบุชื่อ','adm.savedPhotoFail':'บันทึกแล้ว แต่การอัปโหลดรูปภาพล้มเหลว','adm.saved':'✓ บันทึกแล้ว','adm.convertNote':'ผู้สมัครจะถูกแปลงเป็นนักเรียน','adm.enroll':'ลงทะเบียน','adm.enterClass':'กรุณาเลือกชั้นเรียน','adm.enrollingBtn':'กำลังลงทะเบียน…','adm.recordCreated':'✓ สร้างรายการนักเรียนแล้ว — {id} (รอดำเนินการ)','adm.regTitle':'ใบแจ้งหนี้ลงทะเบียน','adm.needAmountItem':'เพิ่มรายการอย่างน้อยหนึ่งรายการที่มีจำนวนเงิน','adm.regCreated':'✓ สร้างใบแจ้งหนี้ลงทะเบียนแล้ว','adm.delTitle':'🗑 ลบผู้สมัครนี้?','adm.delBody':'รายการสมัครจะถูกลบ แต่จะไม่กระทบกับนักเรียนที่อาจสร้างไว้แล้ว',
    'health.bloodType':'กรุ๊ปเลือด','health.allergies':'อาการแพ้','health.allergiesPh':'เช่น ถั่วลิสง เพนิซิลลิน','health.conditions':'โรคประจำตัว','health.conditionsPh':'เช่น หอบหืด','health.medications':'ยา','health.emContactName':'ชื่อผู้ติดต่อฉุกเฉิน','health.emContactPhone':'โทรศัพท์ผู้ติดต่อฉุกเฉิน','health.doctorName':'ชื่อแพทย์','health.doctorPhone':'โทรศัพท์แพทย์','health.notes':'หมายเหตุ','health.allergiesLabel':'อาการแพ้:','health.conditionsLabel':'โรคประจำตัว:','health.emergencyContact':'ผู้ติดต่อฉุกเฉิน','health.doctor':'แพทย์','health.editProfile':'แก้ไขข้อมูลสุขภาพ','health.vaccinations':'วัคซีน','health.noDate':'ไม่มีวันที่','health.noVax':'ยังไม่มีบันทึกวัคซีน','health.addVax':'+ เพิ่มวัคซีน','health.visits':'การพบแพทย์ / พยาบาล','health.noVisits':'ยังไม่มีบันทึกการพบแพทย์','health.logVisit':'+ บันทึกการพบแพทย์','health.editTitle':'แก้ไขข้อมูลสุขภาพ','health.bloodTypePh':'เช่น O+','health.medicationsOpt':'ไม่บังคับ','health.addVaxTitle':'เพิ่มวัคซีน','health.vaccineName':'ชื่อวัคซีน','health.vaccineNamePh':'เช่น MMR','health.dateGiven':'วันที่ได้รับ','health.enterVaccine':'กรุณาใส่ชื่อวัคซีน','health.delVaxTitle':'🗑 ลบบันทึกวัคซีนนี้?','health.logVisitTitle':'บันทึกการพบแพทย์','health.reason':'เหตุผล','health.reasonPh':'เช่น ไข้ ปวดศีรษะ','health.treatment':'การรักษา','health.enterReason':'กรุณาใส่เหตุผล','health.delVisitTitle':'🗑 ลบบันทึกการพบแพทย์นี้?','health.added':'✓ เพิ่มแล้ว','health.logged':'✓ บันทึกแล้ว',
    'lib.titles':'ชื่อหนังสือ','lib.copies':'จำนวนเล่ม','lib.checkedOut':'ถูกยืม','lib.none':'ยังไม่มีหนังสือ — แตะ + เพื่อเพิ่ม','lib.unknownAuthor':'ไม่ทราบผู้แต่ง','lib.newTitle':'หนังสือใหม่','lib.title':'ชื่อเรื่อง','lib.bookTitle':'ชื่อหนังสือ','lib.author':'ผู้แต่ง','lib.category':'หมวดหมู่','lib.categoryPh':'เช่น นิยาย อ้างอิง (ไม่บังคับ)','lib.isbn':'ISBN','lib.add':'เพิ่มหนังสือ','lib.enterTitle':'กรุณาใส่ชื่อหนังสือ','lib.added':'✓ เพิ่มหนังสือแล้ว','lib.avail':'มี {a} เล่ม / ทั้งหมด {t} เล่ม','lib.checkoutBtn':'ยืมให้นักเรียน','lib.currentlyOut':'กำลังถูกยืม','lib.since':'ตั้งแต่ {date}','lib.due':' ครบกำหนด {date}','lib.return':'คืน','lib.none2':'ไม่มีในขณะนี้','lib.history':'ประวัติ','lib.editTitle':'แก้ไขหนังสือ','lib.totalCopies':'จำนวนเล่มทั้งหมด','lib.titleRequired':'ต้องระบุชื่อหนังสือ','lib.checkoutTitle':'ยืมหนังสือ','lib.student':'นักเรียน','lib.selectStudent':'เลือกนักเรียน','lib.checkoutBtn2':'ยืม','lib.pickStudent':'เลือกนักเรียน','lib.checkingOut':'กำลังยืม…','lib.checkedOutToast':'✓ ยืมแล้ว','lib.returnedToast':'✓ คืนแล้ว','lib.delTitle':'🗑 ลบหนังสือนี้?','lib.delBody':'ทำได้เมื่อไม่มีเล่มใดกำลังถูกยืม','lib.mustReturn':'กรุณาคืนหนังสือทั้งหมดก่อนลบ',
    'tr.none':'ยังไม่มีเส้นทาง — แตะ + เพื่อเพิ่ม','tr.noDriver':'ยังไม่ได้กำหนดคนขับ','tr.newTitle':'เส้นทางใหม่','tr.routeName':'ชื่อเส้นทาง','tr.routeNamePh':'เช่น เส้นทาง A — เหนือ','tr.driverName':'ชื่อคนขับ','tr.driverPhone':'โทรศัพท์คนขับ','tr.vehicle':'รถ','tr.vehiclePh':'เช่น Toyota Coaster เลขทะเบียน (ไม่บังคับ)','tr.add':'เพิ่มเส้นทาง','tr.enterName':'กรุณาใส่ชื่อเส้นทาง','tr.added':'✓ เพิ่มเส้นทางแล้ว','tr.driver':'คนขับ','tr.phone':'โทรศัพท์','tr.vehicleLabel':'รถ','tr.students':'นักเรียน ({n})','tr.noStudents':'ยังไม่มีนักเรียนที่กำหนด','tr.assign':'กำหนดนักเรียน','tr.editRoute':'แก้ไขเส้นทาง','tr.deleteRoute':'ลบเส้นทาง','tr.editTitle':'แก้ไขเส้นทาง','tr.routeRequired':'ต้องระบุชื่อเส้นทาง','tr.assignTitle':'กำหนดนักเรียน','tr.pickupStop':'จุดรับ','tr.pickupStopPh':'เช่น ประตูหลัก (ไม่บังคับ)','tr.pickupTime':'เวลารับ','tr.dropoffTime':'เวลาส่ง','tr.assignBtn':'กำหนด','tr.assigning':'กำลังกำหนด…','tr.assigned':'✓ กำหนดแล้ว','tr.delTitle':'🗑 ลบเส้นทางนี้?','tr.delBody':'นักเรียนที่อยู่ในเส้นทางจะถูกยกเลิกการกำหนดเท่านั้น ไม่ถูกลบออกจากโรงเรียน',
    'settings.title':'⚙️ การตั้งค่า','settings.version':'เวอร์ชัน','settings.platform':'แพลตฟอร์ม','settings.school':'โรงเรียน','settings.teacher':'ครู','settings.role':'บทบาท','settings.login':'เข้าสู่ระบบ','settings.telegram':'Telegram','settings.connected':'🟢 เชื่อมต่อแล้ว','settings.notConnected':'⚪ ยังไม่ได้เชื่อมต่อ','settings.manageTeachers':'👥 จัดการครู','settings.connectTelegram':'🔗 เชื่อมต่อ Telegram','settings.disconnectTelegram':'🔌 ยกเลิกการเชื่อมต่อ Telegram','settings.changePassword':'🔑 เปลี่ยนรหัสผ่านของฉัน','settings.footerNote':'SCMS จัดการโดยผู้ดูแลโรงเรียนของคุณ','settings.googleAccount':'บัญชี Google','settings.webPassword':'เว็บ (รหัสผ่าน)',
    'tm.title':'👥 จัดการครู','tm.subtitle':'สร้างบัญชีเข้าสู่ระบบสำหรับครู','tm.addNew':'+ เพิ่มครูใหม่ (รหัสครู + รหัสผ่าน)','tm.inviteGoogle':'✉️ เชิญผ่าน Google (แชร์รหัส)','tm.loading':'กำลังโหลด…','tm.loadFailed':'โหลดข้อมูลครูไม่สำเร็จ','tm.none':'ยังไม่มีครู','tm.lastLogin':'เข้าสู่ระบบล่าสุด: {date}','tm.never':'ไม่เคย','tm.resetPassword':'รีเซ็ตรหัสผ่าน',
    'inv.title':'✉️ เชิญผ่าน Google','inv.subtitle':'ครูเข้าสู่ระบบด้วยบัญชี Google ของตนเองและเข้าร่วมด้วยรหัสนี้','inv.name':'ชื่อ (ไม่บังคับ)','inv.namePh':'เช่น Daw Hla Hla','inv.role':'บทบาท *','inv.roleTeacher':'ครู','inv.roleAdmin':'ผู้ดูแลระบบ','inv.generate':'สร้างรหัส','inv.generating':'กำลังสร้าง…','inv.codeLabel':'รหัสเชิญ','inv.hint':'ส่งรหัสนี้ให้ครู (ใช้ได้ 14 วัน) ครูสามารถใช้รหัสจาก Google Sign-In → “ฉันมีรหัสเชิญ”','inv.pastInvites':'คำเชิญก่อนหน้า','inv.usedBy':'✅ ใช้โดย {id}','inv.expired':'⌛ หมดอายุ','inv.pending':'⏳ รอดำเนินการ','inv.back':'ย้อนกลับ','inv.failed':'สร้างคำเชิญไม่สำเร็จ: {err}'
  });
  window.I18N_TH = Object.assign({}, base, overrides);
})();
