// Japanese locale — complete key parity with English; common UI strings translated natively.
// Unlisted keys intentionally inherit the English source text so new features remain usable.
(function () {
  const base = window.I18N_EN || {};
  const overrides = {
    'app.title':'SCMS — 学校クラス管理システム',
    'common.all':'すべて','common.edit':'編集','common.close':'閉じる','common.cancel':'キャンセル','common.add':'追加','common.saving':'保存中…','common.years':'年','common.failed':'失敗:','common.saveFailed':'保存できません — もう一度お試しください','common.removed':'削除しました',
    'nav.dashboard':'ダッシュボード','nav.students':'生徒','nav.attendance':'出欠','nav.homework':'宿題','nav.messages':'メッセージ','nav.incidents':'インシデント','nav.timetable':'時間割','nav.reports':'レポート','nav.settings':'設定',
    'topbar.search':'検索...','topbar.notifications':'通知','topbar.profile':'プロフィール','topbar.logout':'ログアウト','topbar.language':'言語',
    'btn.save':'保存','btn.cancel':'キャンセル','btn.delete':'削除','btn.edit':'編集','btn.add':'追加','btn.close':'閉じる','btn.confirm':'確認','btn.export':'エクスポート','btn.refresh':'更新','btn.submit':'送信',
    'msg.loading':'読み込み中...','msg.saving':'保存中...','msg.saved':'正常に保存しました','msg.error':'問題が発生しました','msg.noData':'データがありません','msg.offline':'オフラインです','msg.confirmDelete':'本当に削除しますか？',
    'students.title':'生徒','students.name':'名前','students.class':'クラス','students.parent':'保護者','students.phone':'電話','students.addNew':'新しい生徒を追加','att.title':'出欠','att.present':'出席','att.absent':'欠席','att.late':'遅刻','att.leave':'休み','att.markAll':'全員を出席にする','att.date':'日付','att.saveAttendance':'出欠を保存',
    'landing.title':'学校クラス管理を','landing.titleEm':'シンプルに','landing.emailLink':'メールでログイン','landing.or':'または','landing.telegram':'Telegramでログイン','landing.teacherId':'教師IDでログイン','landing.registerSchool':'新しい学校を登録','landing.joinSchool':'既存の学校に参加',
    'login.title':'🔐 ログイン','login.teacherId':'教師ID','login.password':'パスワード','login.btn':'ログイン','login.signingIn':'ログイン中…','pw.old':'現在のパスワード','pw.new':'新しいパスワード（6文字以上）','pw.confirm':'新しいパスワードを再入力','pw.btnChange':'パスワードを変更',
    'page.dashboard.eyebrow':'概要','page.dashboard.title':'今日の<em>ダッシュボード</em>','page.students.title':'私の<em>生徒</em>','page.attend.title':'<em>出欠</em>','page.hw.title':'<em>宿題</em>','page.grades.title':'<em>成績</em>','page.billing.title':'<em>請求</em>','page.admissions.title':'<em>入学受付</em>','page.library.title':'<em>図書館</em>','page.transport.title':'<em>送迎</em>','page.incidents.title':'<em>インシデント</em>','page.timetable.title':'<em>時間割</em>','page.summary.title':'月間<em>サマリー</em>','page.more.title':'その他の<em>機能</em>',
    'tab.students':'生徒','tab.attend':'出欠','tab.daily':'日次','tab.hw':'宿題','tab.chat':'チャット','tab.more':'その他',
    'att.clearMarks':'記録をクリア','att.history':'履歴','att.historyTitle':'履歴とレポート','att.codes':'コード'
  };
  Object.assign(overrides, {
    'hw.tapAdd':'＋をタップして宿題を追加','hw.due':'提出期限','hw.lb':'LBページ','hw.wb':'WBページ','hw.addTitle':'宿題を追加','hw.subject':'科目','hw.addSubject':'科目を追加','hw.class':'クラス','hw.type':'種類','hw.description':'説明','hw.descPh':'宿題の説明…','hw.lbPage':'LBページ','hw.wbPage':'WBページ','hw.pagePh1':'例: 24','hw.pagePh2':'例: 25','hw.dueDate':'提出期限','hw.saved':'✓ 宿題を保存しました','hw.editTitle':'宿題を編集','hw.updated':'✓ 更新しました','hw.confirmTitle':'この宿題を削除しますか？','hw.confirmBody':'この宿題を削除してもよろしいですか？',
    'comms.none':'メッセージはまだありません','comms.noneSub':'ここから保護者にメッセージを送信できます','comms.broadcast':'一斉連絡','comms.classBroadcast':'クラス全体に連絡','comms.purpose':'目的','comms.confirmTitle':'送信を確認','comms.sendTitle':'メッセージを送信','comms.sendTo':'送信先','comms.wholeClass':'クラス全体','comms.individual':'個別','comms.class':'クラス','comms.student':'生徒','comms.chooseStudent':'生徒を選択','comms.message':'メッセージ','comms.msgPh':'メッセージを入力…','comms.send':'送信','comms.pickerTitle':'送信先を選択','comms.msgRequired':'メッセージを入力してください','comms.pickStudentFirst':'先に生徒を選択してください','comms.sending':'送信中…','comms.sent':'✓ 送信しました',
    'inc.none':'インシデントはまだありません','inc.tapLog':'タップして記録','inc.action':'対応','inc.parentNotified':'保護者に通知済み','inc.pickerTitle':'生徒を選択','inc.logTitle':'インシデントを記録','inc.student':'生徒','inc.tapChoose':'タップして選択','inc.type':'種類','inc.severity':'重要度','inc.description':'説明','inc.whatHappened':'何が起きましたか','inc.actionTaken':'対応内容','inc.actionPh':'対応内容を入力…','inc.notifyParent':'保護者に通知','inc.logged':'✓ 記録しました','inc.pickFirst':'先に生徒を選択してください','inc.editTitle':'インシデントを編集','inc.updated':'✓ 更新しました','inc.confirmTitle':'このインシデントを削除しますか？',
    'tt.noClasses':'クラスがありません','tt.adminManages':'時間割は管理者が管理します','tt.room':'教室','tt.periods':'授業時間','tt.period1':'1時間目','tt.adminOnly':'管理者のみ','tt.entryNotFound':'項目が見つかりません','tt.editTitle':'時間割を編集','tt.addTitle':'授業を追加','tt.day':'曜日','tt.periodLbl':'時限','tt.startTime':'開始時刻','tt.class':'クラス','tt.subject':'科目','tt.roomOptional':'教室（任意）','tt.roomPh':'例: 101教室','tt.addEntry':'項目を追加','tt.updated':'✓ 更新しました','tt.added':'✓ 追加しました','tt.confirmDelete':'この項目を削除しますか？',
    'sum.none':'データがありません','sum.noneSub':'この期間の集計データはありません','sum.absent':'欠席','sum.days':'日','sum.hw':'宿題',
    'enum.assessType.Quiz':'小テスト','enum.assessType.Test':'テスト','enum.assessType.Exam':'試験','enum.assessType.Assignment':'課題','enum.assessType.Project':'プロジェクト',
    'grades.current':'現在の学期','grades.addTerm':'学期を追加','grades.reportCard':'成績表','grades.noClasses':'クラスがありません','grades.noAssessments':'評価項目がありません','grades.metaLine':'評価 {n} 件','grades.pickTerm':'学期を選択','grades.pickClass':'クラスを選択','grades.reportTitle':'成績レポート','grades.noGraded':'採点済みデータがありません','grades.thStudent':'生徒','grades.overall':'総合','grades.newTitle':'新しい評価','grades.title':'評価名','grades.titlePh':'例: 数学テスト','grades.type':'種類','grades.maxScore':'満点','grades.weight':'重み','grades.date':'日付','grades.create':'作成','grades.creating':'作成中…','grades.enterTitle':'評価名を入力してください','grades.created':'✓ 作成しました','grades.confirmTitle':'この評価を削除しますか？','grades.confirmBody':'この評価の点数データも削除されます','grades.classMax':'クラスの満点','grades.saveScores':'点数を保存','grades.enterOne':'少なくとも1人の点数を入力してください','grades.scoresSaved':'✓ 点数を保存しました','grades.addTermTitle':'学期を追加','grades.termName':'学期名','grades.termNamePh':'例: 1学期','grades.year':'年','grades.yearPh':'例: 2026','grades.start':'開始日','grades.end':'終了日','grades.enterTermName':'学期名を入力してください','grades.termAdded':'✓ 学期を追加しました',
    'enum.billStatus.All':'すべて','enum.billStatus.Unpaid':'未払い','enum.billStatus.Partial':'一部支払い','enum.billStatus.Paid':'支払済み','enum.billStatus.Overdue':'期限超過','enum.payMethod.Cash':'現金','enum.payMethod.Bank Transfer':'銀行振込','enum.payMethod.Mobile':'モバイル','enum.payMethod.Other':'その他','enum.feeCategory.Tuition':'授業料','enum.feeCategory.Transport':'送迎費','enum.feeCategory.Meals':'給食費','enum.feeCategory.Uniform':'制服代','enum.feeCategory.Books':'教材費','enum.feeCategory.Activity':'活動費','enum.feeCategory.Other':'その他',
    'bill.allTerms':'すべての学期','bill.none':'請求書はありません','bill.cardSub':'請求と支払い','bill.ready':'準備完了','bill.billed':'請求済み','bill.collected':'回収済み','bill.outstanding':'未回収','bill.newTitle':'請求書を作成','bill.student':'生徒','bill.chooseStudent':'生徒を選択','bill.termOptional':'学期（任意）','bill.noTerm':'学期なし','bill.dueDate':'支払期限','bill.lineItems':'明細','bill.addLineItem':'明細を追加','bill.total':'合計','bill.notes':'メモ','bill.optional':'任意','bill.createInvoice':'請求書を作成','bill.pickerTitle':'生徒を選択','bill.fromCatalog':'料金一覧から','bill.descPh':'説明…','bill.chooseStudentToast':'生徒を選択してください','bill.needItem':'明細を1つ以上追加してください','bill.invoiceCreated':'✓ 請求書を作成しました','bill.rowTotal':'合計','bill.rowPaid':'支払済み','bill.rowBalance':'残額','bill.payments':'支払い','bill.noPayments':'支払いはありません','bill.enrollment':'入学','bill.feePaidPending':'料金支払済み・有効化待ち','bill.makeActive':'有効化','bill.pendingNote':'有効化されるまで生徒は保留状態です','bill.recordPayment':'支払いを記録','bill.deleteInvoice':'請求書を削除','bill.activating':'有効化中…','bill.activated':'✓ 有効化しました','bill.amountBalance':'残額','bill.method':'支払方法','bill.savePayment':'支払いを保存','bill.validAmount':'正しい金額を入力してください','bill.paymentRecorded':'✓ 支払いを記録しました','bill.removePayTitle':'この支払いを削除しますか？','bill.removePayBody':'この支払いは請求書から削除されます','bill.removedToast':'✓ 削除しました','bill.delInvTitle':'この請求書を削除しますか？','bill.delInvBody':'請求書の削除は元に戻せません','bill.addFeeItem':'料金項目を追加','bill.noFeeItems':'料金項目がありません','bill.recurring':'定期','bill.addFeeTitle':'料金を追加','bill.name':'名前','bill.namePh':'例: 授業料','bill.category':'カテゴリ','bill.defaultAmount':'既定金額','bill.enterName':'名前を入力してください','bill.feeAdded':'✓ 料金を追加しました','bill.delFeeTitle':'この料金を削除しますか？','bill.delFeeBody':'この料金項目は削除されます',
    'enum.admStatus.All':'すべて','enum.admStatus.Applied':'応募済み','enum.admStatus.Interview Scheduled':'面接予定','enum.admStatus.Interview Done':'面接済み','enum.admStatus.Accepted':'合格','enum.admStatus.Waitlisted':'保留','enum.admStatus.Rejected':'不合格','enum.admStatus.Enrolled':'入学済み','enum.admStatus.Withdrawn':'辞退','enum.gender.Male':'男性','enum.gender.Female':'女性','enum.gender.Other':'その他',
    'adm.none':'応募者はいません','adm.total':'合計','adm.inProgress':'進行中','adm.noParent':'保護者情報なし','adm.appliedOn':'応募日','adm.moveTo':'移動先','adm.movedTo':'移動しました','adm.selected':'選択済み','adm.enrollOwn':'登録','adm.clear':'クリア','adm.bulkMoving':'一括移動中…','adm.bulkMoved':'✓ 移動しました','adm.failedN':'{n}件失敗','adm.noClassSet':'クラスが設定されていません','adm.enrolling':'登録中…','adm.skipped':'スキップしました','adm.enrolledPending':'登録済み — 保留中','adm.newTitle':'新しい応募者','adm.nameEn':'英語名','adm.fullName':'氏名','adm.nameLocalOpt':'現地名（任意）','adm.nameLocal':'現地名','adm.dob':'生年月日','adm.gender':'性別','adm.desiredClass':'希望クラス','adm.parentName':'保護者名','adm.parentPhone':'保護者電話','adm.parentEmail':'保護者メール','adm.optional':'任意','adm.source':'情報源','adm.sourcePh':'例: Webサイト','adm.notes':'メモ','adm.add':'応募者を追加','adm.enterName':'名前を入力してください','adm.validEmail':'メールアドレスが正しくありません','adm.addedPhotoFail':'追加しましたが、画像のアップロードに失敗しました','adm.added':'✓ 追加しました','adm.rowLocal':'現地名','adm.rowParent':'保護者','adm.rowPhone':'電話','adm.rowEmail':'メール','adm.rowApplied':'応募日','adm.rowInterview':'面接','adm.moveToTitle':'応募者を移動','adm.enrollBtn':'生徒として登録','adm.editDetails':'詳細を編集','adm.deleteApplicant':'応募者を削除','adm.officialStudent':'正式な生徒','adm.pendingCreated':'記録を作成しました — 保留中','adm.createRegInvoice':'登録請求書を作成','adm.regPaid':'支払済み','adm.regUnpaid':'未払い','adm.goBilling':'請求へ','adm.scheduleTitle':'面接を設定','adm.interviewDate':'面接日','adm.interviewScheduled':'✓ 面接を予定しました','adm.editTitle':'応募者を編集','adm.nameRequired':'名前は必須です','adm.savedPhotoFail':'保存しましたが、画像のアップロードに失敗しました','adm.saved':'✓ 保存しました','adm.convertNote':'応募者を生徒に変換します','adm.enroll':'登録','adm.enterClass':'クラスを入力してください','adm.enrollingBtn':'登録中…','adm.recordCreated':'✓ 生徒記録を作成しました — {id}（保留）','adm.regTitle':'登録請求書','adm.needAmountItem':'金額のある明細を1つ以上追加してください','adm.regCreated':'✓ 登録請求書を作成しました','adm.delTitle':'🗑 この応募者を削除しますか？','adm.delBody':'応募記録を削除します。すでに生徒に変換された記録には影響しません。',
    'health.bloodType':'血液型','health.allergies':'アレルギー','health.allergiesPh':'例: ピーナッツ、ペニシリン','health.conditions':'持病','health.conditionsPh':'例: 喘息','health.medications':'服薬','health.emContactName':'緊急連絡先名','health.emContactPhone':'緊急連絡先電話','health.doctorName':'医師名','health.doctorPhone':'医師電話','health.notes':'メモ','health.allergiesLabel':'アレルギー:','health.conditionsLabel':'持病:','health.emergencyContact':'緊急連絡先','health.doctor':'医師','health.editProfile':'健康情報を編集','health.vaccinations':'予防接種','health.noDate':'日付なし','health.noVax':'予防接種の記録はありません','health.addVax':'+ 予防接種を追加','health.visits':'診察・看護記録','health.noVisits':'診察記録はありません','health.logVisit':'+ 診察を記録','health.editTitle':'健康情報を編集','health.bloodTypePh':'例: O+','health.medicationsOpt':'任意','health.addVaxTitle':'予防接種を追加','health.vaccineName':'ワクチン名','health.vaccineNamePh':'例: MMR','health.dateGiven':'接種日','health.enterVaccine':'ワクチン名を入力してください','health.delVaxTitle':'🗑 この予防接種記録を削除しますか？','health.logVisitTitle':'診察を記録','health.reason':'理由','health.reasonPh':'例: 発熱、頭痛','health.treatment':'処置','health.enterReason':'理由を入力してください','health.delVisitTitle':'🗑 この診察記録を削除しますか？','health.added':'✓ 追加しました','health.logged':'✓ 記録しました',
    'lib.titles':'書籍数','lib.copies':'冊数','lib.checkedOut':'貸出中','lib.none':'本はまだありません — ＋で追加','lib.unknownAuthor':'著者不明','lib.newTitle':'新しい本','lib.title':'タイトル','lib.bookTitle':'書名','lib.author':'著者','lib.category':'カテゴリ','lib.categoryPh':'例: 小説、参考書（任意）','lib.isbn':'ISBN','lib.add':'本を追加','lib.enterTitle':'タイトルを入力してください','lib.added':'✓ 本を追加しました','lib.avail':'{a}冊利用可能 / 全{t}冊','lib.checkoutBtn':'生徒に貸し出す','lib.currentlyOut':'貸出中','lib.since':'{date}から','lib.due':'、返却期限 {date}','lib.return':'返却','lib.none2':'現在ありません','lib.history':'履歴','lib.editTitle':'本を編集','lib.totalCopies':'総冊数','lib.titleRequired':'タイトルは必須です','lib.checkoutTitle':'貸出','lib.student':'生徒','lib.selectStudent':'生徒を選択','lib.checkoutBtn2':'貸出','lib.pickStudent':'生徒を選択','lib.checkingOut':'貸出中…','lib.checkedOutToast':'✓ 貸し出しました','lib.returnedToast':'✓ 返却しました','lib.delTitle':'🗑 この本を削除しますか？','lib.delBody':'貸出中の冊がない場合のみ削除できます','lib.mustReturn':'削除する前にすべて返却してください',
    'tr.none':'ルートはまだありません — ＋で追加','tr.noDriver':'運転手未設定','tr.newTitle':'新しいルート','tr.routeName':'ルート名','tr.routeNamePh':'例: ルートA — 北','tr.driverName':'運転手名','tr.driverPhone':'運転手電話','tr.vehicle':'車両','tr.vehiclePh':'例: Toyota Coaster、車両番号（任意）','tr.add':'ルートを追加','tr.enterName':'ルート名を入力してください','tr.added':'✓ ルートを追加しました','tr.driver':'運転手','tr.phone':'電話','tr.vehicleLabel':'車両','tr.students':'生徒（{n}）','tr.noStudents':'割り当てられた生徒はいません','tr.assign':'生徒を割り当てる','tr.editRoute':'ルートを編集','tr.deleteRoute':'ルートを削除','tr.editTitle':'ルートを編集','tr.routeRequired':'ルート名は必須です','tr.assignTitle':'生徒を割り当て','tr.pickupStop':'乗車場所','tr.pickupStopPh':'例: 正門（任意）','tr.pickupTime':'迎え時間','tr.dropoffTime':'送り時間','tr.assignBtn':'割り当て','tr.assigning':'割り当て中…','tr.assigned':'✓ 割り当てました','tr.delTitle':'🗑 このルートを削除しますか？','tr.delBody':'このルートの生徒は割り当て解除されるだけで、学校から削除されません。',
    'settings.title':'⚙️ 設定','settings.version':'バージョン','settings.platform':'プラットフォーム','settings.school':'学校','settings.teacher':'教師','settings.role':'役割','settings.login':'ログイン','settings.telegram':'Telegram','settings.connected':'🟢 接続済み','settings.notConnected':'⚪ 未接続','settings.manageTeachers':'👥 教師を管理','settings.connectTelegram':'🔗 Telegramを接続','settings.disconnectTelegram':'🔌 Telegramの接続を解除','settings.changePassword':'🔑 パスワードを変更','settings.footerNote':'SCMSは学校管理者によって管理されています。','settings.googleAccount':'Googleアカウント','settings.webPassword':'Web（パスワード）',
    'tm.title':'👥 教師を管理','tm.subtitle':'教師のログインアカウントを作成します。','tm.addNew':'+ 新しい教師を追加（教師ID＋パスワード）','tm.inviteGoogle':'✉️ Googleで招待（コードを共有）','tm.loading':'読み込み中…','tm.loadFailed':'教師の読み込みに失敗しました','tm.none':'教師はまだいません','tm.lastLogin':'最終ログイン: {date}','tm.never':'なし','tm.resetPassword':'パスワードをリセット',
    'inv.title':'✉️ Googleで招待','inv.subtitle':'教師は自分のGoogleアカウントでログインし、このコードで参加します。','inv.name':'名前（任意）','inv.namePh':'例: Daw Hla Hla','inv.role':'役割 *','inv.roleTeacher':'教師','inv.roleAdmin':'管理者','inv.generate':'コードを生成','inv.generating':'生成中…','inv.codeLabel':'招待コード','inv.hint':'このコードを教師に送ってください（14日間有効）。Google Sign-In → 「招待コードを持っています」から使用できます。','inv.pastInvites':'過去の招待','inv.usedBy':'✅ {id} が使用','inv.expired':'⌛ 期限切れ','inv.pending':'⏳ 保留中','inv.back':'戻る','inv.failed':'招待の作成に失敗しました: {err}'
  });
  window.I18N_JP = Object.assign({}, base, overrides);
})();
