// Japanese locale — complete key parity with English; common UI strings translated natively.
// Unlisted keys intentionally inherit the English source text so new features remain usable.
(function () {
  const base = window.I18N_EN || {};
  const overrides = {
    'app.title':'SCMS — 学校クラス管理システム',
    'common.all':'すべて','common.edit':'編集','common.close':'閉じる','common.cancel':'キャンセル','common.add':'追加','common.saving':'保存中…','common.years':'年','common.failed':'失敗:','common.saveFailed':'保存できません — もう一度お試しください','common.removed':'削除しました',
    'nav.dashboard':'ダッシュボード','nav.students':'生徒','nav.attendance':'出欠','nav.homework':'宿題','nav.messages':'メッセージ','nav.incidents':'インシデント','nav.timetable':'時間割','nav.reports':'レポート','nav.settings':'設定',
    'topbar.search':'検索...','topbar.notifications':'通知','topbar.profile':'プロフィール','topbar.logout':'ログアウト','topbar.language':'言語',
    'btn.save':'保存','btn.cancel':'キャンセル','btn.delete':'削除','btn.edit':'編集','btn.add':'追加','btn.close':'閉じる','btn.confirm':'確認','btn.export':'エクスポート','btn.refresh':'更新','btn.submit':'送信',
    'msg.loading':'読み込み中...','msg.saving':'保存中...','msg.saved':'正常に保存しました','msg.error':'問題が発生しました','msg.noData':'データがありません','msg.offline':'オフラインです','msg.confirmDelete':'本当に削除しますか？',
    'students.title':'生徒','students.name':'名前','students.class':'クラス','students.parent':'保護者','students.phone':'電話','students.addNew':'新しい生徒を追加','att.title':'出欠','att.present':'出席','att.absent':'欠席','att.late':'遅刻','att.leave':'休み','att.markAll':'全員を出席にする','att.date':'日付','att.saveAttendance':'出欠を保存',
    'landing.title':'学校クラス管理を','landing.titleEm':'シンプルに','landing.emailLink':'メールでログイン','landing.or':'または','landing.telegram':'Telegramでログイン','landing.teacherId':'教師IDでログイン','landing.registerSchool':'新しい学校を登録','landing.joinSchool':'既存の学校に参加',
    'login.title':'🔐 ログイン','login.loginName':'ログイン名','login.pin':'PIN','login.btn':'ログイン','login.signingIn':'ログイン中…','pw.old':'現在のパスワード','pw.new':'新しいパスワード（6文字以上）','pw.confirm':'新しいパスワードを再入力','pw.btnChange':'パスワードを変更',
    'page.dashboard.eyebrow':'概要','page.dashboard.title':'今日の<em>ダッシュボード</em>','page.students.title':'私の<em>生徒</em>','page.attend.title':'<em>出欠</em>','page.hw.title':'<em>宿題</em>','page.grades.title':'<em>成績</em>','page.billing.title':'<em>請求</em>','page.admissions.title':'<em>入学受付</em>','page.library.title':'<em>図書館</em>','page.transport.title':'<em>送迎</em>','page.incidents.title':'<em>インシデント</em>','page.timetable.title':'<em>時間割</em>','page.summary.title':'月間<em>サマリー</em>','page.more.title':'その他の<em>機能</em>',
    'tab.students':'生徒','tab.attend':'出欠','tab.daily':'日次','tab.hw':'宿題','tab.chat':'チャット','tab.more':'その他',
    'att.clearMarks':'記録をクリア','att.history':'履歴','att.historyTitle':'履歴とレポート','att.codes':'コード'
  };
  Object.assign(overrides, {
    'hw.tapAdd':'＋をタップして宿題を追加','hw.due':'提出期限','hw.lb':'LBページ','hw.wb':'WBページ','hw.addTitle':'宿題を追加','hw.subject':'科目','hw.addSubject':'科目を追加','hw.class':'クラス','hw.type':'種類','hw.description':'説明','hw.descPh':'宿題の説明…','hw.lbPage':'LBページ','hw.wbPage':'WBページ','hw.pagePh1':'例: 24','hw.pagePh2':'例: 25','hw.dueDate':'提出期限','hw.saved':'✓ 宿題を保存しました','hw.editTitle':'宿題を編集','hw.updated':'✓ 更新しました','hw.confirmTitle':'この宿題を削除しますか？','hw.confirmBody':'この宿題を削除してもよろしいですか？',
    'comms.none':'メッセージはまだありません','comms.noneSub':'ここから保護者にメッセージを送信できます','comms.broadcast':'一斉連絡','comms.classBroadcast':'クラス全体に連絡','comms.purpose':'目的','comms.confirmTitle':'送信を確認','comms.sendTitle':'メッセージを送信','comms.sendTo':'送信先','comms.wholeClass':'クラス全体','comms.individual':'個別','comms.class':'クラス','comms.student':'生徒','comms.chooseStudent':'生徒を選択','comms.message':'メッセージ','comms.msgPh':'メッセージを入力…','comms.send':'送信','comms.pickerTitle':'送信先を選択','comms.msgRequired':'メッセージを入力してください','comms.pickStudentFirst':'先に生徒を選択してください','comms.sending':'送信中…','comms.sent':'✓ 送信しました',
    'inc.none':'インシデントはまだありません','inc.tapLog':'タップして記録','inc.action':'対応','inc.parentNotified':'保護者に通知済み','inc.pickerTitle':'生徒を選択','inc.logTitle':'インシデントを記録','inc.student':'生徒','inc.tapChoose':'タップして選択','inc.type':'種類','inc.severity':'重要度','inc.description':'説明','inc.whatHappened':'何が起きましたか','inc.actionTaken':'対応内容','inc.actionPh':'対応内容を入力…','inc.notifyParent':'保護者に通知','inc.logged':'✓ 記録しました','inc.pickFirst':'先に生徒を選択してください','inc.editTitle':'インシデントを編集','inc.updated':'✓ 更新しました','inc.confirmTitle':'このインシデントを削除しますか？',
    'tt.noClasses':'クラスがありません','tt.adminManages':'時間割は管理者が管理します','tt.room':'教室','tt.periods':'授業時間','tt.period1':'1時間目','tt.adminOnly':'管理者のみ','tt.entryNotFound':'項目が見つかりません','tt.editTitle':'時間割を編集','tt.addTitle':'授業を追加','tt.day':'曜日','tt.periodLbl':'時限','tt.startTime':'開始時刻','tt.class':'クラス','tt.subject':'科目','tt.roomOptional':'教室（任意）','tt.roomPh':'例: 101教室','tt.addEntry':'項目を追加','tt.updated':'✓ 更新しました','tt.added':'✓ 追加しました','tt.confirmDelete':'この項目を削除しますか？',
    'sum.none':'データがありません','sum.noneSub':'この期間の集計データはありません','sum.absent':'欠席','sum.days':'日','sum.hw':'宿題',
    'enum.assessType.Quiz':'小テスト','enum.assessType.Test':'テスト','enum.assessType.Exam':'試験','enum.assessType.Assignment':'課題','enum.assessType.Project':'プロジェクト',
    'grades.current':'現在の学期','grades.addTerm':'学期を追加','grades.reportCard':'成績表','grades.noClasses':'クラスがありません','grades.noAssessments':'評価項目がありません','grades.metaLine':'評価 {n} 件','grades.pickTerm':'学期を選択','grades.pickClass':'クラスを選択','grades.reportTitle':'成績レポート','grades.noGraded':'採点済みデータがありません','grades.thStudent':'生徒','grades.overall':'総合','grades.newTitle':'新しい評価','grades.title':'評価名','grades.titlePh':'例: 数学テスト','grades.type':'種類','grades.maxScore':'満点','grades.weight':'重み','grades.date':'日付','grades.create':'作成','grades.creating':'作成中…','grades.enterTitle':'評価名を入力してください','grades.created':'✓ 作成しました','grades.confirmTitle':'この評価を削除しますか？','grades.confirmBody':'この評価の点数データも削除されます','grades.classMax':'クラスの満点','grades.saveScores':'点数を保存','grades.enterOne':'少なくとも1人の点数を入力してください','grades.scoresSaved':'✓ 点数を保存しました','grades.addTermTitle':'学期を追加','grades.termName':'学期名','grades.termNamePh':'例: 1学期','grades.year':'年','grades.yearPh':'例: 2026','grades.start':'開始日','grades.end':'終了日','grades.enterTermName':'学期名を入力してください','grades.termAdded':'✓ 学期を追加しました',
    'enum.billStatus.All':'すべて','enum.billStatus.Unpaid':'未払い','enum.billStatus.Partial':'一部支払い','enum.billStatus.Paid':'支払済み','enum.billStatus.Overdue':'期限超過','enum.payMethod.Cash':'現金','enum.payMethod.Bank Transfer':'銀行振込','enum.payMethod.Mobile':'モバイル','enum.payMethod.Other':'その他','enum.feeCategory.Tuition':'授業料','enum.feeCategory.Transport':'送迎費','enum.feeCategory.Meals':'給食費','enum.feeCategory.Uniform':'制服代','enum.feeCategory.Books':'教材費','enum.feeCategory.Activity':'活動費','enum.feeCategory.Other':'その他',
    'bill.allTerms':'すべての学期','bill.none':'請求書はありません','bill.cardSub':'請求と支払い','bill.ready':'準備完了','bill.billed':'請求済み','bill.collected':'回収済み','bill.outstanding':'未回収','bill.newTitle':'請求書を作成','bill.student':'生徒','bill.chooseStudent':'生徒を選択','bill.termOptional':'学期（任意）','bill.noTerm':'学期なし','bill.dueDate':'支払期限','bill.lineItems':'明細','bill.addLineItem':'明細を追加','bill.total':'合計','bill.notes':'メモ','bill.optional':'任意','bill.createInvoice':'請求書を作成','bill.pickerTitle':'生徒を選択','bill.fromCatalog':'料金一覧から','bill.descPh':'説明…','bill.chooseStudentToast':'生徒を選択してください','bill.needItem':'明細を1つ以上追加してください','bill.invoiceCreated':'✓ 請求書を作成しました','bill.rowTotal':'合計','bill.rowPaid':'支払済み','bill.rowBalance':'残額','bill.payments':'支払い','bill.noPayments':'支払いはありません','bill.enrollment':'入学','bill.feePaidPending':'料金支払済み・有効化待ち','bill.makeActive':'有効化','bill.pendingNote':'有効化されるまで生徒は保留状態です','bill.recordPayment':'支払いを記録','bill.deleteInvoice':'請求書を削除','bill.activating':'有効化中…','bill.activated':'✓ 有効化しました','bill.amountBalance':'残額','bill.method':'支払方法','bill.savePayment':'支払いを保存','bill.validAmount':'正しい金額を入力してください','bill.paymentRecorded':'✓ 支払いを記録しました','bill.removePayTitle':'この支払いを削除しますか？','bill.removePayBody':'この支払いは請求書から削除されます','bill.removedToast':'✓ 削除しました','bill.delInvTitle':'この請求書を削除しますか？','bill.delInvBody':'請求書の削除は元に戻せません','bill.addFeeItem':'料金項目を追加','bill.noFeeItems':'料金項目がありません','bill.recurring':'定期','bill.addFeeTitle':'料金を追加','bill.name':'名前','bill.namePh':'例: 授業料','bill.category':'カテゴリ','bill.defaultAmount':'既定金額','bill.enterName':'名前を入力してください','bill.feeAdded':'✓ 料金を追加しました','bill.delFeeTitle':'この料金を削除しますか？','bill.delFeeBody':'この料金項目は削除されます',
    'enum.admStatus.All':'すべて','enum.admStatus.Applied':'応募済み','enum.admStatus.Interview Scheduled':'面接予定','enum.admStatus.Interview Done':'面接済み','enum.admStatus.Accepted':'合格','enum.admStatus.Waitlisted':'保留','enum.admStatus.Rejected':'不合格','enum.admStatus.Enrolled':'入学済み','enum.admStatus.Withdrawn':'辞退','enum.gender.Male':'男性','enum.gender.Female':'女性','enum.gender.Other':'その他',
    'adm.none':'応募者はいません','adm.total':'合計','adm.inProgress':'進行中','adm.noParent':'保護者情報なし','adm.appliedOn':'応募日','adm.moveTo':'移動先','adm.movedTo':'移動しました','adm.selected':'選択済み','adm.enrollOwn':'登録','adm.clear':'クリア','adm.bulkMoving':'一括移動中…','adm.bulkMoved':'✓ 移動しました','adm.failedN':'{n}件失敗','adm.noClassSet':'クラスが設定されていません','adm.enrolling':'登録中…','adm.skipped':'スキップしました','adm.enrolledPending':'登録済み — 保留中','adm.newTitle':'新しい応募者','adm.nameEn':'英語名','adm.fullName':'氏名','adm.nameLocalOpt':'現地名（任意）','adm.nameLocal':'現地名','adm.dob':'生年月日','adm.gender':'性別','adm.desiredClass':'希望クラス','adm.parentName':'保護者名','adm.parentPhone':'保護者電話','adm.parentEmail':'保護者メール','adm.optional':'任意','adm.source':'情報源','adm.sourcePh':'例: Webサイト','adm.notes':'メモ','adm.add':'応募者を追加','adm.enterName':'名前を入力してください','adm.validEmail':'メールアドレスが正しくありません','adm.addedPhotoFail':'追加しましたが、画像のアップロードに失敗しました','adm.added':'✓ 追加しました','adm.rowLocal':'現地名','adm.rowParent':'保護者','adm.rowPhone':'電話','adm.rowEmail':'メール','adm.rowApplied':'応募日','adm.rowInterview':'面接','adm.moveToTitle':'応募者を移動','adm.enrollBtn':'生徒として登録','adm.editDetails':'詳細を編集','adm.deleteApplicant':'応募者を削除','adm.officialStudent':'正式な生徒','adm.pendingCreated':'記録を作成しました — 保留中','adm.createRegInvoice':'登録請求書を作成','adm.regPaid':'支払済み','adm.regUnpaid':'未払い','adm.goBilling':'請求へ','adm.scheduleTitle':'面接を設定','adm.interviewDate':'面接日','adm.interviewScheduled':'✓ 面接を予定しました','adm.editTitle':'応募者を編集','adm.nameRequired':'名前は必須です','adm.savedPhotoFail':'保存しましたが、画像のアップロードに失敗しました','adm.saved':'✓ 保存しました','adm.convertNote':'応募者を生徒に変換します','adm.enroll':'登録','adm.enterClass':'クラスを入力してください','adm.enrollingBtn':'登録中…','adm.recordCreated':'✓ 生徒記録を作成しました — {id}（保留）','adm.regTitle':'登録請求書','adm.needAmountItem':'金額のある明細を1つ以上追加してください','adm.regCreated':'✓ 登録請求書を作成しました','adm.delTitle':'🗑 この応募者を削除しますか？','adm.delBody':'応募記録を削除します。すでに生徒に変換された記録には影響しません。',
    'health.bloodType':'血液型','health.allergies':'アレルギー','health.allergiesPh':'例: ピーナッツ、ペニシリン','health.conditions':'持病','health.conditionsPh':'例: 喘息','health.medications':'服薬','health.emContactName':'緊急連絡先名','health.emContactPhone':'緊急連絡先電話','health.doctorName':'医師名','health.doctorPhone':'医師電話','health.notes':'メモ','health.allergiesLabel':'アレルギー:','health.conditionsLabel':'持病:','health.emergencyContact':'緊急連絡先','health.doctor':'医師','health.editProfile':'健康情報を編集','health.vaccinations':'予防接種','health.noDate':'日付なし','health.noVax':'予防接種の記録はありません','health.addVax':'+ 予防接種を追加','health.visits':'診察・看護記録','health.noVisits':'診察記録はありません','health.logVisit':'+ 診察を記録','health.editTitle':'健康情報を編集','health.bloodTypePh':'例: O+','health.medicationsOpt':'任意','health.addVaxTitle':'予防接種を追加','health.vaccineName':'ワクチン名','health.vaccineNamePh':'例: MMR','health.dateGiven':'接種日','health.enterVaccine':'ワクチン名を入力してください','health.delVaxTitle':'🗑 この予防接種記録を削除しますか？','health.logVisitTitle':'診察を記録','health.reason':'理由','health.reasonPh':'例: 発熱、頭痛','health.treatment':'処置','health.enterReason':'理由を入力してください','health.delVisitTitle':'🗑 この診察記録を削除しますか？','health.added':'✓ 追加しました','health.logged':'✓ 記録しました',
    'lib.titles':'書籍数','lib.copies':'冊数','lib.checkedOut':'貸出中','lib.none':'本はまだありません — ＋で追加','lib.unknownAuthor':'著者不明','lib.newTitle':'新しい本','lib.title':'タイトル','lib.bookTitle':'書名','lib.author':'著者','lib.category':'カテゴリ','lib.categoryPh':'例: 小説、参考書（任意）','lib.isbn':'ISBN','lib.add':'本を追加','lib.enterTitle':'タイトルを入力してください','lib.added':'✓ 本を追加しました','lib.avail':'{a}冊利用可能 / 全{t}冊','lib.checkoutBtn':'生徒に貸し出す','lib.currentlyOut':'貸出中','lib.since':'{date}から','lib.due':'、返却期限 {date}','lib.return':'返却','lib.none2':'現在ありません','lib.history':'履歴','lib.editTitle':'本を編集','lib.totalCopies':'総冊数','lib.titleRequired':'タイトルは必須です','lib.checkoutTitle':'貸出','lib.student':'生徒','lib.selectStudent':'生徒を選択','lib.checkoutBtn2':'貸出','lib.pickStudent':'生徒を選択','lib.checkingOut':'貸出中…','lib.checkedOutToast':'✓ 貸し出しました','lib.returnedToast':'✓ 返却しました','lib.delTitle':'🗑 この本を削除しますか？','lib.delBody':'貸出中の冊がない場合のみ削除できます','lib.mustReturn':'削除する前にすべて返却してください',
    'tr.none':'ルートはまだありません — ＋で追加','tr.noDriver':'運転手未設定','tr.newTitle':'新しいルート','tr.routeName':'ルート名','tr.routeNamePh':'例: ルートA — 北','tr.driverName':'運転手名','tr.driverPhone':'運転手電話','tr.vehicle':'車両','tr.vehiclePh':'例: Toyota Coaster、車両番号（任意）','tr.add':'ルートを追加','tr.enterName':'ルート名を入力してください','tr.added':'✓ ルートを追加しました','tr.driver':'運転手','tr.phone':'電話','tr.vehicleLabel':'車両','tr.students':'生徒（{n}）','tr.noStudents':'割り当てられた生徒はいません','tr.assign':'生徒を割り当てる','tr.editRoute':'ルートを編集','tr.deleteRoute':'ルートを削除','tr.editTitle':'ルートを編集','tr.routeRequired':'ルート名は必須です','tr.assignTitle':'生徒を割り当て','tr.pickupStop':'乗車場所','tr.pickupStopPh':'例: 正門（任意）','tr.pickupTime':'迎え時間','tr.dropoffTime':'送り時間','tr.assignBtn':'割り当て','tr.assigning':'割り当て中…','tr.assigned':'✓ 割り当てました','tr.delTitle':'🗑 このルートを削除しますか？','tr.delBody':'このルートの生徒は割り当て解除されるだけで、学校から削除されません。',
    'settings.title':'⚙️ 設定','settings.version':'バージョン','settings.platform':'プラットフォーム','settings.school':'学校','settings.teacher':'教師','settings.role':'役割','settings.login':'ログイン','settings.telegram':'Telegram','settings.connected':'🟢 接続済み','settings.notConnected':'⚪ 未接続','settings.manageTeachers':'👥 教師を管理','settings.connectTelegram':'🔗 Telegramを接続','settings.disconnectTelegram':'🔌 Telegramの接続を解除','settings.changePassword':'🔑 パスワードを変更','settings.footerNote':'SCMSは学校管理者によって管理されています。','settings.googleAccount':'Googleアカウント','settings.webPassword':'Web（パスワード）',
    'tm.title':'👥 教師を管理','tm.subtitle':'教師のログインアカウントを作成します。','tm.addNew':'+ 新しい教師を追加（教師ID＋パスワード）','tm.inviteGoogle':'✉️ Googleで招待（コードを共有）','tm.loading':'読み込み中…','tm.loadFailed':'教師の読み込みに失敗しました','tm.none':'教師はまだいません','tm.lastLogin':'最終ログイン: {date}','tm.never':'なし','tm.idCard':'教師IDカード','tm.cardLoading':'安全なカードを生成中…','tm.cardScan':'QRをスキャンして教師ログインを開始',
    'tm.cardPurposeTitle':'このカードは何のためですか？',
    'tm.cardPurpose':'このカードは学校システムへ安全に教師ログインするために使用します。',
    'tm.cardStep1':'1. このカードのQRコードをスキャンします。',
    'tm.cardStep2':'2. Login Nameを入力します。',
    'tm.cardStep3':'3. PINを入力してログインします。',
    'tm.cardSecurity':'カードとPINを安全に保管し、QRコードやPINを共有しないでください。','tm.printCard':'カードを印刷','tm.regenerateCard':'カードを再生成','tm.cardFailed':'教師IDカードを生成できませんでした','tm.resetPassword':'パスワードをリセット',
    'inv.title':'✉️ Googleで招待','inv.subtitle':'教師は自分のGoogleアカウントでログインし、このコードで参加します。','inv.name':'名前（任意）','inv.namePh':'例: Daw Hla Hla','inv.role':'役割 *','inv.roleTeacher':'教師','inv.roleAdmin':'管理者','inv.generate':'コードを生成','inv.generating':'生成中…','inv.codeLabel':'招待コード','inv.hint':'このコードを教師に送ってください（14日間有効）。Google Sign-In → 「招待コードを持っています」から使用できます。','inv.pastInvites':'過去の招待','inv.usedBy':'✅ {id} が使用','inv.expired':'⌛ 期限切れ','inv.pending':'⏳ 保留中','inv.back':'戻る','inv.failed':'招待の作成に失敗しました: {err}'
  });
  Object.assign(overrides, {
    'students.stat.students':'生徒','students.stat.classes':'クラス','students.stat.hereToday':'本日出席','students.subtitle':'{c}クラスに在籍するアクティブな生徒 {n} 人','students.empty.title':'生徒が見つかりません','students.empty.searchHint':'別の検索語をお試しください','students.empty.addHint':'＋をタップして生徒を追加','students.notMarked':'未記録','students.tgLinked':'TG連携済み','students.homeLabel':'ホーム:','students.bday.today':'今日！','students.bday.tooltip':'{n}日後が誕生日','students.linked':'✓ 連携済み','students.getLink':'リンクを取得 →','students.sendLinkBtn':'📤 保護者にリンクを送る','students.field.gender':'性別','students.field.grade':'学年','students.field.birthday':'誕生日','students.field.home':'ホーム','students.field.parent':'保護者','students.field.parentPhone':'保護者電話','students.field.parentEmail':'保護者メール','students.field.parentTg':'保護者Telegram','students.detail.recentReports':'最近のレポート','students.detail.recentIncidents':'最近のインシデント','students.detail.editInfo':'生徒情報を編集',
    'students.form.editTitle':'生徒を編集','students.form.addTitle':'新しい生徒を追加','students.form.removePhoto':'写真を削除','students.form.localName':'現地名（ミャンマー語 / 母語）','students.form.localNamePh':'生徒名…','students.form.englishName':'英語名 *','students.form.englishNamePh':'英語の氏名','students.form.class':'クラス *','students.form.selectClass':'クラスを選択','students.form.grade':'学年','students.form.selectGrade':'学年を選択','students.form.gender':'性別','students.form.genderM':'男性','students.form.genderF':'女性','students.form.genderOther':'その他','students.form.birthday':'誕生日','students.form.birthdayHint':'（🎂 リマインダーに使用）','students.form.homeColor':'ハウスカラー','students.form.homeColorHint':'（チーム / ハウス）','students.form.parentSection':'保護者 / 代理人','students.form.parentName':'保護者名','students.form.parentNamePh':'保護者名','students.form.parentPhone':'保護者電話','students.form.parentPhonePh':'+95 9 xxx xxx xxx','students.form.parentEmail':'保護者メール','students.form.parentEmailOptional':'保護者メール（任意）','students.form.parentEmailPh':'parent@example.com','students.form.parentTg':'保護者Telegram','students.form.saveEdit':'変更を保存','students.form.register':'生徒を登録','students.form.removeBtn':'生徒を削除','students.form.savingEdit':'保存中…','students.form.registering':'登録中…','students.form.parentTgInfo':'生徒を登録すると保護者のTelegram IDが<b>自動的に</b>入力されます。保護者に共有するリンクが表示され、TelegramでタップするとIDが取得されます。',
    'students.toast.imageOnly':'画像ファイルを選択してください','students.toast.imageTooBig':'写真が大きすぎます（最大20 MB）','students.toast.studentNotFound':'生徒が見つかりません','students.toast.nameRequired':'英語名は必須です','students.toast.classRequired':'クラスは必須です','students.toast.emailInvalid':'保護者メールが正しくありません','students.toast.phoneInvalid':'保護者電話が正しくありません','students.toast.updated':'✓ {name} を更新しました','students.toast.registered':'✓ {name} を登録しました','students.toast.photoUploadFailedEdit':'保存しましたが写真のアップロードに失敗しました: {err}','students.toast.photoRemoveFailed':'保存しましたが写真の削除に失敗しました: {err}','students.toast.photoUploadFailedAdd':'登録しましたが写真のアップロードに失敗しました: {err}','students.toast.saveFailed':'保存に失敗しました: {err}','students.toast.registerFailed':'登録に失敗しました: {err}','students.delete.title':'{name} を削除しますか？','students.delete.body':'生徒を<b>非アクティブ</b>にします。出欠やレポートは保持されますが、日次リストには表示されません。','students.delete.confirm':'はい、削除','students.delete.done':'✓ 生徒を削除しました',
    'parentLink.title':'保護者のTelegramを連携','parentLink.body':'{name} の保護者にこのリンクを共有してください。Telegramでタップすると、この生徒に保護者IDが自動連携されます。','parentLink.copy':'📋 リンクをコピー','parentLink.share':'📤 Telegramで共有','parentLink.waiting':'保護者がリンクをタップするのを待っています…','parentLink.linkedHtml':'✓ <b>連携済み！</b> 保護者ID: <code>{id}</code>','parentLink.done':'完了 — 後で共有します','parentLink.copied':'✓ リンクをコピーしました','parentLink.copyFail':'コピーできません — 長押しして手動でコピーしてください','parentLink.shareText':'こんにちは！学校からの {name} に関する更新を受け取るには、このリンクをTelegramでタップしてください:',
    'picker.class.title':'クラスを選択','picker.class.addLabel':'新しいクラスを追加','picker.class.placeholder':'（例: P4 Online）','picker.grade.title':'学年を選択','picker.grade.addLabel':'新しい学年を追加','picker.select':'選択…','picker.empty':'選択肢がありません — 下から追加','picker.typeName':'先に名前を入力してください','picker.deleteConfirm':'{list} リストから「{value}」を削除しますか？',
    'leave.pageEyebrow':'申請','leave.pageTitle':'休暇申請','leave.loading':'休暇申請を読み込み中…','leave.empty':'休暇申請はありません','leave.status.Pending':'保留中','leave.status.Approved':'承認済み','leave.status.Rejected':'却下済み','leave.approve':'承認','leave.reject':'却下','leave.approveTitle':'この休暇申請を承認しますか？','leave.approveMsg':'期間内の各日を「休暇」として出席記録します。','leave.rejectTitle':'この休暇申請を却下しますか？','leave.rejectMsg':'保護者には自動通知されません。','leave.decided':'休暇申請は{status}、{n}日を記録しました','leave.decideFailed':'申請を更新できませんでした',
    'dash.classesToday':'今日のクラス','dash.notYetMarked':'未記録','dash.homeworkLogged2d':'宿題記録（2日）','dash.recentIncidents':'最近のインシデント','dash.messagesQueued':'送信待ちメッセージ','dash.myClassesOnly':'自分のクラスのみ','dash.todaysSchedule':'今日の予定','dash.noClassesToday':'今日は授業がありません。','dash.quickActions':'クイックアクション','dash.takeAttendance':'出欠を取る','dash.logHomework':'宿題を記録','dash.messageParent':'保護者にメッセージ','dash.recordIncident':'インシデントを記録','dash.studentsAttention':'要注意の生徒','dash.recentIncidentsTitle':'最近のインシデント','dash.absences14':'過去14日間の欠席 {n} 件','dash.bannerTitle':'未送信メッセージ {n} 件','dash.bannerText':'Telegram配信ボットは現在オフラインです。保護者へのメッセージはキューに残っています。','dash.loading':'ダッシュボードを読み込み中…','dash.loadFailed':'ダッシュボードの読み込みに失敗しました','dash.todayLabel':'今日','dash.totalStudents':'生徒総数','dash.presentToday':'本日の出席','dash.absentToday':'本日の欠席','dash.pendingHomework':'未完了の宿題','dash.leaveRequests':'休暇申請','dash.notifications':'通知','dash.newCount':'新着 {n} 件','dash.leavePendingOne':'休暇申請 {n} 件が保留中','dash.leavePendingMany':'休暇申請 {n} 件が保留中','dash.leaveReview':'新しい休暇申請を確認してください。','dash.messageNotDeliveredOne':'未送信メッセージ {n} 件','dash.messageNotDeliveredMany':'未送信メッセージ {n} 件','dash.noNewNotifications':'新しい通知はありません',
    'idCard.title':'生徒証','idCard.failed':'カードを作成できません: {err}。生徒は有効状態である必要があります。','idCard.scanHint':'保護者がスキャンしてParent Portalにサインインします。','idCard.copyLink':'リンクをコピー','idCard.testHint':'リンクのテストや、スキャンできない保護者への直接送信に使えます。','idCard.print':'🖨 カードを印刷','idCard.lost':'🔄 カード紛失 — 新しいコードを発行','idCard.regenTitle':'🔄 新しいコードを発行しますか？','idCard.regenBody':'古いカードのQRコードはすぐに使えなくなります。新しいカードを配布する前に印刷してください。','idCard.regenConfirm':'新しいコードを発行','idCard.regenDone':'✓ 新しいコードを発行しました','idCard.selectMode':'生徒証用に選択','idCard.nSelected':'{n}件選択','idCard.selectAllVisible':'表示中をすべて選択','idCard.selectNone':'クリア','idCard.printSelected':'生徒証を印刷','idCard.preparing':'{n}枚を準備中…','idCard.orientVertical':'縦型カード','idCard.orientHorizontal':'横型カード',
    'stuLib.title':'図書貸出','stuLib.empty':'貸出記録はありません','stuLib.since':'{date}から','stuLib.returnedOn':'{date}に返却','stuLib.return':'返却','stuLib.returned':'✓ 返却済み','stuTr.title':'送迎','stuTr.none':'ルート未設定','stuTr.goto':'送迎へ','stuTr.route':'ルート','stuTr.driver':'運転手','stuTr.phone':'電話','stuTr.pickupStop':'乗車場所','stuTr.pickupTime':'迎え時間','stuTr.dropoffTime':'送り時間','stuTr.manage':'送迎を管理',
    'picker.remove':'削除','picker.removeFromList':'リストから削除','picker.deleteNote':'この{kind}に登録済みの生徒には影響しません','picker.list.classes':'クラス','picker.list.grades':'学年','picker.kind.classes':'クラス','picker.kind.grades':'学年',
    'att.code.P.label':'出席','att.code.P.short':'出','att.code.P.desc':'生徒は出席しています','att.code.A.label':'欠席','att.code.A.short':'欠','att.code.A.desc':'無断欠席','att.code.L.label':'休暇','att.code.L.short':'休','att.code.L.desc':'承認済み休暇','att.code.T.label':'遅刻','att.code.T.short':'遅','att.code.T.desc':'遅れて到着','att.code.S.label':'病欠','att.code.S.short':'病','att.code.S.desc':'病気で欠席','att.code.E.label':'公欠','att.code.E.short':'公','att.code.E.desc':'正当な理由のある欠席','att.code.H.label':'半日','att.code.H.short':'½日','att.code.H.desc':'一日の一部のみ出席','att.noClasses':'クラスがありません — 先に生徒を追加してください','att.classOption':'{name} クラス','att.noActive':'{cls} に有効な生徒はいません','att.noteAdd':'メモを追加','att.noteAddTitle':'理由 / メモを追加','att.hasNote':'メモあり: {note}','att.codeGroup':'出欠コード','att.notMarkedYet':'未記録','att.noteTitle':'{name} のメモ','att.currentStatus':'現在の状態:','att.reasonLabel':'理由 / メモ（任意）','att.reasonPh':'例: 医師受診、家族行事、バス遅延…','att.charCount':'{n} / 200文字','att.saveNote':'メモを保存','att.noteSaved':'メモを保存しました','att.noteRemoved':'メモを削除しました','att.markedAll':'すべてを{label}にしました','att.cleared':'記録をクリアしました','att.legendTitle':'出欠コード','att.legendHint':'生徒名の下のコードをタップして出欠を記録します。','att.gotIt':'了解','att.stat.marked':'記録済み','att.stat.more':'その他','att.selectClassFirst':'先にクラスを選択してください','att.noStudentsInClass':'このクラスに生徒はいません','att.saved':'✓ {cls} の出欠を保存しました — {date}','att.saveFailed':'保存に失敗しました: {err}',
    'landing.subtitle':'出欠、宿題、保護者への更新、チーム管理をすべて1か所で。','landing.getStarted':'または始める','landing.registerSchoolSub':'Telegramで学校を設定','landing.joinSchoolSub':'教師として申請','landing.parentQ':'保護者ですか？','landing.parentBody':'アプリは不要です。教師からTelegramのリンクを受け取れば、そこでレポートを受け取れます。','landing.waitTg':'Telegramを待っています…','landing.waitTgSub':'Telegramを開きました。ボットで<b>Start</b>をタップしてログインしてください。','landing.openAgain':'Telegramをもう一度開く','landing.tgNotOpen':'Telegramが開きませんか？','landing.tgManual':'このリンクをコピーしてTelegramで開いてください:','landing.copyLink':'📋 リンクをコピー','landing.copied':'✓ コピーしました','landing.checking':'ログインを確認中…','landing.timeout':'タイムアウトしました。もう一度試しますか？','landing.signedIn':'ログインしました！学校を読み込んでいます…',
    'login.sub':'学校管理者から受け取ったTeacher IDを使用してください。','login.teacherIdPh':'例: T123456','login.needBoth':'Teacher IDとパスワードを入力してください','login.failed':'ログインに失敗しました','login.connErr':'接続エラー — インターネットを確認してください','pw.titleFirst':'新しいパスワードを設定','pw.titleChange':'パスワードを変更','pw.firstNote':'初回ログイン時にパスワードを変更する必要があります。','pw.btnFirst':'パスワードを設定して続行','pw.tooShort':'パスワードは6文字以上必要です','pw.mismatch':'パスワードが一致しません','pw.sessionExpired':'セッションの有効期限が切れました — 再度ログインしてください','pw.failed':'パスワードを変更できませんでした','pw.connErr':'接続エラー','pw.done':'✓ パスワードを変更しました','login.help':'Teacher IDがない場合は管理者に作成してもらうか、<b>Telegramでログイン</b>してください。',
    'page.dashboard.sub':'今日の概要をひと目で確認できます','page.students.eyebrow':'名簿','page.attend.eyebrow':'毎日の出欠','page.attend.sub':'今日のクラスの出欠を記録します','page.daily.eyebrow':'保護者向け','page.daily.title':'デイリー<em>レポート</em>','page.daily.sub':'今日の概要を保護者に送信します','page.hw.eyebrow':'課題','page.hw.sub':'クラスごとの宿題を管理・割り当てます','page.grades.eyebrow':'評価','page.grades.sub':'生徒の評価点を記録・追跡します','page.billing.eyebrow':'料金','page.billing.sub':'生徒ごとの請求と支払い','page.admissions.eyebrow':'入学受付','page.admissions.sub':'問い合わせから入学まで応募者を管理します','page.library.eyebrow':'リソース','page.library.sub':'蔵書と貸出を管理します','page.transport.eyebrow':'リソース','page.transport.sub':'送迎ルートと生徒の乗降を管理します','page.parents.eyebrow':'コミュニケーション','page.parents.title':'保護者<em>メッセージ</em>','page.parents.sub':'家庭との最近の連絡','page.incidents.eyebrow':'記録','page.incidents.sub':'行動、成果、重要なメモ','page.timetable.eyebrow':'スケジュール','page.summary.eyebrow':'分析','page.more.eyebrow':'ツール',
    'msg.offlineBanner':'📡 オフライン — 再接続すると変更が同期されます','btn.retry':'再試行','menu.open':'メニューを開く','menu.title':'メニュー','status.connection':'接続状態','lang.switchTitle':'言語を切り替え','btn.refreshData':'データを更新','students.searchPh':'生徒を検索…','att.prevWeek':'前の週','att.jumpToday':'今日へ','att.nextWeek':'次の週','btn.addNew':'新規追加','billing.feeItems':'料金項目','att.legendBtn':'出欠コードを見る',
    'module.incidents':'インシデント','module.grades':'成績','module.billing':'請求','module.admissions':'入学受付','module.library':'図書館','module.transport':'送迎','module.parents':'保護者','module.timetable':'時間割','module.summary':'概要',
    'sb.dashboard':'ダッシュボード','sb.leave':'休暇','page.leave.eyebrow':'申請','page.leave.title':'休暇申請','sb.students':'生徒','sb.attend':'出欠','sb.daily':'日次','sb.hw':'宿題','sb.chat':'チャット','sb.settings':'設定','sb.signout':'ログアウト','sb.cover':'カバー画像','sb.changeCover':'カバー画像を変更','sb.changeLogo':'ロゴを変更',
    'more.browse':'閲覧','more.help':'ヘルプ','more.modules':'モジュール','more.staffChat':'スタッフチャット','more.admin':'管理者','more.logo':'ロゴ','more.cover':'カバー','more.classes':'クラス','more.schoolSettings':'学校設定','more.teachers':'教師','more.export':'エクスポート','more.exportSoon':'エクスポートは近日利用可能','more.display':'表示','more.bottomBar':'下部バー','more.bottomBarSub':'下部ナビゲーションを表示','more.bottomBarOn':'オン','more.bottomBarOff':'オフ','more.about':'SCMSについて','more.schoolId':'学校ID','more.activeStudents':'在籍中の生徒','more.platform':'プラットフォーム','more.version':'バージョン','more.currentTerm':'現在の学期','more.changeLogo':'ロゴを変更','more.changePhoto':'写真を変更','more.changePhotoAria':'写真を変更','more.logoAlt':'学校ロゴ',
    'modules.title':'モジュール','modules.hint':'サイドバーに表示するモジュールを選択','modules.showInSidebar':'サイドバーに表示','modules.save':'保存','modules.needWeb':'Webが必要','modules.saved':'✓ 保存しました','modules.saveFailed':'保存に失敗しました',
    'signout.title':'ログアウトしますか？','signout.body':'本当にログアウトしますか？','schoolInfo.title':'学校情報','schoolInfo.name':'学校名','schoolInfo.subjects':'科目','schoolInfo.attCodes':'出欠コード','schoolInfo.currency':'通貨','schoolInfo.hint':'この情報は学校全体で使用されます',
    'cg.adminOnly':'管理者のみ','cg.none':'データがありません','cg.hint':'学校のクラスと学年を管理','cg.classes':'クラス','cg.grades':'学年','cg.classPh':'例: P4 Online','cg.gradePh':'例: Grade 4','cg.exists':'すでに存在します','cg.confirmRemove':'この項目を削除しますか？','cg.couldNotSave':'保存できませんでした','common.done':'完了','common.saved':'保存しました','common.saveFailedShort':'保存に失敗しました','common.unknown':'不明',
    'boot.openingTg':'Telegramを開いています','boot.starting':'開始中…','boot.preview':'プレビュー','boot.title':'SCMSを開いています','boot.auth':'認証を確認中','boot.user':'ユーザー','boot.loadingSchool':'学校を読み込み中','boot.building':'システムを準備中','boot.signingIn':'ログイン中','boot.loadingYourSchool':'学校を読み込み中',
    'err.connFailed':'接続に失敗しました','err.authFailed':'認証に失敗しました','err.notRegistered':'未登録です','err.startup':'起動に失敗しました','err.unknown':'不明なエラーが発生しました','toast.refreshing':'更新中…','toast.updated':'更新しました','toast.refreshFailed':'更新に失敗しました','subject.add':'科目を追加','subject.ph':'科目名','subject.enter':'科目名を入力してください','subject.adding':'追加中…','subject.added':'✓ 科目を追加しました','picker.searchPh':'検索…','chat.ph':'メッセージを入力…','chat.loadFailed':'チャットの読み込みに失敗しました','chat.retry':'再試行','chat.emptyTitle':'メッセージはありません','chat.emptySub':'会話を始めましょう','chat.sendFailed':'メッセージの送信に失敗しました',
    'enum.meal.Full':'完食','enum.meal.Half':'半分','enum.meal.Little':'少し','enum.meal.None':'食べていない','enum.mood.Happy':'嬉しい','enum.mood.OK':'普通','enum.mood.Tired':'疲れた','enum.mood.Sad':'悲しい','enum.mood.Energetic':'元気','enum.yesno.Yes':'はい','enum.yesno.No':'いいえ','enum.hwType.Homework':'宿題','enum.hwType.Lesson':'授業','enum.hwType.Test':'テスト','enum.hwType.Quiz':'小テスト','enum.hwType.Project':'プロジェクト','enum.hwType.Worksheet':'ワークシート','enum.commType.All':'すべて','enum.commType.General':'一般','enum.commType.Absent Alert':'欠席通知','enum.commType.Daily Report':'日次レポート','enum.commType.Praise':'称賛','enum.commType.Incident':'インシデント','enum.commType.Homework':'宿題','enum.commType.Broadcast':'一斉連絡','enum.commStatus.Sent':'送信済み','enum.commStatus.queued':'送信待ち','enum.commStatus.Queued':'送信待ち','enum.incType.All':'すべて','enum.incType.Good Behaviour':'良い行動','enum.incType.Participation':'参加','enum.incType.Achievement':'達成','enum.incType.Concern':'懸念','enum.incType.Conflict':'対立','enum.incType.Health':'健康','enum.incType.Bullying':'いじめ','enum.incType.Injury':'けが','enum.incType.Other':'その他','enum.severity.Info':'情報','enum.severity.Low':'低','enum.severity.Medium':'中','enum.severity.High':'高','enum.severity.Critical':'重大','enum.subject.Mathematics':'数学','enum.subject.English':'英語','enum.subject.Science':'理科','enum.subject.Social Studies':'社会',
    'common.deleted':'削除しました','common.deleteFailed':'削除に失敗しました','common.updateFailed':'更新に失敗しました','common.itemNotFound':'項目が見つかりません','common.cantUndo':'元に戻せません','common.saveChanges':'変更を保存','common.opt':'任意',
    'daily.noClasses':'クラスがありません','daily.addStudentsFirst':'先に生徒を追加してください','daily.noStudents':'生徒がいません','daily.nap':'昼寝','daily.min':'分','daily.notFilled':'未入力','daily.confirmDelete':'このレポートを削除しますか？','daily.modalTitle':'日次レポート','daily.mealToday':'今日の食事','daily.napMin':'昼寝時間（分）','daily.mood':'気分','daily.behaviourNote':'行動メモ','daily.behaviourPh':'メモを入力…','daily.toilet':'トイレ','daily.save':'保存','daily.pickMeal':'食事を選択','daily.pickMood':'気分を選択','daily.saved':'✓ 保存しました','daily.pickerTitle':'生徒のレポート','daily.pickerSub':'生徒を選択してレポートを入力'
  });
  Object.assign(overrides, {
    'students.rollNo':'出席番号','students.section':'セクション','students.searchPlaceholder':'名前または出席番号で検索','common.optional':'（任意）','common.error':'エラー','common.networkError':'ネットワークエラー','common.loadFailed':'読み込みに失敗しました: {err}','students.subtitleOneClass':'{c}クラスに在籍するアクティブな生徒 {n} 人','students.subtitleOne':'{c}クラスに在籍するアクティブな生徒 {n} 人','students.bday.tooltipOne':'1日後が誕生日','students.bday.short':'{n}日','students.detail.meal':'食事:','students.btn.health':'健康記録',
    'color.red':'赤','color.orange':'オレンジ','color.amber':'アンバー','color.yellow':'黄','color.lime':'ライム','color.green':'緑','color.teal':'ティール','color.cyan':'シアン','color.sky':'空色','color.blue':'青','color.indigo':'藍','color.violet':'紫','color.fuchsia':'フューシャ','color.pink':'ピンク','color.rose':'ローズ','color.slate':'スレート','page.summary.sub':'今月のパフォーマンス概要','hw.none':'宿題はまだありません',
    'ct.title':'+ 新しい教師','ct.subtitle':'ログインアカウントを作成します。初回ログイン時に初期パスワードを変更します。','ct.teacherId':'教師ID *','ct.teacherIdPh':'例: T1001','ct.loginName':'ログイン名 *','ct.loginNamePh':'例: teacher1','ct.teacherName':'教師名 *','ct.email':'メール（任意）','ct.role':'役割 *','ct.roleAdmin':'管理者（他の教師を管理できます）','ct.startPw':'初期パスワード（6文字以上） *','ct.startPwHint':'このパスワードを安全に共有してください。初回ログイン時に変更します。','ct.create':'アカウントを作成','ct.needFields':'教師ID、名前、パスワードはすべて必須です','ct.pwTooShort':'パスワードは6文字以上必要です','ct.sessionExpired':'管理者セッションの期限が切れました。再度ログインしてください。','ct.creating':'作成中…','ct.createFailed':'作成に失敗しました','ct.created':'✓ 教師アカウントを作成しました','ct.connErr':'接続エラー','rp.prompt':'{name}（{id}）のパスワードをリセットします。\n\n新しいパスワード（6文字以上）:','rp.sessionExpired':'管理者セッションの期限が切れました','rp.failed':'リセットに失敗しました: {err}','rp.done':'✓ {name} の新しいパスワード: {pw}\n本人に共有してください',
    'ga.signingIn':'ログイン中…','ga.loginFailed':'ログインに失敗しました','ga.connErr':'接続エラー — インターネットを確認してください','ga.welcome':'👋 ようこそ','ga.noAccount':'このGoogleアカウントにはSCMSアカウントがありません。何をしますか？','ga.startSchool':'新しい学校を始める','ga.startSchoolSub':'あなたが管理者になります','ga.haveInvite':'招待コードを持っています','ga.haveInviteSub':'管理者からのコードで参加','ga.back':'← 戻る','ga.yourName':'あなたの名前','ga.namePh':'例: Sangfa','ga.schoolName':'学校名','ga.schoolNamePh':'例: Vavida ISB','ga.startSchoolBtn':'学校を始める','ga.enterSchoolName':'学校名を入力してください','ga.inviteCode':'招待コード','ga.inviteCodePh':'例: AC3F79','ga.join':'参加','ga.enterInviteCode':'招待コードを入力してください','ga.emailSignIn':'📧 メールでログイン','ga.emailSignInSub':'メールアドレスとパスワードを入力','ga.email':'メール','ga.password':'パスワード','ga.rememberMe':'ログイン情報を記憶','ga.signIn':'ログイン','ga.noAccountQ':'アカウントがありませんか？','ga.signUp':'登録','ga.enterEmailPw':'メールとパスワードを入力','ga.createAccount':'✨ 新しいアカウントを作成','ga.createAccountSub':'メールとパスワードを自分で設定','ga.atLeast6':'6文字以上','ga.whatToDo':'何をしますか？','ga.chooseToContinue':'続行する項目を選択','ga.haveAccountQ':'すでにアカウントがありますか？','ga.enterName':'名前を入力','ga.enterEmail':'メールを入力','ga.pwAtLeast6':'パスワードは6文字以上必要です','ga.chooseSchoolOrInvite':'新しい学校または招待コードを選択','ga.creatingAccount':'アカウントを作成中…','ga.signupFailed':'登録に失敗しました',
    'tg.connectTitle':'🔗 Telegramを接続','tg.connectSub':'保護者レポートとバックアップログインのためTelegramを接続します。','tg.waitingStart':'Telegramボットを開いてStartをタップ…','tg.openTelegram':'Telegramを開く','tg.connectFailed':'接続できません — もう一度お試しください','tg.reopen':'もう一度開く','tg.waitingTap':'TelegramでStartをタップ… 待機中','tg.timedOut':'タイムアウト — もう一度お試しください','tg.connected':'✓ Telegramを接続しました','tg.disconnectTitle':'🔌 Telegramの接続を解除しますか？','tg.disconnectSub':'保護者レポートとバックアップログイン用のTelegram接続を解除します。','tg.disconnect':'接続を解除','tg.disconnected':'Telegramの接続を解除しました','ga.showPassword':'パスワードを表示',
    'branding.adminOnly':'管理者のみ変更できます','branding.chooseImage':'📷 画像を選択','branding.imageTypes':'PNG、JPG、WebP画像を選択してください','branding.imageTooBig':'画像が大きすぎます（最大8 MB）','branding.tryAgain':'もう一度試す','reg.title':'登録','reg.instructions':'新しい学校を登録するか教師として参加するには、Telegramボットのコマンドを使用してください:','reg.createSchool':'新しい学校を作成','reg.joinSchool':'既存の学校に参加','reg.approvedNote':'管理者が承認するとアカウントが有効になり、ダッシュボードが自動的に読み込まれます。','reg.gotIt':'了解','enum.roleName.admin':'管理者','enum.roleName.teacher':'教師','enum.roleName.super_admin':'スーパー管理者',
    'help.title':'SCMSの使い方','help.subtitle':'使い方 · クイックガイド','help.tab.basics':'基本','help.tab.features':'機能','help.tab.admin':'管理者','help.tab.trouble':'トラブルシューティング','help.tab.about':'概要',
    'help.basics.introTitle':'SCMSとは？','help.basics.introBody':'学校クラス管理システム — 1つのTelegramボットから学校全体を管理できます。出欠、宿題、日次レポート、保護者メッセージをまとめて管理します。','help.basics.step1Title':'ログイン','help.basics.step1Body':'Telegramボットのメニューボタンをタップしてアプリを開きます。アカウントは自動検出されます。','help.basics.step2Title':'下部タブ','help.basics.step2Body':'生徒 · 出欠 · 日次 · 宿題 · その他 — タップして移動します。','help.basics.step3Title':'+ ボタン（FAB）','help.basics.step3Body':'右下の＋ボタンは現在のページに応じて「追加」を実行します。例: 生徒ページでは新しい生徒を追加します。','help.basics.step4Title':'更新','help.basics.step4Body':'右上の↻ボタンで最新データを取得します。','help.basics.tip':'ヒント: 初めて使うときは、まず生徒を追加してください。その後、出欠や宿題などが使えるようになります。',
    'help.feat.students.title':'生徒','help.feat.students.1':'生徒カードをタップ → 詳細を見る','help.feat.students.2':'✎ 編集 — 名前、クラス、誕生日、保護者メールを変更','help.feat.students.3':'生徒追加後に保護者リンクを表示 → 送信 → Telegramで自動連携','help.feat.students.4':'🎂 近日誕生日の生徒を表示','help.feat.attend.title':'出欠','help.feat.attend.1':'日付バー — 記録する日を選択','help.feat.attend.2':'生徒ごと — P/A/L/T/S/E/Hコードをタップ','help.feat.attend.3':'「全員出席」 — ワンタップで全員を出席に','help.feat.attend.4':'✏️ メモ — 理由を追加','help.feat.attend.5':'最後に「出欠を保存」をタップ','help.feat.daily.title':'日次レポート','help.feat.daily.1':'生徒ごと — 食事、気分、昼寝、行動を記録','help.feat.daily.2':'保護者に送信可能','help.feat.daily.3':'✎ 編集、🗑 削除','help.feat.hw.title':'宿題','help.feat.hw.1':'科目、クラス、種類、説明を追加','help.feat.hw.2':'LB/WBページ番号を追加できます','help.feat.hw.3':'提出期限を設定できます','help.feat.hw.4':'✎ 編集 / 🗑 削除','help.feat.msg.title':'保護者メッセージ','help.feat.msg.1':'クラス全体または個別の生徒を選択','help.feat.msg.2':'メッセージを入力して送信','help.feat.msg.3':'Telegramで保護者に直接届きます','help.feat.inc.title':'インシデント','help.feat.inc.1':'行動、成果、健康メモを記録','help.feat.inc.2':'重要度（Info/Low/Medium/High）を設定','help.feat.inc.3':'保護者通知チェックボックス',
    'help.ai.introTitle':'AIスマートアシスタント','help.ai.introBody':'Telegramチャットでフォーム入力なしに話しかけるだけでデータを追加できます。ミャンマー語と英語を理解します。','help.ai.examplesLabel':'こんなふうに言ってみてください —','help.ai.ex1':'Adam is absent today','help.ai.ex2':'✓ Adam → 欠席に記録','help.ai.ex3':'Hannah is sick','help.ai.ex4':'✓ Hannah → 病欠に記録','help.ai.ex5':'P4に明日数学テストがあると伝えて','help.ai.ex6':'✓ 宿題を保存 · 保護者に一斉送信','help.ai.ex7':'昨日の数学の宿題を削除して','help.ai.ex8':'どれ？ 1. 数学 P4 · 2. 数学 KG','help.ai.cheatLabel':'カテゴリ別コマンド','help.ai.cheat.attend.title':'✅ 出欠（クラス全体）','help.ai.cheat.attend.1':'「Adam is here」/「Adam present」','help.ai.cheat.attend.2':'「Hannah is absent」/「Hannah absent」','help.ai.cheat.attend.3':'「Mg Mg is sick」→ 病欠','help.ai.cheat.attend.4':'「Su Su is late」→ 遅刻','help.ai.cheat.attend.5':'「P4 is all here」→ 全員出席','help.ai.cheat.hw.title':'📚 宿題','help.ai.cheat.hw.1':'「Give P4 Maths page 24-25」','help.ai.cheat.hw.2':'「KG English worksheet 3」','help.ai.cheat.hw.3':'「Change yesterday’s Science HW description」','help.ai.cheat.hw.4':'「Delete today’s Maths HW」','help.ai.cheat.daily.title':'📋 日次レポート','help.ai.cheat.daily.1':'「Adam ate all his food today, happy」','help.ai.cheat.daily.2':'「Hannah napped 30 minutes」','help.ai.cheat.daily.3':'「Change Adam’s report mood to Happy」','help.ai.cheat.inc.title':'⚡ インシデント','help.ai.cheat.inc.1':'「Adam helped a classmate - good behaviour」','help.ai.cheat.inc.2':'「Change Mg Mg’s incident severity to High」','help.ai.cheat.inc.3':'「Delete Hannah’s incident」','help.ai.cheat.parent.title':'💬 保護者 / 一斉連絡','help.ai.cheat.parent.1':'「Adamの保護者に学校へ電話するよう伝えて」','help.ai.cheat.parent.2':'「P4全員に明日は休校と伝えて」','help.ai.cheat.parent.3':'「間違って送った一斉連絡を削除して」','help.ai.cheat.query.title':'🔍 質問','help.ai.cheat.query.1':'「P4には何人いますか？」','help.ai.cheat.query.2':'「Adamの電話番号」','help.ai.cheat.query.3':'「今日欠席しているのは誰？」','help.ai.cheat.query.4':'「生徒一覧を表示」','help.ai.tip1':'AIは出欠、日次レポート、宿題、インシデント、保護者メッセージ、一斉連絡、時間割などを追加・編集・削除できます。生徒一覧や情報を質問することもできます。','help.ai.tip2':'注意: 削除や編集ではAIがまず「どれ？」と確認します。正しい項目を選んだ後だけ実行するため、誤削除を防げます。',
    'help.trouble.introTitle':'トラブルシューティング','help.trouble.introBody':'問題が発生したら、以下を試してください。','help.trouble.q1':'アプリが開かない / 「Connection failed」と表示される','help.trouble.a1':'インターネット接続を確認してRetryをタップしてください。2〜3回試しても失敗する場合は管理者に連絡してください。','help.trouble.q2':'出欠を保存できない','help.trouble.a2':'上部の日付が正しいか確認し、生徒を記録した後に「出欠を保存」をタップしてください。','help.trouble.q3':'新しい生徒を追加できない','help.trouble.a3':'英語名は必須です（*）。クラスも選択してください。','help.trouble.q4':'保護者のTelegramを接続できない','help.trouble.a4':'生徒追加後に表示されたリンクを保護者に送ってください。保護者がリンクをタップしてStartを押し、約1分待ちます。','help.trouble.q5':'AIが理解しない','help.trouble.a5':'より明確に言ってみてください。例: 「Adam is absent today」。生徒名のスペルも確認してください。','help.trouble.q6':'データが表示されない / 古いデータ','help.trouble.a6':'右上の↻更新をタップしてください。アプリを閉じて再度開く方法もあります。','help.trouble.tip':'解決しない場合は学校管理者またはサポート窓口に連絡してください。',
    'help.admin.introTitle':'管理者ツール','help.admin.introBody':'管理者は学校全体の設定を変更できます。','help.admin.logo.title':'学校ロゴ','help.admin.logo.1':'その他 → 学校ロゴ → 画像アップロード','help.admin.logo.2':'ヘッダー、サイドバー、レポートに表示されます','help.admin.classes.title':'クラスと学年','help.admin.classes.1':'その他 → クラスと学年','help.admin.classes.2':'学校のクラス名を追加・削除','help.admin.classes.3':'生徒追加時にこの一覧が表示されます','help.admin.timetable.title':'時間割','help.admin.timetable.1':'その他 → 時間割 → ＋で授業を追加','help.admin.timetable.2':'曜日、時限、クラス、科目、教室','help.admin.reg.title':'登録','help.admin.reg.1':'新しい教師 — ボットで /register_teacher','help.admin.reg.2':'管理者が承認すると教師アカウントが有効になります',
    'help.about.introTitle':'SCMSについて','help.about.introBody':'SCMS v11 — Telegramを中心とした学校管理。ミャンマーの学校向けに作られています。','help.about.version':'バージョン','help.about.platform':'プラットフォーム','help.about.school':'学校','help.about.needHelpTitle':'ヘルプが必要ですか？','help.about.needHelpBody':'問題が発生した場合は学校管理者またはサポート窓口に連絡してください。','help.about.replayTour':'🔄 ウェルカムツアーをもう一度見る','help.close':'閉じる',
    'tour.s1.title':'SCMSへようこそ 👋','tour.s1.text':'ここから学校全体を管理できます。5ステップで見ていきましょう。','tour.s2.title':'生徒','tour.s2.text':'生徒はこちらです。カードをタップして詳細を表示・編集できます。','tour.s3.title':'出欠','tour.s3.text':'今日の出席・欠席をP/A/L/T/S/E/Hコードでワンタップ記録できます。','tour.s4.title':'+ ボタン','tour.s4.text':'この＋ボタンは現在のページで「新規追加」を実行します。','tour.s5.title':'その他 — ヘルプはこちら','tour.s5.text':'その他タブには使い方、管理者ツール、設定があります。','tour.skip':'スキップ','tour.next':'次へ →','tour.done':'完了 ✓'
  });
  Object.assign(overrides, {
    'modules.saveFailed':'保存できませんでした: {err}','cg.confirmRemove':'{list} から「{value}」を削除しますか？','cg.couldNotSave':'保存できませんでした: {err}','boot.user':'ユーザー: {name}','common.deleteFailed':'削除に失敗しました: {err}','common.updateFailed':'更新に失敗しました: {err}','daily.noStudents':'{cls} に生徒はいません','daily.modalTitle':'日次レポート — {name}','daily.saved':'✓ {name} のレポートを保存しました','daily.pickerSub':'{date} のレポート','hw.lb':'LB p.{n}','hw.wb':'WB p.{n}','comms.classBroadcast':'一斉連絡 — {class}','tt.noClasses':'{day} のクラスはありません','tt.room':'教室 {n}','tt.periods':'{day} に {n} 時限','tt.period1':'{day} に {n} 時限','grades.metaLine':'{date} · 満点 {max} · 重み {w}%','grades.classMax':'{cls} · 満点 {max}','bill.cardSub':'{cls} · 期限 {due} · 合計 {total}'
  });
  Object.assign(overrides, {'bill.total':'รวม: {n}','bill.feePaidPending':'ชำระค่าธรรมเนียมแล้ว ✓ — {name} はまだ <em>保留中</em> で、生徒一覧には表示されません。','bill.amountBalance':'金額（残額: {n}）','adm.appliedOn':'{date} に応募','adm.movedTo':'✓ {status} に移動しました','adm.selected':'{n}件選択','adm.bulkMoving':'{n}件を{status}へ移動中…','adm.bulkMoved':'✓ {ok}件を{status}へ移動しました','adm.enrolling':'{n}件を登録中…','adm.skipped':'（{n}件スキップ — クラスなし）','adm.enrolledPending':'✓ {ok}件を登録しました（保留）','adm.savedPhotoFail':'保存しましたが、写真のアップロードに失敗しました: {err}'});
  Object.assign(overrides, {'adm.addedPhotoFail':'追加しましたが、写真のアップロードに失敗しました: {err}','adm.officialStudent':'✓ 正式な生徒 — ID <strong>{id}</strong>、クラス {cls}。生徒一覧に表示されます。','adm.pendingCreated':'生徒記録を作成しました（ID <strong>{id}</strong>）が、<em>保留中</em>です — 登録料の支払いまで生徒一覧には表示されません。','adm.regPaid':'登録請求書 {no} — <strong>支払済み ✓</strong>。請求ページで請求書を開き、<em>生徒を有効化</em>をタップしてください。','adm.regUnpaid':'登録請求書 {no} — {status}、残額 {bal}。請求ページで支払いを記録し、支払済みになったら<em>生徒を有効化</em>してください。'});

  Object.assign(overrides, {
    'students.validation.parentEmail':'保護者のメールアドレスを正しく入力してください','students.validation.phone1':'主な電話番号を確認してください','students.validation.phone2':'予備の電話番号を確認してください',
    'students.form.savingParent':'保存中…','students.toast.parentSaved':'保護者情報を保存しました','students.form.saveParentDetails':'保護者情報を保存','students.form.parentGuardian':'保護者 / 連絡先',
    'students.history.title':'生徒履歴','students.history.empty':'履歴はまだありません','students.toast.reactivated':'生徒を再有効化しました',
    'att.historyRecent':'最近の記録と30日間の概要。','att.report30':'30日間レポート','att.auditWebOnly':'監査ビューアーはWebセッションでのみ利用できます。',
    'att.auditTitle':'出欠監査','att.auditSubtitle':'この学校の出欠保存履歴は管理者のみ閲覧できます。','att.auditLoading':'監査履歴を読み込み中…',
    'att.auditEmpty':'出欠監査の記録はありません。','att.auditLoadFailed':'監査履歴を読み込めませんでした。','att.correctionMode':'修正モード：選択した日付を確認して保存してください。',
    'comms.portalScheduleTitle':'保護者ポータルの予定','comms.portalScheduleSub':'学校の面談、告知、イベントを保護者ポータルに表示します。',
    'comms.portalTitlePh':'例 — 保護者・教師面談','comms.portalDescPh':'保護者に知らせる情報','comms.portalRequired':'タイトルと開始時刻を入力してください。','comms.portalPublished':'保護者ポータルに公開しました。'
  });
  Object.assign(overrides, {'err.sessionVerify':'保存されたセッションを確認できませんでした。','err.retryHint':'「再試行」をタップして、もう一度お試しください。','err.serverUnreachable':'SCMSサーバーに接続できませんでした。','err.technicalDetails':'技術的な詳細（サポートに問い合わせる際はスクリーンショットを添付してください）：','err.likelyCause':'考えられる原因：n8nワークフローがActiveではない、URLが正しくない、またはCORSがリクエストをブロックしています。'});
  Object.assign(overrides, {'login.loading':'ログインを読み込み中…','login.waitRetry':'少し待ってから、もう一度お試しください。','cg.required':'Class と Grade の両方を入力してください。'});
  Object.assign(overrides, {'teacher.editTitle':'教師を編集','teacher.editSubtitle':'IDカードと教師ログインで使用する教師名とログイン名を更新します。','teacher.superAdmin':'スーパー管理者'});
  window.I18N_JP = Object.assign({}, base, overrides);
})();
  'teacher.editTitle': '教師を編集',
  'teacher.editSubtitle': 'IDカードと教師ログインで使用する教師名とログイン名を更新します。',
  'teacher.superAdmin': 'スーパー管理者',
