// Bahasa Melayu — SCMS locale (part 1)
window.I18N_MS = Object.assign(window.I18N_MS || {}, {
  'app.title': 'SCMS — Pengurusan Kelas Sekolah',
  'common.all': 'Semua', 'common.edit': 'Edit', 'common.close': 'Tutup', 'common.cancel': 'Batal', 'common.add': 'Tambah', 'common.saving': 'Menyimpan…', 'common.years': 'thn', 'common.failed': 'Gagal:', 'common.saveFailed': 'Tidak dapat menyimpan — cuba lagi', 'common.removed': 'Dibuang',
  'students.stat.students': 'Murid', 'students.stat.classes': 'Kelas', 'students.stat.hereToday': 'Hadir hari ini', 'students.subtitle': '{n} murid aktif dalam {c} kelas',
  'students.empty.title': 'Tiada murid ditemui', 'students.empty.searchHint': 'Cuba istilah carian yang lain', 'students.empty.addHint': 'Tekan + untuk menambah murid', 'students.notMarked': 'Belum ditanda', 'students.tgLinked': 'Telegram dipautkan', 'students.homeLabel': 'Rumah:', 'students.bday.today': 'Hari ini!', 'students.bday.tooltip': 'Hari lahir dalam {n} hari', 'students.linked': '✓ Dipautkan', 'students.getLink': 'Dapatkan pautan →', 'students.sendLinkBtn': '📤 Hantar pautan kepada ibu bapa',
  'students.field.gender': 'Jantina', 'students.field.grade': 'Darjah', 'students.field.birthday': 'Hari lahir', 'students.field.home': 'Rumah', 'students.field.parent': 'Ibu bapa', 'students.field.parentPhone': 'Telefon ibu bapa', 'students.field.parentEmail': 'E-mel ibu bapa', 'students.field.parentTg': 'Telegram ibu bapa', 'students.detail.recentReports': 'Laporan terkini', 'students.detail.recentIncidents': 'Insiden terkini', 'students.detail.editInfo': 'Edit maklumat murid',
  'students.form.editTitle': 'Edit Murid', 'students.form.addTitle': 'Tambah Murid Baharu', 'students.form.removePhoto': 'Buang foto', 'students.form.localName': 'Nama tempatan (Myanmar / asal)', 'students.form.localNamePh': 'Nama murid…', 'students.form.englishName': 'Nama Inggeris *', 'students.form.englishNamePh': 'Nama penuh dalam bahasa Inggeris', 'students.form.class': 'Kelas *', 'students.form.selectClass': 'Pilih kelas', 'students.form.grade': 'Darjah', 'students.form.selectGrade': 'Pilih darjah', 'students.form.gender': 'Jantina', 'students.form.genderM': 'L', 'students.form.genderF': 'P', 'students.form.genderOther': 'Lain-lain', 'students.form.birthday': 'Hari lahir', 'students.form.birthdayHint': '(digunakan untuk peringatan 🎂)', 'students.form.homeColor': 'Warna rumah', 'students.form.homeColorHint': '(pasukan / rumah)', 'students.form.parentSection': 'Ibu Bapa / Penjaga', 'students.form.parentName': 'Nama ibu bapa', 'students.form.parentNamePh': 'Nama ibu bapa / penjaga', 'students.form.parentPhone': 'Telefon ibu bapa', 'students.form.parentPhonePh': '+95 9 xxx xxx xxx', 'students.form.parentEmail': 'E-mel ibu bapa', 'students.form.parentEmailOptional': 'E-mel ibu bapa (pilihan)', 'students.form.parentEmailPh': 'parent@example.com', 'students.form.parentTg': 'Telegram ibu bapa', 'students.form.saveEdit': 'Simpan perubahan', 'students.form.register': 'Daftar Murid', 'students.form.removeBtn': 'Buang murid', 'students.form.savingEdit': 'Menyimpan…', 'students.form.registering': 'Mendaftar…', 'students.form.parentTgInfo': 'ID Telegram ibu bapa akan diisi <b>secara automatik</b> selepas anda mendaftarkan murid. Kami akan menunjukkan pautan untuk dikongsi dengan ibu bapa — apabila mereka menekannya dalam Telegram, ID mereka akan direkodkan.',
  'students.toast.imageOnly': 'Sila pilih fail imej', 'students.toast.imageTooBig': 'Foto terlalu besar (maksimum 20 MB)', 'students.toast.studentNotFound': 'Murid tidak ditemui', 'students.toast.nameRequired': 'Nama Inggeris diperlukan', 'students.toast.classRequired': 'Kelas diperlukan', 'students.toast.emailInvalid': 'E-mel ibu bapa nampaknya tidak sah', 'students.toast.phoneInvalid': 'Telefon ibu bapa nampaknya tidak sah', 'students.toast.updated': '✓ {name} dikemas kini', 'students.toast.registered': '✓ {name} didaftarkan', 'students.toast.photoUploadFailedEdit': 'Disimpan, tetapi muat naik foto gagal: {err}', 'students.toast.photoRemoveFailed': 'Disimpan, tetapi membuang foto gagal: {err}', 'students.toast.photoUploadFailedAdd': 'Didaftarkan, tetapi muat naik foto gagal: {err}', 'students.toast.saveFailed': 'Simpan gagal: {err}', 'students.toast.registerFailed': 'Pendaftaran gagal: {err}',
  'students.delete.title': 'Buang {name}?', 'students.delete.body': 'Murid akan ditandakan sebagai <b>Tidak aktif</b>. Rekod mereka (kehadiran, laporan) dikekalkan, tetapi mereka tidak akan muncul dalam senarai harian. Anda boleh meminta pentadbir memulihkannya kemudian.', 'students.delete.confirm': 'Ya, buang', 'students.delete.done': '✓ Murid dibuang',
  'parentLink.title': 'Pautkan Telegram ibu bapa', 'parentLink.body': 'Kongsi pautan ini dengan ibu bapa {name}. Apabila ibu bapa menekannya dalam Telegram, bot kami akan mendapatkan ID mereka dan memautkannya kepada murid ini — secara automatik.', 'parentLink.copy': '📋 Salin pautan', 'parentLink.share': '📤 Kongsi melalui Telegram', 'parentLink.waiting': 'Menunggu ibu bapa menekan pautan…', 'parentLink.linkedHtml': '✓ <b>Dipautkan!</b> ID ibu bapa: <code>{id}</code>', 'parentLink.done': 'Selesai — saya akan kongsi kemudian', 'parentLink.copied': '✓ Pautan disalin', 'parentLink.copyFail': 'Gagal menyalin — tekan lama untuk menyalin secara manual', 'parentLink.shareText': 'Hai! Sila tekan pautan ini dalam Telegram untuk menerima kemas kini tentang {name} daripada sekolah:',
  'picker.class.title': 'Pilih kelas', 'picker.class.addLabel': 'Tambah kelas baharu', 'picker.class.placeholder': '(cth. P4 Online)', 'picker.grade.title': 'Pilih darjah', 'picker.grade.addLabel': 'Tambah darjah baharu', 'picker.select': 'Pilih…', 'picker.empty': 'Belum ada pilihan — tambah satu di bawah', 'picker.typeName': 'Taip nama dahulu', 'picker.deleteConfirm': 'Buang "{value}" daripada senarai {list}?',
  'nav.dashboard': 'Papan Pemuka', 'nav.students': 'Murid', 'nav.attendance': 'Kehadiran', 'nav.homework': 'Kerja Rumah', 'nav.messages': 'Mesej', 'nav.incidents': 'Insiden', 'nav.timetable': 'Jadual Waktu', 'nav.reports': 'Laporan', 'nav.settings': 'Tetapan',
  'topbar.search': 'Cari...', 'topbar.notifications': 'Pemberitahuan', 'topbar.profile': 'Profil', 'topbar.logout': 'Log Keluar', 'topbar.language': 'Bahasa',
  'btn.save': 'Simpan', 'btn.cancel': 'Batal', 'btn.delete': 'Padam', 'btn.edit': 'Edit', 'btn.add': 'Tambah', 'btn.close': 'Tutup', 'btn.confirm': 'Sahkan', 'btn.export': 'Eksport', 'btn.refresh': 'Muat semula', 'btn.submit': 'Hantar',
  'msg.loading': 'Memuatkan...', 'msg.saving': 'Menyimpan...', 'msg.saved': 'Berjaya disimpan', 'msg.error': 'Sesuatu telah berlaku', 'msg.noData': 'Tiada data tersedia', 'msg.offline': 'Anda di luar talian', 'msg.confirmDelete': 'Adakah anda pasti mahu memadam?',
  'leave.pageEyebrow': 'Permintaan', 'leave.pageTitle': 'Permintaan cuti', 'leave.loading': 'Memuatkan permintaan cuti…', 'leave.empty': 'Tiada permintaan cuti.', 'leave.status.Pending': 'Menunggu', 'leave.status.Approved': 'Diluluskan', 'leave.status.Rejected': 'Ditolak', 'leave.approve': 'Luluskan', 'leave.reject': 'Tolak', 'leave.approveTitle': 'Luluskan permintaan cuti ini?', 'leave.approveMsg': 'Kehadiran akan ditandakan "Cuti" untuk setiap hari dalam tempoh tersebut.', 'leave.rejectTitle': 'Tolak permintaan cuti ini?', 'leave.rejectMsg': 'Ibu bapa tidak akan dimaklumkan secara automatik (penghantaran Telegram sedang dijeda).', 'leave.decided': 'Permintaan cuti {status}, {n} hari ditandakan', 'leave.decideFailed': 'Tidak dapat mengemas kini permintaan ini',
  'dash.classesToday': 'Kelas hari ini', 'dash.notYetMarked': 'Belum ditanda', 'dash.homeworkLogged2d': 'Kerja rumah direkodkan (2 hari)', 'dash.recentIncidents': 'Insiden terkini', 'dash.messagesQueued': 'Mesej dalam giliran (belum dihantar)', 'dash.myClassesOnly': 'Kelas saya sahaja', 'dash.todaysSchedule': 'Jadual Hari Ini', 'dash.noClassesToday': 'Tiada kelas dijadualkan hari ini.', 'dash.quickActions': 'Tindakan Pantas', 'dash.takeAttendance': 'Rekod Kehadiran', 'dash.logHomework': 'Rekod Kerja Rumah', 'dash.messageParent': 'Mesej Ibu Bapa', 'dash.recordIncident': 'Rekod Insiden', 'dash.studentsAttention': 'Murid yang Memerlukan Perhatian', 'dash.recentIncidentsTitle': 'Insiden Terkini', 'dash.absences14': '{n} ketidakhadiran dalam 14 hari terakhir', 'dash.bannerTitle': '{n} mesej tidak dihantar', 'dash.bannerText': 'Bot penghantaran Telegram sedang luar talian. Mesej ibu bapa ini tersekat dalam giliran dan belum sampai kepada ibu bapa.', 'dash.loading': 'Memuatkan papan pemuka…', 'dash.loadFailed': 'Papan pemuka gagal dimuatkan', 'dash.todayLabel': 'Hari ini', 'dash.totalStudents': 'Jumlah Murid', 'dash.presentToday': 'Hadir Hari Ini', 'dash.absentToday': 'Tidak Hadir Hari Ini', 'dash.pendingHomework': 'Kerja Rumah Tertangguh', 'dash.leaveRequests': 'Permintaan cuti', 'dash.notifications': 'Pemberitahuan', 'dash.newCount': '{n} baharu', 'dash.leavePendingOne': '{n} permintaan cuti menunggu', 'dash.leavePendingMany': '{n} permintaan cuti menunggu', 'dash.leaveReview': 'Permintaan cuti baharu memerlukan semakan anda.', 'dash.messageNotDeliveredOne': '{n} mesej tidak dihantar', 'dash.messageNotDeliveredMany': '{n} mesej tidak dihantar', 'dash.noNewNotifications': 'Tiada pemberitahuan baharu',
  'students.title': 'Murid', 'students.name': 'Nama', 'students.rollNo': 'No. Giliran', 'students.class': 'Kelas', 'students.section': 'Seksyen', 'students.parent': 'Ibu Bapa', 'students.phone': 'Telefon', 'students.addNew': 'Tambah Murid Baharu', 'students.searchPlaceholder': 'Cari mengikut nama atau nombor giliran',
  'att.title': 'Kehadiran', 'att.present': 'Hadir', 'att.absent': 'Tidak Hadir', 'att.late': 'Lewat', 'att.leave': 'Cuti', 'att.markAll': 'Tandakan Semua Hadir', 'att.date': 'Tarikh', 'att.saveAttendance': 'Simpan Kehadiran',
  'common.optional': '(pilihan)', 'common.error': 'ralat', 'common.networkError': 'Ralat rangkaian', 'common.loadFailed': 'Gagal memuatkan: {err}', 'students.subtitleOneClass': '{n} murid aktif dalam {c} kelas', 'students.subtitleOne': '{n} murid aktif dalam {c} kelas', 'students.bday.tooltipOne': 'Hari lahir dalam 1 hari', 'students.bday.short': '{n}h', 'students.detail.meal': 'Makanan:', 'students.btn.health': 'Rekod Kesihatan',
  'idCard.title': 'Kad ID Murid', 'idCard.failed': 'Tidak dapat menjana kad: {err}. Murid mestilah Aktif.', 'idCard.scanHint': 'Ibu bapa mengimbas ini untuk log masuk ke Portal Ibu Bapa.', 'idCard.copyLink': 'Salin pautan', 'idCard.testHint': 'Berguna untuk menguji pautan sendiri, atau menghantarnya terus jika ibu bapa tidak dapat mengimbas.', 'idCard.print': '🖨 Cetak kad', 'idCard.lost': '🔄 Kad hilang — keluarkan kod baharu', 'idCard.regenTitle': 'Keluarkan kod baharu?', 'idCard.regenBody': 'Kod QR kad lama akan berhenti berfungsi serta-merta — cetak semula sebelum mengedarkan yang baharu. Ibu bapa yang telah log masuk akan kekal log masuk.', 'idCard.regenConfirm': 'Keluarkan kod baharu', 'idCard.regenDone': '✓ Kod baharu dikeluarkan', 'idCard.selectMode': 'Pilih untuk kad ID', 'idCard.nSelected': '{n} dipilih', 'idCard.selectAllVisible': 'Pilih semua yang ditunjukkan', 'idCard.selectNone': 'Kosongkan', 'idCard.printSelected': 'Cetak Kad ID', 'idCard.preparing': 'Menyediakan {n} kad…', 'idCard.orientVertical': 'Kad menegak', 'idCard.orientHorizontal': 'Kad mendatar'
});
