/* SCMS v12 — Staff Chat locale extension
 * Loaded after the seven base locale dictionaries and before the i18n engine.
 * Keeps Chat-only additions centralized and guarantees key parity for all languages.
 */
(function () {
  const chat = {
    en: {
      'chat.schoolChat':'School Chat','chat.backToSchoolChat':'Back to School Chat','chat.selectGrade':'Select a grade','chat.gradeSchoolIsolated':'Grade staff conversations are school-isolated.','chat.loadGradesFailed':'Unable to load grades.','chat.retry':'Retry','chat.unread':'unread','chat.staffConversation':'Staff conversation','chat.you':'You','chat.staff':'Staff','chat.emptyTitle':'No messages yet','chat.backToGrades':'Back to grades','chat.schoolIsolated':'School isolated','chat.writeGradeMessage':'Write a grade message...','chat.gradeUnauthorized':'Grade access is not authorized.','chat.gradeSendFailed':'Grade message could not be sent.',
      'chat.departmentOnlyAssigned':'Only explicitly assigned active staff can enter a department.','chat.schoolIsolatedStaff':'School-isolated staff conversation.','chat.authorizedMembers':'Authorized members','chat.selectDepartmentBelong':'Select a department you belong to.','chat.loadDepartmentsFailed':'Unable to load departments.','chat.departmentUnauthorized':'Department access is not authorized.','chat.backToDepartments':'Back to departments','chat.staffOnlyConversation':'Staff-only conversation','chat.startDepartment':'Start the department conversation.','chat.writeDepartmentMessage':'Write a department message...','chat.departmentSendFailed':'Department message could not be sent.',
      'chat.groupChat':'GROUP CHAT','chat.newGroup':'New group','chat.newGroupDescription':'Create a temporary project or event group','chat.selectGroup':'Select a group','chat.groupSchoolIsolated':'Project and event conversations stay inside your school.','chat.noGroupsDescription':'Project or event groups created for your school will appear here.','chat.loadGroupsFailed':'Unable to load groups.','chat.groupNamePrompt':'Group name','chat.groupTypePrompt':'Type: PROJECT or EVENT','chat.invalidGroupType':'Invalid group type.','chat.groupDescriptionPrompt':'Description (optional)','chat.groupMembersPrompt':'Add members by teacher ID, comma-separated.','chat.startDatePrompt':'Start date/time (optional, ISO format e.g. 2026-10-10T09:00)','chat.endDatePrompt':'End date/time (optional, ISO format e.g. 2026-10-10T17:00)','chat.createFailed':'Create failed','chat.groupCreateFailed':'Group could not be created.','chat.loading':'Loading…','chat.openFailed':'Open failed','chat.backToGroups':'Back to groups','chat.schoolMembersOnly':'School members only','chat.startGroup':'Start the group conversation.','chat.writeMessage':'Write a message…','chat.openGroupFailed':'Unable to open this group.','chat.sendFailed':'Send failed','chat.messageSendFailed':'Message could not be sent.'
    },
    my: {
      'chat.schoolChat':'ကျောင်းစကားပြော','chat.backToSchoolChat':'ကျောင်းစကားပြောသို့ ပြန်ရန်','chat.selectGrade':'အတန်းရွေးပါ','chat.gradeSchoolIsolated':'အတန်းဝန်ထမ်း စကားပြောခန်းသည် ကျောင်းအလိုက် သီးခြားဖြစ်သည်။','chat.loadGradesFailed':'အတန်းများ မရယူနိုင်ပါ။','chat.retry':'ပြန်စမ်းရန်','chat.unread':'မဖတ်ရသေး','chat.staffConversation':'ဝန်ထမ်း စကားပြောခန်း','chat.you':'သင်','chat.staff':'ဝန်ထမ်း','chat.emptyTitle':'မက်ဆေ့ချ် မရှိသေးပါ','chat.backToGrades':'အတန်းများသို့ ပြန်ရန်','chat.schoolIsolated':'ကျောင်းအလိုက် သီးခြား','chat.writeGradeMessage':'အတန်းမက်ဆေ့ချ် ရေးပါ...','chat.gradeUnauthorized':'အတန်းဝင်ရောက်ခွင့် မရှိပါ။','chat.gradeSendFailed':'အတန်းမက်ဆေ့ချ် ပို့၍မရပါ။',
      'chat.departmentOnlyAssigned':'တိတိကျကျ တာဝန်ပေးထားသော လက်ရှိဝန်ထမ်းများသာ ဌာနသို့ ဝင်ရောက်နိုင်သည်။','chat.schoolIsolatedStaff':'ကျောင်းအလိုက် သီးခြား ဝန်ထမ်းစကားပြောခန်း။','chat.authorizedMembers':'ခွင့်ပြုထားသော အဖွဲ့ဝင်များ','chat.selectDepartmentBelong':'သင်ပါဝင်သော ဌာနကို ရွေးပါ။','chat.loadDepartmentsFailed':'ဌာနများ မရယူနိုင်ပါ။','chat.departmentUnauthorized':'ဌာနဝင်ရောက်ခွင့် မရှိပါ။','chat.backToDepartments':'ဌာနများသို့ ပြန်ရန်','chat.staffOnlyConversation':'ဝန်ထမ်းများသာ စကားပြောနိုင်သည်','chat.startDepartment':'ဌာန စကားပြောခန်းကို စတင်ပါ။','chat.writeDepartmentMessage':'ဌာနမက်ဆေ့ချ် ရေးပါ...','chat.departmentSendFailed':'ဌာနမက်ဆေ့ချ် ပို့၍မရပါ။',
      'chat.groupChat':'အဖွဲ့စကားပြော','chat.newGroup':'အဖွဲ့အသစ်','chat.newGroupDescription':'ယာယီ ပရောဂျက် သို့မဟုတ် ပွဲအဖွဲ့ ဖန်တီးပါ','chat.selectGroup':'အဖွဲ့ရွေးပါ','chat.groupSchoolIsolated':'ပရောဂျက်နှင့် ပွဲစကားပြောခန်းများသည် သင့်ကျောင်းအတွင်းသာ ဖြစ်သည်။','chat.noGroupsDescription':'သင့်ကျောင်းအတွက် ဖန်တီးထားသော ပရောဂျက်/ပွဲအဖွဲ့များ ဤနေရာတွင် ပေါ်လာမည်။','chat.loadGroupsFailed':'အဖွဲ့များ မရယူနိုင်ပါ။','chat.groupNamePrompt':'အဖွဲ့အမည်','chat.groupTypePrompt':'အမျိုးအစား: PROJECT သို့မဟုတ် EVENT','chat.invalidGroupType':'အဖွဲ့အမျိုးအစား မမှန်ပါ။','chat.groupDescriptionPrompt':'ဖော်ပြချက် (ရွေးချယ်နိုင်သည်)','chat.groupMembersPrompt':'ဆရာ ID များကို ကော်မာဖြင့် ခွဲ၍ ထည့်ပါ။','chat.startDatePrompt':'စတင်ရက်/အချိန် (ရွေးချယ်နိုင်သည်၊ ISO ပုံစံ ဥပမာ 2026-10-10T09:00)','chat.endDatePrompt':'ပြီးဆုံးရက်/အချိန် (ရွေးချယ်နိုင်သည်၊ ISO ပုံစံ ဥပမာ 2026-10-10T17:00)','chat.createFailed':'ဖန်တီး၍မရပါ','chat.groupCreateFailed':'အဖွဲ့ ဖန်တီး၍မရပါ။','chat.loading':'ဖွင့်နေသည်…','chat.openFailed':'ဖွင့်၍မရပါ','chat.backToGroups':'အဖွဲ့များသို့ ပြန်ရန်','chat.schoolMembersOnly':'ကျောင်းအဖွဲ့ဝင်များသာ','chat.startGroup':'အဖွဲ့စကားပြောခန်းကို စတင်ပါ။','chat.writeMessage':'မက်ဆေ့ချ် ရေးပါ…','chat.openGroupFailed':'အဖွဲ့ကို ဖွင့်၍မရပါ။','chat.sendFailed':'ပို့၍မရပါ','chat.messageSendFailed':'မက်ဆေ့ချ် ပို့၍မရပါ။'
    },
    th: {}, jp: {}, ms: {}, km: {}, zh: {}
  };
  const fill={
    th:{'chat.schoolChat':'School Chat','chat.backToSchoolChat':'กลับไปแชทโรงเรียน','chat.selectGrade':'เลือกชั้นเรียน','chat.gradeSchoolIsolated':'การสนทนาของเจ้าหน้าที่ระดับชั้นแยกตามโรงเรียน','chat.retry':'ลองอีกครั้ง','chat.unread':'ยังไม่ได้อ่าน','chat.staffConversation':'การสนทนาของเจ้าหน้าที่','chat.you':'คุณ','chat.staff':'เจ้าหน้าที่','chat.emptyTitle':'ยังไม่มีข้อความ','chat.backToGrades':'กลับไปยังชั้นเรียน','chat.schoolIsolated':'แยกตามโรงเรียน','chat.writeGradeMessage':'เขียนข้อความถึงชั้นเรียน...','chat.gradeUnauthorized':'ไม่ได้รับอนุญาตให้เข้าถึงชั้นเรียน','chat.gradeSendFailed':'ไม่สามารถส่งข้อความระดับชั้นได้','chat.selectDepartmentBelong':'เลือกแผนกที่คุณสังกัด','chat.departmentUnauthorized':'ไม่ได้รับอนุญาตให้เข้าถึงแผนก','chat.backToDepartments':'กลับไปยังแผนก','chat.startDepartment':'เริ่มการสนทนาของแผนก','chat.writeDepartmentMessage':'เขียนข้อความถึงแผนก...','chat.departmentSendFailed':'ไม่สามารถส่งข้อความแผนกได้','chat.groupChat':'แชทกลุ่ม','chat.newGroup':'กลุ่มใหม่','chat.newGroupDescription':'สร้างกลุ่มโครงการหรือกิจกรรมชั่วคราว','chat.selectGroup':'เลือกกลุ่ม','chat.noGroupsDescription':'กลุ่มโครงการหรือกิจกรรมของโรงเรียนจะแสดงที่นี่','chat.loadGroupsFailed':'โหลดกลุ่มไม่ได้','chat.invalidGroupType':'ประเภทกลุ่มไม่ถูกต้อง','chat.groupCreateFailed':'สร้างกลุ่มไม่ได้','chat.loading':'กำลังโหลด…','chat.backToGroups':'กลับไปยังกลุ่ม','chat.schoolMembersOnly':'เฉพาะสมาชิกโรงเรียน','chat.startGroup':'เริ่มการสนทนากลุ่ม','chat.writeMessage':'เขียนข้อความ…','chat.openGroupFailed':'เปิดกลุ่มไม่ได้','chat.messageSendFailed':'ส่งข้อความไม่ได้'},
    jp:{'chat.schoolChat':'スクールチャット','chat.backToSchoolChat':'スクールチャットに戻る','chat.selectGrade':'学年を選択','chat.gradeSchoolIsolated':'学年スタッフの会話は学校ごとに分離されています','chat.retry':'再試行','chat.unread':'未読','chat.staffConversation':'スタッフ会話','chat.you':'あなた','chat.staff':'スタッフ','chat.emptyTitle':'まだメッセージはありません','chat.backToGrades':'学年に戻る','chat.schoolIsolated':'学校内で分離','chat.writeGradeMessage':'学年メッセージを書く…','chat.gradeUnauthorized':'学年へのアクセスが許可されていません','chat.gradeSendFailed':'学年メッセージを送信できません','chat.selectDepartmentBelong':'所属する部署を選択','chat.departmentUnauthorized':'部署へのアクセスが許可されていません','chat.backToDepartments':'部署に戻る','chat.startDepartment':'部署の会話を開始','chat.writeDepartmentMessage':'部署メッセージを書く…','chat.departmentSendFailed':'部署メッセージを送信できません','chat.groupChat':'グループチャット','chat.newGroup':'新しいグループ','chat.newGroupDescription':'一時的なプロジェクトまたはイベントグループを作成','chat.selectGroup':'グループを選択','chat.noGroupsDescription':'学校のプロジェクト・イベントグループがここに表示されます','chat.loadGroupsFailed':'グループを読み込めません','chat.invalidGroupType':'グループ種別が無効です','chat.groupCreateFailed':'グループを作成できません','chat.loading':'読み込み中…','chat.backToGroups':'グループに戻る','chat.schoolMembersOnly':'学校メンバーのみ','chat.startGroup':'グループ会話を開始','chat.writeMessage':'メッセージを書く…','chat.openGroupFailed':'グループを開けません','chat.messageSendFailed':'メッセージを送信できません'},
    ms:{'chat.schoolChat':'Sembang Sekolah','chat.backToSchoolChat':'Kembali ke Sembang Sekolah','chat.selectGrade':'Pilih gred','chat.gradeSchoolIsolated':'Perbualan staf gred diasingkan mengikut sekolah','chat.retry':'Cuba lagi','chat.unread':'belum dibaca','chat.staffConversation':'Perbualan staf','chat.you':'Anda','chat.staff':'Staf','chat.emptyTitle':'Tiada mesej lagi','chat.backToGrades':'Kembali ke gred','chat.schoolIsolated':'Diasingkan mengikut sekolah','chat.writeGradeMessage':'Tulis mesej gred...','chat.gradeUnauthorized':'Akses gred tidak dibenarkan','chat.gradeSendFailed':'Mesej gred tidak dapat dihantar','chat.selectDepartmentBelong':'Pilih jabatan yang anda sertai','chat.departmentUnauthorized':'Akses jabatan tidak dibenarkan','chat.backToDepartments':'Kembali ke jabatan','chat.startDepartment':'Mulakan perbualan jabatan','chat.writeDepartmentMessage':'Tulis mesej jabatan...','chat.departmentSendFailed':'Mesej jabatan tidak dapat dihantar','chat.groupChat':'SEMBANG KUMPULAN','chat.newGroup':'Kumpulan baharu','chat.newGroupDescription':'Cipta kumpulan projek atau acara sementara','chat.selectGroup':'Pilih kumpulan','chat.noGroupsDescription':'Kumpulan projek atau acara sekolah akan muncul di sini','chat.loadGroupsFailed':'Tidak dapat memuatkan kumpulan','chat.invalidGroupType':'Jenis kumpulan tidak sah','chat.groupCreateFailed':'Kumpulan tidak dapat dicipta','chat.loading':'Memuatkan…','chat.backToGroups':'Kembali ke kumpulan','chat.schoolMembersOnly':'Ahli sekolah sahaja','chat.startGroup':'Mulakan perbualan kumpulan','chat.writeMessage':'Tulis mesej…','chat.openGroupFailed':'Tidak dapat membuka kumpulan','chat.messageSendFailed':'Mesej tidak dapat dihantar'},
    km:{'chat.schoolChat':'ការជជែកសាលា','chat.backToSchoolChat':'ត្រឡប់ទៅការជជែកសាលា','chat.selectGrade':'ជ្រើសរើសថ្នាក់','chat.gradeSchoolIsolated':'ការសន្ទនារបស់បុគ្គលិកតាមថ្នាក់ត្រូវបានបែងចែកតាមសាលា','chat.retry':'ព្យាយាមម្តងទៀត','chat.unread':'មិនទាន់អាន','chat.staffConversation':'ការសន្ទនាបុគ្គលិក','chat.you':'អ្នក','chat.staff':'បុគ្គលិក','chat.emptyTitle':'មិនទាន់មានសារ','chat.backToGrades':'ត្រឡប់ទៅថ្នាក់','chat.schoolIsolated':'បែងចែកតាមសាលា','chat.writeGradeMessage':'សរសេរសារថ្នាក់...','chat.gradeUnauthorized':'មិនមានសិទ្ធិចូលថ្នាក់','chat.gradeSendFailed':'មិនអាចផ្ញើសារថ្នាក់បានទេ','chat.selectDepartmentBelong':'ជ្រើសរើសនាយកដ្ឋានដែលអ្នកស្ថិតនៅ','chat.departmentUnauthorized':'មិនមានសិទ្ធិចូលនាយកដ្ឋាន','chat.backToDepartments':'ត្រឡប់ទៅនាយកដ្ឋាន','chat.startDepartment':'ចាប់ផ្តើមការសន្ទនានាយកដ្ឋាន','chat.writeDepartmentMessage':'សរសេរសារនាយកដ្ឋាន...','chat.departmentSendFailed':'មិនអាចផ្ញើសារនាយកដ្ឋានបានទេ','chat.groupChat':'ការជជែកជាក្រុម','chat.newGroup':'ក្រុមថ្មី','chat.newGroupDescription':'បង្កើតក្រុមគម្រោង ឬព្រឹត្តិការណ៍បណ្តោះអាសន្ន','chat.selectGroup':'ជ្រើសរើសក្រុម','chat.noGroupsDescription':'ក្រុមគម្រោង ឬព្រឹត្តិការណ៍របស់សាលានឹងបង្ហាញនៅទីនេះ','chat.loadGroupsFailed':'មិនអាចផ្ទុកក្រុមបានទេ','chat.invalidGroupType':'ប្រភេទក្រុមមិនត្រឹមត្រូវ','chat.groupCreateFailed':'មិនអាចបង្កើតក្រុមបានទេ','chat.loading':'កំពុងផ្ទុក…','chat.backToGroups':'ត្រឡប់ទៅក្រុម','chat.schoolMembersOnly':'សមាជិកសាលាតែប៉ុណ្ណោះ','chat.startGroup':'ចាប់ផ្តើមការសន្ទនាក្រុម','chat.writeMessage':'សរសេរសារ…','chat.openGroupFailed':'មិនអាចបើកក្រុមបានទេ','chat.messageSendFailed':'មិនអាចផ្ញើសារបានទេ'},
    zh:{'chat.schoolChat':'学校聊天','chat.backToSchoolChat':'返回学校聊天','chat.selectGrade':'选择年级','chat.gradeSchoolIsolated':'年级工作人员会话按学校隔离','chat.retry':'重试','chat.unread':'未读','chat.staffConversation':'员工会话','chat.you':'你','chat.staff':'员工','chat.emptyTitle':'暂无消息','chat.backToGrades':'返回年级','chat.schoolIsolated':'学校隔离','chat.writeGradeMessage':'输入年级消息…','chat.gradeUnauthorized':'无权访问该年级','chat.gradeSendFailed':'无法发送年级消息','chat.selectDepartmentBelong':'选择您所属的部门','chat.departmentUnauthorized':'无权访问该部门','chat.backToDepartments':'返回部门','chat.startDepartment':'开始部门会话','chat.writeDepartmentMessage':'输入部门消息…','chat.departmentSendFailed':'无法发送部门消息','chat.groupChat':'群组聊天','chat.newGroup':'新建群组','chat.newGroupDescription':'创建临时项目或活动群组','chat.selectGroup':'选择群组','chat.noGroupsDescription':'您学校创建的项目或活动群组将显示在这里','chat.loadGroupsFailed':'无法加载群组','chat.invalidGroupType':'群组类型无效','chat.groupCreateFailed':'无法创建群组','chat.loading':'加载中…','chat.backToGroups':'返回群组','chat.schoolMembersOnly':'仅限学校成员','chat.startGroup':'开始群组会话','chat.writeMessage':'输入消息…','chat.openGroupFailed':'无法打开群组','chat.messageSendFailed':'无法发送消息'}
  };
  Object.assign(chat.th,fill.th); Object.assign(chat.jp,fill.jp); Object.assign(chat.ms,fill.ms); Object.assign(chat.km,fill.km); Object.assign(chat.zh,fill.zh);
  const my=chat.my,en=chat.en;
  // Keys whose localized wording is not critical to the UI but must exist for parity.
  ['th','jp','ms','km','zh'].forEach(code=>Object.keys(en).forEach(k=>{ if(!(k in chat[code])) chat[code][k]=en[k]; }));
  const maps={en:'I18N_EN',my:'I18N_MY',th:'I18N_TH',jp:'I18N_JP',ms:'I18N_MS',km:'I18N_KM',zh:'I18N_ZH'};
  Object.keys(maps).forEach(code=>{ window[maps[code]]=Object.assign({},window[maps[code]]||{},code==='en'?en:code==='my'?my:chat[code]); });
})();