/* SCMS v12 — Staff Chat locale extension
 * Loaded after the seven base locale dictionaries and before the i18n engine.
 * Keeps Chat-only additions centralized and guarantees key parity for all languages.
 */
(function () {
  const chat = {
    en: {
      'chat.schoolChat':'School Chat','chat.backToSchoolChat':'Back to School Chat','chat.selectGrade':'Select a grade','chat.gradeSchoolIsolated':'Grade staff conversations are school-isolated.','chat.loadGradesFailed':'Unable to load grades.','chat.retry':'Retry','chat.unread':'unread','chat.staffConversation':'Staff conversation','chat.you':'You','chat.staff':'Staff','chat.emptyTitle':'No messages yet','chat.backToGrades':'Back to grades','chat.schoolIsolated':'School isolated','chat.writeGradeMessage':'Write a grade message...','chat.gradeUnauthorized':'Grade access is not authorized.','chat.gradeSendFailed':'Grade message could not be sent.',
      'chat.departmentOnlyAssigned':'Only explicitly assigned active staff can enter a department.','chat.schoolIsolatedStaff':'School-isolated staff conversation.','chat.authorizedMembers':'Authorized members','chat.selectDepartmentBelong':'Select a department you belong to.','chat.loadDepartmentsFailed':'Unable to load departments.','chat.departmentUnauthorized':'Department access is not authorized.','chat.backToDepartments':'Back to departments','chat.staffOnlyConversation':'Staff-only conversation','chat.startDepartment':'Start the department conversation.','chat.writeDepartmentMessage':'Write a department message...','chat.departmentSendFailed':'Department message could not be sent.',
      'chat.groupChat':'GROUP CHAT','chat.newGroup':'New group','chat.newGroupDescription':'Create a temporary project or event group','chat.selectGroup':'Select a group','chat.groupSchoolIsolated':'Project and event conversations stay inside your school.','chat.noGroupsDescription':'Project or event groups created for your school will appear here.','chat.loadGroupsFailed':'Unable to load groups.','chat.groupNamePrompt':'Group name','chat.groupTypePrompt':'Type: PROJECT or EVENT','chat.invalidGroupType':'Invalid group type.','chat.groupDescriptionPrompt':'Description (optional)','chat.groupMembersPrompt':'Select staff members to add to the group.','chat.startDatePrompt':'Start date/time (optional, ISO format e.g. 2026-10-10T09:00)','chat.endDatePrompt':'End date/time (optional, ISO format e.g. 2026-10-10T17:00)','chat.createFailed':'Create failed','chat.groupCreateFailed':'Group could not be created.','chat.loading':'Loading…','chat.openFailed':'Open failed','chat.backToGroups':'Back to groups','chat.schoolMembersOnly':'School members only','chat.startGroup':'Start the group conversation.','chat.writeMessage':'Write a message…','chat.openGroupFailed':'Unable to open this group.','chat.sendFailed':'Send failed','chat.messageSendFailed':'Message could not be sent.'
    },
    my: {
      'chat.schoolChat':'ကျောင်းစကားပြော','chat.backToSchoolChat':'ကျောင်းစကားပြောသို့ ပြန်ရန်','chat.selectGrade':'အတန်းရွေးပါ','chat.gradeSchoolIsolated':'အတန်းဝန်ထမ်း စကားပြောခန်းသည် ကျောင်းအလိုက် သီးခြားဖြစ်သည်။','chat.loadGradesFailed':'အတန်းများ မရယူနိုင်ပါ။','chat.retry':'ပြန်စမ်းရန်','chat.unread':'မဖတ်ရသေး','chat.staffConversation':'ဝန်ထမ်း စကားပြောခန်း','chat.you':'သင်','chat.staff':'ဝန်ထမ်း','chat.emptyTitle':'မက်ဆေ့ချ် မရှိသေးပါ','chat.backToGrades':'အတန်းများသို့ ပြန်ရန်','chat.schoolIsolated':'ကျောင်းအလိုက် သီးခြား','chat.writeGradeMessage':'အတန်းမက်ဆေ့ချ် ရေးပါ...','chat.gradeUnauthorized':'အတန်းဝင်ရောက်ခွင့် မရှိပါ။','chat.gradeSendFailed':'အတန်းမက်ဆေ့ချ် ပို့၍မရပါ။',
      'chat.departmentOnlyAssigned':'တိတိကျကျ တာဝန်ပေးထားသော လက်ရှိဝန်ထမ်းများသာ ဌာနသို့ ဝင်ရောက်နိုင်သည်။','chat.schoolIsolatedStaff':'ကျောင်းအလိုက် သီးခြား ဝန်ထမ်းစကားပြောခန်း။','chat.authorizedMembers':'ခွင့်ပြုထားသော အဖွဲ့ဝင်များ','chat.selectDepartmentBelong':'သင်ပါဝင်သော ဌာနကို ရွေးပါ။','chat.loadDepartmentsFailed':'ဌာနများ မရယူနိုင်ပါ။','chat.departmentUnauthorized':'ဌာနဝင်ရောက်ခွင့် မရှိပါ။','chat.backToDepartments':'ဌာနများသို့ ပြန်ရန်','chat.staffOnlyConversation':'ဝန်ထမ်းများသာ စကားပြောနိုင်သည်','chat.startDepartment':'ဌာန စကားပြောခန်းကို စတင်ပါ။','chat.writeDepartmentMessage':'ဌာနမက်ဆေ့ချ် ရေးပါ...','chat.departmentSendFailed':'ဌာနမက်ဆေ့ချ် ပို့၍မရပါ။',
      'chat.groupChat':'အဖွဲ့စကားပြော','chat.newGroup':'အဖွဲ့အသစ်','chat.newGroupDescription':'ယာယီ ပရောဂျက် သို့မဟုတ် ပွဲအဖွဲ့ ဖန်တီးပါ','chat.selectGroup':'အဖွဲ့ရွေးပါ','chat.groupSchoolIsolated':'ပရောဂျက်နှင့် ပွဲစကားပြောခန်းများသည် သင့်ကျောင်းအတွင်းသာ ဖြစ်သည်။','chat.noGroupsDescription':'သင့်ကျောင်းအတွက် ဖန်တီးထားသော ပရောဂျက်/ပွဲအဖွဲ့များ ဤနေရာတွင် ပေါ်လာမည်။','chat.loadGroupsFailed':'အဖွဲ့များ မရယူနိုင်ပါ။','chat.groupNamePrompt':'အဖွဲ့အမည်','chat.groupTypePrompt':'အမျိုးအစား: PROJECT သို့မဟုတ် EVENT','chat.invalidGroupType':'အဖွဲ့အမျိုးအစား မမှန်ပါ။','chat.groupDescriptionPrompt':'ဖော်ပြချက် (ရွေးချယ်နိုင်သည်)','chat.groupMembersPrompt':'အဖွဲ့ထဲသို့ ထည့်မည့် ဝန်ထမ်းများကို ရွေးပါ။','chat.startDatePrompt':'စတင်ရက်/အချိန် (ရွေးချယ်နိုင်သည်၊ ISO ပုံစံ ဥပမာ 2026-10-10T09:00)','chat.endDatePrompt':'ပြီးဆုံးရက်/အချိန် (ရွေးချယ်နိုင်သည်၊ ISO ပုံစံ ဥပမာ 2026-10-10T17:00)','chat.createFailed':'ဖန်တီး၍မရပါ','chat.groupCreateFailed':'အဖွဲ့ ဖန်တီး၍မရပါ။','chat.loading':'ဖွင့်နေသည်…','chat.openFailed':'ဖွင့်၍မရပါ','chat.backToGroups':'အဖွဲ့များသို့ ပြန်ရန်','chat.schoolMembersOnly':'ကျောင်းအဖွဲ့ဝင်များသာ','chat.startGroup':'အဖွဲ့စကားပြောခန်းကို စတင်ပါ။','chat.writeMessage':'မက်ဆေ့ချ် ရေးပါ…','chat.openGroupFailed':'အဖွဲ့ကို ဖွင့်၍မရပါ။','chat.sendFailed':'ပို့၍မရပါ','chat.messageSendFailed':'မက်ဆေ့ချ် ပို့၍မရပါ။'
    },
    th: {}, jp: {}, ms: {}, km: {}, zh: {}
  };
  const fill={
    th:{'chat.reason':"เหตุผล",'chat.officialCommunication':"การสื่อสารอย่างเป็นทางการของโรงเรียน",'chat.writeOfficialMessage':"เขียนข้อความทางการ...",'chat.noVerifiedRecipient':"ไม่มีผู้รับที่ยืนยันแล้ว",'chat.noVerifiedSameSchoolRecipient':"ไม่พบผู้รับที่ใช้งานอยู่ในโรงเรียนเดียวกันจากการตรวจสอบของเซิร์ฟเวอร์",'chat.systemGeneratedOfficialMessage':"ข้อความทางการที่ระบบสร้าง",'chat.adminComposer':"ผู้ดูแลสร้างข้อความทางการ",'chat.officialCommunication':"การสื่อสารอย่างเป็นทางการของโรงเรียน",'chat.writeOfficialMessage':"เขียนข้อความทางการ...",'chat.oneVerifiedRecipient':"ผู้รับที่ยืนยันแล้ว 1 คน",'chat.noVerifiedRecipient':"ไม่มีผู้รับที่ยืนยันแล้ว",'chat.noVerifiedSameSchoolRecipient':"การอนุญาตจากเซิร์ฟเวอร์ไม่พบผู้รับที่ใช้งานอยู่ในโรงเรียนเดียวกัน",'chat.officialAnnouncements':"ช่องประกาศอย่างเป็นทางการ",'chat.officialStaffTask':"งานอย่างเป็นทางการของเจ้าหน้าที่",'chat.staffNotice':"ประกาศเจ้าหน้าที่",'chat.exitChat':"ออกจากแชท",'chat.aiPlaceholder':"ถามเกี่ยวกับตารางเรียน นักเรียน การเข้าเรียน...",'chat.selectTicketDots':"เลือกตั๋ว...",'chat.unreadMessages':"ข้อความที่ยังไม่ได้อ่าน",'chat.noInquiryTickets':"ไม่มีตั๋วสอบถาม",'chat.createTicketHint':"สร้างตั๋วเมื่อมีปัญหาของเจ้าหน้าที่ที่ต้องติดตาม",'chat.backToInquiryTickets':"กลับไปยังตั๋วสอบถาม",'chat.authorized':"ได้รับอนุญาต",'chat.ticketClosed':"ปิดตั๋วแล้ว",'chat.writeReply':"เขียนตอบ...",'chat.authorizedTicketAccess':"เฉพาะเจ้าหน้าที่ที่ได้รับอนุญาตในโรงเรียนนี้เท่านั้นที่เข้าถึงข้อความตั๋วได้",'chat.createOrSelectTicket':"สร้างหรือเลือกตั๋วเจ้าหน้าที่",'chat.noTicketsYet':"ยังไม่มีตั๋ว",'chat.subject':"หัวข้อ",'chat.whatNeedsAttention':"ต้องการให้ตรวจสอบเรื่องใด?",'chat.studentId':"รหัสนักเรียน",'chat.optionalSameSchool':"ไม่บังคับ · โรงเรียนเดียวกันเท่านั้น",'chat.describeIssue':"อธิบายปัญหาให้ชัดเจน...",'chat.newOfficialMessage':"ข้อความทางการใหม่",'chat.closeOfficialMessage':"ปิดแบบฟอร์มข้อความทางการ",'chat.backToAnnouncements':"กลับไปยังประกาศ",'chat.officialAnnouncement':"ประกาศอย่างเป็นทางการ",'chat.systemGeneratedOfficialMessage':"ข้อความทางการที่ระบบสร้าง",'chat.read':"อ่านแล้ว",'chat.reason':"เหตุผล",'chat.chooseTeacher':"เลือกครู",'chat.startPrivateConversation':"เริ่มการสนทนาส่วนตัวแบบ 1 ต่อ 1",'chat.teacher':"ครู",'chat.privateOneToOne':"ส่วนตัว 1 ต่อ 1",'chat.unableOpenConversation':"ไม่สามารถเปิดการสนทนาได้",'chat.writeDepartmentMessage':"เขียนข้อความถึงแผนก...",'chat.writeGradeMessage':"เขียนข้อความถึงระดับชั้น...",'chat.writeMessage':"เขียนข้อความ...",'chat.messageSendFailed':"ส่งข้อความไม่สำเร็จ",'chat.groupCreateFailed':"สร้างกลุ่มไม่สำเร็จ",'chat.gradeSendFailed':"ส่งข้อความระดับชั้นไม่สำเร็จ",'chat.departmentSendFailed':"ส่งข้อความถึงแผนกไม่สำเร็จ"},
    jp:{'chat.reason':"理由",'chat.officialCommunication':"学校公式連絡",'chat.writeOfficialMessage':"公式メッセージを書く…",'chat.noVerifiedRecipient':"確認済み受信者がいません",'chat.noVerifiedSameSchoolRecipient':"サーバー認証で同じ学校の有効な受信者が見つかりませんでした",'chat.systemGeneratedOfficialMessage':"システム生成公式メッセージ",'chat.adminComposer':"管理者公式メッセージ作成",'chat.officialCommunication':"学校公式連絡",'chat.writeOfficialMessage':"公式メッセージを書く…",'chat.oneVerifiedRecipient':"確認済み受信者 1 人",'chat.noVerifiedRecipient':"確認済み受信者なし",'chat.noVerifiedSameSchoolRecipient':"サーバー認証で同じ学校の有効な受信者が返されませんでした",'chat.officialAnnouncements':"公式お知らせチャンネル",'chat.officialStaffTask':"スタッフ公式タスク",'chat.staffNotice':"スタッフ通知",'chat.exitChat':"チャットを終了",'chat.aiPlaceholder':"時間割・生徒・出欠について質問…",'chat.selectTicketDots':"チケットを選択…",'chat.unreadMessages':"未読メッセージ",'chat.noInquiryTickets':"問い合わせチケットなし",'chat.createTicketHint':"スタッフの問題に対応する必要がある場合はチケットを作成します",'chat.backToInquiryTickets':"問い合わせチケットに戻る",'chat.authorized':"承認済み",'chat.ticketClosed':"チケットは終了しました",'chat.writeReply':"返信を書く…",'chat.authorizedTicketAccess':"この学校で承認されたスタッフのみチケットメッセージにアクセスできます",'chat.createOrSelectTicket':"スタッフチケットを作成または選択してください",'chat.noTicketsYet':"チケットはまだありません",'chat.subject':"件名",'chat.whatNeedsAttention':"何に対応する必要がありますか？",'chat.studentId':"生徒ID",'chat.optionalSameSchool':"任意・同じ学校のみ",'chat.describeIssue':"問題を明確に説明してください…",'chat.newOfficialMessage':"新しい公式メッセージ",'chat.closeOfficialMessage':"公式メッセージフォームを閉じる",'chat.backToAnnouncements':"お知らせに戻る",'chat.officialAnnouncement':"公式お知らせ",'chat.systemGeneratedOfficialMessage':"システム生成公式メッセージ",'chat.read':"既読",'chat.reason':"理由",'chat.chooseTeacher':"先生を選択",'chat.startPrivateConversation':"非公開の1対1会話を開始",'chat.teacher':"先生",'chat.privateOneToOne':"非公開1対1",'chat.unableOpenConversation':"会話を開けません",'chat.writeDepartmentMessage':"部署へのメッセージを書く…",'chat.writeGradeMessage':"学年へのメッセージを書く…",'chat.writeMessage':"メッセージを書く…",'chat.messageSendFailed':"メッセージを送信できませんでした。",'chat.groupCreateFailed':"グループを作成できませんでした。",'chat.gradeSendFailed':"学年メッセージを送信できませんでした。",'chat.departmentSendFailed':"部署メッセージを送信できませんでした。"},
    ms:{'chat.reason':"Sebab",'chat.officialCommunication':"Komunikasi rasmi sekolah",'chat.writeOfficialMessage':"Tulis mesej rasmi...",'chat.noVerifiedRecipient':"Tiada penerima yang disahkan",'chat.noVerifiedSameSchoolRecipient':"Pengesahan pelayan tidak menemui penerima aktif dari sekolah yang sama.",'chat.systemGeneratedOfficialMessage':"Mesej rasmi yang dijana oleh sistem",'chat.adminComposer':"Komposer mesej rasmi pentadbir",'chat.officialCommunication':"Komunikasi rasmi sekolah",'chat.writeOfficialMessage':"Tulis mesej rasmi...",'chat.oneVerifiedRecipient':"1 penerima disahkan",'chat.noVerifiedRecipient':"Tiada penerima disahkan",'chat.noVerifiedSameSchoolRecipient':"Kebenaran pelayan tidak memulangkan penerima aktif dari sekolah yang sama.",'chat.officialAnnouncements':"Saluran Pengumuman Rasmi",'chat.officialStaffTask':"Tugasan Rasmi Staf",'chat.staffNotice':"Notis Staf",'chat.exitChat':"Keluar Chat",'chat.aiPlaceholder':"Tanya tentang jadual, murid, kehadiran...",'chat.selectTicketDots':"Pilih tiket...",'chat.unreadMessages':"Mesej belum dibaca",'chat.noInquiryTickets':"Tiada tiket pertanyaan",'chat.createTicketHint':"Cipta tiket apabila isu staf memerlukan perhatian.",'chat.backToInquiryTickets':"Kembali ke tiket pertanyaan",'chat.authorized':"Dibenarkan",'chat.ticketClosed':"Tiket ditutup",'chat.writeReply':"Tulis balasan...",'chat.authorizedTicketAccess':"Hanya staf yang dibenarkan di sekolah ini boleh mengakses mesej tiket.",'chat.createOrSelectTicket':"Cipta atau pilih tiket staf.",'chat.noTicketsYet':"Tiada tiket lagi.",'chat.subject':"Subjek",'chat.whatNeedsAttention':"Apa yang perlu diberi perhatian?",'chat.studentId':"ID Murid",'chat.optionalSameSchool':"pilihan · sekolah yang sama sahaja",'chat.describeIssue':"Terangkan isu dengan jelas...",'chat.newOfficialMessage':"Mesej rasmi baharu",'chat.closeOfficialMessage':"Tutup borang mesej rasmi",'chat.backToAnnouncements':"Kembali ke pengumuman",'chat.officialAnnouncement':"Pengumuman Rasmi",'chat.systemGeneratedOfficialMessage':"MESEJ RASMI DIJANA SISTEM",'chat.read':"Dibaca",'chat.reason':"Sebab",'chat.chooseTeacher':"Pilih guru",'chat.startPrivateConversation':"Mulakan perbualan peribadi 1-dengan-1",'chat.teacher':"Guru",'chat.privateOneToOne':"Peribadi 1-dengan-1",'chat.unableOpenConversation':"Tidak dapat membuka perbualan",'chat.writeDepartmentMessage':"Tulis mesej jabatan...",'chat.writeGradeMessage':"Tulis mesej tingkatan...",'chat.writeMessage':"Tulis mesej...",'chat.messageSendFailed':"Mesej tidak dapat dihantar.",'chat.groupCreateFailed':"Kumpulan tidak dapat dicipta.",'chat.gradeSendFailed':"Mesej tingkatan tidak dapat dihantar.",'chat.departmentSendFailed':"Mesej jabatan tidak dapat dihantar."},
    km:{'chat.reason':"មូលហេតុ",'chat.officialCommunication':"ការទំនាក់ទំនងផ្លូវការរបស់សាលា",'chat.writeOfficialMessage':"សរសេរសារផ្លូវការ...",'chat.noVerifiedRecipient':"គ្មានអ្នកទទួលដែលបានផ្ទៀងផ្ទាត់",'chat.noVerifiedSameSchoolRecipient':"ការផ្ទៀងផ្ទាត់ពីម៉ាស៊ីនមេមិនបានរកឃើញអ្នកទទួលសកម្មពីសាលាដូចគ្នាទេ",'chat.systemGeneratedOfficialMessage':"សារផ្លូវការដែលបង្កើតដោយប្រព័ន្ធ",'chat.adminComposer':"ផ្ទាំងបង្កើតសារផ្លូវការរបស់អ្នកគ្រប់គ្រង",'chat.officialCommunication':"ការទំនាក់ទំនងផ្លូវការរបស់សាលា",'chat.writeOfficialMessage':"សរសេរសារផ្លូវការ...",'chat.oneVerifiedRecipient':"អ្នកទទួលដែលបានផ្ទៀងផ្ទាត់ ១ នាក់",'chat.noVerifiedRecipient':"គ្មានអ្នកទទួលដែលបានផ្ទៀងផ្ទាត់",'chat.noVerifiedSameSchoolRecipient':"ការអនុញ្ញាតពីម៉ាស៊ីនមេមិនបានផ្តល់អ្នកទទួលសកម្មពីសាលាដូចគ្នាទេ",'chat.officialAnnouncements':"ឆានែលសេចក្តីជូនដំណឹងផ្លូវការ",'chat.officialStaffTask':"ភារកិច្ចផ្លូវការរបស់បុគ្គលិក",'chat.staffNotice':"សេចក្តីជូនដំណឹងបុគ្គលិក",'chat.exitChat':"ចាកចេញពីការជជែក",'chat.aiPlaceholder':"សួរអំពីកាលវិភាគ សិស្ស និងវត្តមាន...",'chat.selectTicketDots':"ជ្រើសរើសសំបុត្រ...",'chat.unreadMessages':"សារមិនទាន់អាន",'chat.noInquiryTickets':"គ្មានសំបុត្រសំណួរ",'chat.createTicketHint':"បង្កើតសំបុត្រនៅពេលបញ្ហាបុគ្គលិកត្រូវការការយកចិត្តទុកដាក់",'chat.backToInquiryTickets':"ត្រឡប់ទៅសំបុត្រសំណួរ",'chat.authorized':"បានអនុញ្ញាត",'chat.ticketClosed':"សំបុត្រត្រូវបានបិទ",'chat.writeReply':"សរសេរឆ្លើយតប...",'chat.authorizedTicketAccess':"មានតែបុគ្គលិកដែលបានអនុញ្ញាតក្នុងសាលានេះប៉ុណ្ណោះដែលអាចចូលមើលសារសំបុត្រ",'chat.createOrSelectTicket':"បង្កើត ឬជ្រើសរើសសំបុត្របុគ្គលិក",'chat.noTicketsYet':"មិនទាន់មានសំបុត្រ",'chat.subject':"ប្រធានបទ",'chat.whatNeedsAttention':"តើអ្វីត្រូវការការយកចិត្តទុកដាក់?",'chat.studentId':"លេខសម្គាល់សិស្ស",'chat.optionalSameSchool':"ជាជម្រើស · សាលាដូចគ្នាប៉ុណ្ណោះ",'chat.describeIssue':"ពិពណ៌នាបញ្ហាឱ្យបានច្បាស់...",'chat.newOfficialMessage':"សារផ្លូវការថ្មី",'chat.closeOfficialMessage':"បិទទម្រង់សារផ្លូវការ",'chat.backToAnnouncements':"ត្រឡប់ទៅសេចក្តីជូនដំណឹង",'chat.officialAnnouncement':"សេចក្តីជូនដំណឹងផ្លូវការ",'chat.systemGeneratedOfficialMessage':"សារផ្លូវការដែលប្រព័ន្ធបង្កើត",'chat.read':"បានអាន",'chat.reason':"មូលហេតុ",'chat.chooseTeacher':"ជ្រើសរើសគ្រូ",'chat.startPrivateConversation':"ចាប់ផ្តើមការសន្ទនាឯកជន ១ ទល់ ១",'chat.teacher':"គ្រូ",'chat.privateOneToOne':"ឯកជន ១ ទល់ ១",'chat.unableOpenConversation':"មិនអាចបើកការសន្ទនាបានទេ",'chat.writeDepartmentMessage':"សរសេរសារទៅកាន់នាយកដ្ឋាន...",'chat.writeGradeMessage':"សរសេរសារទៅកាន់កម្រិតថ្នាក់...",'chat.writeMessage':"សរសេរសារ...",'chat.messageSendFailed':"មិនអាចផ្ញើសារបានទេ។",'chat.groupCreateFailed':"មិនអាចបង្កើតក្រុមបានទេ។",'chat.gradeSendFailed':"មិនអាចផ្ញើសារកម្រិតថ្នាក់បានទេ។",'chat.departmentSendFailed':"មិនអាចផ្ញើសារទៅកាន់នាយកដ្ឋានបានទេ។"},
    zh:{'chat.reason':"原因",'chat.officialCommunication':"学校官方沟通",'chat.writeOfficialMessage':"输入官方消息…",'chat.noVerifiedRecipient':"没有已验证的收件人",'chat.noVerifiedSameSchoolRecipient':"服务器验证未找到同校的有效收件人",'chat.systemGeneratedOfficialMessage':"系统生成的官方消息",'chat.adminComposer':"管理员官方消息编辑器",'chat.officialCommunication':"学校官方沟通",'chat.writeOfficialMessage':"输入官方消息…",'chat.oneVerifiedRecipient':"1 位已验证收件人",'chat.noVerifiedRecipient':"没有已验证收件人",'chat.noVerifiedSameSchoolRecipient':"服务器授权未返回同校的有效收件人。",'chat.officialAnnouncements':"官方公告频道",'chat.officialStaffTask':"员工官方任务",'chat.staffNotice':"员工通知",'chat.exitChat':"退出聊天",'chat.aiPlaceholder':"询问课表、学生、出勤…",'chat.selectTicketDots':"选择工单…",'chat.unreadMessages':"未读消息",'chat.noInquiryTickets':"暂无咨询工单",'chat.createTicketHint':"需要处理员工问题时创建工单。",'chat.backToInquiryTickets':"返回咨询工单",'chat.authorized':"已授权",'chat.ticketClosed':"工单已关闭",'chat.writeReply':"输入回复…",'chat.authorizedTicketAccess':"仅本校获授权员工可访问工单消息。",'chat.createOrSelectTicket':"创建或选择员工工单。",'chat.noTicketsYet':"暂无工单。",'chat.subject':"主题",'chat.whatNeedsAttention':"需要处理什么？",'chat.studentId':"学生ID",'chat.optionalSameSchool':"可选 · 仅限同校",'chat.describeIssue':"请清楚描述问题…",'chat.newOfficialMessage':"新建官方消息",'chat.closeOfficialMessage':"关闭官方消息表单",'chat.backToAnnouncements':"返回公告",'chat.officialAnnouncement':"官方公告",'chat.systemGeneratedOfficialMessage':"系统生成的官方消息",'chat.read':"已读",'chat.reason':"原因",'chat.chooseTeacher':"选择教师",'chat.startPrivateConversation':"开始私人一对一会话",'chat.teacher':"教师",'chat.privateOneToOne':"私人一对一",'chat.unableOpenConversation':"无法打开会话",'chat.writeDepartmentMessage':"输入部门消息…",'chat.writeGradeMessage':"输入年级消息…",'chat.writeMessage':"输入消息…",'chat.messageSendFailed':"消息发送失败。",'chat.groupCreateFailed':"群组创建失败。",'chat.gradeSendFailed':"年级消息发送失败。",'chat.departmentSendFailed':"部门消息发送失败。"}
  };
  Object.assign(chat.th,fill.th); Object.assign(chat.jp,fill.jp); Object.assign(chat.ms,fill.ms); Object.assign(chat.km,fill.km); Object.assign(chat.zh,fill.zh);
  const my=chat.my,en=chat.en;
  // Keys whose localized wording is not critical to the UI but must exist for parity.
  ['th','jp','ms','km','zh'].forEach(code=>Object.keys(en).forEach(k=>{ if(!(k in chat[code])) chat[code][k]=en[k]; }));

  // Complete Staff Chat runtime copy. These keys cover labels/states that are
  // rendered after the initial page template and therefore cannot rely on
  // the legacy page-level locale dictionaries alone.
  const extra={
    en:{
      'chat.allStaff':'All Staff','chat.gradePrefix':'Grade: ','chat.individualPrefix':'Individual: ','chat.selectTeacher':'Select a teacher','chat.gradeRecipientsMissing':'No active verified teachers were found for this grade. Check the grade/class mapping and active teacher assignments, then refresh recipients.',
      'chat.communicationCenter':'COMMUNICATION CENTER','chat.schoolCommunicationDesc':'School communication and AI operations — kept separate, one tap away.',
      'chat.staffGeneral':'General staff conversation','chat.officialNotices':'System-generated official notices','chat.departmentGrade':'Department & Grade','chat.classDepartmentChannels':'Class / department channels',
      'chat.workspace.tickets':'Inquiry Tickets','chat.studentParentConversations':'Student / parent conversations','chat.directMessages':'1-on-1 Direct Messages','chat.privateStaffChat':'Private staff-to-staff chat','chat.workspace.groups':'Project / Event Groups','chat.temporaryWorkGroups':'Temporary work groups','chat.verifiedStaffOnly':'Verified staff only',
      'chat.inquiryDescription':'Staff-only student / parent issue tracking','chat.noMessages':'No messages yet','chat.officialPrefix':'Official','chat.announcement':'Announcement','chat.verified':'Verified','chat.findTeacher':'Find a teacher…','chat.startNewConversation':'Start a new conversation','chat.activeStaffOnly':'Active staff only','chat.startDirect':'Select a teacher to start messaging…',
      'chat.noConversations':'No conversations yet','chat.writePrivate':'Write a private message…','chat.newConversation':'New conversation','chat.sendFirstPrivate':'Send the first private message.','chat.loadFailed':'Unable to load chat.','chat.emptySub':'Start a conversation','chat.pending':'sending','chat.failed':'failed','chat.today':'Today','chat.yesterday':'Yesterday','chat.channelPreviewOnly':'This channel is preview-only.','chat.aiPreview':'AI preview',
      'chat.reason':'Reason','chat.officialCommunication':'Official school communication','chat.oneVerifiedRecipient':'One verified recipient','chat.staffNotice':'Staff notice','chat.writeOfficialMessage':'Write an official message…','chat.noVerifiedRecipient':'No verified recipients','chat.noVerifiedSameSchoolRecipient':'Server verification returned no active recipients from this school.','chat.systemGeneratedOfficialMessage':'System-generated official message','chat.adminTools':'ADMIN TOOLS','chat.officialMessage':'Official message','chat.messageBody':"Message body",'chat.officialMessageHint':'Official messages require a reason and are routed only to server-verified active staff.','chat.serverVerified':'SERVER VERIFIED','chat.recipientType':'Recipient type','chat.grade':'Grade','chat.individualTeacher':'Individual teacher','chat.loadingGrades':'Loading available grades…','chat.messageType':'Message type','chat.officialTask':'Official task','chat.refreshRecipients':'Refresh recipients','chat.sendOfficialMessage':'Send official message','chat.checkingRecipients':'Checking verified recipients…','chat.sent':'Sent','chat.officialMessageSent':'Official message sent to {count} verified staff.','chat.reasonBodyRequired':'Reason and message body are required.','chat.officialMessageFailed':'Official message could not be sent.','chat.systemGeneratedHeader':'SYSTEM-GENERATED HEADER','chat.verifiedRecipients':'Verified recipients',
      'chat.aiAssistant':'AI Assistant','chat.aiOperations':'School operations · schedule · planning','chat.todaySchedule':'Today’s schedule','chat.scheduleTask':'Schedule a task','chat.checkTimetable':'Check timetable','chat.planTomorrow':'Plan tomorrow','chat.schedule':'SCHEDULE','chat.aiScheduleHint':'AI can prepare, check and organize school tasks.','chat.previewFlow':'Preview flow','chat.uiShellOnly':'UI shell only','chat.aiNotConnected':'AI Universe Layer execution is intentionally not connected yet. When it is ready, this interface will connect to the authorized AI action flow.','chat.channelNotConnected':'Channel backend is not connected yet','chat.preview':'Preview',
      'chat.inquiry':'INQUIRY','chat.refresh':'Refresh','chat.newTicket':'New ticket','chat.loadTicketsFailed':'Unable to load tickets.','chat.status':'Status','chat.statusOpen':'OPEN','chat.statusAssigned':'ASSIGNED','chat.statusInProgress':'IN PROGRESS','chat.statusWaiting':'WAITING','chat.statusResolved':'RESOLVED','chat.statusClosed':'CLOSED','chat.assignee':'Assignee','chat.unassigned':'Unassigned','chat.priority':'Priority','chat.cancel':'Cancel','chat.createTicket':'Create ticket','chat.official':'OFFICIAL','chat.announcements':'Announcements','chat.schoolAuthorizedNotices':'School-authorized notices for your staff account.','chat.noOfficialAnnouncements':'No official announcements','chat.newVerifiedNotices':'New verified notices will appear here.','chat.loadAnnouncementsFailed':'Unable to load announcements.','chat.chooseOfficialNotice':'Choose an official notice from the list.','chat.selectAnnouncementToRead':'Select an announcement to read it.','chat.selectAnnouncement':'Select an announcement','chat.chooseTeacher':'Choose a teacher','chat.startPrivateConversation':'Start a private 1-on-1 conversation.','chat.unableLoadDirect':'Unable to load direct messages.','chat.unableOpenConversation':'Unable to open conversation.','chat.privateOneToOne':'Private 1-on-1','chat.selectTicketDots':'Select a ticket…','chat.noTicketsYet':'No tickets yet.'
    },
    my:{
      'chat.allStaff':'ဝန်ထမ်းအားလုံး','chat.gradePrefix':'အတန်း: ','chat.individualPrefix':'တစ်ဦးချင်း: ','chat.selectTeacher':'ဆရာ/ဆရာမ ရွေးပါ','chat.gradeRecipientsMissing':'ဤအတန်းအတွက် လက်ရှိအသုံးပြုနေသော အတည်ပြုထားသည့် ဆရာ/ဆရာမ မတွေ့ပါ။ အတန်းနှင့် Class ချိတ်ဆက်မှု၊ ဆရာ/ဆရာမ assignment များကို စစ်ပြီး လက်ခံသူများကို ပြန်လည်စစ်ဆေးပါ။','chat.communicationCenter':'ဆက်သွယ်ရေးဗဟို','chat.schoolCommunicationDesc':'ကျောင်းဆက်သွယ်ရေးနှင့် AI လုပ်ငန်းများကို သီးခြားထားပြီး တစ်ချက်နှိပ်၍ အသုံးပြုနိုင်သည်။','chat.staffGeneral':'ဝန်ထမ်းအထွေထွေ စကားပြောခန်း','chat.officialNotices':'စနစ်မှထုတ်ပေးသော တရားဝင်အသိပေးချက်များ','chat.departmentGrade':'ဌာနနှင့် အတန်း','chat.classDepartmentChannels':'အတန်း / ဌာနချန်နယ်များ','chat.workspace.tickets':'စုံစမ်းမေးမြန်းမှု လက်မှတ်များ','chat.studentParentConversations':'ကျောင်းသား / မိဘ ဆက်သွယ်မှုများ','chat.directMessages':'တစ်ဦးချင်း တိုက်ရိုက်မက်ဆေ့ချ်','chat.privateStaffChat':'ဝန်ထမ်းအချင်းချင်း ကိုယ်ပိုင်စကားပြောခန်း','chat.workspace.groups':'ပရောဂျက် / ပွဲအဖွဲ့များ','chat.temporaryWorkGroups':'ယာယီအလုပ်အဖွဲ့များ','chat.verifiedStaffOnly':'အတည်ပြုထားသော ဝန်ထမ်းများသာ','chat.inquiryDescription':'ဝန်ထမ်းများအတွက် ကျောင်းသား / မိဘ ပြဿနာစီမံမှု','chat.noMessages':'မက်ဆေ့ချ် မရှိသေးပါ','chat.officialPrefix':'တရားဝင်','chat.announcement':'ကြေညာချက်','chat.verified':'အတည်ပြုပြီး','chat.findTeacher':'ဆရာ/ဆရာမ ရှာပါ…','chat.startNewConversation':'စကားပြောအသစ် စတင်ရန်','chat.activeStaffOnly':'လက်ရှိဝန်ထမ်းများသာ','chat.startDirect':'မက်ဆေ့ချ်စတင်ရန် ဆရာ/ဆရာမ ရွေးပါ…','chat.noConversations':'စကားပြောခန်း မရှိသေးပါ','chat.writePrivate':'ကိုယ်ပိုင်မက်ဆေ့ချ် ရေးပါ…','chat.newConversation':'စကားပြောအသစ်','chat.sendFirstPrivate':'ပထမဆုံး ကိုယ်ပိုင်မက်ဆေ့ချ်ကို ပို့ပါ။','chat.loadFailed':'Chat ဖွင့်၍မရပါ။','chat.emptySub':'စကားပြောခန်း စတင်ပါ','chat.pending':'ပို့နေသည်','chat.failed':'မအောင်မြင်ပါ','chat.today':'ယနေ့','chat.yesterday':'မနေ့က','chat.channelPreviewOnly':'ဤချန်နယ်သည် အကြိုကြည့်ရှုမှုသာ ဖြစ်သည်။','chat.aiPreview':'AI အကြိုကြည့်ရှုမှု',
      'chat.adminTools':'စီမံခန့်ခွဲသူကိရိယာများ','chat.officialMessage':'တရားဝင်မက်ဆေ့ချ်','chat.messageBody':"မက်ဆေ့ချ်စာသား",'chat.officialMessageHint':'တရားဝင်မက်ဆေ့ချ်များတွင် အကြောင်းပြချက်လိုအပ်ပြီး server မှ အတည်ပြုထားသော လက်ရှိဝန်ထမ်းများထံသာ ပို့မည်။','chat.serverVerified':'SERVER မှ အတည်ပြုပြီး','chat.recipientType':'လက်ခံသူအမျိုးအစား','chat.grade':'အတန်း','chat.individualTeacher':'ဆရာ/ဆရာမ တစ်ဦးချင်း','chat.loadingGrades':'ရရှိနိုင်သောအတန်းများကို ဖွင့်နေသည်…','chat.messageType':'မက်ဆေ့ချ်အမျိုးအစား','chat.officialTask':'တရားဝင်တာဝန်','chat.refreshRecipients':'လက်ခံသူများ ပြန်လည်စစ်ဆေးရန်','chat.sendOfficialMessage':'တရားဝင်မက်ဆေ့ချ် ပို့ရန်','chat.checkingRecipients':'အတည်ပြုလက်ခံသူများကို စစ်ဆေးနေသည်…','chat.sent':'ပို့ပြီး','chat.officialMessageSent':'အတည်ပြုထားသော ဝန်ထမ်း {count} ဦးထံ တရားဝင်မက်ဆေ့ချ် ပို့ပြီးပါပြီ။','chat.reasonBodyRequired':'အကြောင်းပြချက်နှင့် မက်ဆေ့ချ်စာသား လိုအပ်သည်။','chat.officialMessageFailed':'တရားဝင်မက်ဆေ့ချ် ပို့၍မရပါ။','chat.systemGeneratedHeader':'စနစ်ထုတ် တရားဝင်ခေါင်းစီး','chat.verifiedRecipients':'အတည်ပြုလက်ခံသူများ',
      'chat.aiAssistant':'AI Assistant','chat.aiOperations':'ကျောင်းလုပ်ငန်းများ · အချိန်ဇယား · စီမံချက်','chat.todaySchedule':'ယနေ့အချိန်ဇယား','chat.scheduleTask':'တာဝန်အချိန်ဇယားသတ်မှတ်ရန်','chat.checkTimetable':'အချိန်ဇယား စစ်ဆေးရန်','chat.planTomorrow':'မနက်ဖြန် စီစဉ်ရန်','chat.schedule':'အချိန်ဇယား','chat.aiScheduleHint':'AI သည် ကျောင်းတာဝန်များကို ပြင်ဆင်၊ စစ်ဆေး၊ စုစည်းပေးနိုင်သည်။','chat.previewFlow':'အကြိုကြည့်ရှုမှု','chat.uiShellOnly':'UI shell သာ','chat.aiNotConnected':'AI Universe Layer execution ကို လက်ရှိတွင် မချိတ်ဆက်ရသေးပါ။ အဆင်သင့်ဖြစ်ပါက ခွင့်ပြုထားသော AI action flow နှင့် ချိတ်ဆက်မည်။','chat.channelNotConnected':'ဤချန်နယ် backend မချိတ်ဆက်ရသေးပါ','chat.preview':'အကြိုကြည့်ရှုမှု',
      'chat.inquiry':'စုံစမ်းမေးမြန်းမှု','chat.refresh':'ပြန်လည်ဖွင့်ရန်','chat.newTicket':'လက်မှတ်အသစ်','chat.loadTicketsFailed':'လက်မှတ်များကို ဖွင့်၍မရပါ။','chat.status':'အခြေအနေ','chat.statusOpen':'ဖွင့်ထား','chat.statusAssigned':'တာဝန်ပေးထား','chat.statusInProgress':'လုပ်ဆောင်နေ','chat.statusWaiting':'စောင့်ဆိုင်းနေ','chat.statusResolved':'ဖြေရှင်းပြီး','chat.statusClosed':'ပိတ်ထား','chat.assignee':'တာဝန်ခံ','chat.unassigned':'တာဝန်မပေးရသေး','chat.priority':'ဦးစားပေးမှု','chat.cancel':'ပယ်ဖျက်','chat.createTicket':'လက်မှတ်ဖန်တီးရန်','chat.official':'တရားဝင်','chat.announcements':'ကြေညာချက်များ','chat.schoolAuthorizedNotices':'သင့်ဝန်ထမ်းအကောင့်အတွက် ကျောင်းမှ ခွင့်ပြုထားသော အသိပေးချက်များ။','chat.noOfficialAnnouncements':'တရားဝင်ကြေညာချက် မရှိသေးပါ','chat.newVerifiedNotices':'အတည်ပြုထားသော အသိပေးချက်အသစ်များ ဤနေရာတွင် ပေါ်လာမည်။','chat.loadAnnouncementsFailed':'ကြေညာချက်များကို ဖွင့်၍မရပါ။','chat.chooseOfficialNotice':'တရားဝင်အသိပေးချက်တစ်ခုကို ရွေးပါ။','chat.selectAnnouncementToRead':'ဖတ်ရန် ကြေညာချက်တစ်ခု ရွေးပါ။','chat.selectAnnouncement':'ကြေညာချက် ရွေးပါ','chat.chooseTeacher':'ဆရာ/ဆရာမ ရွေးပါ','chat.startPrivateConversation':'ကိုယ်ပိုင် ၁-ဦးချင်း စကားပြောခန်း စတင်ပါ။','chat.unableLoadDirect':'တိုက်ရိုက်မက်ဆေ့ချ်များကို ဖွင့်၍မရပါ။','chat.unableOpenConversation':'စကားပြောခန်း ဖွင့်၍မရပါ။','chat.privateOneToOne':'ကိုယ်ပိုင် ၁-ဦးချင်း','chat.selectTicketDots':'လက်မှတ် ရွေးပါ…','chat.noTicketsYet':'လက်မှတ် မရှိသေးပါ။','chat.oneVerifiedRecipient':'အတည်ပြုထားသော လက်ခံသူတစ်ဦး'
    },
    th:{},jp:{},ms:{},km:{},zh:{}
  };
  Object.keys(extra).forEach(code=>Object.assign(chat[code],extra[code]));
  const fallbackKeys=Object.keys(extra.en);
  const localized={
    th:{
      'chat.allStaff':'บุคลากรทั้งหมด','chat.gradePrefix':'ระดับชั้น: ','chat.individualPrefix':'รายบุคคล: ','chat.selectTeacher':'เลือกครู','chat.communicationCenter':'ศูนย์การสื่อสาร','chat.schoolCommunicationDesc':'การสื่อสารของโรงเรียนและงาน AI แยกจากกันอย่างชัดเจน ใช้งานได้ในแตะเดียว','chat.staffGeneral':'การสนทนาทั่วไปของบุคลากร','chat.officialNotices':'ประกาศทางการที่ระบบสร้าง','chat.departmentGrade':'แผนกและระดับชั้น','chat.classDepartmentChannels':'ช่องชั้นเรียน / แผนก','chat.workspace.tickets':'ตั๋วสอบถาม','chat.studentParentConversations':'การสนทนานักเรียน / ผู้ปกครอง','chat.directMessages':'ข้อความตรง 1 ต่อ 1','chat.privateStaffChat':'แชตส่วนตัวระหว่างบุคลากร','chat.workspace.groups':'กลุ่มโครงการ / กิจกรรม','chat.temporaryWorkGroups':'กลุ่มงานชั่วคราว','chat.verifiedStaffOnly':'เฉพาะบุคลากรที่ยืนยันแล้ว','chat.inquiryDescription':'ติดตามปัญหานักเรียน / ผู้ปกครองสำหรับบุคลากร','chat.noMessages':'ยังไม่มีข้อความ','chat.officialPrefix':'ทางการ','chat.announcement':'ประกาศ','chat.verified':'ยืนยันแล้ว','chat.findTeacher':'ค้นหาครู…','chat.startNewConversation':'เริ่มการสนทนาใหม่','chat.activeStaffOnly':'เฉพาะบุคลากรที่ใช้งานอยู่','chat.startDirect':'เลือกครูเพื่อเริ่มส่งข้อความ…','chat.noConversations':'ยังไม่มีการสนทนา','chat.writePrivate':'เขียนข้อความส่วนตัว…','chat.newConversation':'การสนทนาใหม่','chat.sendFirstPrivate':'ส่งข้อความส่วนตัวแรก','chat.loadFailed':'ไม่สามารถโหลดแชตได้','chat.emptySub':'เริ่มการสนทนา','chat.pending':'กำลังส่ง','chat.failed':'ล้มเหลว','chat.today':'วันนี้','chat.yesterday':'เมื่อวาน','chat.channelPreviewOnly':'ช่องนี้เป็นเพียงตัวอย่าง','chat.aiPreview':'ตัวอย่าง AI'
    },
    jp:{'chat.allStaff':'全スタッフ','chat.gradePrefix':'学年: ','chat.individualPrefix':'個別: ','chat.selectTeacher':'教員を選択','chat.communicationCenter':'コミュニケーションセンター','chat.schoolCommunicationDesc':'学校連絡とAI運用を分離し、ワンタップで切り替えます','chat.staffGeneral':'スタッフ全体の会話','chat.officialNotices':'システム公式通知','chat.departmentGrade':'部署と学年','chat.classDepartmentChannels':'クラス / 部署チャンネル','chat.workspace.tickets':'問い合わせチケット','chat.studentParentConversations':'生徒 / 保護者の会話','chat.directMessages':'1対1ダイレクトメッセージ','chat.privateStaffChat':'スタッフ間のプライベートチャット','chat.workspace.groups':'プロジェクト / イベントグループ','chat.temporaryWorkGroups':'一時作業グループ','chat.verifiedStaffOnly':'確認済みスタッフのみ','chat.inquiryDescription':'スタッフ専用の生徒 / 保護者問題管理','chat.noMessages':'メッセージはまだありません','chat.officialPrefix':'公式','chat.announcement':'お知らせ','chat.verified':'確認済み','chat.findTeacher':'教員を検索…','chat.startNewConversation':'新しい会話を開始','chat.activeStaffOnly':'有効なスタッフのみ','chat.startDirect':'メッセージを開始する教員を選択…','chat.noConversations':'会話はまだありません','chat.writePrivate':'プライベートメッセージを入力…','chat.newConversation':'新しい会話','chat.sendFirstPrivate':'最初のプライベートメッセージを送信','chat.loadFailed':'チャットを読み込めません','chat.emptySub':'会話を始めましょう','chat.pending':'送信中','chat.failed':'失敗','chat.today':'今日','chat.yesterday':'昨日','chat.channelPreviewOnly':'このチャンネルはプレビューのみです','chat.aiPreview':'AIプレビュー'},
    ms:{'chat.allStaff':'Semua Staf','chat.gradePrefix':'Tahun: ','chat.individualPrefix':'Individu: ','chat.selectTeacher':'Pilih guru','chat.communicationCenter':'Pusat Komunikasi','chat.schoolCommunicationDesc':'Komunikasi sekolah dan operasi AI diasingkan dengan jelas, satu ketikan untuk bertukar','chat.staffGeneral':'Perbualan umum staf','chat.officialNotices':'Notis rasmi dijana sistem','chat.departmentGrade':'Jabatan & Tahun','chat.classDepartmentChannels':'Saluran kelas / jabatan','chat.workspace.tickets':'Tiket Pertanyaan','chat.studentParentConversations':'Perbualan murid / ibu bapa','chat.directMessages':'Mesej Langsung 1-dengan-1','chat.privateStaffChat':'Sembang peribadi staf','chat.workspace.groups':'Kumpulan Projek / Acara','chat.temporaryWorkGroups':'Kumpulan kerja sementara','chat.verifiedStaffOnly':'Staf disahkan sahaja','chat.inquiryDescription':'Jejak isu murid / ibu bapa untuk staf','chat.noMessages':'Tiada mesej lagi','chat.officialPrefix':'Rasmi','chat.announcement':'Pengumuman','chat.verified':'Disahkan','chat.findTeacher':'Cari guru…','chat.startNewConversation':'Mulakan perbualan baharu','chat.activeStaffOnly':'Staf aktif sahaja','chat.startDirect':'Pilih guru untuk mula menghantar mesej…','chat.noConversations':'Tiada perbualan lagi','chat.writePrivate':'Tulis mesej peribadi…','chat.newConversation':'Perbualan baharu','chat.sendFirstPrivate':'Hantar mesej peribadi pertama','chat.loadFailed':'Tidak dapat memuatkan chat','chat.emptySub':'Mulakan perbualan','chat.pending':'menghantar','chat.failed':'gagal','chat.today':'Hari ini','chat.yesterday':'Semalam','chat.channelPreviewOnly':'Saluran ini hanya pratonton','chat.aiPreview':'Pratonton AI'},
    km:{'chat.allStaff':'បុគ្គលិកទាំងអស់','chat.gradePrefix':'ថ្នាក់: ','chat.individualPrefix':'បុគ្គល: ','chat.selectTeacher':'ជ្រើសរើសគ្រូ','chat.communicationCenter':'មជ្ឈមណ្ឌលទំនាក់ទំនង','chat.schoolCommunicationDesc':'ការទំនាក់ទំនងសាលា និងប្រតិបត្តិការ AI ត្រូវបានបំបែកច្បាស់លាស់ អាចប្តូរដោយចុចម្តង','chat.staffGeneral':'ការសន្ទនាទូទៅរបស់បុគ្គលិក','chat.officialNotices':'សេចក្តីជូនដំណឹងផ្លូវការដែលប្រព័ន្ធបង្កើត','chat.departmentGrade':'ផ្នែក និងថ្នាក់','chat.classDepartmentChannels':'ឆានែលថ្នាក់ / ផ្នែក','chat.workspace.tickets':'សំបុត្រសំណួរ','chat.studentParentConversations':'ការសន្ទនាសិស្ស / មាតាបិតា','chat.directMessages':'សារផ្ទាល់ ១ ទល់ ១','chat.privateStaffChat':'ការជជែកឯកជនរបស់បុគ្គលិក','chat.workspace.groups':'ក្រុមគម្រោង / ព្រឹត្តិការណ៍','chat.temporaryWorkGroups':'ក្រុមការងារបណ្តោះអាសន្ន','chat.verifiedStaffOnly':'បុគ្គលិកដែលបានផ្ទៀងផ្ទាត់ប៉ុណ្ណោះ','chat.inquiryDescription':'តាមដានបញ្ហាសិស្ស / មាតាបិតាសម្រាប់បុគ្គលិក','chat.noMessages':'មិនទាន់មានសារ','chat.officialPrefix':'ផ្លូវការ','chat.announcement':'សេចក្តីជូនដំណឹង','chat.verified':'បានផ្ទៀងផ្ទាត់','chat.findTeacher':'ស្វែងរកគ្រូ…','chat.startNewConversation':'ចាប់ផ្តើមការសន្ទនាថ្មី','chat.activeStaffOnly':'បុគ្គលិកសកម្មប៉ុណ្ណោះ','chat.startDirect':'ជ្រើសរើសគ្រូដើម្បីចាប់ផ្តើមផ្ញើសារ…','chat.noConversations':'មិនទាន់មានការសន្ទនា','chat.writePrivate':'សរសេរសារឯកជន…','chat.newConversation':'ការសន្ទនាថ្មី','chat.sendFirstPrivate':'ផ្ញើសារឯកជនដំបូង','chat.loadFailed':'មិនអាចផ្ទុកការជជែកបាន','chat.emptySub':'ចាប់ផ្តើមការសន្ទនា','chat.pending':'កំពុងផ្ញើ','chat.failed':'បរាជ័យ','chat.today':'ថ្ងៃនេះ','chat.yesterday':'ម្សិលមិញ','chat.channelPreviewOnly':'ឆានែលនេះសម្រាប់មើលជាមុនប៉ុណ្ណោះ','chat.aiPreview':'មើលជាមុន AI'},
    zh:{'chat.allStaff':'全体员工','chat.gradePrefix':'年级：','chat.individualPrefix':'个人：','chat.selectTeacher':'选择教师','chat.communicationCenter':'沟通中心','chat.schoolCommunicationDesc':'学校沟通与 AI 操作清晰分开，一键切换','chat.staffGeneral':'员工群聊','chat.officialNotices':'系统生成的官方通知','chat.departmentGrade':'部门与年级','chat.classDepartmentChannels':'班级 / 部门频道','chat.workspace.tickets':'咨询工单','chat.studentParentConversations':'学生 / 家长会话','chat.directMessages':'1对1私信','chat.privateStaffChat':'员工私聊','chat.workspace.groups':'项目 / 活动群组','chat.temporaryWorkGroups':'临时工作组','chat.verifiedStaffOnly':'仅限已验证员工','chat.inquiryDescription':'员工专用学生 / 家长问题跟踪','chat.noMessages':'暂无消息','chat.officialPrefix':'官方','chat.announcement':'公告','chat.verified':'已验证','chat.findTeacher':'搜索教师…','chat.startNewConversation':'开始新会话','chat.activeStaffOnly':'仅限活跃员工','chat.startDirect':'选择教师开始发消息…','chat.noConversations':'暂无会话','chat.writePrivate':'输入私信…','chat.newConversation':'新会话','chat.sendFirstPrivate':'发送第一条私信','chat.loadFailed':'无法加载聊天','chat.emptySub':'开始会话','chat.pending':'发送中','chat.failed':'失败','chat.today':'今天','chat.yesterday':'昨天','chat.channelPreviewOnly':'此频道仅供预览','chat.aiPreview':'AI 预览'}
  };
  Object.keys(localized).forEach(code=>Object.assign(chat[code],localized[code]));
  Object.keys(chat).forEach(code=>fallbackKeys.forEach(k=>{if(!(k in chat[code])) chat[code][k]=chat.en[k];}));


  const localizedUi={
    th:{
      'chat.adminTools':'เครื่องมือผู้ดูแล','chat.officialMessage':'ข้อความทางการ','chat.messageBody':"เนื้อหาข้อความ",'chat.officialMessageHint':'ข้อความทางการต้องมีเหตุผลและส่งเฉพาะบุคลากรที่ใช้งานอยู่ซึ่งเซิร์ฟเวอร์ยืนยันแล้ว','chat.serverVerified':'ยืนยันโดยเซิร์ฟเวอร์','chat.recipientType':'ประเภทผู้รับ','chat.grade':'ระดับชั้น','chat.individualTeacher':'ครูรายบุคคล','chat.loadingGrades':'กำลังโหลดระดับชั้นที่ใช้ได้…','chat.messageType':'ประเภทข้อความ','chat.officialTask':'งานทางการ','chat.refreshRecipients':'รีเฟรชผู้รับ','chat.sendOfficialMessage':'ส่งข้อความทางการ','chat.checkingRecipients':'กำลังตรวจสอบผู้รับที่ยืนยันแล้ว…','chat.sent':'ส่งแล้ว','chat.officialMessageSent':'ส่งข้อความทางการถึงบุคลากรที่ยืนยันแล้ว {count} คน','chat.reasonBodyRequired':'ต้องระบุเหตุผลและข้อความ','chat.officialMessageFailed':'ไม่สามารถส่งข้อความทางการได้','chat.systemGeneratedHeader':'หัวข้อที่ระบบสร้าง','chat.verifiedRecipients':'ผู้รับที่ยืนยันแล้ว','chat.aiAssistant':'ผู้ช่วย AI','chat.aiOperations':'งานโรงเรียน · ตาราง · การวางแผน','chat.todaySchedule':'ตารางวันนี้','chat.scheduleTask':'กำหนดงาน','chat.checkTimetable':'ตรวจตารางเรียน','chat.planTomorrow':'วางแผนพรุ่งนี้','chat.schedule':'ตาราง','chat.aiScheduleHint':'AI สามารถเตรียม ตรวจสอบ และจัดระเบียบงานโรงเรียน','chat.previewFlow':'ตัวอย่างการทำงาน','chat.uiShellOnly':'เฉพาะ UI','chat.aiNotConnected':'ยังไม่ได้เชื่อมต่อการทำงาน AI Universe Layer','chat.channelNotConnected':'แบ็กเอนด์ของช่องนี้ยังไม่เชื่อมต่อ','chat.preview':'ตัวอย่าง','chat.inquiry':'สอบถาม','chat.refresh':'รีเฟรช','chat.newTicket':'ตั๋วใหม่','chat.loadTicketsFailed':'ไม่สามารถโหลดตั๋วได้','chat.status':'สถานะ','chat.assignee':'ผู้รับผิดชอบ','chat.unassigned':'ยังไม่มอบหมาย','chat.priority':'ลำดับความสำคัญ','chat.cancel':'ยกเลิก','chat.createTicket':'สร้างตั๋ว','chat.official':'ทางการ','chat.announcements':'ประกาศ','chat.schoolAuthorizedNotices':'ประกาศที่โรงเรียนอนุมัติสำหรับบัญชีบุคลากรของคุณ','chat.noOfficialAnnouncements':'ยังไม่มีประกาศทางการ','chat.newVerifiedNotices':'ประกาศที่ยืนยันใหม่จะแสดงที่นี่','chat.loadAnnouncementsFailed':'ไม่สามารถโหลดประกาศได้','chat.chooseOfficialNotice':'เลือกประกาศทางการ','chat.selectAnnouncementToRead':'เลือกประกาศเพื่ออ่าน','chat.selectAnnouncement':'เลือกประกาศ','chat.chooseTeacher':'เลือกครู','chat.startPrivateConversation':'เริ่มการสนทนาส่วนตัว 1 ต่อ 1','chat.unableLoadDirect':'ไม่สามารถโหลดข้อความตรงได้','chat.privateOneToOne':'ส่วนตัว 1 ต่อ 1','chat.selectTicketDots':'เลือกตั๋ว…','chat.noTicketsYet':'ยังไม่มีตั๋ว'
    },
    jp:{
      'chat.adminTools':'管理者ツール','chat.officialMessage':'公式メッセージ','chat.messageBody':"メッセージ本文",'chat.officialMessageHint':'公式メッセージには理由が必要で、サーバー確認済みの有効なスタッフにのみ送信されます','chat.serverVerified':'サーバー確認済み','chat.recipientType':'受信者タイプ','chat.grade':'学年','chat.individualTeacher':'個別の教員','chat.loadingGrades':'利用可能な学年を読み込み中…','chat.messageType':'メッセージ種別','chat.officialTask':'公式タスク','chat.refreshRecipients':'受信者を更新','chat.sendOfficialMessage':'公式メッセージを送信','chat.checkingRecipients':'確認済み受信者を確認中…','chat.sent':'送信済み','chat.officialMessageSent':'確認済みスタッフ {count} 人に公式メッセージを送信しました','chat.reasonBodyRequired':'理由と本文は必須です','chat.officialMessageFailed':'公式メッセージを送信できませんでした','chat.systemGeneratedHeader':'システム生成ヘッダー','chat.verifiedRecipients':'確認済み受信者','chat.aiAssistant':'AIアシスタント','chat.aiOperations':'学校運営 · スケジュール · 計画','chat.todaySchedule':'今日の予定','chat.scheduleTask':'タスクを予定','chat.checkTimetable':'時間割を確認','chat.planTomorrow':'明日の計画','chat.schedule':'スケジュール','chat.aiScheduleHint':'AIは学校タスクの準備、確認、整理を支援します','chat.previewFlow':'プレビューフロー','chat.uiShellOnly':'UIシェルのみ','chat.aiNotConnected':'AI Universe Layerの実行はまだ接続されていません','chat.channelNotConnected':'このチャンネルのバックエンドは未接続です','chat.preview':'プレビュー','chat.inquiry':'問い合わせ','chat.refresh':'更新','chat.newTicket':'新しいチケット','chat.loadTicketsFailed':'チケットを読み込めません','chat.status':'ステータス','chat.assignee':'担当者','chat.unassigned':'未割り当て','chat.priority':'優先度','chat.cancel':'キャンセル','chat.createTicket':'チケットを作成','chat.official':'公式','chat.announcements':'お知らせ','chat.schoolAuthorizedNotices':'スタッフアカウント向けの学校承認済み通知','chat.noOfficialAnnouncements':'公式お知らせはありません','chat.newVerifiedNotices':'確認済みの新しい通知がここに表示されます','chat.loadAnnouncementsFailed':'お知らせを読み込めません','chat.chooseOfficialNotice':'公式通知を選択','chat.selectAnnouncementToRead':'読むお知らせを選択','chat.selectAnnouncement':'お知らせを選択','chat.chooseTeacher':'教員を選択','chat.startPrivateConversation':'非公開の1対1会話を開始','chat.unableLoadDirect':'ダイレクトメッセージを読み込めません','chat.privateOneToOne':'非公開1対1','chat.selectTicketDots':'チケットを選択…','chat.noTicketsYet':'チケットはまだありません'
    },
    ms:{
      'chat.adminTools':'Alat Pentadbir','chat.officialMessage':'Mesej rasmi','chat.messageBody':"Kandungan mesej",'chat.officialMessageHint':'Mesej rasmi memerlukan sebab dan hanya dihantar kepada staf aktif yang disahkan pelayan','chat.serverVerified':'DISAHKAN PELAYAN','chat.recipientType':'Jenis penerima','chat.grade':'Tahun','chat.individualTeacher':'Guru individu','chat.loadingGrades':'Memuatkan tahun yang tersedia…','chat.messageType':'Jenis mesej','chat.officialTask':'Tugasan rasmi','chat.refreshRecipients':'Muat semula penerima','chat.sendOfficialMessage':'Hantar mesej rasmi','chat.checkingRecipients':'Memeriksa penerima yang disahkan…','chat.sent':'Dihantar','chat.officialMessageSent':'Mesej rasmi dihantar kepada {count} staf disahkan','chat.reasonBodyRequired':'Sebab dan kandungan mesej diperlukan','chat.officialMessageFailed':'Mesej rasmi tidak dapat dihantar','chat.systemGeneratedHeader':'PENGEPALA DIJANA SISTEM','chat.verifiedRecipients':'Penerima disahkan','chat.aiAssistant':'Pembantu AI','chat.aiOperations':'Operasi sekolah · jadual · perancangan','chat.todaySchedule':'Jadual hari ini','chat.scheduleTask':'Jadualkan tugasan','chat.checkTimetable':'Semak jadual waktu','chat.planTomorrow':'Rancang esok','chat.schedule':'JADUAL','chat.aiScheduleHint':'AI boleh menyediakan, menyemak dan menyusun tugasan sekolah','chat.previewFlow':'Aliran pratonton','chat.uiShellOnly':'UI sahaja','chat.aiNotConnected':'Pelaksanaan AI Universe Layer belum disambungkan','chat.channelNotConnected':'Backend saluran ini belum disambungkan','chat.preview':'Pratonton','chat.inquiry':'PERTANYAAN','chat.refresh':'Muat semula','chat.newTicket':'Tiket baharu','chat.loadTicketsFailed':'Tiket tidak dapat dimuatkan','chat.status':'Status','chat.assignee':'Penyelaras','chat.unassigned':'Belum ditugaskan','chat.priority':'Keutamaan','chat.cancel':'Batal','chat.createTicket':'Cipta tiket','chat.official':'RASMI','chat.announcements':'Pengumuman','chat.schoolAuthorizedNotices':'Notis yang diluluskan sekolah untuk akaun staf anda','chat.noOfficialAnnouncements':'Tiada pengumuman rasmi','chat.newVerifiedNotices':'Notis baharu yang disahkan akan muncul di sini','chat.loadAnnouncementsFailed':'Pengumuman tidak dapat dimuatkan','chat.chooseOfficialNotice':'Pilih notis rasmi','chat.selectAnnouncementToRead':'Pilih pengumuman untuk dibaca','chat.selectAnnouncement':'Pilih pengumuman','chat.chooseTeacher':'Pilih guru','chat.startPrivateConversation':'Mulakan perbualan peribadi 1-dengan-1','chat.unableLoadDirect':'Mesej langsung tidak dapat dimuatkan','chat.privateOneToOne':'Peribadi 1-dengan-1','chat.selectTicketDots':'Pilih tiket…','chat.noTicketsYet':'Tiada tiket lagi'
    },
    km:{
      'chat.adminTools':'ឧបករណ៍អ្នកគ្រប់គ្រង','chat.officialMessage':'សារផ្លូវការ','chat.messageBody':"ខ្លឹមសារសារ",'chat.officialMessageHint':'សារផ្លូវការត្រូវការមូលហេតុ ហើយផ្ញើតែទៅបុគ្គលិកសកម្មដែលម៉ាស៊ីនមេបានផ្ទៀងផ្ទាត់','chat.serverVerified':'បានផ្ទៀងផ្ទាត់ដោយម៉ាស៊ីនមេ','chat.recipientType':'ប្រភេទអ្នកទទួល','chat.grade':'ថ្នាក់','chat.individualTeacher':'គ្រូម្នាក់ៗ','chat.loadingGrades':'កំពុងផ្ទុកថ្នាក់ដែលអាចប្រើបាន…','chat.messageType':'ប្រភេទសារ','chat.officialTask':'ភារកិច្ចផ្លូវការ','chat.refreshRecipients':'ធ្វើបច្ចុប្បន្នភាពអ្នកទទួល','chat.sendOfficialMessage':'ផ្ញើសារផ្លូវការ','chat.checkingRecipients':'កំពុងពិនិត្យអ្នកទទួលដែលបានផ្ទៀងផ្ទាត់…','chat.sent':'បានផ្ញើ','chat.officialMessageSent':'បានផ្ញើសារផ្លូវការទៅបុគ្គលិកដែលបានផ្ទៀងផ្ទាត់ {count} នាក់','chat.reasonBodyRequired':'ត្រូវការមូលហេតុ និងខ្លឹមសារសារ','chat.officialMessageFailed':'មិនអាចផ្ញើសារផ្លូវការបានទេ','chat.systemGeneratedHeader':'បឋមកថាដែលប្រព័ន្ធបង្កើត','chat.verifiedRecipients':'អ្នកទទួលដែលបានផ្ទៀងផ្ទាត់','chat.aiAssistant':'ជំនួយការ AI','chat.aiOperations':'ប្រតិបត្តិការសាលា · កាលវិភាគ · ផែនការ','chat.todaySchedule':'កាលវិភាគថ្ងៃនេះ','chat.scheduleTask':'កំណត់ភារកិច្ច','chat.checkTimetable':'ពិនិត្យកាលវិភាគ','chat.planTomorrow':'រៀបចំផែនការថ្ងៃស្អែក','chat.schedule':'កាលវិភាគ','chat.aiScheduleHint':'AI អាចរៀបចំ ពិនិត្យ និងសម្របសម្រួលភារកិច្ចសាលា','chat.previewFlow':'លំហូរមើលជាមុន','chat.uiShellOnly':'UI ប៉ុណ្ណោះ','chat.aiNotConnected':'ការដំណើរការ AI Universe Layer មិនទាន់បានភ្ជាប់ទេ','chat.channelNotConnected':'Backend របស់ឆានែលនេះមិនទាន់ភ្ជាប់ទេ','chat.preview':'មើលជាមុន','chat.inquiry':'សំណួរ','chat.refresh':'ធ្វើបច្ចុប្បន្នភាព','chat.newTicket':'សំបុត្រថ្មី','chat.loadTicketsFailed':'មិនអាចផ្ទុកសំបុត្របានទេ','chat.status':'ស្ថានភាព','chat.assignee':'អ្នកទទួលខុសត្រូវ','chat.unassigned':'មិនទាន់ចាត់តាំង','chat.priority':'អាទិភាព','chat.cancel':'បោះបង់','chat.createTicket':'បង្កើតសំបុត្រ','chat.official':'ផ្លូវការ','chat.announcements':'សេចក្តីជូនដំណឹង','chat.schoolAuthorizedNotices':'សេចក្តីជូនដំណឹងដែលសាលាអនុម័តសម្រាប់គណនីបុគ្គលិករបស់អ្នក','chat.noOfficialAnnouncements':'គ្មានសេចក្តីជូនដំណឹងផ្លូវការ','chat.newVerifiedNotices':'សេចក្តីជូនដំណឹងថ្មីដែលបានផ្ទៀងផ្ទាត់នឹងបង្ហាញនៅទីនេះ','chat.loadAnnouncementsFailed':'មិនអាចផ្ទុកសេចក្តីជូនដំណឹងបានទេ','chat.chooseOfficialNotice':'ជ្រើសរើសសេចក្តីជូនដំណឹងផ្លូវការ','chat.selectAnnouncementToRead':'ជ្រើសរើសសេចក្តីជូនដំណឹងដើម្បីអាន','chat.selectAnnouncement':'ជ្រើសរើសសេចក្តីជូនដំណឹង','chat.chooseTeacher':'ជ្រើសរើសគ្រូ','chat.startPrivateConversation':'ចាប់ផ្តើមការសន្ទនាឯកជន ១ ទល់ ១','chat.unableLoadDirect':'មិនអាចផ្ទុកសារផ្ទាល់បានទេ','chat.privateOneToOne':'ឯកជន ១ ទល់ ១','chat.selectTicketDots':'ជ្រើសរើសសំបុត្រ…','chat.noTicketsYet':'មិនទាន់មានសំបុត្រ'
    },
    zh:{
      'chat.adminTools':'管理员工具','chat.officialMessage':'官方消息','chat.messageBody':"消息正文",'chat.officialMessageHint':'官方消息必须填写原因，并且仅发送给服务器验证的活跃员工','chat.serverVerified':'服务器已验证','chat.recipientType':'收件人类型','chat.grade':'年级','chat.individualTeacher':'单个教师','chat.loadingGrades':'正在加载可用年级…','chat.messageType':'消息类型','chat.officialTask':'官方任务','chat.refreshRecipients':'刷新收件人','chat.sendOfficialMessage':'发送官方消息','chat.checkingRecipients':'正在检查已验证收件人…','chat.sent':'已发送','chat.officialMessageSent':'官方消息已发送给 {count} 位已验证员工','chat.reasonBodyRequired':'原因和消息正文均为必填项','chat.officialMessageFailed':'无法发送官方消息','chat.systemGeneratedHeader':'系统生成的标题','chat.verifiedRecipients':'已验证收件人','chat.aiAssistant':'AI 助手','chat.aiOperations':'学校运营 · 课表 · 规划','chat.todaySchedule':'今日课表','chat.scheduleTask':'安排任务','chat.checkTimetable':'检查课表','chat.planTomorrow':'规划明天','chat.schedule':'课表','chat.aiScheduleHint':'AI 可以准备、检查并整理学校任务','chat.previewFlow':'预览流程','chat.uiShellOnly':'仅 UI 外壳','chat.aiNotConnected':'AI Universe Layer 执行尚未连接','chat.channelNotConnected':'此频道后端尚未连接','chat.preview':'预览','chat.inquiry':'咨询','chat.refresh':'刷新','chat.newTicket':'新工单','chat.loadTicketsFailed':'无法加载工单','chat.status':'状态','chat.assignee':'负责人','chat.unassigned':'未分配','chat.priority':'优先级','chat.cancel':'取消','chat.createTicket':'创建工单','chat.official':'官方','chat.announcements':'公告','chat.schoolAuthorizedNotices':'学校授权的员工账号通知','chat.noOfficialAnnouncements':'暂无官方公告','chat.newVerifiedNotices':'新的已验证通知将在此显示','chat.loadAnnouncementsFailed':'无法加载公告','chat.chooseOfficialNotice':'选择官方通知','chat.selectAnnouncementToRead':'选择要阅读的公告','chat.selectAnnouncement':'选择公告','chat.chooseTeacher':'选择教师','chat.startPrivateConversation':'开始私人一对一会话','chat.unableLoadDirect':'无法加载私信','chat.privateOneToOne':'私人一对一','chat.selectTicketDots':'选择工单…','chat.noTicketsYet':'暂无工单'
    }
  };
  Object.keys(localizedUi).forEach(code=>Object.assign(chat[code],localizedUi[code]));


  const micro={
    en:{'chat.privateLabel':'PRIVATE','chat.noActiveTeacher':'No active teacher found.','chat.ticketCreateFailed':'Ticket could not be created.','chat.studentLabel':'Student','chat.details':'Details','chat.ph':'Write a message...','chat.selectTicket':'Select a ticket','chat.unableLoadConversation':'Unable to load conversation.'},
    my:{'chat.privateLabel':'ကိုယ်ပိုင်','chat.noActiveTeacher':'လက်ရှိဆရာ/ဆရာမ မတွေ့ပါ။','chat.ticketCreateFailed':'လက်မှတ် ဖန်တီး၍မရပါ။','chat.studentLabel':'ကျောင်းသား','chat.details':'အသေးစိတ်','chat.ph':'မက်ဆေ့ချ် ရေးပါ...','chat.selectTicket':'လက်မှတ် ရွေးပါ','chat.unableLoadConversation':'စကားပြောခန်းကို ဖွင့်၍မရပါ။'},
    th:{'chat.privateLabel':'ส่วนตัว','chat.noActiveTeacher':'ไม่พบครูที่ใช้งานอยู่','chat.ticketCreateFailed':'ไม่สามารถสร้างตั๋วได้','chat.studentLabel':'นักเรียน','chat.details':'รายละเอียด','chat.ph':'เขียนข้อความ...','chat.selectTicket':'เลือกตั๋ว','chat.unableLoadConversation':'ไม่สามารถโหลดการสนทนาได้'},
    jp:{'chat.privateLabel':'非公開','chat.noActiveTeacher':'有効な教員が見つかりません','chat.ticketCreateFailed':'チケットを作成できませんでした','chat.studentLabel':'生徒','chat.details':'詳細','chat.ph':'メッセージを書く…','chat.selectTicket':'チケットを選択','chat.unableLoadConversation':'会話を読み込めません'},
    ms:{'chat.privateLabel':'PERIBADI','chat.noActiveTeacher':'Tiada guru aktif ditemui.','chat.ticketCreateFailed':'Tiket tidak dapat dicipta.','chat.studentLabel':'Murid','chat.details':'Butiran','chat.ph':'Tulis mesej...','chat.selectTicket':'Pilih tiket','chat.unableLoadConversation':'Perbualan tidak dapat dimuatkan.'},
    km:{'chat.privateLabel':'ឯកជន','chat.noActiveTeacher':'រកមិនឃើញគ្រូសកម្មទេ។','chat.ticketCreateFailed':'មិនអាចបង្កើតសំបុត្របានទេ។','chat.studentLabel':'សិស្ស','chat.details':'ព័ត៌មានលម្អិត','chat.ph':'សរសេរសារ...','chat.selectTicket':'ជ្រើសរើសសំបុត្រ','chat.unableLoadConversation':'មិនអាចផ្ទុកការសន្ទនាបានទេ'},
    zh:{'chat.privateLabel':'私密','chat.noActiveTeacher':'未找到活跃教师。','chat.ticketCreateFailed':'无法创建工单。','chat.studentLabel':'学生','chat.details':'详情','chat.ph':'输入消息…','chat.selectTicket':'选择工单','chat.unableLoadConversation':'无法加载会话。'}
  };
  Object.keys(micro).forEach(code=>Object.assign(chat[code],micro[code]));


  const uiFix={
    en:{'chat.noGradesAvailable':'No grades available','chat.newDepartment':'New department','chat.closeDepartment':'Close department form','chat.departmentCode':'Department code','chat.departmentName':'Department name','chat.createDepartment':'Create department','chat.departmentCreated':'Department created','chat.departmentCreateFailed':'Department could not be created.','chat.departmentNameRequired':'Department name is required.','chat.departmentCodeRequired':'Department code is required.'},
    my:{'chat.noGradesAvailable':'အတန်း မရှိသေးပါ','chat.newDepartment':'ဌာနအသစ်','chat.closeDepartment':'ဌာနဖောင် ပိတ်ရန်','chat.departmentCode':'ဌာနကုဒ်','chat.departmentName':'ဌာနအမည်','chat.createDepartment':'ဌာနဖန်တီးရန်','chat.departmentCreated':'ဌာန ဖန်တီးပြီးပါပြီ','chat.departmentCreateFailed':'ဌာန ဖန်တီး၍မရပါ။','chat.departmentNameRequired':'ဌာနအမည် လိုအပ်ပါသည်။','chat.departmentCodeRequired':'ဌာနကုဒ် လိုအပ်ပါသည်။'},
    th:{'chat.noGradesAvailable':'ไม่มีเกรดที่พร้อมใช้งาน','chat.newDepartment':'แผนกใหม่','chat.closeDepartment':'ปิดแบบฟอร์มแผนก','chat.departmentCode':'รหัสแผนก','chat.departmentName':'ชื่อแผนก','chat.createDepartment':'สร้างแผนก','chat.departmentCreated':'สร้างแผนกแล้ว','chat.departmentCreateFailed':'ไม่สามารถสร้างแผนกได้','chat.departmentNameRequired':'ต้องระบุชื่อแผนก','chat.departmentCodeRequired':'ต้องระบุรหัสแผนก'},
    jp:{'chat.noGradesAvailable':'利用可能な学年はありません','chat.newDepartment':'新しい部署','chat.closeDepartment':'部署フォームを閉じる','chat.departmentCode':'部署コード','chat.departmentName':'部署名','chat.createDepartment':'部署を作成','chat.departmentCreated':'部署を作成しました','chat.departmentCreateFailed':'部署を作成できませんでした','chat.departmentNameRequired':'部署名は必須です','chat.departmentCodeRequired':'部署コードは必須です'},
    ms:{'chat.noGradesAvailable':'Tiada tahun tersedia','chat.newDepartment':'Jabatan baharu','chat.closeDepartment':'Tutup borang jabatan','chat.departmentCode':'Kod jabatan','chat.departmentName':'Nama jabatan','chat.createDepartment':'Cipta jabatan','chat.departmentCreated':'Jabatan berjaya dicipta','chat.departmentCreateFailed':'Jabatan tidak dapat dicipta.','chat.departmentNameRequired':'Nama jabatan diperlukan.','chat.departmentCodeRequired':'Kod jabatan diperlukan.'},
    km:{'chat.noGradesAvailable':'គ្មានថ្នាក់ដែលអាចប្រើបាន','chat.newDepartment':'នាយកដ្ឋានថ្មី','chat.closeDepartment':'បិទទម្រង់នាយកដ្ឋាន','chat.departmentCode':'កូដនាយកដ្ឋាន','chat.departmentName':'ឈ្មោះនាយកដ្ឋាន','chat.createDepartment':'បង្កើតនាយកដ្ឋាន','chat.departmentCreated':'បានបង្កើតនាយកដ្ឋាន','chat.departmentCreateFailed':'មិនអាចបង្កើតនាយកដ្ឋានបានទេ។','chat.departmentNameRequired':'ត្រូវការឈ្មោះនាយកដ្ឋាន។','chat.departmentCodeRequired':'ត្រូវការកូដនាយកដ្ឋាន។'},
    zh:{'chat.noGradesAvailable':'暂无可用年级','chat.newDepartment':'新部门','chat.closeDepartment':'关闭部门表单','chat.departmentCode':'部门代码','chat.departmentName':'部门名称','chat.createDepartment':'创建部门','chat.departmentCreated':'部门已创建','chat.departmentCreateFailed':'无法创建部门','chat.departmentNameRequired':'部门名称为必填项','chat.departmentCodeRequired':'部门代码为必填项'}
  };
  Object.keys(uiFix).forEach(code=>Object.assign(chat[code],uiFix[code]));

  const auditFix={
    en:{'chat.officialNotice':'Official notice','chat.unknownStaff':'Unknown staff'},
    my:{'chat.officialNotice':'တရားဝင် အသိပေးချက်','chat.unknownStaff':'မသိရသေးသော ဝန်ထမ်း'},
    th:{'chat.officialNotice':'ประกาศอย่างเป็นทางการ','chat.unknownStaff':'ไม่ทราบชื่อพนักงาน'},
    jp:{'chat.officialNotice':'公式通知','chat.unknownStaff':'不明なスタッフ'},
    ms:{'chat.officialNotice':'Notis rasmi','chat.unknownStaff':'Staf tidak dikenali'},
    km:{'chat.officialNotice':'សេចក្តីជូនដំណឹងផ្លូវការ','chat.unknownStaff':'បុគ្គលិកមិនស្គាល់'},
    zh:{'chat.officialNotice':'官方通知','chat.unknownStaff':'未知员工'}
  };
  Object.keys(auditFix).forEach(code=>Object.assign(chat[code],auditFix[code]));

  // Burmese copy for the official-announcement composer; prevents raw i18n keys in Myanmar locale.
  Object.assign(my, {
    'chat.reason':'အကြောင်းပြချက်',
    'chat.officialCommunication':'ကျောင်း၏ တရားဝင်ဆက်သွယ်ရေး',
    'chat.writeOfficialMessage':'တရားဝင်မက်ဆေ့ချ် ရေးပါ…',
    'chat.noVerifiedRecipient':'အတည်ပြုထားသော လက်ခံသူ မရှိပါ',
    'chat.noVerifiedSameSchoolRecipient':'ဆာဗာအတည်ပြုချက်အရ တူညီသောကျောင်းမှ အသုံးပြုနေသော လက်ခံသူ မတွေ့ပါ။',
    'chat.messageBody':'မက်ဆေ့ချ်အကြောင်းအရာ',
    'chat.systemGeneratedOfficialMessage':'စနစ်မှ ဖန်တီးထားသော တရားဝင်မက်ဆေ့ချ်',
    'chat.adminTools':'စီမံခန့်ခွဲသူ ကိရိယာများ',
    'chat.officialMessage':'တရားဝင်မက်ဆေ့ချ်',
    'chat.officialMessageHint':'ကျောင်းမှ အတည်ပြုထားသော လက်ခံသူများထံ တရားဝင်စာပို့ပါ။',
    'chat.serverVerified':'ဆာဗာမှ အတည်ပြုထားသည်',
    'chat.recipientType':'လက်ခံသူအမျိုးအစား',
    'chat.allStaff':'ဝန်ထမ်းအားလုံး',
    'chat.grade':'အတန်း',
    'chat.loadingGrades':'အတန်းများ ဖွင့်နေသည်…',
    'chat.noGradesAvailable':'ရရှိနိုင်သော အတန်းမရှိပါ',
    'chat.individualTeacher':'ဆရာတစ်ဦးချင်း',
    'chat.messageType':'မက်ဆေ့ချ်အမျိုးအစား',
    'chat.announcement':'ကြေညာချက်',
    'chat.officialTask':'တရားဝင်တာဝန်',
    'chat.staffNotice':'ဝန်ထမ်းအသိပေးချက်',
    'chat.checkingRecipients':'လက်ခံသူများကို စစ်ဆေးနေသည်…',
    'chat.refreshRecipients':'လက်ခံသူများ ပြန်စစ်ရန်',
    'chat.sendOfficialMessage':'တရားဝင်မက်ဆေ့ချ် ပို့ရန်',
    'chat.reasonBodyRequired':'အကြောင်းပြချက်နှင့် မက်ဆေ့ချ်အကြောင်းအရာ ဖြည့်ပါ။',
    'chat.noVerifiedRecipient':'အတည်ပြုထားသော လက်ခံသူ မရှိပါ',
    'chat.noVerifiedSameSchoolRecipient':'ဆာဗာအတည်ပြုချက်အရ တူညီသောကျောင်းမှ အသုံးပြုနေသော လက်ခံသူ မတွေ့ပါ။',
    'chat.officialAnnouncement':'တရားဝင်ကြေညာချက်',
    'chat.officialAnnouncements':'တရားဝင်ကြေညာချက်များ',
    'chat.newOfficialMessage':'တရားဝင်မက်ဆေ့ချ်အသစ်',
    'chat.closeOfficialMessage':'တရားဝင်မက်ဆေ့ချ်ဖောင် ပိတ်ရန်',
    'chat.backToAnnouncements':'ကြေညာချက်များသို့ ပြန်ရန်'
  });

  const setupHints = {
    en: {'chat.setupWhy':'Why is this unavailable?','chat.setupDepartmentSteps':'Create at least one department first, then assign active staff to it. The department chat list will appear when access is available.','chat.setupCreateDepartment':'Create department','chat.setupGradeSteps':'Make sure the school has active students in a grade and active teachers assigned to that grade. Only verified grades are listed.','chat.setupGradePath':'Check Students → Grade/Class and Teachers → Teacher Assignment.'},
    my: {'chat.setupWhy':'ဘာကြောင့် အသုံးမပြုနိုင်သေးတာလဲ။','chat.setupDepartmentSteps':'ဌာနတစ်ခု အရင်ဖန်တီးပြီး ဝန်ထမ်းများကို ထိုဌာနသို့ သတ်မှတ်ပေးပါ။ ဝင်ခွင့်ရှိသည့်အခါ ဌာနစကားပြောစာရင်း ပေါ်လာပါမည်။','chat.setupCreateDepartment':'ဌာနဖန်တီးရန်','chat.setupGradeSteps':'ကျောင်းတွင် အသုံးပြုနေသော ကျောင်းသားများရှိသည့် အတန်းနှင့် ထိုအတန်းသို့ သတ်မှတ်ထားသော အသုံးပြုနေသည့် ဆရာ/ဆရာမများ ရှိကြောင်း စစ်ဆေးပါ။ အတည်ပြုထားသော အတန်းများသာ ပေါ်ပါမည်။','chat.setupGradePath':'ကျောင်းသားများ → အတန်း/အခန်း နှင့် ဆရာ/ဆရာမများ → Teacher Assignment ကို စစ်ဆေးပါ။'},
    th: {'chat.setupWhy':'เหตุใดจึงยังใช้งานไม่ได้?','chat.setupDepartmentSteps':'สร้างแผนกอย่างน้อยหนึ่งแผนกก่อน แล้วกำหนดบุคลากรที่ใช้งานอยู่ให้แผนกนั้น','chat.setupCreateDepartment':'สร้างแผนก','chat.setupGradeSteps':'ตรวจสอบว่ามีนักเรียนที่ใช้งานอยู่ในระดับชั้น และมีครูที่ใช้งานอยู่ได้รับมอบหมายให้ระดับชั้นนั้น ระบบจะแสดงเฉพาะระดับชั้นที่ตรวจสอบแล้ว','chat.setupGradePath':'ตรวจสอบ Students → Grade/Class และ Teachers → Teacher Assignment'},
    jp: {'chat.setupWhy':'利用できない理由','chat.setupDepartmentSteps':'先に部署を作成し、有効な職員をその部署に割り当ててください。アクセス権がある場合に部署チャットが表示されます。','chat.setupCreateDepartment':'部署を作成','chat.setupGradeSteps':'在籍中の生徒がいる学年と、その学年に割り当てられた有効な教師がいることを確認してください。確認済みの学年のみ表示されます。','chat.setupGradePath':'Students → Grade/Class と Teachers → Teacher Assignment を確認してください。'},
    ms: {'chat.setupWhy':'Mengapa belum tersedia?','chat.setupDepartmentSteps':'Cipta sekurang-kurangnya satu jabatan dahulu, kemudian tetapkan kakitangan aktif kepada jabatan itu.','chat.setupCreateDepartment':'Cipta jabatan','chat.setupGradeSteps':'Pastikan terdapat pelajar aktif dalam gred dan guru aktif yang ditugaskan kepada gred tersebut. Hanya gred yang disahkan dipaparkan.','chat.setupGradePath':'Semak Students → Grade/Class dan Teachers → Teacher Assignment.'},
    km: {'chat.setupWhy':'ហេតុអ្វីមិនទាន់អាចប្រើបាន?','chat.setupDepartmentSteps':'បង្កើតនាយកដ្ឋានយ៉ាងហោចណាស់មួយសិន ហើយចាត់តាំងបុគ្គលិកសកម្មទៅនាយកដ្ឋាននោះ។','chat.setupCreateDepartment':'បង្កើតនាយកដ្ឋាន','chat.setupGradeSteps':'ពិនិត្យថាមានសិស្សសកម្មក្នុងថ្នាក់ និងគ្រូសកម្មដែលបានចាត់តាំងទៅថ្នាក់នោះ។ បង្ហាញតែថ្នាក់ដែលបានផ្ទៀងផ្ទាត់ប៉ុណ្ណោះ។','chat.setupGradePath':'ពិនិត្យ Students → Grade/Class និង Teachers → Teacher Assignment។'},
    zh: {'chat.setupWhy':'为什么暂时无法使用？','chat.setupDepartmentSteps':'请先创建至少一个部门，再将在职员工分配到该部门。有访问权限后，部门聊天列表才会显示。','chat.setupCreateDepartment':'创建部门','chat.setupGradeSteps':'请确认该年级有在读学生，并且有已分配到该年级的在职教师。系统只显示已验证的年级。','chat.setupGradePath':'检查 Students → Grade/Class 和 Teachers → Teacher Assignment。'}
  };
  Object.keys(setupHints).forEach(code => Object.assign(chat[code], setupHints[code]));

  // Keep these runtime labels explicitly translated in every supported locale.
  // This avoids English fallbacks when the chat workspace renders dynamically.
  const verifiedRecipientLocaleFix = {
    en: {'chat.schoolChat':'School Chat','chat.oneVerifiedRecipient':'One verified recipient'},
    my: {'chat.schoolChat':'ကျောင်းစကားပြော','chat.oneVerifiedRecipient':'အတည်ပြုထားသော လက်ခံသူတစ်ဦး'},
    th: {'chat.schoolChat':'แชตโรงเรียน','chat.oneVerifiedRecipient':'ผู้รับที่ยืนยันแล้ว 1 คน'},
    jp: {'chat.schoolChat':'スクールチャット','chat.oneVerifiedRecipient':'確認済み受信者 1 人'},
    ms: {'chat.schoolChat':'Sembang Sekolah','chat.oneVerifiedRecipient':'1 penerima disahkan'},
    km: {'chat.schoolChat':'ការជជែករបស់សាលា','chat.oneVerifiedRecipient':'អ្នកទទួលដែលបានផ្ទៀងផ្ទាត់ ១ នាក់'},
    zh: {'chat.schoolChat':'学校聊天','chat.oneVerifiedRecipient':'1 位已验证收件人'}
  };
  Object.keys(verifiedRecipientLocaleFix).forEach(code =>
    Object.assign(chat[code], verifiedRecipientLocaleFix[code])
  );

  // The group member UI is a checkbox picker, not a comma-separated ID input.
  // Keep its instruction explicit and translated in every supported locale.
  const groupMemberPickerLocaleFix = {
    en: { 'chat.groupMembersPrompt': 'Select staff members to add to the group.' },
    my: { 'chat.groupMembersPrompt': 'အဖွဲ့ထဲသို့ ထည့်မည့် ဝန်ထမ်းများကို ရွေးပါ။' },
    th: { 'chat.groupMembersPrompt': 'เลือกบุคลากรที่จะเพิ่มเข้ากลุ่ม' },
    jp: { 'chat.groupMembersPrompt': 'グループに追加する職員を選択してください。' },
    ms: { 'chat.groupMembersPrompt': 'Pilih kakitangan untuk ditambahkan ke kumpulan.' },
    km: { 'chat.groupMembersPrompt': 'ជ្រើសរើសបុគ្គលិកដែលត្រូវបន្ថែមទៅក្នុងក្រុម។' },
    zh: { 'chat.groupMembersPrompt': '选择要添加到群组的教职员工。' }
  };
  Object.keys(groupMemberPickerLocaleFix).forEach(code =>
    Object.assign(chat[code], groupMemberPickerLocaleFix[code])
  );

  const maps={en:'I18N_EN',my:'I18N_MY',th:'I18N_TH',jp:'I18N_JP',ms:'I18N_MS',km:'I18N_KM',zh:'I18N_ZH'};
  Object.keys(maps).forEach(code=>{ window[maps[code]]=Object.assign({},window[maps[code]]||{},code==='en'?en:code==='my'?my:chat[code]); });
})();