/* SCMS v12 — Department Chat workspace */
'use strict';
let _departmentRows=[],_departmentId=null,_departmentMessages=[],_departmentPollTimer=null;
function _renderDepartmentWorkspace(targetId='smartChatModeBody'){return _chatChannelBack('School Chat') + `
<div class="smart-chat-list-title">Department & Grade <span style="float:right"><button type="button" class="btn-pill-action" disabled>Department</button> <button type="button" class="btn-pill-action" onclick="_showGradeWorkspace()">Grade</button></span></div>
<div class="smart-chat-direct-shell smart-chat-department-shell${_departmentId ? " has-selection" : ""}">
<aside class="smart-chat-direct-list"><div class="smart-chat-direct-list-head"><div><div class="smart-chat-kicker">DEPARTMENT CHAT</div><strong>Departments</strong></div><div class="smart-chat-list-actions"><button type="button" class="smart-chat-refresh-btn" onclick="_loadDepartmentWorkspace()" title=${t('chat.department.refresh')}>↻</button></div></div>
<div class="smart-chat-directory-title">Only explicitly assigned active staff can enter a department.</div><div id="departmentList" class="smart-chat-conversation-list"></div></aside>
<section class="smart-chat-direct-conversation" style="display:flex"><div id="departmentHead" class="smart-chat-conversation-head"><div><strong>Select a department</strong><small>School-isolated staff conversation.</small></div><span class="smart-chat-verified-pill">Authorized members</span></div>
<div id="departmentMessageStream" class="chat-stream smart-chat-direct-stream"><div class="chat-empty"><div class="chat-empty-icon">📚</div><div class="chat-empty-title">Department Chat</div><div class="chat-empty-sub">Select a department you belong to.</div></div></div>
<form class="chat-composer smart-chat-direct-composer" onsubmit="return _sendDepartmentFromComposer(event)"><textarea id="departmentChatInput" placeholder=${t('chat.department.select')} rows="1" disabled></textarea><button type="submit" class="chat-send-btn" id="departmentSendBtn" disabled>➤</button></form></section></div>`;}
function _renderDepartmentList(){const box=document.getElementById('departmentList');if(!box)return;box.innerHTML=_departmentRows.length?_departmentRows.map(d=>`<button data-testid="department-row-${Number(d.id)}" class="smart-chat-channel-card ${Number(d.id)===Number(_departmentId)?'active':''}" onclick="_openDepartmentChat(${Number(d.id)})"><span class="smart-chat-channel-icon">📚</span><span><strong>${esc(d.department_name)}</strong><small>${esc(d.department_code)}</small></span><b>›</b></button>`).join(''):'<div class="smart-chat-list-empty-card"><div class="icon">📚</div><strong>No department access yet</strong><small>Your administrator must assign you to an active department before it can appear here.</small></div>';}
async function _loadDepartmentWorkspace(){try{const b=document.getElementById('departmentList');if(b)b.innerHTML=skeletonCards(2);_departmentRows=await API.getDepartmentChats();_renderDepartmentList();if(_departmentId&&_departmentRows.some(d=>Number(d.id)===Number(_departmentId)))await _openDepartmentChat(_departmentId);}catch(e){const b=document.getElementById('departmentList');if(b)b.innerHTML='<div class="chat-error"><div>📚</div><div>Unable to load departments.</div><button type="button" class="btn-secondary" onclick="_loadDepartmentWorkspace()">Retry</button></div>';}}
function _startDepartmentPolling(){if(_departmentPollTimer)clearInterval(_departmentPollTimer);_departmentPollTimer=setInterval(()=>{if(document.getElementById('departmentMessageStream')&&_departmentId)_openDepartmentChat(_departmentId,true).catch(()=>{});},5000);}
async function _openDepartmentChat(id,silent=false){const nextId=Number(id);if(!Number.isFinite(nextId)||nextId<=0)return;const r=await API.openDepartmentChat(nextId);if(!r?.ok){if(!silent)showToast('Department access is not authorized.');return;} _departmentId=nextId;_setDepartmentMobileView(true);_renderDepartmentList();const h=document.getElementById('departmentHead'),s=document.getElementById('departmentMessageStream'),i=document.getElementById('departmentChatInput'),b=document.getElementById('departmentSendBtn');if(h)h.innerHTML=`<div class="smart-chat-direct-peer"><button type="button" class="smart-chat-mobile-back" onclick="_clearDepartmentSelection()" aria-label="Back to departments">‹</button><div><strong>${esc(r.department?.department_name||'Department')}</strong><small>${esc(r.department?.department_code||'')} · Staff-only conversation</small></div></div><span class="smart-chat-verified-pill">School isolated</span>`;_departmentMessages=Array.isArray(r.rows)?r.rows:[];if(s){const rows=[..._departmentMessages].sort((a,b)=>new Date(a.created_at)-new Date(b.created_at));s.innerHTML=rows.length?rows.map(m=>{const mine=m.sender_teacher_id===window.APP?.teacher_id;const when=m.created_at?new Date(m.created_at).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'}):'';return `<div class="chat-bubble-row ${mine?'mine':'theirs'}">${mine?'':`<div class="chat-bubble-avatar">${esc((m.sender_teacher_name||'?')[0])}</div>`}<div class="chat-bubble"><div class="chat-bubble-author">${mine?'You':esc(m.sender_teacher_name||'Staff')}</div><div class="chat-bubble-text">${esc(m.body||'')}</div><div class="chat-bubble-time">${esc(when)}</div></div></div>`;}).join(''):'<div class="chat-empty"><div class="chat-empty-icon">📚</div><div class="chat-empty-title">No messages yet</div><div class="chat-empty-sub">Start the department conversation.</div></div>';requestAnimationFrame(()=>{s.scrollTop=s.scrollHeight;});}if(i){i.disabled=false;i.placeholder=${t('chat.department.placeholder')};}if(b)b.disabled=false;await API.markDepartmentRead(_departmentId);if(!silent)_startDepartmentPolling();}
window._sendDepartmentFromComposer=async function(ev){ev?.preventDefault?.();const i=document.getElementById('departmentChatInput'),b=document.getElementById('departmentSendBtn'),body=i?.value.trim();if(!_departmentId||!body||!b)return false;b.disabled=true;i.disabled=true;try{const r=await API.sendDepartmentMessage(_departmentId,body);if(!r?.ok)throw new Error(r?.error||${t('chat.sendFailed')});i.value='';i.style.height='auto';await _openDepartmentChat(_departmentId);}catch(e){showToast('Department message could not be sent.');}finally{b.disabled=false;i.disabled=false;i.focus();}return false;};
window._setDepartmentMobileView=function(selected){const shell=document.querySelector('.smart-chat-department-shell');if(shell)shell.classList.toggle('has-selection',!!selected);};
window._clearDepartmentSelection=function(){if(_departmentPollTimer)clearInterval(_departmentPollTimer);_departmentPollTimer=null;_departmentId=null;_departmentMessages=[];_setDepartmentMobileView(false);_renderChatMode();};
window._loadDepartmentWorkspace=_loadDepartmentWorkspace;window._openDepartmentChat=_openDepartmentChat;
