'use strict';
let _chatGroups=[],_chatGroupId=null,_chatGroupCurrent=null;
function _renderGroupWorkspace(){
 const root=document.getElementById('smartChatModeBody'); if(!root)return;
 root.innerHTML=_chatChannelBack('School Chat') + `<div class="smart-chat-direct-shell smart-chat-group-shell${_chatGroupId ? ' has-selection' : ''}"><aside class="smart-chat-direct-list"><div class="smart-chat-direct-list-head"><div><div class="smart-chat-kicker">${t('chat.groupChat')}</div><strong>${t('chat.workspace.groups')}</strong></div><button type="button" class="smart-chat-refresh-btn" onclick="_loadChatGroups(false)" title="${t('chat.groups.refresh')}">↻</button></div><button class="smart-chat-channel-card" onclick="_newChatGroup()"><span class="smart-chat-channel-icon">＋</span><span><strong>${t('chat.newGroup')}</strong><small>${t('chat.newGroupDescription')}</small></span><b>›</b></button><div id="chatGroupList"></div></aside><section class="smart-chat-direct-conversation" id="chatGroupConversation"><div class="chat-empty"><div class="chat-empty-icon">🗂️</div><div class="chat-empty-title">${t('chat.selectGroup')}</div><div class="chat-empty-sub">${t('chat.groupSchoolIsolated')}</div></div></section></div>`;
 _loadChatGroups();
}
async function _loadChatGroups(autoOpen=true){
 try{const box=document.getElementById('chatGroupList');if(box)box.innerHTML=skeletonCards(2);_chatGroups=await API.getChatGroups();if(box)box.innerHTML=_chatGroups.length?_chatGroups.map(g=>`<button class="smart-chat-channel-card ${Number(g.id)===Number(_chatGroupId)?'active':''}" onclick="_openChatGroup(${Number(g.id)})"><span class="smart-chat-channel-icon">${g.group_type==='EVENT'?'📅':'📁'}</span><span><strong>${esc(g.name)}</strong><small>${esc(g.group_type)} · ${esc(g.status)}${Number(g.unread_count)>0?' · '+esc(g.unread_count)+' '+t('chat.unread'):''}</small></span><b>›</b></button>`).join(''):`<div class="smart-chat-list-empty-card"><div class="icon">🗂️</div><strong>${t('chat.noGroups')}</strong><small>${t('chat.noGroupsDescription')}</small></div>`;if(autoOpen&&_chatGroupId)await _openChatGroup(_chatGroupId);}catch(e){const box=document.getElementById('chatGroupList');if(box)box.innerHTML=`<div class="chat-error"><div>🗂️</div><div>${t('chat.loadGroupsFailed')}</div><button type="button" class="btn-secondary" onclick="_loadChatGroups(false)">${t('chat.retry')}</button></div>`;}}
window._newChatGroup=async function(){
 const name=prompt(t('chat.groupNamePrompt'));if(!name?.trim())return;
 const type=(prompt(t('chat.groupTypePrompt'),'PROJECT')||'PROJECT').toUpperCase();
 if(!['PROJECT','EVENT'].includes(type)){showToast(t('chat.invalidGroupType'));return;}
 const desc=prompt(t('chat.groupDescriptionPrompt'))||'';
 let staff=[];try{staff=await API.getDirectStaffDirectory();}catch(e){staff=[];}
 const choices=Array.isArray(staff)?staff.filter(x=>x?.teacher_id&&x.teacher_id!==window.APP?.teacher_id&&x.status!=='inactive'):[];
 const roster=choices.map(x=>`${x.teacher_id} — ${x.teacher_name||t('chat.staff')}`).join('\n');
 const rawMembers=choices.length?prompt(t('chat.groupMembersPrompt')+'\n\n'+roster,''):'';
 const memberIds=(rawMembers||'').split(',').map(x=>x.trim()).filter(Boolean);
 const startsRaw=prompt(t('chat.startDatePrompt'))||'';
 const endsRaw=prompt(t('chat.endDatePrompt'))||'';
 const startsAt=startsRaw.trim()||null,endsAt=endsRaw.trim()||null;
 _createChatGroup(name.trim(),desc,type,startsAt,endsAt,memberIds);
};
async function _createChatGroup(name,desc,type,startsAt=null,endsAt=null,memberIds=[]){
 try{const r=await API.createChatGroup(name,desc,type,startsAt,endsAt,memberIds);if(!r?.ok)throw new Error(r?.error||t('chat.groups.createFailed'));_chatGroupId=Number(r.group_id);await _loadChatGroups();}catch(e){showToast(t('chat.groupCreateFailed'));}}
window._openChatGroup=async function(id){
 _chatGroupId=Number(id);const root=document.getElementById('chatGroupConversation');if(!root)return;
 root.innerHTML=`<div class="chat-stream" id="chatGroupStream"><div class="chat-empty-sub">${t('chat.loading')}</div></div>`;
 try{const r=await API.openChatGroup(_chatGroupId);if(!r?.ok)throw new Error(r?.error||t('chat.openFailed'));_chatGroupCurrent=r.group;const msgs=Array.isArray(r.messages)?r.messages:[];root.innerHTML=`<div class="smart-chat-conversation-head"><div class="smart-chat-direct-peer"><button type="button" class="smart-chat-mobile-back" onclick="_clearChatGroupSelection()" aria-label="${t('chat.backToGroups')}">‹</button><div><strong>${esc(r.group.name)}</strong><small>${esc(r.group.group_type)} · ${esc(r.group.status)}</small></div><span class="smart-chat-verified-pill">${t('chat.schoolMembersOnly')}</span></div><div class="chat-stream" id="chatGroupStream">${msgs.length?msgs.map(m=>`<div class="chat-bubble-row ${m.sender_teacher_id===window.APP?.teacher_id?'mine':'theirs'}"><div class="chat-bubble">${m.sender_teacher_id===window.APP?.teacher_id?'':`<div class="chat-bubble-author">${esc(m.sender_teacher_name)}</div>`}<div class="chat-bubble-text">${esc(m.body)}</div><div class="chat-bubble-time">${esc(new Date(m.created_at).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'}))}</div></div></div>`).join(''):`<div class="chat-empty"><div class="chat-empty-icon">🗂️</div><div class="chat-empty-title">${t('chat.noMessages')}</div><div class="chat-empty-sub">${t('chat.startGroup')}</div></div>`}</div><form class="chat-composer" onsubmit="return _sendChatGroup(event)"><textarea id="chatGroupInput" rows="1" placeholder="${t('chat.groups.placeholder')}" oninput="_autoGrowChatInput(this)"></textarea><button class="chat-send-btn" type="submit">${_chatIcon('send')}</button></form>`;await API.markChatGroupRead(_chatGroupId);const g=_chatGroups.find(x=>Number(x.id)===_chatGroupId);if(g)g.unread_count=0;await _loadChatGroups(false); }catch(e){root.innerHTML=`<div class="chat-error"><div>🗂️</div><div>${t('chat.openGroupFailed')}</div><button type="button" class="btn-secondary" onclick="_openChatGroup(_chatGroupId)">${t('chat.retry')}</button></div>`;}}
window._setChatGroupMobileView=function(selected){const shell=document.querySelector('.smart-chat-group-shell');if(shell)shell.classList.toggle('has-selection',!!selected);};
window._clearChatGroupSelection=function(){_chatGroupId=null;_chatGroupCurrent=null;_setChatGroupMobileView(false);_renderGroupWorkspace();};
window._sendChatGroup=async function(ev){ev?.preventDefault?.();const input=document.getElementById('chatGroupInput'),v=input?.value.trim();if(!_chatGroupId||!v)return false;try{const r=await API.sendChatGroupMessage(_chatGroupId,v);if(!r?.ok)throw new Error(r?.error||t('chat.sendFailed'));input.value='';await _openChatGroup(_chatGroupId);}catch(e){showToast(t('chat.messageSendFailed'));}return false;};
window.renderChatGroups=_renderGroupWorkspace;