'use strict';
let _announcementRows=[];
function _renderAnnouncementsWorkspace(){
 const root=document.getElementById('smartChatModeBody');if(!root)return;
 root.innerHTML=\`<div class="smart-chat-school-grid"><aside class="smart-chat-channel-list"><div class="smart-chat-list-title">Official Announcements</div><div class="smart-chat-directory-title">Official messages are generated by authorized school staff.</div><div id="announcementList" class="smart-chat-conversation-list"></div></aside><section class="smart-chat-conversation" id="announcementConversation"><div class="chat-empty"><div class="chat-empty-icon">📢</div><div class="chat-empty-title">Official Announcements</div><div class="chat-empty-sub">Select an announcement to read it.</div></div></section></div>\`;
 _loadAnnouncements();
}
async function _loadAnnouncements(){
 try{_announcementRows=await API.getStaffAnnouncements();const box=document.getElementById('announcementList');if(box)box.innerHTML=_announcementRows.length?_announcementRows.map(a=>\`<button class="smart-chat-channel-card" onclick="_openAnnouncement(\${Number(a.id)})"><span class="smart-chat-channel-icon">📢</span><span><strong>\${esc(a.message_type||'Announcement')}</strong><small>\${esc(a.reason||'Official notice')} · \${a.is_read?'Read':'Unread'}</small></span><b>›</b></button>\`).join(''):'<div class="chat-empty-sub">No official announcements.</div>';}catch(e){const box=document.getElementById('announcementList');if(box)box.innerHTML='<div class="chat-error">Unable to load announcements.</div>';}}
window._openAnnouncement=async function(id){
 const a=_announcementRows.find(x=>Number(x.id)===Number(id));const root=document.getElementById('announcementConversation');if(!a||!root)return;
 root.innerHTML=\`<div class="smart-chat-conversation-head"><div><strong>Official \${esc(a.message_type||'Announcement')}</strong><small>\${esc(a.created_at||'')}</small></div><span class="smart-chat-verified-pill">Official</span></div><div class="chat-stream"><div class="smart-chat-official-preview"><div class="smart-chat-preview-label">SYSTEM-GENERATED HEADER</div><div class="smart-chat-preview-header">Official School Announcement</div><div class="smart-chat-preview-reason"><strong>Reason</strong><span>\${esc(a.reason||'')}</span></div><div class="smart-chat-preview-body">\${esc(a.body||'').replace(/\\n/g,'<br>')}</div></div></div>\`;
 try{await API.markStaffAnnouncementRead(id);a.is_read=true;await _loadAnnouncements();}catch(e){}
};
window._renderAnnouncementsWorkspace=_renderAnnouncementsWorkspace;
