// Simplified Chinese translation batch D — staging only; not registered.
window.I18N_ZH_BATCH_D={
'settings.title':'⚙️ 设置','settings.version':'版本','settings.platform':'平台','settings.school':'学校','settings.teacher':'教师','settings.role':'角色','settings.login':'登录','settings.telegram':'Telegram','settings.connected':'🟢 已连接','settings.notConnected':'⚪ 未连接','settings.manageTeachers':'👥 管理教师','settings.connectTelegram':'🔗 连接 Telegram','settings.disconnectTelegram':'🔌 断开 Telegram','settings.changePassword':'🔑 修改我的密码','settings.footerNote':'SCMS 由学校管理员管理。','settings.googleAccount':'Google 账号','settings.webPassword':'网页（密码）',
'tm.title':'👥 管理教师','tm.subtitle':'为教师创建登录账号。','tm.addNew':'+ 添加教师（教师 ID + 密码）','tm.inviteGoogle':'✉️ 通过 Google 邀请（分享代码）','tm.loading':'加载中…','tm.loadFailed':'教师加载失败','tm.none':'暂无教师。','tm.lastLogin':'上次登录：{date}','tm.never':'从未','tm.idCard':'教师 ID 卡','tm.cardLoading':'正在生成安全卡…','tm.cardScan':'扫描二维码开始教师登录','tm.cardPurposeTitle':'此卡用途','tm.cardPurpose':'此卡用于安全登录学校系统。','tm.cardStep1':'扫描此卡上的二维码。','tm.cardStep2':'输入登录名称。','tm.cardStep3':'输入 PIN 登录。','tm.cardSecurity':'请妥善保管此卡和 PIN。不要分享二维码或 PIN。','tm.printCard':'打印卡片','tm.regenerateCard':'重新生成卡片','tm.cardFailed':'无法生成教师 ID 卡','tm.resetPassword':'重置 PIN',
'inv.title':'✉️ 通过 Google 邀请','inv.subtitle':'教师使用自己的 Google 账号登录，并通过此代码加入。','inv.name':'姓名（可选）','inv.namePh':'例如 张丽丽','inv.role':'角色 *','inv.roleTeacher':'教师','inv.roleAdmin':'管理员','inv.generate':'生成代码','inv.generating':'生成中…','inv.codeLabel':'邀请代码','inv.hint':'将此代码发送给教师（有效期 14 天）。教师可在 Google 登录 → “我有邀请代码”中兑换。','inv.pastInvites':'历史邀请','inv.usedBy':'✅ 已被 {id} 使用','inv.expired':'⌛ 已过期','inv.pending':'⏳ 待处理','inv.back':'返回','inv.failed':'无法创建邀请：{err}',
'ct.title':'+ 新建教师','ct.subtitle':'创建登录账号。首次登录时必须修改初始密码。','ct.teacherId':'教师 ID *','ct.teacherIdPh':'例如 T1001','ct.loginName':'登录名称 *','ct.loginNamePh':'例如 teacher1','ct.teacherName':'教师姓名 *','ct.email':'邮箱（可选）','ct.role':'角色 *','ct.roleAdmin':'管理员（可管理其他教师）','ct.startPw':'初始 PIN（至少 6 个字符） *','ct.startPwHint':'请安全地将密码提供给教师。首次登录时需要修改。','ct.create':'创建账号','ct.needFields':'教师 ID、登录名称、教师姓名和 PIN 均为必填项','ct.pwTooShort':'PIN 至少需要 6 个字符','ct.sessionExpired':'管理员会话已过期。请重新登录。','ct.creating':'创建中…','ct.createFailed':'创建失败','ct.created':'✓ 教师账号已创建','ct.connErr':'连接错误',
'rp.prompt':'为 {name}（{id}）重置 PIN。\\n\\n新 PIN（至少 6 个字符）：','rp.sessionExpired':'管理员会话已过期','rp.failed':'重置失败：{err}','rp.done':'✓ {name} 的新密码：{pw}\\n请将其提供给教师。',
'ga.signingIn':'登录中…','ga.loginFailed':'登录失败','ga.connErr':'连接错误 — 请检查网络','ga.welcome':'👋 欢迎','ga.noAccount':'此 Google 账号尚无 SCMS 账号。请选择操作：','ga.startSchool':'创建新学校','ga.startSchoolSub':'您将成为管理员','ga.haveInvite':'我有邀请代码','ga.haveInviteSub':'使用管理员提供的代码加入','ga.back':'← 返回','ga.yourName':'您的姓名','ga.namePh':'例如 Sangfa','ga.schoolName':'学校名称','ga.schoolNamePh':'例如 Vavida ISB','ga.startSchoolBtn':'创建学校','ga.enterSchoolName':'请输入学校名称','ga.inviteCode':'邀请代码','ga.inviteCodePh':'例如 AC3F79','ga.join':'加入','ga.enterInviteCode':'请输入邀请代码','ga.emailSignIn':'📧 使用邮箱登录','ga.emailSignInSub':'输入邮箱地址和密码','ga.email':'邮箱','ga.password':'密码','ga.rememberMe':'记住我','ga.signIn':'登录','ga.noAccountQ':'还没有账号？','ga.signUp':'注册','ga.enterEmailPw':'请输入邮箱和密码','ga.createAccount':'✨ 创建新账号','ga.createAccountSub':'使用您自己的邮箱和密码','ga.atLeast6':'至少 6 个字符','ga.whatToDo':'您想做什么？','ga.chooseToContinue':'请选择一个选项继续','ga.haveAccountQ':'已有账号？','ga.enterName':'请输入姓名','ga.enterEmail':'请输入邮箱','ga.pwAtLeast6':'密码至少需要 6 个字符','ga.chooseSchoolOrInvite':'选择新学校或输入邀请代码','ga.creatingAccount':'正在创建账号…','ga.signupFailed':'注册失败',
'tg.connectTitle':'🔗 连接 Telegram','tg.connectSub':'连接 Telegram，用于家长报告和备用登录。','tg.waitingStart':'打开 Telegram 机器人并点击 Start…','tg.openTelegram':'打开 Telegram','tg.connectFailed':'无法连接 — 请重试','tg.reopen':'再次打开','tg.waitingTap':'请在 Telegram 中点击 Start… 等待中','tg.timedOut':'已超时 — 请重试','tg.connected':'✓ Telegram 已连接','tg.disconnectTitle':'🔌 断开 Telegram？','tg.disconnectSub':'这将断开用于家长报告和备用登录的 Telegram。','tg.disconnect':'断开连接','tg.disconnected':'Telegram 已断开','ga.showPassword':'显示密码',
'branding.adminOnly':'只有管理员可以修改此项','branding.chooseImage':'📷 选择图片','branding.imageTypes':'请选择 PNG、JPG 或 WebP 图片','branding.imageTooBig':'图片过大（最大 8 MB）','branding.tryAgain':'重试','reg.title':'注册','reg.instructions':'要注册新学校或以教师身份加入，请使用 Telegram 机器人命令：','reg.createSchool':'创建新学校','reg.joinSchool':'加入现有学校','reg.approvedNote':'管理员批准后，您的账号将启用，此仪表板会自动加载。','reg.gotIt':'知道了','enum.roleName.admin':'管理员','enum.roleName.teacher':'教师','enum.roleName.super_admin':'超级管理员',
'help.title':'如何使用 SCMS','help.subtitle':'使用方法 · 快速指南','help.tab.basics':'基础','help.tab.features':'功能','help.tab.admin':'管理员','help.tab.trouble':'故障排除','help.tab.about':'关于',
'help.basics.introTitle':'什么是 SCMS？','help.basics.introBody':'学校班级管理系统 — 通过一个 Telegram 机器人管理整个学校。考勤、作业、每日报告、家长消息，一站式完成。','help.basics.step1Title':'登录','help.basics.step1Body':'点击 Telegram 机器人中的菜单按钮打开应用。系统会自动识别您的账号。','help.basics.step2Title':'底部标签','help.basics.step2Body':'学生 · 考勤 · 每日 · 作业 · 更多 — 点击即可导航。','help.basics.step3Title':'+ 按钮（FAB）','help.basics.step3Body':'右下角的 + 按钮会根据当前页面执行“添加”操作，例如在学生页面添加新学生。','help.basics.step4Title':'刷新','help.basics.step4Body':'点击右上角的 ↻ 按钮获取最新数据。','help.basics.tip':'提示：第一次使用时先添加学生，然后考勤、作业等功能就可以正常使用。',
'help.feat.students.title':'学生','help.feat.students.1':'点击学生卡片 → 查看详情','help.feat.students.2':'✎ 编辑按钮 — 修改姓名、班级、生日、家长邮箱','help.feat.students.3':'添加学生后会显示家长链接 → 发送链接 → Telegram 自动连接','help.feat.students.4':'🎂 表示即将过生日的学生',
'help.feat.attend.title':'考勤','help.feat.attend.1':'日期栏 — 选择要登记的日期','help.feat.attend.2':'每位学生 — 点击 P/A/L/T/S/E/H 代码','help.feat.attend.3':'“全部出勤” — 一键将所有人标记为出勤','help.feat.attend.4':'✏️ 备注 — 添加“原因”说明','help.feat.attend.5':'最后别忘了点击“保存考勤”',
'help.feat.daily.title':'每日报告','help.feat.daily.1':'每位学生 — 记录餐食、情绪、午睡、行为','help.feat.daily.2':'准备发送给家长','help.feat.daily.3':'✎ 编辑，🗑 删除','help.feat.hw.title':'作业','help.feat.hw.1':'添加科目、班级、类型、描述','help.feat.hw.2':'可添加 LB/WB 页码','help.feat.hw.3':'可以设置截止日期','help.feat.hw.4':'✎ 编辑 / 🗑 删除',
'help.feat.msg.title':'家长消息','help.feat.msg.1':'选择整个班级或单个学生','help.feat.msg.2':'输入消息并发送','help.feat.msg.3':'消息会直接发送到家长的 Telegram','help.feat.inc.title':'事件','help.feat.inc.1':'记录行为、成就、健康备注','help.feat.inc.2':'设置严重程度（信息/低/中/高）','help.feat.inc.3':'家长已通知复选框',
'help.ai.introTitle':'AI 智能助手','help.ai.introBody':'在 Telegram 聊天中无需填写表单，只需对话即可添加数据。支持缅甸语和英语。','help.ai.examplesLabel':'试着这样说 —','help.ai.ex1':'Adam 今天缺勤','help.ai.ex2':'✓ Adam → 已标记为缺勤','help.ai.ex3':'Hannah 生病了','help.ai.ex4':'✓ Hannah → 已标记为生病','help.ai.ex5':'告诉 P4 明天有数学考试','help.ai.ex6':'✓ 作业已保存 · 已向家长发送广播','help.ai.ex7':'删除昨天的数学作业','help.ai.ex8':'是哪一个？1. 数学 P4 · 2. 数学 KG','help.ai.cheatLabel':'按类别查看命令',
'help.ai.cheat.attend.title':'✅ 考勤（全班）','help.ai.cheat.attend.1':'“Adam is here” / “Adam present”','help.ai.cheat.attend.2':'“Hannah is absent” / “Hannah absent”','help.ai.cheat.attend.3':'“Mg Mg is sick” → 生病','help.ai.cheat.attend.4':'“Su Su is late” → 迟到','help.ai.cheat.attend.5':'“P4 is all here” → 全员出勤','help.ai.cheat.hw.title':'📚 作业','help.ai.cheat.hw.1':'“Give P4 Maths page 24-25”','help.ai.cheat.hw.2':'“KG English worksheet 3”','help.ai.cheat.hw.3':'“Change yesterday’s Science HW description”','help.ai.cheat.hw.4':'“Delete today’s Maths HW”',
'help.ai.cheat.daily.title':'📋 每日报告','help.ai.cheat.daily.1':'“Adam ate all his food today, happy”','help.ai.cheat.daily.2':'“Hannah napped 30 minutes”','help.ai.cheat.daily.3':'“Change Adam’s report mood to Happy”','help.ai.cheat.inc.title':'⚡ 事件','help.ai.cheat.inc.1':'“Adam helped a classmate - good behaviour”','help.ai.cheat.inc.2':'“Change Mg Mg’s incident severity to High”','help.ai.cheat.inc.3':'“Delete Hannah’s incident”','help.ai.cheat.parent.title':'💬 家长 / 广播','help.ai.cheat.parent.1':'“Tell Adam’s parent to call the school”','help.ai.cheat.parent.2':'“Tell all of P4 school is closed tomorrow”','help.ai.cheat.parent.3':'“Delete that broadcast I sent by mistake”','help.ai.cheat.query.title':'🔍 提问','help.ai.cheat.query.1':'“How many students in P4?”','help.ai.cheat.query.2':'“Adam’s phone number”','help.ai.cheat.query.3':'“Who’s absent today?”','help.ai.cheat.query.4':'“Show student list”','help.ai.tip1':'AI 可以处理：考勤、每日报告、作业、事件、家长消息、广播、课表 — 全部支持添加/编辑/删除。也可以查询学生名单或其他信息。','help.ai.tip2':'注意：删除或编辑时，AI 会先询问“是哪一个？”。只有选择正确项目后才会执行，因此不会误删。',
'help.trouble.introTitle':'故障排除','help.trouble.introBody':'如果遇到问题，请尝试下面的解决方法。','help.trouble.q1':'应用无法打开 / 显示“连接失败”','help.trouble.a1':'检查网络连接，然后点击重试。如果尝试 2–3 次仍失败，请联系管理员。','help.trouble.q2':'无法保存考勤','help.trouble.a2':'检查顶部日期是否正确。标记学生后，别忘了点击底部的“保存考勤”。','help.trouble.q3':'无法添加新学生','help.trouble.a3':'英文姓名为必填项（标有 * 的字段）。还需要选择班级。','help.trouble.q4':'无法连接家长的 Telegram','help.trouble.a4':'将添加学生后显示的链接发送给家长。家长点击链接，再在机器人中点击 Start。请等待约一分钟。','help.trouble.q5':'AI 无法理解','help.trouble.a5':'尝试说得更清楚。例如不要只说“Adam”，而是说“Adam 今天缺勤”。请确保学生姓名拼写正确。','help.trouble.q6':'数据未显示 / 显示旧数据','help.trouble.a6':'点击右上角 ↻ 刷新按钮。也可以关闭并重新打开应用。','help.trouble.tip':'如果仍无法解决，请联系学校管理员或支持渠道。',
'help.admin.introTitle':'管理员工具','help.admin.introBody':'作为管理员，您可以修改整个学校的设置。','help.admin.logo.title':'学校 Logo','help.admin.logo.1':'更多 → 学校 Logo → 上传图片','help.admin.logo.2':'会显示在页眉、侧边栏和报告中','help.admin.classes.title':'班级与年级','help.admin.classes.1':'更多 → 班级与年级','help.admin.classes.2':'添加/删除学校班级名称（P4 Online、C1…）','help.admin.classes.3':'添加学生时会显示此列表','help.admin.timetable.title':'课表','help.admin.timetable.1':'更多 → 课表 → + 添加课次','help.admin.timetable.2':'星期、课次、班级、科目、教室','help.admin.reg.title':'注册','help.admin.reg.1':'新教师 — 在机器人中使用 /register_teacher','help.admin.reg.2':'管理员批准后教师账号才会启用','help.about.introTitle':'关于 SCMS','help.about.introBody':'SCMS v11 — 以 Telegram 为核心的学校管理系统。为缅甸学校打造。','help.about.version':'版本','help.about.platform':'平台','help.about.school':'学校','help.about.needHelpTitle':'需要帮助？','help.about.needHelpBody':'如果遇到问题，请联系学校管理员或支持渠道。','help.about.replayTour':'🔄 再看一次欢迎引导','help.close':'关闭',
'tour.s1.title':'欢迎使用 SCMS 👋','tour.s1.text':'您可以在这里管理整个学校。我们用 5 个步骤带您了解。','tour.s2.title':'学生','tour.s2.text':'学生都在这里。点击卡片查看详情或编辑。','tour.s3.title':'考勤','tour.s3.text':'今天谁出勤、谁缺勤 — 使用 P/A/L/T/S/E/H 代码一键标记。','tour.s4.title':'+ 按钮','tour.s4.text':'这个 + 按钮会根据当前页面执行“添加新项目”操作。','tour.s5.title':'更多 — 帮助在这里','tour.s5.text':'“更多”标签包含完整使用指南、管理员工具和设置。','tour.skip':'跳过','tour.next':'下一步 →','tour.done':'完成 ✓'
};