// Simplified Chinese translation batch A1 — staging only; not registered in production runtime.
window.I18N_ZH_BATCH_A1 = {
  'app.title': 'SCMS — 学校班级管理',
  'common.all': '全部','common.edit': '编辑','common.close': '关闭','common.cancel': '取消','common.add': '添加','common.saving': '保存中…','common.years': '岁','common.failed': '失败：','common.saveFailed': '无法保存 — 请重试','common.removed': '已移除',
  'students.stat.students': '学生','students.stat.classes': '班级','students.stat.hereToday': '今日到校','students.subtitle': '{n} 名在读学生，分布在 {c} 个班级',
  'students.empty.title': '未找到学生','students.empty.searchHint': '请尝试其他搜索词','students.empty.addHint': '点击 + 添加学生','students.notMarked': '未标记','students.tgLinked': '已关联 TG','students.homeLabel': '住址：','students.bday.today': '今天！','students.bday.tooltip': '{n} 天后生日','students.linked': '✓ 已关联','students.getLink': '获取链接 →','students.sendLinkBtn': '📤 发送链接给家长',
  'students.field.gender': '性别','students.field.grade': '年级','students.field.birthday': '生日','students.field.home': '住址','students.field.parent': '家长','students.field.parentPhone': '家长电话','students.field.parentEmail': '家长邮箱','students.field.parentTg': '家长 Telegram','students.detail.recentReports': '最近报告','students.detail.recentIncidents': '最近事件','students.detail.editInfo': '编辑学生信息',
  'students.form.editTitle': '编辑学生','students.form.addTitle': '添加新学生','students.form.removePhoto': '移除照片','students.form.localName': '本地姓名（缅甸语 / 本民族语言）','students.form.localNamePh': '学生姓名…','students.form.englishName': '英文姓名 *','students.form.englishNamePh': '完整英文姓名','students.form.class': '班级 *','students.form.selectClass': '选择班级','students.form.grade': '年级','students.form.selectGrade': '选择年级','students.form.gender': '性别','students.form.genderM': '男','students.form.genderF': '女','students.form.genderOther': '其他','students.form.birthday': '生日','students.form.birthdayHint': '（用于 🎂 生日提醒）','students.form.homeColor': '组别颜色','students.form.homeColorHint': '（队伍 / House）','students.form.parentSection': '家长 / 监护人','students.form.parentName': '家长姓名','students.form.parentNamePh': '家长 / 监护人姓名','students.form.parentPhone': '家长电话','students.form.parentPhonePh': '+95 9 xxx xxx xxx','students.form.parentEmail': '家长邮箱','students.form.parentEmailOptional': '家长邮箱（可选）','students.form.parentEmailPh': 'parent@example.com','students.form.parentTg': '家长 Telegram','students.form.saveEdit': '保存更改','students.form.register': '注册学生','students.form.removeBtn': '移除学生','students.form.savingEdit': '保存中…','students.form.registering': '注册中…','students.form.parentTgInfo': '注册学生后，家长 Telegram ID 会<b>自动</b>填写。我们会显示一个可分享给家长的链接——家长在 Telegram 中点击链接后，系统会自动获取其 ID。',
  'students.toast.imageOnly': '请选择图片文件','students.toast.imageTooBig': '照片过大（最大 20 MB）','students.toast.studentNotFound': '未找到学生','students.toast.nameRequired': '必须填写英文姓名','students.toast.classRequired': '必须选择班级','students.toast.emailInvalid': '家长邮箱格式可能无效','students.toast.phoneInvalid': '家长电话格式可能无效','students.toast.updated': '✓ {name} 已更新','students.toast.registered': '✓ {name} 已注册','students.toast.photoUploadFailedEdit': '已保存，但照片上传失败：{err}','students.toast.photoRemoveFailed': '已保存，但移除照片失败：{err}','students.toast.photoUploadFailedAdd': '已注册，但照片上传失败：{err}','students.toast.saveFailed': '保存失败：{err}','students.toast.registerFailed': '注册失败：{err}',
  'students.delete.title': '移除 {name}？','students.delete.body': '此操作会将学生标记为 <b>停用</b>。其记录（出勤、报告）会保留，但不会出现在每日列表中。之后可以请管理员恢复。','students.delete.confirm': '是，移除','students.delete.done': '✓ 学生已移除',
  'parentLink.title': '关联家长的 Telegram','parentLink.body': '请将此链接分享给 {name} 的家长。家长在 Telegram 中点击后，我们的机器人会获取其 ID，并自动将其关联到该学生。','parentLink.copy': '📋 复制链接','parentLink.share': '📤 通过 Telegram 分享','parentLink.waiting': '等待家长点击链接…','parentLink.linkedHtml': '✓ <b>已关联！</b> 家长 ID：<code>{id}</code>','parentLink.done': '完成 — 我稍后再分享','parentLink.copied': '✓ 链接已复制','parentLink.copyFail': '复制失败 — 请长按手动复制','parentLink.shareText': '你好！请在 Telegram 中点击此链接，以接收学校关于 {name} 的更新：',
  'picker.class.title': '选择班级','picker.class.addLabel': '添加新班级','picker.class.placeholder': '（例如 P4 Online）','picker.grade.title': '选择年级','picker.grade.addLabel': '添加新年级','picker.select': '选择…','picker.empty': '暂无选项 — 请在下方添加','picker.typeName': '请先输入名称','picker.deleteConfirm': '要从 {list} 列表中移除“{value}”吗？',
  'nav.dashboard': '仪表盘','nav.students': '学生','nav.attendance': '出勤','nav.homework': '作业','nav.messages': '消息','nav.incidents': '事件','nav.timetable': '课表','nav.reports': '报告','nav.settings': '设置',
  'topbar.search': '搜索...','topbar.notifications': '通知','topbar.profile': '个人资料','topbar.logout': '退出登录','topbar.language': '语言',
  'btn.save': '保存','btn.cancel': '取消','btn.delete': '删除','btn.edit': '编辑','btn.add': '添加','btn.close': '关闭','btn.confirm': '确认','btn.export': '导出','btn.refresh': '刷新','btn.submit': '提交',
  'msg.loading': '加载中...','msg.saving': '保存中...','msg.saved': '保存成功','msg.error': '发生错误','msg.noData': '暂无数据','msg.offline': '您当前处于离线状态','msg.confirmDelete': '确定要删除吗？'
};
