// Simplified Chinese translation batch F — staging only; not registered.
window.I18N_ZH_BATCH_F={
'students.title':'学生','students.name':'姓名','students.rollNo':'学号','students.class':'班级','students.section':'分组','students.parent':'家长','students.phone':'电话','students.addNew':'添加新学生','students.searchPlaceholder':'按姓名或学号搜索',
'att.title':'考勤','att.present':'出勤','att.absent':'缺勤','att.late':'迟到','att.leave':'请假','att.markAll':'全部标记为出勤','att.date':'日期','att.saveAttendance':'保存考勤',
'common.optional':'（可选）','common.error':'错误','common.networkError':'网络错误','common.loadFailed':'加载失败：{err}','students.subtitleOneClass':'{n} 名在读学生，分布于 {c} 个班级','students.subtitleOne':'{n} 名在读学生，分布于 {c} 个班级','students.bday.tooltipOne':'1 天后生日','students.bday.short':'{n}天','students.detail.meal':'餐食：','students.btn.health':'健康记录',
'idCard.title':'学生证','idCard.failed':'无法生成卡片：{err}。学生必须处于在读状态。','idCard.scanHint':'家长扫描此二维码登录家长门户。','idCard.copyLink':'复制链接','idCard.testHint':'可用于自行测试链接，或在家长无法扫描时直接发送。','idCard.print':'🖨 打印卡片','idCard.lost':'🔄 卡片丢失 — 生成新代码','idCard.regenTitle':'🔄 生成新代码？','idCard.regenBody':'旧卡片的二维码将立即失效 — 请在发放新卡前重新打印。已经登录的家长不会被退出。','idCard.regenConfirm':'生成新代码','idCard.regenDone':'✓ 新代码已生成','idCard.selectMode':'选择学生证','idCard.nSelected':'已选择 {n} 个','idCard.selectAllVisible':'选择当前显示的全部','idCard.selectNone':'清除','idCard.printSelected':'打印学生证','idCard.preparing':'正在准备 {n} 张卡片…','idCard.orientVertical':'竖版卡片','idCard.orientHorizontal':'横版卡片',
'stuLib.title':'图书借阅','stuLib.empty':'暂无借阅记录。','stuLib.since':'自 {date} 起','stuLib.returnedOn':'于 {date} 归还','stuLib.return':'归还','stuLib.returned':'✓ 已归还','stuTr.title':'交通','stuTr.none':'尚未分配路线。','stuTr.goto':'前往交通管理','stuTr.route':'路线','stuTr.driver':'司机','stuTr.phone':'电话','stuTr.pickupStop':'上车点','stuTr.pickupTime':'上车时间','stuTr.dropoffTime':'下车时间','stuTr.manage':'在交通管理中设置',
'picker.remove':'移除','picker.removeFromList':'从列表中移除','picker.deleteNote':'此{kind}中的现有学生不会受到影响。','picker.list.classes':'班级','picker.list.grades':'年级','picker.kind.classes':'班级','picker.kind.grades':'年级',
'color.red':'红色','color.orange':'橙色','color.amber':'琥珀色','color.yellow':'黄色','color.lime':'青柠色','color.green':'绿色','color.teal':'青绿色','color.cyan':'青色','color.sky':'天蓝色','color.blue':'蓝色','color.indigo':'靛蓝色','color.violet':'紫罗兰色','color.fuchsia':'品红色','color.pink':'粉色','color.rose':'玫瑰色','color.slate':'石板灰',
'att.code.P.label':'出勤','att.code.P.short':'勤','att.code.P.desc':'学生已到校','att.code.A.label':'缺勤','att.code.A.short':'缺','att.code.A.desc':'无正当理由缺勤','att.code.L.label':'请假','att.code.L.short':'假','att.code.L.desc':'已批准请假 / 假期','att.code.T.label':'迟到','att.code.T.short':'迟','att.code.T.desc':'迟到到校','att.code.S.label':'生病','att.code.S.short':'病','att.code.S.desc':'因病缺勤','att.code.E.label':'事假','att.code.E.short':'事','att.code.E.desc':'获准缺勤','att.code.H.label':'半天','att.code.H.short':'½天','att.code.H.desc':'仅出勤半天',
'att.noClasses':'暂无班级 — 请先添加学生','att.classOption':'{name} 班','att.noActive':'{cls} 中没有在读学生','att.noteAdd':'添加备注','att.noteAddTitle':'添加原因 / 备注','att.hasNote':'备注：{note}','att.codeGroup':'考勤代码','att.notMarkedYet':'尚未标记','att.noteTitle':'{name} 的备注','att.currentStatus':'当前状态：','att.reasonLabel':'原因 / 备注（可选）','att.reasonPh':'例如：看医生、家庭活动、公交车晚点…','att.charCount':'{n} / 200 个字符','att.saveNote':'保存备注','att.noteSaved':'备注已保存','att.noteRemoved':'备注已移除','att.markedAll':'已将全部标记为{label}','att.cleared':'标记已清除','att.legendTitle':'考勤代码','att.legendHint':'点击学生姓名下方的任意代码即可登记考勤。','att.gotIt':'知道了','att.stat.marked':'已标记','att.stat.more':'更多','att.selectClassFirst':'请先选择班级','att.noStudentsInClass':'此班级没有学生','att.saved':'✓ 已保存 {cls} 的考勤 — {date}','att.saveFailed':'保存失败：{err}'
};