(function(){
"use strict";
const DEFAULT_SECTIONS=[{id:"hero",type:"hero",label:"Home",visible:true,locked:true},{id:"about",type:"about",label:"About",visible:true},{id:"programs",type:"programs",label:"Programs",visible:true},{id:"facilities",type:"facilities",label:"Facilities",visible:true},{id:"news",type:"news",label:"News & events",visible:true},{id:"contact",type:"contact",label:"Contact",visible:true}];
const state={template:"modern",logo:"",schoolName:"",tagline:"",aboutTitle:"",aboutText:"",contactTitle:"",contactText:"",programs:[],facilities:[],news:[],sections:DEFAULT_SECTIONS.map(x=>({...x}))};
const templateMeta={modern:{label:"Modern School",hero:"Clean, calm and welcoming"},classic:{label:"Classic Academy",hero:"Formal and traditional"},premium:{label:"Premium Campus",hero:"Editorial and sophisticated"}};
const fieldMeta={
 logo:["School logo","Upload your school logo here when image upload is enabled.","A clear square logo works best."],
 schoolName:["School name","Give families the name they should remember.","Example: Bright Future International School"],
 tagline:["Welcome message","One short sentence that captures your school.","Example: Growing curious minds with care and confidence."],
 aboutTitle:["School introduction","A simple heading for your introduction.","Example: A place to learn, grow and belong."],
 aboutText:["About your school","Tell families what makes your school special.","Keep this clear and welcoming."],
 contactTitle:["Contact heading","A short heading for your contact area.","Example: We would love to hear from you."],
 contactText:["Contact details","Add the information families need to reach your school.","Example: +95 9... · hello@school.com · Mandalay"]
};
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const dialog=$("#editorDialog"),input=$("#dialogInput"),title=$("#dialogTitle"),label=$("#dialogLabel"),hint=$("#dialogHint"),toast=$("#toast");
let activeField=null,activeCollection=null;
function showToast(message){toast.textContent=message;toast.classList.add("show");clearTimeout(showToast.t);showToast.t=setTimeout(()=>toast.classList.remove("show"),1800)}
function openField(field){activeField=field;activeCollection=null;const m=fieldMeta[field];title.textContent=m[0];label.textContent=m[0];input.value=state[field];hint.textContent=m[2];input.placeholder=m[1];input.maxLength=field==="aboutText"?4000:field==="contactText"?2000:300;input.removeAttribute("aria-invalid");dialog.showModal();setTimeout(()=>input.focus(),30)}
function openItem(collection){activeCollection=collection;activeField=null;const names={programs:["Add a program","Example: Primary Education"],facilities:["Add a facility","Example: Science & Innovation Lab"],news:["Add news or event","Example: Open Day 2026"]};const m=names[collection];title.textContent=m[0];label.textContent="Title";input.value="";hint.textContent=m[1];input.placeholder=m[1];input.maxLength=200;input.removeAttribute("aria-invalid");dialog.showModal();setTimeout(()=>input.focus(),30)}
function applyTemplate(){const meta=templateMeta[state.template]||templateMeta.modern;const label=$("#changeTemplate");if(label)label.textContent=meta.label+" selected";const name=$("#templateName");if(name)name.textContent=meta.label;$(".template-option").forEach(x=>x.classList.toggle("selected",x.dataset.template===state.template));document.body.dataset.template=state.template}
function normalizeSections(){if(!Array.isArray(state.sections)||!state.sections.length)state.sections=DEFAULT_SECTIONS.map(x=>({...x}));state.sections=state.sections.filter(x=>x&&typeof x.id==="string"&&typeof x.type==="string").map(x=>({...x,visible:x.visible!==false,locked:x.type==="hero"||x.locked===true}));}
function renderSectionLayout(){normalizeSections();const canvas=$("#pageCanvas");const nodes=new Map($("[data-block]").map(n=>[n.id,n]));state.sections.forEach(meta=>{const node=nodes.get(meta.id);if(!node)return;node.hidden=!meta.visible;canvas.appendChild(node);const hide=node.querySelector("[data-section-action=hide]");if(hide){hide.textContent=meta.visible?"Hide":"Show";hide.setAttribute("aria-label",(meta.visible?"Hide ":"Show ")+meta.label);hide.disabled=!!meta.locked;}const up=node.querySelector("[data-section-action=up]"),down=node.querySelector("[data-section-action=down]");if(up)up.disabled=meta.id==="hero";if(down)down.disabled=state.sections[state.sections.length-1]?.id===meta.id;});}
function sectionIndex(id){return state.sections.findIndex(x=>x.id===id)}
function sectionAction(id,action){normalizeSections();const i=sectionIndex(id),m=state.sections[i];if(i<0||!m)return;if(action==="hide"&&!m.locked)m.visible=!m.visible;else if(action==="up"&&i>0)[state.sections[i-1],state.sections[i]]=[state.sections[i],state.sections[i-1]];else if(action==="down"&&i<state.sections.length-1)[state.sections[i+1],state.sections[i]]=[state.sections[i],state.sections[i+1]];else if(action==="duplicate"&&!m.locked){const source=$("#"+CSS.escape(id));if(!source)return;const copy=source.cloneNode(true),copyId=id+"-copy-"+Date.now().toString(36);copy.id=copyId;copy.dataset.sectionLabel=m.label+" copy";copy.querySelectorAll("[data-section-id]").forEach(b=>{b.dataset.sectionId=copyId;b.disabled=false});state.sections.splice(i+1,0,{...m,id:copyId,label:m.label+" copy",locked:false});$("#pageCanvas").insertBefore(copy,source.nextSibling);showToast(m.label+" duplicated")}renderSectionLayout();renderPreview();persistDraft();}
function persistDraft(){try{localStorage.setItem("scms-website-draft",JSON.stringify(state));$("#saveState").textContent="Saved locally"}catch(_){$("#saveState").textContent="Draft"}}
function normalizeSections(){const canonical=["hero","about","programs","facilities","news","contact"];const saved=Array.isArray(state.sections)?state.sections:[];const seen=new Set();state.sections=saved.filter(x=>x&&canonical.includes(x.id)&&!seen.has(x.id)&&(seen.add(x.id),true));for(const id of canonical)if(!seen.has(id))state.sections.push({id,visible:true,locked:id==="hero"});state.sections.forEach(x=>{x.visible=x.visible!==false;if(x.id==="hero")x.locked=true});}
function applySectionState(){normalizeSections();const canvas=$("#pageCanvas");const nodes=new Map($("#pageCanvas > .site-block").map(n=>[n.dataset.block,n]));state.sections.forEach(x=>{const node=nodes.get(x.id);if(node)canvas.appendChild(node);});state.sections.forEach(x=>{const node=nodes.get(x.id);if(!node)return;node.hidden=!x.visible;const hide=node.querySelector("[data-section-action=hide]");if(hide){hide.textContent=x.visible?"Hide":"Show";hide.disabled=x.locked===true;hide.setAttribute("aria-label",x.visible?"Hide "+x.id:"Show "+x.id)}});updateSectionControls();}
function updateSectionControls(){const visible=state.sections.filter(x=>x.visible);state.sections.forEach((x,i)=>{const node=$("#"+x.id);if(!node)return;const up=node.querySelector("[data-section-action=up]"),down=node.querySelector("[data-section-action=down]"),dup=node.querySelector("[data-section-action=duplicate]");if(up)up.disabled=i===0;if(down)down.disabled=i===state.sections.length-1;if(dup)dup.disabled=x.locked===true;});}
function render(){
 applySectionState();
 $("[data-field]").forEach(el=>{const f=el.dataset.field;const fallback={logo:"＋ Add your school logo",schoolName:"Click here to add your school name",tagline:"Click here to add a short welcome message",aboutTitle:"Click here to add your school introduction",aboutText:"Tell families what makes your school special. A short, clear introduction works best.",contactTitle:"Click here to add your contact details",contactText:"Phone · Email · Address · Location"}[f];el.textContent=state[f]||fallback;el.classList.toggle("filled",!!state[f])});
 normalizeSections();renderSectionLayout();renderCollection("programs");renderCollection("facilities");renderCollection("news");applyTemplate();renderPreview();updateProgress();
 persistDraft()
}
function updateProgress(){const fields=["schoolName","tagline","aboutTitle","aboutText","contactTitle","contactText"];const done=fields.filter(f=>state[f]).length;$("#fieldProgress").textContent=done+" of "+fields.length+" completed"}
function renderCollection(c){const target=$("#"+(c==="programs"?"programItems":c==="facilities"?"facilityItems":"newsItems"));const items=state[c];target.innerHTML=items.length?items.map((x,i)=>'<article class="added-card"><button class="remove-card" data-remove="'+c+'" data-index="'+i+'" aria-label="Remove">×</button><b>'+escapeHtml(x)+'</b><span>Ready for review</span></article>').join(""):'<button class="add-card" data-add-item="'+c+'" type="button">＋<span>'+({programs:"Add your first program",facilities:"Show families your school",news:"Add your first news item"}[c])+'</span></button>'}
function renderPreview(){const meta=templateMeta[state.template]||templateMeta.modern;const name=escapeHtml(state.schoolName||"Your School"),tag=escapeHtml(state.tagline||meta.hero);normalizeSections();const contentByType={about:["About",state.aboutText],programs:["Programs",state.programs.join(" · ")],facilities:["School life",state.facilities.join(" · ")],news:["News & events",state.news.join(" · ")],contact:["Contact",state.contactText]};const sections=state.sections.filter(s=>s.visible&&contentByType[s.type]).map(s=>contentByType[s.type]);const preview=$("#previewCanvas");preview.dataset.template=state.template;preview.innerHTML='<div class="mini-hero"><div class="mini-logo">'+(state.schoolName?escapeHtml(state.schoolName[0].toUpperCase()):"S")+'</div><h1>'+name+'</h1><p>'+tag+'</p></div>'+sections.map(x=>'<section class="mini-section"><h2>'+escapeHtml(x[0])+'</h2><p>'+escapeHtml(x[1]||"Content will appear here when you add it.")+"</p></section>").join("")}
function escapeHtml(v){return String(v).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]||c))}
function manageSection(id,action){normalizeSections();const i=state.sections.findIndex(x=>x.id===id);if(i<0)return;const s=state.sections[i];if(action==="hide"&&!s.locked){s.visible=!s.visible;render();showToast(s.visible?"Section shown":"Section hidden");return;}if(action==="up"&&i>0){[state.sections[i-1],state.sections[i]]=[state.sections[i],state.sections[i-1]];render();showToast("Section moved up");return;}if(action==="down"&&i<state.sections.length-1){[state.sections[i+1],state.sections[i]]=[state.sections[i],state.sections[i+1]];render();showToast("Section moved down");return;}if(action==="duplicate"&&!s.locked&&["programs","facilities","news"].includes(id)){const copy=state[id][state[id].length-1];if(copy)state[id].push(copy);else{showToast("Add content before duplicating");return;}render();showToast("Section content duplicated");}}
function addSection(){$("#sectionDialog").showModal()}function initSectionNavigation(){const links=$(".section-nav a"),sections=links.map(a=>$(a.getAttribute("href"))).filter(Boolean);if(!("IntersectionObserver" in window))return;const observer=new IntersectionObserver(entries=>{const visible=entries.filter(e=>e.isIntersecting).sort((a,b)=>b.intersectionRatio-a.intersectionRatio)[0];if(!visible)return;links.forEach(a=>a.classList.toggle("active",a.getAttribute("href")==="#"+visible.target.id));},{rootMargin:"-22% 0px -62% 0px",threshold:[0,.25,.5]});sections.forEach(section=>observer.observe(section));links.forEach(link=>link.addEventListener("click",()=>links.forEach(a=>a.classList.toggle("active",a===link))));if(links[0])links[0].classList.add("active")}
$$("[data-field]").forEach(el=>el.addEventListener("click",()=>openField(el.dataset.field)));
document.addEventListener("click",e=>{const sectionButton=e.target.closest("[data-section-action]");if(sectionButton){sectionAction(sectionButton.dataset.sectionId,sectionButton.dataset.sectionAction);return;}const add=e.target.closest("[data-add-item]");if(add)openItem(add.dataset.addItem);const remove=e.target.closest("[data-remove]");if(remove){state[remove.dataset.remove].splice(Number(remove.dataset.index),1);render();showToast("Removed from draft")}});
$$(".block-edit").forEach(el=>el.addEventListener("click",()=>{const b=el.dataset.edit;if(fieldMeta[b])openField(b);else if(["programs","facilities","news"].includes(b))openItem(b);else showToast("Choose the fields you need to update.")}));
$("#dialogSave").addEventListener("click",e=>{e.preventDefault();const value=input.value.trim();if(!value){input.setAttribute("aria-invalid","true");input.focus();hint.textContent="Please enter some information before saving.";return;}if(activeField)state[activeField]=value;if(activeCollection)state[activeCollection].push(value);dialog.close();render();showToast("Draft updated")});
$("#addSectionBottom").addEventListener("click",addSection);$("#closeSectionDialog").addEventListener("click",()=>$("#sectionDialog").close());
$$(".section-options button").forEach(b=>b.addEventListener("click",()=>{const c=b.dataset.section;$("#sectionDialog").close();if(["programs","facilities","news"].includes(c))openItem(c);else showToast(c+" will be available as a guided section in the next builder step.")}));
$("#previewToggle").addEventListener("click",()=>{const p=$("#previewPanel");p.classList.toggle("open");$("#previewToggle").setAttribute("aria-expanded",String(p.classList.contains("open")))});
$("#closePreview").addEventListener("click",()=>$("#previewPanel").classList.remove("open"));
$("#publishButton").addEventListener("click",()=>showToast("Preview only — publishing requires authorized review and the secure publish workflow."));
const templateDialog=$("#templateDialog");
$("#changeTemplate").addEventListener("click",()=>templateDialog.showModal());$("#closeTemplateDialog").addEventListener("click",()=>templateDialog.close());
$$(".template-option").forEach(b=>b.addEventListener("click",()=>{state.template=b.dataset.template;$$(".template-option").forEach(x=>x.classList.toggle("selected",x===b));templateDialog.close();showToast(b.querySelector("b").textContent+" selected")}));
try{const saved=JSON.parse(localStorage.getItem("scms-website-draft")||"null");if(saved)Object.assign(state,saved)}catch(_){}normalizeSections();
render();
initSectionNavigation();
})();