-- SCMS v12 — Staff-to-staff direct messaging
-- Server-authorized 1-on-1 conversations. AI/automation is intentionally out of scope.

create table if not exists public.staff_direct_conversations (
  id bigint generated by default as identity primary key,
  school_id text not null,
  pair_key text not null,
  created_by_teacher_id text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (school_id, pair_key)
);

create table if not exists public.staff_direct_members (
  conversation_id bigint not null references public.staff_direct_conversations(id) on delete cascade,
  school_id text not null,
  teacher_id text not null,
  teacher_name text not null,
  joined_at timestamptz not null default now(),
  last_read_at timestamptz,
  primary key (conversation_id, teacher_id)
);

create table if not exists public.staff_direct_messages (
  id bigint generated by default as identity primary key,
  conversation_id bigint not null references public.staff_direct_conversations(id) on delete cascade,
  school_id text not null,
  sender_teacher_id text not null,
  sender_teacher_name text not null,
  text text not null,
  created_at timestamptz not null default now(),
  reply_to_id bigint references public.staff_direct_messages(id) on delete set null
);

create index if not exists idx_staff_direct_members_teacher
  on public.staff_direct_members (school_id, teacher_id, conversation_id);

create index if not exists idx_staff_direct_messages_conversation
  on public.staff_direct_messages (conversation_id, created_at desc, id desc);

alter table public.staff_direct_conversations enable row level security;
alter table public.staff_direct_members enable row level security;
alter table public.staff_direct_messages enable row level security;

revoke all on public.staff_direct_conversations from anon, authenticated;
revoke all on public.staff_direct_members from anon, authenticated;
revoke all on public.staff_direct_messages from anon, authenticated;

create or replace function public.rpc_chat_staff_directory(p_session_token text)
returns jsonb
language plpgsql
security definer
set search_path to 'public','pg_temp'
as $function$
declare
  v_sess record;
  v_rows jsonb;
begin
  select s.school_id, s.teacher_id, s.role
    into v_sess
    from public.app_web_sessions s
    join public.teachers t on t.teacher_id = s.teacher_id
   where s.session_token = p_session_token
     and s.expires_at > now()
     and t.status = 'active'
     and t.school_id = s.school_id
     and t.role = s.role
   limit 1;

  if v_sess is null then
    return jsonb_build_object('ok', false, 'error', 'invalid_session');
  end if;

  select coalesce(jsonb_agg(to_jsonb(x) order by lower(x.teacher_name)), '[]'::jsonb)
    into v_rows
    from (
      select t.teacher_id, t.teacher_name, t.role, t.photo_url, t.classes
        from public.teachers t
       where t.school_id = v_sess.school_id
         and t.status = 'active'
         and t.teacher_id <> v_sess.teacher_id
    ) x;

  return jsonb_build_object('ok', true, 'rows', v_rows);
end
$function$;

create or replace function public.rpc_chat_direct_open(
  p_session_token text,
  p_teacher_id text
)
returns jsonb
language plpgsql
security definer
set search_path to 'public','pg_temp'
as $function$
declare
  v_sess record;
  v_target record;
  v_pair text;
  v_conversation_id bigint;
begin
  select s.school_id, s.teacher_id, s.role
    into v_sess
    from public.app_web_sessions s
    join public.teachers t on t.teacher_id = s.teacher_id
   where s.session_token = p_session_token
     and s.expires_at > now()
     and t.status = 'active'
     and t.school_id = s.school_id
     and t.role = s.role
   limit 1;

  if v_sess is null then
    return jsonb_build_object('ok', false, 'error', 'invalid_session');
  end if;

  if p_teacher_id is null or btrim(p_teacher_id) = '' or length(btrim(p_teacher_id)) > 100 then
    return jsonb_build_object('ok', false, 'error', 'bad_target');
  end if;

  if btrim(p_teacher_id) = v_sess.teacher_id then
    return jsonb_build_object('ok', false, 'error', 'cannot_message_self');
  end if;

  select t.teacher_id, t.teacher_name, t.role, t.photo_url, t.classes
    into v_target
    from public.teachers t
   where t.school_id = v_sess.school_id
     and t.teacher_id = btrim(p_teacher_id)
     and t.status = 'active'
   limit 1;

  if v_target is null then
    return jsonb_build_object('ok', false, 'error', 'target_not_found');
  end if;

  v_pair := case
    when v_sess.teacher_id < v_target.teacher_id
      then v_sess.teacher_id || ':' || v_target.teacher_id
    else v_target.teacher_id || ':' || v_sess.teacher_id
  end;

  insert into public.staff_direct_conversations(school_id, pair_key, created_by_teacher_id)
  values (v_sess.school_id, v_pair, v_sess.teacher_id)
  on conflict (school_id, pair_key)
  do update set updated_at = now()
  returning id into v_conversation_id;

  insert into public.staff_direct_members(conversation_id, school_id, teacher_id, teacher_name)
  values
    (v_conversation_id, v_sess.school_id, v_sess.teacher_id,
      (select teacher_name from public.teachers where teacher_id=v_sess.teacher_id and school_id=v_sess.school_id)),
    (v_conversation_id, v_sess.school_id, v_target.teacher_id, v_target.teacher_name)
  on conflict (conversation_id, teacher_id) do update
    set teacher_name = excluded.teacher_name;

  return jsonb_build_object(
    'ok', true,
    'conversation_id', v_conversation_id,
    'peer', jsonb_build_object(
      'teacher_id', v_target.teacher_id,
      'teacher_name', v_target.teacher_name,
      'role', v_target.role,
      'photo_url', v_target.photo_url,
      'classes', v_target.classes
    )
  );
end
$function$;

create or replace function public.rpc_chat_direct_conversations(p_session_token text)
returns jsonb
language plpgsql
security definer
set search_path to 'public','pg_temp'
as $function$
declare
  v_sess record;
  v_rows jsonb;
begin
  select s.school_id, s.teacher_id, s.role
    into v_sess
    from public.app_web_sessions s
    join public.teachers t on t.teacher_id = s.teacher_id
   where s.session_token = p_session_token
     and s.expires_at > now()
     and t.status = 'active'
     and t.school_id = s.school_id
     and t.role = s.role
   limit 1;

  if v_sess is null then
    return jsonb_build_object('ok', false, 'error', 'invalid_session');
  end if;

  select coalesce(jsonb_agg(to_jsonb(x) order by x.last_message_at desc nulls last), '[]'::jsonb)
    into v_rows
    from (
      select c.id as conversation_id,
             peer.teacher_id,
             peer.teacher_name,
             peer.role,
             peer.photo_url,
             peer.classes,
             lm.text as last_message,
             lm.created_at as last_message_at,
             coalesce(unread.unread_count,0) as unread_count
        from public.staff_direct_conversations c
        join public.staff_direct_members me
          on me.conversation_id=c.id and me.teacher_id=v_sess.teacher_id and me.school_id=v_sess.school_id
        join public.staff_direct_members peer_member
          on peer_member.conversation_id=c.id and peer_member.teacher_id<>v_sess.teacher_id
        join public.teachers peer
          on peer.teacher_id=peer_member.teacher_id
         and peer.school_id=v_sess.school_id
         and peer.status='active'
        left join lateral (
          select m.text,m.created_at
            from public.staff_direct_messages m
           where m.conversation_id=c.id
           order by m.created_at desc,m.id desc
           limit 1
        ) lm on true
        left join lateral (
          select count(*)::int as unread_count
            from public.staff_direct_messages m
           where m.conversation_id=c.id
             and m.sender_teacher_id<>v_sess.teacher_id
             and (me.last_read_at is null or m.created_at>me.last_read_at)
        ) unread on true
       where c.school_id=v_sess.school_id
    ) x;

  return jsonb_build_object('ok', true, 'rows', v_rows);
end
$function$;

create or replace function public.rpc_chat_direct_messages(
  p_session_token text,
  p_conversation_id bigint,
  p_limit integer default 50
)
returns jsonb
language plpgsql
security definer
set search_path to 'public','pg_temp'
as $function$
declare
  v_sess record;
  v_rows jsonb;
begin
  select s.school_id, s.teacher_id, s.role
    into v_sess
    from public.app_web_sessions s
    join public.teachers t on t.teacher_id = s.teacher_id
   where s.session_token = p_session_token
     and s.expires_at > now()
     and t.status = 'active'
     and t.school_id = s.school_id
     and t.role = s.role
   limit 1;

  if v_sess is null then
    return jsonb_build_object('ok', false, 'error', 'invalid_session');
  end if;

  if not exists (
    select 1 from public.staff_direct_members
     where conversation_id=p_conversation_id
       and school_id=v_sess.school_id
       and teacher_id=v_sess.teacher_id
  ) then
    return jsonb_build_object('ok', false, 'error', 'not_a_member');
  end if;

  select coalesce(jsonb_agg(to_jsonb(x) order by x.created_at), '[]'::jsonb)
    into v_rows
    from (
      select id, conversation_id, sender_teacher_id, sender_teacher_name, text, created_at, reply_to_id
        from public.staff_direct_messages
       where conversation_id=p_conversation_id
         and school_id=v_sess.school_id
       order by created_at desc, id desc
       limit least(greatest(coalesce(p_limit,50),1),200)
    ) x;

  return jsonb_build_object('ok', true, 'rows', v_rows);
end
$function$;

create or replace function public.rpc_chat_direct_send(
  p_session_token text,
  p_conversation_id bigint,
  p_text text,
  p_reply_to_id bigint default null
)
returns jsonb
language plpgsql
security definer
set search_path to 'public','pg_temp'
as $function$
declare
  v_sess record;
  v_row record;
begin
  select s.school_id, s.teacher_id, s.role, t.teacher_name
    into v_sess
    from public.app_web_sessions s
    join public.teachers t on t.teacher_id = s.teacher_id
   where s.session_token = p_session_token
     and s.expires_at > now()
     and t.status = 'active'
     and t.school_id = s.school_id
     and t.role = s.role
   limit 1;

  if v_sess is null then
    return jsonb_build_object('ok', false, 'error', 'invalid_session');
  end if;

  if p_text is null or length(btrim(p_text))=0 or length(p_text)>4000 then
    return jsonb_build_object('ok', false, 'error', 'bad_text');
  end if;

  if not exists (
    select 1 from public.staff_direct_members
     where conversation_id=p_conversation_id
       and school_id=v_sess.school_id
       and teacher_id=v_sess.teacher_id
  ) then
    return jsonb_build_object('ok', false, 'error', 'not_a_member');
  end if;

  if exists (
    select 1
      from public.staff_direct_members m
      join public.teachers t on t.teacher_id=m.teacher_id and t.school_id=v_sess.school_id
     where m.conversation_id=p_conversation_id
       and m.teacher_id<>v_sess.teacher_id
       and t.status<>'active'
  ) then
    return jsonb_build_object('ok', false, 'error', 'recipient_inactive');
  end if;

  if p_reply_to_id is not null and not exists (
    select 1
      from public.staff_direct_messages r
     where r.id=p_reply_to_id
       and r.conversation_id=p_conversation_id
       and r.school_id=v_sess.school_id
  ) then
    return jsonb_build_object('ok', false, 'error', 'invalid_reply_target');
  end if;

  insert into public.staff_direct_messages(
    conversation_id, school_id, sender_teacher_id, sender_teacher_name, text, reply_to_id
  )
  values (
    p_conversation_id, v_sess.school_id, v_sess.teacher_id, v_sess.teacher_name, btrim(p_text), p_reply_to_id
  )
  returning * into v_row;

  update public.staff_direct_conversations
     set updated_at=now()
   where id=p_conversation_id and school_id=v_sess.school_id;

  return jsonb_build_object('ok', true, 'message', to_jsonb(v_row));
end
$function$;

create or replace function public.rpc_chat_direct_mark_read(
  p_session_token text,
  p_conversation_id bigint
)
returns jsonb
language plpgsql
security definer
set search_path to 'public','pg_temp'
as $function$
declare
  v_sess record;
begin
  select s.school_id, s.teacher_id
    into v_sess
    from public.app_web_sessions s
    join public.teachers t on t.teacher_id=s.teacher_id
   where s.session_token=p_session_token
     and s.expires_at>now()
     and t.status='active'
     and t.school_id=s.school_id
     and t.role=s.role
   limit 1;

  if v_sess is null then
    return jsonb_build_object('ok',false,'error','invalid_session');
  end if;

  update public.staff_direct_members
     set last_read_at=now()
   where conversation_id=p_conversation_id
     and school_id=v_sess.school_id
     and teacher_id=v_sess.teacher_id;

  if not found then
    return jsonb_build_object('ok',false,'error','not_a_member');
  end if;

  return jsonb_build_object('ok',true);
end
$function$;

revoke all on function public.rpc_chat_staff_directory(text) from public;
revoke all on function public.rpc_chat_direct_open(text,text) from public;
revoke all on function public.rpc_chat_direct_conversations(text) from public;
revoke all on function public.rpc_chat_direct_messages(text,bigint,integer) from public;
revoke all on function public.rpc_chat_direct_send(text,bigint,text,bigint) from public;
revoke all on function public.rpc_chat_direct_mark_read(text,bigint) from public;

grant execute on function public.rpc_chat_staff_directory(text) to anon, authenticated;
grant execute on function public.rpc_chat_direct_open(text,text) to anon, authenticated;
grant execute on function public.rpc_chat_direct_conversations(text) to anon, authenticated;
grant execute on function public.rpc_chat_direct_messages(text,bigint,integer) to anon, authenticated;
grant execute on function public.rpc_chat_direct_send(text,bigint,text,bigint) to anon, authenticated;
grant execute on function public.rpc_chat_direct_mark_read(text,bigint) to anon, authenticated;
