-- SCMS v12 — Grade channel messaging
-- Department mapping is not yet authoritative in the current schema; this migration
-- implements the verified Grade side using teacher_class_assignments.

create table if not exists public.staff_grade_conversations (
  id bigint generated by default as identity primary key,
  school_id text not null,
  grade_name text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (school_id, grade_name)
);

create table if not exists public.staff_grade_messages (
  id bigint generated by default as identity primary key,
  conversation_id bigint not null references public.staff_grade_conversations(id) on delete cascade,
  school_id text not null,
  grade_name text not null,
  sender_teacher_id text not null,
  sender_teacher_name text not null,
  text text not null,
  created_at timestamptz not null default now(),
  reply_to_id bigint references public.staff_grade_messages(id) on delete set null
);

create index if not exists idx_staff_grade_messages_conversation
  on public.staff_grade_messages (conversation_id, created_at desc, id desc);

alter table public.staff_grade_conversations enable row level security;
alter table public.staff_grade_messages enable row level security;
revoke all on public.staff_grade_conversations from anon, authenticated;
revoke all on public.staff_grade_messages from anon, authenticated;

create or replace function public.rpc_chat_grade_list(
  p_session_token text,
  p_grade text
)
returns jsonb
language plpgsql
security definer
set search_path to 'public','pg_temp'
as $function$
declare
  v_sess record;
  v_grade text := nullif(btrim(p_grade),'');
  v_conversation_id bigint;
  v_rows jsonb;
begin
  select s.school_id,s.teacher_id,s.role,t.teacher_name
    into v_sess
    from public.app_web_sessions s
    join public.teachers t on t.teacher_id=s.teacher_id
   where s.session_token=p_session_token
     and s.expires_at>now()
     and t.status='active'
     and t.school_id=s.school_id
     and t.role=s.role
   limit 1;

  if v_sess is null then return jsonb_build_object('ok',false,'error','invalid_session'); end if;
  if v_grade is null or length(v_grade)>100 then return jsonb_build_object('ok',false,'error','bad_grade'); end if;

  if not exists (
    select 1 from public.teacher_class_assignments a
     where a.school_id=v_sess.school_id
       and a.teacher_id=v_sess.teacher_id
       and a.is_active=true
       and lower(a.class_name)=lower(v_grade)
  ) then
    return jsonb_build_object('ok',false,'error','not_assigned');
  end if;

  insert into public.staff_grade_conversations(school_id,grade_name)
  values(v_sess.school_id,v_grade)
  on conflict(school_id,grade_name) do update set updated_at=now()
  returning id into v_conversation_id;

  select coalesce(jsonb_agg(to_jsonb(x) order by x.created_at), '[]'::jsonb)
    into v_rows
    from (
      select id,conversation_id,sender_teacher_id,sender_teacher_name,text,created_at,reply_to_id
        from public.staff_grade_messages
       where conversation_id=v_conversation_id
         and school_id=v_sess.school_id
         and lower(grade_name)=lower(v_grade)
       order by created_at desc,id desc
       limit 100
    ) x;

  return jsonb_build_object('ok',true,'conversation_id',v_conversation_id,'grade',v_grade,'rows',v_rows);
end
$function$;

create or replace function public.rpc_chat_grade_send(
  p_session_token text,
  p_grade text,
  p_text text,
  p_reply_to_id bigint default null
)
returns jsonb
language plpgsql
security definer
set search_path to 'public','pg_temp'
as $function$
declare
  v_sess record;
  v_grade text := nullif(btrim(p_grade),'');
  v_conversation_id bigint;
  v_row record;
begin
  select s.school_id,s.teacher_id,s.role,t.teacher_name
    into v_sess
    from public.app_web_sessions s
    join public.teachers t on t.teacher_id=s.teacher_id
   where s.session_token=p_session_token
     and s.expires_at>now()
     and t.status='active'
     and t.school_id=s.school_id
     and t.role=s.role
   limit 1;

  if v_sess is null then return jsonb_build_object('ok',false,'error','invalid_session'); end if;
  if v_grade is null or length(v_grade)>100 then return jsonb_build_object('ok',false,'error','bad_grade'); end if;
  if p_text is null or length(btrim(p_text))=0 or length(p_text)>4000 then return jsonb_build_object('ok',false,'error','bad_text'); end if;

  if not exists (
    select 1 from public.teacher_class_assignments a
     where a.school_id=v_sess.school_id
       and a.teacher_id=v_sess.teacher_id
       and a.is_active=true
       and lower(a.class_name)=lower(v_grade)
  ) then
    return jsonb_build_object('ok',false,'error','not_assigned');
  end if;

  insert into public.staff_grade_conversations(school_id,grade_name)
  values(v_sess.school_id,v_grade)
  on conflict(school_id,grade_name) do update set updated_at=now()
  returning id into v_conversation_id;

  if p_reply_to_id is not null and not exists (
    select 1 from public.staff_grade_messages
     where id=p_reply_to_id
       and conversation_id=v_conversation_id
       and school_id=v_sess.school_id
       and lower(grade_name)=lower(v_grade)
  ) then
    return jsonb_build_object('ok',false,'error','invalid_reply_target');
  end if;

  insert into public.staff_grade_messages(
    conversation_id,school_id,grade_name,sender_teacher_id,sender_teacher_name,text,reply_to_id
  ) values (
    v_conversation_id,v_sess.school_id,v_grade,v_sess.teacher_id,v_sess.teacher_name,btrim(p_text),p_reply_to_id
  ) returning * into v_row;

  update public.staff_grade_conversations set updated_at=now()
   where id=v_conversation_id and school_id=v_sess.school_id;

  return jsonb_build_object('ok',true,'message',to_jsonb(v_row));
end
$function$;

create or replace function public.rpc_chat_grade_mark_read(
  p_session_token text,
  p_grade text
)
returns jsonb
language plpgsql
security definer
set search_path to 'public','pg_temp'
as $function$
declare v_sess record; v_grade text:=nullif(btrim(p_grade),'');
begin
  select s.school_id,s.teacher_id,s.role into v_sess
    from public.app_web_sessions s join public.teachers t on t.teacher_id=s.teacher_id
   where s.session_token=p_session_token and s.expires_at>now()
     and t.status='active' and t.school_id=s.school_id and t.role=s.role limit 1;
  if v_sess is null then return jsonb_build_object('ok',false,'error','invalid_session'); end if;
  if v_grade is null or length(v_grade)>100 then return jsonb_build_object('ok',false,'error','bad_grade'); end if;
  if not exists(select 1 from public.teacher_class_assignments a where a.school_id=v_sess.school_id and a.teacher_id=v_sess.teacher_id and a.is_active=true and lower(a.class_name)=lower(v_grade))
    then return jsonb_build_object('ok',false,'error','not_assigned'); end if;
  return jsonb_build_object('ok',true);
end
$function$;

revoke all on function public.rpc_chat_grade_list(text,text) from public;
revoke all on function public.rpc_chat_grade_send(text,text,text,bigint) from public;
revoke all on function public.rpc_chat_grade_mark_read(text,text) from public;
grant execute on function public.rpc_chat_grade_list(text,text) to anon,authenticated;
grant execute on function public.rpc_chat_grade_send(text,text,text,bigint) to anon,authenticated;
grant execute on function public.rpc_chat_grade_mark_read(text,text) to anon,authenticated;
