-- SCMS v12 — Department routing foundation
-- Authoritative department membership for Staff Chat. No implicit department
-- inference from teacher role/classes is permitted.

create table if not exists public.staff_departments (
  id bigint generated by default as identity primary key,
  school_id text not null,
  department_code text not null,
  department_name text not null,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (school_id, department_code),
  unique (school_id, department_name)
);

create table if not exists public.staff_department_members (
  department_id bigint not null references public.staff_departments(id) on delete cascade,
  school_id text not null,
  teacher_id text not null,
  member_role text not null default 'MEMBER'
    check (member_role in ('MEMBER','LEAD')),
  is_active boolean not null default true,
  joined_at timestamptz not null default now(),
  primary key (department_id, teacher_id)
);

create index if not exists idx_staff_departments_school_active
  on public.staff_departments (school_id, is_active, lower(department_name));

create index if not exists idx_staff_department_members_teacher
  on public.staff_department_members (school_id, teacher_id, is_active, department_id);

alter table public.staff_departments enable row level security;
alter table public.staff_department_members enable row level security;

revoke all on public.staff_departments from anon, authenticated;
revoke all on public.staff_department_members from anon, authenticated;

create or replace function public.rpc_chat_department_list(p_session_token text)
returns jsonb
language plpgsql
security definer
set search_path to 'public','pg_temp'
as $function$
declare
  v_sess record;
  v_rows jsonb;
begin
  select s.school_id, s.teacher_id, s.role
    into v_sess
    from public.app_web_sessions s
    join public.teachers t on t.teacher_id=s.teacher_id
   where s.session_token=p_session_token
     and s.expires_at>now()
     and t.status='active'
     and t.school_id=s.school_id
     and t.role=s.role
   limit 1;

  if v_sess is null then
    return jsonb_build_object('ok',false,'error','invalid_session');
  end if;

  select coalesce(jsonb_agg(to_jsonb(x) order by lower(x.department_name)),'[]'::jsonb)
    into v_rows
    from (
      select d.id,d.department_code,d.department_name,m.member_role
        from public.staff_departments d
        join public.staff_department_members m
          on m.department_id=d.id
         and m.school_id=v_sess.school_id
         and m.teacher_id=v_sess.teacher_id
         and m.is_active=true
       where d.school_id=v_sess.school_id
         and d.is_active=true
    ) x;

  return jsonb_build_object('ok',true,'rows',v_rows);
end
$function$;

create or replace function public.rpc_chat_department_admin_upsert(
  p_session_token text,
  p_department_code text,
  p_department_name text,
  p_is_active boolean default true
)
returns jsonb
language plpgsql
security definer
set search_path to 'public','pg_temp'
as $function$
declare
  v_sess record;
  v_id bigint;
begin
  select s.school_id,s.teacher_id,s.role
    into v_sess
    from public.app_web_sessions s
    join public.teachers t on t.teacher_id=s.teacher_id
   where s.session_token=p_session_token
     and s.expires_at>now()
     and t.status='active'
     and t.school_id=s.school_id
     and t.role=s.role
   limit 1;

  if v_sess is null then
    return jsonb_build_object('ok',false,'error','invalid_session');
  end if;

  if lower(coalesce(v_sess.role,'')) not in ('admin','super_admin') then
    return jsonb_build_object('ok',false,'error','forbidden');
  end if;

  if p_department_code is null or btrim(p_department_code)='' or length(btrim(p_department_code))>50
     or p_department_name is null or btrim(p_department_name)='' or length(btrim(p_department_name))>120 then
    return jsonb_build_object('ok',false,'error','invalid_department');
  end if;

  insert into public.staff_departments(school_id,department_code,department_name,is_active)
  values(v_sess.school_id,upper(btrim(p_department_code)),btrim(p_department_name),coalesce(p_is_active,true))
  on conflict (school_id,department_code)
  do update set department_name=excluded.department_name,is_active=excluded.is_active,updated_at=now()
  returning id into v_id;

  return jsonb_build_object('ok',true,'department_id',v_id);
end
$function$;

create or replace function public.rpc_chat_department_admin_set_members(
  p_session_token text,
  p_department_id bigint,
  p_teacher_ids text[]
)
returns jsonb
language plpgsql
security definer
set search_path to 'public','pg_temp'
as $function$
declare
  v_sess record;
  v_department record;
  v_teacher_id text;
  v_count integer:=0;
begin
  select s.school_id,s.teacher_id,s.role
    into v_sess
    from public.app_web_sessions s
    join public.teachers t on t.teacher_id=s.teacher_id
   where s.session_token=p_session_token
     and s.expires_at>now()
     and t.status='active'
     and t.school_id=s.school_id
     and t.role=s.role
   limit 1;

  if v_sess is null then
    return jsonb_build_object('ok',false,'error','invalid_session');
  end if;

  if lower(coalesce(v_sess.role,'')) not in ('admin','super_admin') then
    return jsonb_build_object('ok',false,'error','forbidden');
  end if;

  select id,school_id into v_department
    from public.staff_departments
   where id=p_department_id and school_id=v_sess.school_id and is_active=true
   limit 1;

  if v_department is null then
    return jsonb_build_object('ok',false,'error','department_not_found');
  end if;

  update public.staff_department_members
     set is_active=false
   where department_id=p_department_id and school_id=v_sess.school_id;

  foreach v_teacher_id in array coalesce(p_teacher_ids,array[]::text[]) loop
    if exists (
      select 1 from public.teachers t
       where t.teacher_id=btrim(v_teacher_id)
         and t.school_id=v_sess.school_id
         and t.status='active'
    ) then
      insert into public.staff_department_members(department_id,school_id,teacher_id,is_active)
      values(p_department_id,v_sess.school_id,btrim(v_teacher_id),true)
      on conflict (department_id,teacher_id)
      do update set is_active=true;
      v_count:=v_count+1;
    end if;
  end loop;

  return jsonb_build_object('ok',true,'member_count',v_count);
end
$function$;

revoke all on function public.rpc_chat_department_list(text) from public;
revoke all on function public.rpc_chat_department_admin_upsert(text,text,text,boolean) from public;
revoke all on function public.rpc_chat_department_admin_set_members(text,bigint,text[]) from public;

grant execute on function public.rpc_chat_department_list(text) to anon,authenticated;
grant execute on function public.rpc_chat_department_admin_upsert(text,text,text,boolean) to anon,authenticated;
grant execute on function public.rpc_department_admin_set_members(text,bigint,text[]) to anon,authenticated;
