-- SCMS v12 — Staff Inquiry Tickets
-- Staff-only workflow. Parent/student operational data is referenced by ID only;
-- no parent contact fields are copied into the chat model.

create table if not exists public.staff_inquiry_tickets (
  id bigint generated by default as identity primary key,
  school_id text not null,
  student_id text,
  subject text not null,
  status text not null default 'OPEN',
  priority text not null default 'NORMAL',
  created_by_teacher_id text not null,
  created_by_teacher_name text not null,
  assigned_teacher_id text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  resolved_at timestamptz,
  closed_at timestamptz,
  constraint staff_inquiry_ticket_status_ck check (status in ('OPEN','ASSIGNED','IN_PROGRESS','WAITING','RESOLVED','CLOSED')),
  constraint staff_inquiry_ticket_priority_ck check (priority in ('LOW','NORMAL','HIGH','URGENT'))
);

create table if not exists public.staff_inquiry_ticket_members (
  ticket_id bigint not null references public.staff_inquiry_tickets(id) on delete cascade,
  school_id text not null,
  teacher_id text not null,
  member_role text not null default 'MEMBER',
  added_at timestamptz not null default now(),
  primary key (ticket_id, teacher_id),
  constraint staff_inquiry_ticket_member_role_ck check (member_role in ('MEMBER','ASSIGNEE','WATCHER'))
);

create table if not exists public.staff_inquiry_ticket_messages (
  id bigint generated by default as identity primary key,
  ticket_id bigint not null references public.staff_inquiry_tickets(id) on delete cascade,
  school_id text not null,
  sender_teacher_id text not null,
  sender_teacher_name text not null,
  body text not null,
  created_at timestamptz not null default now()
);

create index if not exists idx_staff_inquiry_tickets_school_status
  on public.staff_inquiry_tickets(school_id,status,updated_at desc);
create index if not exists idx_staff_inquiry_ticket_members_teacher
  on public.staff_inquiry_ticket_members(school_id,teacher_id,ticket_id);
create index if not exists idx_staff_inquiry_ticket_messages_ticket
  on public.staff_inquiry_ticket_messages(ticket_id,created_at desc,id desc);

alter table public.staff_inquiry_tickets enable row level security;
alter table public.staff_inquiry_ticket_members enable row level security;
alter table public.staff_inquiry_ticket_messages enable row level security;
revoke all on public.staff_inquiry_tickets from anon,authenticated;
revoke all on public.staff_inquiry_ticket_members from anon,authenticated;
revoke all on public.staff_inquiry_ticket_messages from anon,authenticated;

create or replace function public.rpc_chat_inquiry_list(
  p_session_token text,
  p_status text default null,
  p_limit integer default 50
) returns jsonb
language plpgsql security definer set search_path to 'public','pg_temp'
as $$
declare v record; v_rows jsonb;
begin
  select s.school_id,s.teacher_id,t.teacher_name into v
  from public.app_web_sessions s join public.teachers t on t.teacher_id=s.teacher_id
  where s.session_token=p_session_token and s.expires_at>now()
    and t.status='active' and t.school_id=s.school_id and t.role=s.role limit 1;
  if v is null then return jsonb_build_object('ok',false,'error','invalid_session'); end if;

  select coalesce(jsonb_agg(to_jsonb(x) order by x.updated_at desc),'[]'::jsonb) into v_rows
  from (
    select t.id,t.student_id,t.subject,t.status,t.priority,t.created_by_teacher_id,t.created_by_teacher_name,
           t.assigned_teacher_id,t.created_at,t.updated_at,t.resolved_at,t.closed_at
    from public.staff_inquiry_tickets t
    where t.school_id=v.school_id
      and (p_status is null or t.status=p_status)
      and (t.created_by_teacher_id=v.teacher_id
           or exists(select 1 from public.staff_inquiry_ticket_members m
                     where m.ticket_id=t.id and m.school_id=v.school_id and m.teacher_id=v.teacher_id))
    order by t.updated_at desc,t.id desc limit greatest(1,least(coalesce(p_limit,50),100))
  ) x;
  return jsonb_build_object('ok',true,'rows',v_rows);
end $$;

create or replace function public.rpc_chat_inquiry_open(
  p_session_token text,
  p_ticket_id bigint
) returns jsonb
language plpgsql security definer set search_path to 'public','pg_temp'
as $$
declare v record; v_ticket record; v_rows jsonb;
begin
  select s.school_id,s.teacher_id,t.teacher_name into v
  from public.app_web_sessions s join public.teachers t on t.teacher_id=s.teacher_id
  where s.session_token=p_session_token and s.expires_at>now()
    and t.status='active' and t.school_id=s.school_id and t.role=s.role limit 1;
  if v is null then return jsonb_build_object('ok',false,'error','invalid_session'); end if;

  select * into v_ticket from public.staff_inquiry_tickets t
  where t.id=p_ticket_id and t.school_id=v.school_id
    and (t.created_by_teacher_id=v.teacher_id or exists(
      select 1 from public.staff_inquiry_ticket_members m
      where m.ticket_id=t.id and m.school_id=v.school_id and m.teacher_id=v.teacher_id));
  if v_ticket is null then return jsonb_build_object('ok',false,'error','ticket_forbidden'); end if;

  select coalesce(jsonb_agg(to_jsonb(x) order by x.created_at),'[]'::jsonb) into v_rows
  from (
    select id,sender_teacher_id,sender_teacher_name,body,created_at
    from public.staff_inquiry_ticket_messages
    where ticket_id=v_ticket.id and school_id=v.school_id
    order by created_at asc,id asc
  ) x;
  return jsonb_build_object('ok',true,'ticket',to_jsonb(v_ticket),'messages',v_rows);
end $$;

create or replace function public.rpc_chat_inquiry_send(
  p_session_token text,
  p_ticket_id bigint,
  p_body text
) returns jsonb
language plpgsql security definer set search_path to 'public','pg_temp'
as $$
declare v record; v_ticket record; v_msg record;
begin
  select s.school_id,s.teacher_id,t.teacher_name into v
  from public.app_web_sessions s join public.teachers t on t.teacher_id=s.teacher_id
  where s.session_token=p_session_token and s.expires_at>now()
    and t.status='active' and t.school_id=s.school_id and t.role=s.role limit 1;
  if v is null then return jsonb_build_object('ok',false,'error','invalid_session'); end if;
  if p_body is null or length(btrim(p_body))=0 or length(p_body)>4000 then
    return jsonb_build_object('ok',false,'error','bad_text');
  end if;
  select * into v_ticket from public.staff_inquiry_tickets t
  where t.id=p_ticket_id and t.school_id=v.school_id
    and (t.created_by_teacher_id=v.teacher_id or exists(
      select 1 from public.staff_inquiry_ticket_members m
      where m.ticket_id=t.id and m.school_id=v.school_id and m.teacher_id=v.teacher_id));
  if v_ticket is null then return jsonb_build_object('ok',false,'error','ticket_forbidden'); end if;
  if v_ticket.status='CLOSED' then return jsonb_build_object('ok',false,'error','ticket_closed'); end if;

  insert into public.staff_inquiry_ticket_messages(ticket_id,school_id,sender_teacher_id,sender_teacher_name,body)
  values(p_ticket_id,v.school_id,v.teacher_id,v.teacher_name,btrim(p_body)) returning * into v_msg;
  update public.staff_inquiry_tickets set updated_at=now(),
    status=case when status='OPEN' then 'IN_PROGRESS' else status end where id=p_ticket_id and school_id=v.school_id;
  return jsonb_build_object('ok',true,'message',to_jsonb(v_msg));
end $$;

create or replace function public.rpc_chat_inquiry_create(
  p_session_token text,
  p_subject text,
  p_body text,
  p_student_id text default null,
  p_priority text default 'NORMAL'
) returns jsonb
language plpgsql security definer set search_path to 'public','pg_temp'
as $$
declare v record; v_ticket record; v_msg record;
begin
  select s.school_id,s.teacher_id,t.teacher_name into v
  from public.app_web_sessions s join public.teachers t on t.teacher_id=s.teacher_id
  where s.session_token=p_session_token and s.expires_at>now()
    and t.status='active' and t.school_id=s.school_id and t.role=s.role limit 1;
  if v is null then return jsonb_build_object('ok',false,'error','invalid_session'); end if;
  if p_subject is null or length(btrim(p_subject))=0 or length(p_subject)>200 then return jsonb_build_object('ok',false,'error','bad_subject'); end if;
  if p_body is null or length(btrim(p_body))=0 or length(p_body)>4000 then return jsonb_build_object('ok',false,'error','bad_text'); end if;
  if p_priority not in ('LOW','NORMAL','HIGH','URGENT') then return jsonb_build_object('ok',false,'error','bad_priority'); end if;
  if p_student_id is not null and not exists(select 1 from public.students s where s.student_id=p_student_id and s.school_id=v.school_id)
    then return jsonb_build_object('ok',false,'error','student_forbidden'); end if;

  insert into public.staff_inquiry_tickets(school_id,student_id,subject,priority,created_by_teacher_id,created_by_teacher_name)
  values(v.school_id,nullif(btrim(p_student_id),''),btrim(p_subject),p_priority,v.teacher_id,v.teacher_name) returning * into v_ticket;
  insert into public.staff_inquiry_ticket_members(ticket_id,school_id,teacher_id,member_role)
  values(v_ticket.id,v.school_id,v.teacher_id,'MEMBER');
  insert into public.staff_inquiry_ticket_messages(ticket_id,school_id,sender_teacher_id,sender_teacher_name,body)
  values(v_ticket.id,v.school_id,v.teacher_id,v.teacher_name,btrim(p_body)) returning * into v_msg;
  return jsonb_build_object('ok',true,'ticket',to_jsonb(v_ticket),'message',to_jsonb(v_msg));
end $$;

revoke all on function public.rpc_chat_inquiry_list(text,text,integer) from public;
revoke all on function public.rpc_chat_inquiry_open(text,bigint) from public;
revoke all on function public.rpc_chat_inquiry_send(text,bigint,text) from public;
revoke all on function public.rpc_chat_inquiry_create(text,text,text,text,text) from public;
grant execute on function public.rpc_chat_inquiry_list(text,text,integer) to anon,authenticated;
grant execute on function public.rpc_chat_inquiry_open(text,bigint) to anon,authenticated;
grant execute on function public.rpc_chat_inquiry_send(text,bigint,text) to anon,authenticated;
grant execute on function public.rpc_chat_inquiry_create(text,text,text,text,text) to anon,authenticated;
