-- Teacher assignment + granular permission foundation.
-- Idempotent: the live database may already contain these objects from staged rollout.
create table if not exists public.teacher_class_assignments (
  id bigint generated by default as identity primary key,
  school_id text not null,
  teacher_id text not null,
  class_name text not null,
  assignment_type text not null default 'class_teacher',
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint teacher_class_assignments_type_ck check (assignment_type in ('class_teacher','assistant','subject_teacher','other')),
  constraint teacher_class_assignments_class_ck check (length(trim(class_name)) > 0),
  constraint teacher_class_assignments_uq unique (school_id, teacher_id, class_name, assignment_type),
  constraint teacher_class_assignments_teacher_fk foreign key (teacher_id) references public.teachers(teacher_id) on delete cascade
);

create table if not exists public.teacher_subject_assignments (
  id bigint generated by default as identity primary key,
  school_id text not null,
  teacher_id text not null,
  subject_id bigint not null,
  class_name text not null,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint teacher_subject_assignments_class_ck check (length(trim(class_name)) > 0),
  constraint teacher_subject_assignments_uq unique (school_id, teacher_id, subject_id, class_name),
  constraint teacher_subject_assignments_teacher_fk foreign key (teacher_id) references public.teachers(teacher_id) on delete cascade,
  constraint teacher_subject_assignments_subject_fk foreign key (subject_id) references public.subjects(id) on delete cascade
);

create table if not exists public.permission_definitions (
  permission_key text primary key,
  category text not null,
  description text not null,
  scope_type text not null,
  is_sensitive boolean not null default false,
  is_active boolean not null default true,
  display_order integer not null default 0,
  constraint permission_definitions_scope_ck check (scope_type in ('global','class','subject','class_subject')),
  constraint permission_definitions_key_ck check (length(trim(permission_key)) > 0)
);

create table if not exists public.role_permissions (
  role text not null,
  permission_key text not null references public.permission_definitions(permission_key) on delete cascade,
  allowed boolean not null default false,
  primary key (role, permission_key)
);

create table if not exists public.teacher_permissions (
  id bigint generated by default as identity primary key,
  school_id text not null,
  teacher_id text not null,
  permission_key text not null references public.permission_definitions(permission_key) on delete cascade,
  allowed boolean not null,
  scope_type text not null,
  class_name text,
  subject_id bigint,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint teacher_permissions_scope_ck check (scope_type in ('global','class','subject','class_subject')),
  constraint teacher_permissions_scope_data_ck check (
    (scope_type = 'global' and class_name is null and subject_id is null)
    or (scope_type = 'class' and class_name is not null and subject_id is null)
    or (scope_type = 'subject' and class_name is null and subject_id is not null)
    or (scope_type = 'class_subject' and class_name is not null and subject_id is not null)
  ),
  constraint teacher_permissions_teacher_fk foreign key (teacher_id) references public.teachers(teacher_id) on delete cascade,
  constraint teacher_permissions_subject_fk foreign key (subject_id) references public.subjects(id) on delete cascade
);

create unique index if not exists teacher_permissions_scope_uq
on public.teacher_permissions (teacher_id, permission_key, scope_type, coalesce(class_name, ''), coalesce(subject_id, 0));
create index if not exists idx_teacher_class_assignments_lookup
on public.teacher_class_assignments (school_id, teacher_id, is_active, class_name);
create index if not exists idx_teacher_class_assignments_class
on public.teacher_class_assignments (school_id, class_name, is_active);
create index if not exists idx_teacher_subject_assignments_lookup
on public.teacher_subject_assignments (school_id, teacher_id, is_active, class_name, subject_id);
create index if not exists idx_teacher_subject_assignments_subject
on public.teacher_subject_assignments (school_id, subject_id, class_name, is_active);
create index if not exists idx_teacher_permissions_lookup
on public.teacher_permissions (school_id, teacher_id, permission_key, allowed);

alter table public.teacher_class_assignments enable row level security;
alter table public.teacher_subject_assignments enable row level security;
alter table public.permission_definitions enable row level security;
alter table public.role_permissions enable row level security;
alter table public.teacher_permissions enable row level security;

revoke all on table public.teacher_class_assignments, public.teacher_subject_assignments, public.permission_definitions, public.role_permissions, public.teacher_permissions from anon, authenticated;

insert into public.permission_definitions
(permission_key,category,description,scope_type,is_sensitive,display_order)
values
('dashboard.view','dashboard','View the school dashboard','global',false,10),
('students.view','students','View student records','global',false,20),
('students.edit','students','Create and edit student records','global',false,21),
('leave.view','leave','View leave requests','class',false,30),
('leave.approve','leave','Approve or reject leave requests','class',false,31),
('attendance.view','attendance','View attendance records','class',false,40),
('attendance.edit','attendance','Record and edit attendance','class',false,41),
('homework.view','homework','View homework','class_subject',false,50),
('homework.create','homework','Create homework','class_subject',false,51),
('homework.edit','homework','Edit homework','class_subject',false,52),
('homework.delete','homework','Delete homework','class_subject',true,53),
('assessment.view','assessment','View assessments','class_subject',false,60),
('assessment.create','assessment','Create assessments','class_subject',false,61),
('assessment.edit','assessment','Edit assessments','class_subject',false,62),
('assessment.delete','assessment','Delete assessments','class_subject',true,63),
('billing.view','billing','View billing information','global',true,70),
('billing.write','billing','Create and modify billing records','global',true,71),
('teachers.view','teacher_management','View teachers','global',true,80),
('teachers.manage','teacher_management','Manage teachers and assignments','global',true,81),
('permissions.manage','teacher_management','Manage teacher permissions','global',true,82)
on conflict (permission_key) do update set
category=excluded.category, description=excluded.description, scope_type=excluded.scope_type,
is_sensitive=excluded.is_sensitive, display_order=excluded.display_order, is_active=true;

insert into public.role_permissions(role,permission_key,allowed)
select 'teacher', permission_key,
       permission_key in ('dashboard.view','students.view','leave.view','leave.approve','attendance.view','attendance.edit',
                          'homework.view','homework.create','homework.edit','assessment.view','assessment.create','assessment.edit')
from public.permission_definitions
on conflict (role,permission_key) do update set allowed=excluded.allowed;

insert into public.role_permissions(role,permission_key,allowed)
select r.role, p.permission_key, true
from (values ('admin'),('super_admin')) r(role)
cross join public.permission_definitions p
on conflict (role,permission_key) do update set allowed=true;
