-- DEPRECATED MIGRATION FILENAME
-- The canonical migration is:
-- 20260929043000_security_grants_hardening.sql
-- Kept as a no-op because this legacy filename does not follow the Supabase
-- YYYYMMDDHHmmss_description.sql convention.
